huggingface/huggingface_hub

setup.py
src/huggingface_hub/file_download.py

Importing torch and tf just to check if they're available takes too much time.
Use importlib metadata instead.
It's a buitin package from python 3.8. It was backported as the importlib_metadata package.
Now importing huggingface_hub or calling the cli in instantaneous.

Fast start up

---

src/huggingface_hub/commands/lfs.py

Got reminded about that by https://github.com/huggingface/autonlp/pull/18#discussion_r585660502

multipart: don't wait for first chunk to be uploaded to start all workers

---

src/huggingface_hub/constants.py
src/huggingface_hub/file_download.py
tests/test_file_download.py
tests/test_offline_utils.py
tests/testing_utils.py

This adds the `HF_HUB_OFFLINE` env var to tell `huggingface_hub` (same as in hf/transformers and hf/datasets).
This allows to tell the library to look directly at the cache instead of trying network calls.
Moreover I fixed/changed a few things:
- I added a default timeout for requests in file_download.py (otherwise they could hang in a firewalled environment) and never fall back on the cache
- I made it so `force_download=True` doesn't check the cache if there's no internet connection, but raises an error instead.
- I added retries as in hf/datasets if one network call fails if you're unlucky or have bad wifi
- I added a testing utility context manager called `offline` that you can use to test the library's behavior under different offline modes (same as in hf/datasets)
I'm not sure why …

Add HF_HUB_OFFLINE env var

---

src/huggingface_hub/__init__.py
src/huggingface_hub/hub_mixin.py
src/huggingface_hub/repository.py
src/huggingface_hub/saving_utils.py
tests/test_hubmixin.py

This PR will add feature as discussed in issue #9.
```python
from huggingface_hub import ModelHubMixin
class MyModel(nn.Module, ModelHubMixin):
def __init__(self, **kwargs):
super().__init__()
self.config = kwargs.pop("config", None)
self.layer = ...
def forward(self, ...):
return ...
model = MyModel()
model.save_pretrained("mymodel", upload_to_hub=True, config={"act": "gelu"})
model = MyModel.from_pretrained("username/mymodel@main")
```
- In case user want to save some specific layers as per his needs, he can simple overwrite `._save_pretrained()` method.
- Supporting all kind of `PyTorch` model.
- `tf2` not supported currently

Adding mixin class for ease saving, uploading, downloading (as discussed in issue #9).

---

.github/workflows/python-quality.yml
.github/workflows/python-tests.yml

I had forgotten this in the previous PR, which led to the CI being run twice.

Only run CI once

---

.github/workflows/python-quality.yml
.github/workflows/python-tests.yml
.github/workflows/release-conda.yml

This PR fixes two things:
- The anaconda upload fails because it lacks support for python 3.9, while python 3.9 is the default conda installation. This PR sets python 3.8 as the default
- The current CI doesn't run on `main`

Fix conda by specifying python version + add tests to main branch

---

.github/workflows/python-tests.yml
setup.py
src/huggingface_hub/hub_mixin.py
tests/test_hubmixin.py

Improves the Mixin in the hub by adding support for `api_endpoint`, `use_auth_token`, as well as `git_user` and `git_email`. 
It updates the tests so that they run in the staging environment. In doing so, I found a bug relative to absolute paths in `from_pretrained`, this fixes that at the same time.

Improve Mixin

---

src/huggingface_hub/commands/lfs.py
src/huggingface_hub/hf_api.py

This includes the start of a better `__repr__` for the `ModelInfo` class, started from this issue: https://github.com/huggingface/huggingface_hub/issues/31
This is based on what I've started for the [AdaptNLP](https://github.com/Novetta/adaptnlp/blob/nbdev_conversion/adaptnlp/model_hub.py#L51)
A few points of difference that could be done here is we could also programmatically include the tasks available for it, similar to what was done in AdaptNLP, but I guess the key information is what would be the best-case scenario for a model repr? Currently what I have lets it look like so:
```python
Model Name: "gpt2", Tags: ['pytorch', 'tf', 't5'], Task: ['summarization']
```
For adapt I go a bit further (with the whole programmatic way I mentioned early) by checking what tags are also tasks and …

Include a readable repr for ModelInfo

---

src/huggingface_hub/snapshot_download.py

Enables passing `library_name`, `library_version` and `user_agent` in `snapshot_download`.
Fixes https://github.com/huggingface/huggingface_hub/issues/37

Enable `library_name` and `library_version` in `snapshot_download`

---

src/huggingface_hub/hf_api.py

I recently had some issues which could have been easily found if the error message was more verbose.
Before: 
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://huggingface.co/api/repos/create
After: 
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://huggingface.co/api/repos/create - Only regular characters and '-', '_', '.' accepted

Make error message more verbose when creating a repo

---

modelcard.md

Hi all, opening this PR so that we can all align on the metadata spec for model cards. This metadata is important as it closes the bridge between tasks, datasets, and metrics for a given checkpoint. This will eventually allow programmatic analysis and handling of model cards' metadata on the hub.
The metadata was drafted during the collaboration with papers-with-code in order to have a ranked leaderboard for the XLSR sprint. The following format was adopted:
```
model-index:  
- name: {model_id}
results:
- task: 
name: {task_name}
type: {task_type}
dataset:
name: {dataset_name}
type: {dataset_type}
args: {arg_0}
metrics:
- name: {metric_name} 
type: {metric_type}
value: {metric_value}
args: {arg_0}
```
This format should allow for multiple tasks and multiple metrics within each task.
Some …

Alignment on modelcard metadata specification

---

interfaces/Libraries.ts
interfaces/README.md

Reviewers: see also upcoming PR in moon-landing [internal]

[interfaces] Expose configuration options for external libraries

---

interfaces/Libraries.ts

@dathudeptrai FYI
Example results - users will be able to add a tensorflowtts tag in the model repo, search by library and see a very basic code snippet that shows how to load the model.

Add TensorFlowTTS as library + code snippet

---

api-inference-community/api_inference_community/validation.py
api-inference-community/tests/test_nlp.py

Summary of changes:
* Aligned max length with `max_new_tokens` in [docs](https://api-inference.huggingface.co/docs/python/html/detailed_parameters.html). 
* Changed `max_length` to `max_new_tokens` for `text-generation`, which I think would be the right param.
* Added `return_full_text` and `num_return_sequences` for `text-generation`
* Added `summarization`, `table-question-answering`, and `text2text-generation` validation.
* Fixed `conversational`. It was using params instead of inputs, and the inputs are others.
Let me know if you disagree with any and I can revert :)

Update validation for NLP tasks

---

interfaces/Libraries.ts

Here is how it would look like. 
@ines FYI

spaCy code snippet and language tag

---

interfaces/Libraries.ts

Sibling [PR]( https://github.com/huggingface/moon-landing/pull/734) in moon landing. Thanks to that PR, the config is read from `adapter_config.json` and we get access to specific info from there for the code snippet.
🚀 🚀 
@calpt FYI :)

Add Adapter Transformers snippet

---

src/huggingface_hub/hf_api.py

Refactor create_repo

---

api-inference-community/api_inference_community/routes.py
api-inference-community/docker_images/common/app/main.py
api-inference-community/tests/test_dockers.py
api-inference-community/tests/test_routes.py

We need to display some error about what is happening.

When pipelines fail to load in framework code, for whatever reason

---

tests/test_hf_api.py
tests/test_hubmixin.py
tests/test_repository.py
tests/testing_utils.py

Removing `.git` directories on Windows with `shutil.rmtree` raises a permission error.
Changing the file's permission and retrying solves this.

Solve `rmtree` issue on windows

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

Explicitly mention the request returns 409 when the uploaded file already exists on the hub and is identical
cc @osanseviero

Add identical_ok option to HfApi.upload_file method

---

tests/test_hf_api.py

The `check_output` of `subprocess.run` argument is not available in Python 3.6, but the lib is advertized to be compatible with Python >= 3.6

Solve compatibility issues when calling `subprocess.run`

---

interfaces/Libraries.ts

following #87 (typescript is throwing errors in moon-landing otherwise)

model `tags` can be `undefined`

---

interfaces/Types.ts
widgets/src/lib/InferenceWidget/InferenceWidget.svelte
widgets/src/lib/InferenceWidget/shared/ViewUtils.ts
widgets/src/lib/InferenceWidget/shared/WidgetRecorder/Recorder.ts
widgets/src/lib/InferenceWidget/widgets/AudioToAudioWidget/AudioToAudioWidget.svelte
widgets/src/routes/index.svelte

To be done 
After #87 
After #93 
Before #94

adding audio-to-audio widget.

---

api-inference-community/api_inference_community/routes.py
api-inference-community/docker_images/common/app/main.py
api-inference-community/docker_images/common/app/pipelines/audio_to_audio.py
api-inference-community/docker_images/common/tests/test_api_audio_to_audio.py
api-inference-community/docker_images/sentence_transformers/app/main.py
api-inference-community/docker_images/sentence_transformers/requirements.txt
api-inference-community/manage.py
api-inference-community/tests/test_routes.py

This PR does two things
* Updates style of some files which are not correctly formatted (`make style`)
* Upgrade `api-inference-community` in sentence transformers to include #96 and have better error messages (FYI @nreimers)

Add formatting and upgrade Sentence Transformers api version for better error messages

---

api-inference-community/docker_images/sentence_transformers/requirements.txt

This might potentially break some of the existing models with the previous v2 (I think they were all mine though), but this will make sure @nreimers can try out Inference API with latest changes.

Change sentence transformers source to original repo

---

setup.py
src/huggingface_hub/file_download.py

see also https://github.com/huggingface/huggingface_hub/pull/27

Allow Python versions with letters in the minor version suffix

---

src/huggingface_hub/__init__.py
src/huggingface_hub/file_download.py
tests/test_file_download.py

Offer an additional method `hf_hub_download` to bypass the call of `hf_hub_url` followed by `cached_download`

HF Hub download

---

src/huggingface_hub/hub_mixin.py
src/huggingface_hub/repository.py
tests/test_hubmixin.py
tests/test_repository.py

This PR offers a slightly reworked `Repository.clone_from` method. 
It currently behaves as follows:
```
clone_from
-> Empty folder
-> Clones the repository inside the empty folder
-> Folder contains files
-> git init, git fetch, git reset origin/main, git checkout origin/main
```
The principal reason that led to this proposal are:
- It is currently possible to use `clone_from` in a directory that contains a `.git` that has a completely unrelated git history, replacing the `.git` but keeping all other files in the working directory. No file on the remote repository will be pulled in the local directory.
This PR proposes to change the behavior when the folder contains files:
```
clone_from
-> Empty folder
-> Clones the repository inside the empty folder
-> Folder contains files
-> The …
```

Repository power-up

---

src/huggingface_hub/repository.py
tests/test_repository.py

The `is_git_repo` can fail even if a folder is a local clone of the distant repo because it takes the tokens into account. This PR ignores the tokens and also displays the repo url without token in error message to be a bit clearer to the user.

Fix is_git_repo by ignoring tokens

---

README.md
docs/hub/adding-a-library.md
docs/hub/inference.md
docs/hub/libraries.md
docs/hub/main.md
docs/hub/model-repos.md

With https://github.com/huggingface/huggingface_hub/pull/145 the links to the documentation need to be updated or point to a 404
Closes https://github.com/huggingface/huggingface_hub/issues/146

Update links to docs

---

src/huggingface_hub/__init__.py
src/huggingface_hub/constants.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/repository.py
tests/fixtures/tiny_dataset/some_text.txt
tests/fixtures/tiny_dataset/test.py
tests/test_hf_api.py
tests/test_repository.py

This PR is built on top of https://github.com/huggingface/huggingface_hub/pull/148 for the tests and https://github.com/huggingface/huggingface_hub/pull/150 for the lack of requirement regarding the namespace definition in the clone.
This enables `datasets` handling from `Repository`'s `clone_from` method.
Closes https://github.com/huggingface/huggingface_hub/issues/144
@SBrandeis could you try it out and let me know if it fixes your issue?

Enable dataset repositories

---

.github/workflows/python-tests.yml
src/huggingface_hub/__init__.py
src/huggingface_hub/constants.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/repository.py
tests/fixtures/tiny_dataset/some_text.txt
tests/fixtures/tiny_dataset/test.py
tests/test_hf_api.py
tests/test_repository.py

This PR is built on top of https://github.com/huggingface/huggingface_hub/pull/148 for the tests.
This enables doing the following when authenticated:
```py
from huggingface_hub import Repository
repo = Repository(local_directory, clone_from="torch-model", use_auth_token=True)
```
It uses the user namespace by default.
previously this required passing the namespace as well:
```py
from huggingface_hub import Repository
repo = Repository(local_directory, clone_from="user/torch-model", use_auth_token=True)
repo = Repository(local_directory, clone_from="org/torch-model", use_auth_token=True)
```

Allow passing only model ID to clone when authenticated

---

.github/workflows/python-tests.yml
src/huggingface_hub/__init__.py
src/huggingface_hub/constants.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/repository.py
tests/fixtures/tiny_dataset/some_text.txt
tests/fixtures/tiny_dataset/test.py
tests/test_file_download.py
tests/test_hf_api.py
tests/test_repository.py
tests/test_snapshot_download.py
tests/testing_constants.py
tests/testing_utils.py

This PR switches the default endpoint to use the moon-landing endpoint when the `HUGGINGFACE_CO_STAGING` environment variable is set.
Doing this enables testing for HF Hub IDs without needing to specify the moon-landing endpoint explicitly, in turn adding coverage for the user/organization and model ID identification.

More robust endpoint with toggled staging endpoint

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

Here is an example from `list_models` for `adapter-transformers`.
FYI @calpt
```
ModelInfo: {
modelId: AdapterHub/roberta-base-pf-sick
sha: b4cbe28cab4c4ac47d1cb431c73ac7917e38c0d0
lastModified: 2021-06-16T16:11:08.000Z
tags: ['roberta', 'en', 'dataset:sick', 'adapter-transformers']
pipeline_tag: None
siblings: [ModelFile(rfilename='.gitattributes'), ModelFile(rfilename='README.md'), ModelFile(rfilename='adapter_config.json'), ModelFile(rfilename='head_config.json'), ModelFile(rfilename='pytorch_adapter.bin'), ModelFile(rfilename='pytorch_model_head.bin')]
config: {'model_type': 'roberta', 'adapter_transformers': {'model_name': 'roberta-base', 'model_class': 'RobertaModelWithHeads'}}
private: False
library_name: adapter-transformers
}
ModelInfo: {
modelId: calpt/adapter-bert-base-squad1 …
```

Add config to list_models

---

widgets/src/lib/InferenceWidget/widgets/AudioToAudioWidget/AudioToAudioWidget.svelte
widgets/src/routes/index.svelte

`src` does NOT exist on the incoming payload.
`content-type`, `blob` and `label` are the keys.
`src` is only added later as a convenience to display.
Example of usable model: https://huggingface.co/julien-c/DPRNNTasNet-ks16_WHAM_sepclean

Fixing audio-to-audio validation.

---

src/huggingface_hub/repository.py

This sets the `use_auth_token` parameter to `True` by default for the `Repository` instantiation.
If users are not logged in, then it will behave similarly to the previous default, or if the `use_auth_token` parameter was set to `False`: the `HfFolder().get_token()` returns `None`, and the `Repository` behaves as unauthenticated.
For logged-in users, however, this should dramatically reduce the user errors linked to cloning a repository without specifying the authentication token, in turn being unable to push to that repository with an unhelpful error.
Fix https://github.com/huggingface/huggingface_hub/issues/187

Set use_auth_token to True by default

---

src/huggingface_hub/hf_api.py
src/huggingface_hub/repository.py
tests/test_hf_api.py
tests/test_repository.py
tests/testing_utils.py

This patches an issue where the token was necessary to understand links to the Hugging Face Hub, which was involuntary behavior.
Fixes https://github.com/huggingface/huggingface_hub/issues/186

No need for token to understand HF urls

---

src/huggingface_hub/repository.py

The `--no-renames` argument was introduced in git version 2.18, and git is installed with version 2.17 on colab notebooks. Removing this argument so that `hfh` is compatible with colab notebooks.

Remove `--no_renames` argument to list deleted files.

---

docs/hub/spaces.md

This new link is a more readable getting started page

[Docs] Update link to Gradio documentation 

---

src/huggingface_hub/repository.py
tests/test_repository.py

Adds the `filename` parameter which can be used to set all the `patterns` passed to `lfs_track` as filenames rather than globs.
Closes https://github.com/huggingface/huggingface_hub/issues/168

Add `filename` option to `lfs_track`

---

src/huggingface_hub/repository.py
tests/test_repository.py

Fixes two issues with the `Repository` class and adds tests:
- The context manager `commit`'s track_large_files was not taken into account in the `git_add`.
- The `repo_type_and_id_from_hf_id` introduction ended up making the `Repository` unable to clone a repository that wasn't hosted on the `huggingface.co` website. This fixes that and introduces a regression test.

Repository fixes

---

src/huggingface_hub/hub_mixin.py

Use `hf_hub_download` instead of combination of `cached_download` and `hf_hub_url`. Mentioned in #159

Use hf_hub_download in mixins

---

api-inference-community/api_inference_community/validation.py
api-inference-community/tests/test_nlp.py

This is based on https://github.com/huggingface/huggingface_hub/issues/113 and https://github.com/huggingface/huggingface_hub/pull/131. The API contract allows defining how many images will be returned, which can go from 1 to 10. Let me know if you think we should not allow generating multiple images in a single go, but this resembles well the text to text Inference API.
FYI @mishig25

Add validation for text to image in Inference API

---

docs/hub/inference.md
src/huggingface_hub/README.md
src/huggingface_hub/inference_api.py

TODO: add documentation to https://api-inference.huggingface.co/docs/python/html/detailed_parameters.html (different repo)

Add documentation to GitHub and the Hub docs about the Inference client wrapper

---

src/huggingface_hub/repository.py

Enable large files by default when using `Repository`
Closes https://github.com/huggingface/huggingface_hub/issues/217

Have large files enabled by default when using `Repository`

---

docs/hub/adding-a-library.md
docs/hub/main.md
docs/hub/model-repos.md
modelcard.md
widgets/src/lib/InferenceWidget/widgets/TextGenerationWidget/TextGenerationWidget.svelte
widgets/src/lib/ModelPipelineTag/ModelPipelineTag.svelte
widgets/src/lib/interfaces/Types.ts

⚠️ Warning: I got a little carried away with the https://github.com/huggingface/huggingface_hub/pull/265/commits/7d1d7c930cfd0755822e5b39242286480bd31a3d commit (😂), as it may very well break stuff in moon-landing, and it will require others JS-codebase PRs (like @mishig25's) to be rebased.
Let's see if maybe we want to split that change into a different PR

Clarify/specify/document model card metadata, `model-index`, and pipeline/task types

---

src/huggingface_hub/repository.py

This PR adds progress bars to the `Repository` utility. The progress bars are visible for large files (>10MB) and any other file tracked with git-lfs.
It adds a context manager to be used internally as a wrapper for subprocess calls. This uses the `GIT_LFS_PROGRESS` environment variable to output the progress to a file, tails the file and parses each line. It makes use of temporary directories in order to be used in parallel across the system. Usage is the following:
```py
with lfs_log_progress():
subprocess.run(f"git lfs clone {repo_url} .".split())
```
It works both in notebooks and scripts. Example with a clone:
```py
from huggingface_hub import Repository
repository = Repository("distilbert", clone_from="distilbert-base-uncased")
```
```
Cloning …
```

Progress bars

---

src/huggingface_hub/file_download.py
src/huggingface_hub/hub_mixin.py
src/huggingface_hub/keras_mixin.py
tests/test_keras_mixin.py

Add keras mixin

---

src/huggingface_hub/repository.py
tests/test_repository.py

This PR offers the ability to manage revisions (and therefore branches) with the `Repository` class. The revision management is introduced at two levels:
- When initializing a repository, with the `revision` keyword argument. If the revision exists (it is a reference to a commit, a branch, or a tag), then this revision will be checked out. If the revision does not exist, a new branch will be created with the branching point set to the current default branch's head.
- Using the `git_checkout` method to manually check out a `revision`. It has a `create_branch_ok` argument that is meant to behave as the `exist_ok` argument of `os.makedir` -> it checks out the revision if it exists, otherwise it creates the branch. I found this to be the most compatible with the way repositories would be used …

Branch push to hub

---

api-inference-community/docker_images/common/app/pipelines/text_to_image.py
api-inference-community/docker_images/common/tests/test_api_text_to_image.py
api-inference-community/docker_images/generic/app/main.py
api-inference-community/docker_images/generic/app/pipelines/__init__.py
api-inference-community/docker_images/generic/app/pipelines/text_to_image.py
api-inference-community/docker_images/generic/requirements.txt
api-inference-community/docker_images/generic/tests/test_api.py
api-inference-community/docker_images/generic/tests/test_api_text_to_image.py
api-inference-community/docker_images/generic/tests/test_api_token_classification.py

Similar to #244, this PR adds support for `text-to-image` pipeline.
Here is an [example repo](https://huggingface.co/osanseviero/BigGAN-deep-128) that uses BigGAN-deep-128 (the return of pytorch-pretrained-BigGAN). As can be seen, users specify their own `requirements.txt` and `pipeline.py`. I struggled a bit with the output, but it's a base64 string of the image. This PR should unblock #131. 
Here is a corresponding repo template https://huggingface.co/templates/text-to-image

Add text to image pipeline to generic inference

---

src/huggingface_hub/commands/user.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/repository.py
tests/test_hf_api.py
tests/test_repository.py

*Thoroughly tested in practice, will implement unit tests in a bit but the API will remain as it is so pinging you for review.*
Fixes https://github.com/huggingface/huggingface_hub/issues/211 and https://github.com/huggingface/moon-landing/issues/150
This PR offers a long-awaited overhaul of the login system through the `huggingface_hub` library. The way the login system is currently designed is complex and led to a lot of errors mid-training during the Jax/Flax community week - as well as a general misunderstanding of what was happening behind the scenes.
The core issue is that logging in through `huggingface_cli login` does *not* log the user through git. The user will have to reauthenticate when pushing. This is particularly an issue on Google Colab, where a simple `git push` is met by …

Git credentials

---

widgets/src/lib/InferenceWidget/InferenceWidget.svelte
widgets/src/lib/InferenceWidget/widgets/TextToImageWidget/TextToImageWidget.svelte
widgets/src/routes/index.svelte

Closes #131 read #131 for more details.
Creating a new PR here since #131 is trying to merge a branch from my fork into `hugginface_hub`, which is not supported by Github Actions (thus, action workflows are failing).
@beurkinger, regarding [this comment](https://github.com/huggingface/huggingface_hub/pull/131#pullrequestreview-729500327), `huggingface_hub` doesn't have [[INTERNAL](https://github.com/huggingface/moon-landing/blob/master/front/theme/various.css#L47-L61)] alert-error css, which is why the error doesn't have red background. However, when consumed from moon-landing, everything works since `alert-error` css is defined there. 
Find screenshots here:

Widget text to image

---

src/huggingface_hub/repository.py
tests/test_repository.py

Completes the `revision`-based API by adding branches management to `push_to_hub` and the `commit` context manager.
```python
project_name = 'org/project'
hf_repo = Repository(project_name, clone_from=project_name, revision='test-1')
model = GPT2LMHeadModel.from_pretrained(project_name)
model.save_pretrained(project_name)
hf_repo.push_to_hub(commit_message=f'step {step}')
```
```python
project_name = 'org/project'
hf_repo = Repository(project_name, clone_from=project_name)
hf_repo.git_checkout("branch")
model = GPT2LMHeadModel.from_pretrained(project_name)
model.save_pretrained(project_name)
hf_repo.push_to_hub(commit_message=f'step {step}')
```
Note that the `push_to_hub` method interacts in a complex manner:
- The branch must first be checked out
- The files are saved
- Push to hub …

Push to hub/commit with branches

---

src/huggingface_hub/repository.py

The `is_tracked_with_lfs` method has branching logic set according to the contents of an error message. However, this error message comes from `git` which has localization support: if the default locale is set to something other than English, then the error message will be different. 
While it isn't an issue in other parts of the library where we leverage this error message to give more information about the error, it would be an issue here as the end result is vastly different: from a `return False` to a `raise Exception`. Raising an exception here would result in a non-understandable error that would be complex to diagnose.
Instead, we choose to check if the folder is a git repository when an error is detected: if it is not, then the file is not tracked with GIT LFS. If it is a git …

Remove custom language pack behavior

---

docs/hub/adding-a-model.md
src/huggingface_hub/README.md

This PR does two things
* Updates the add a model guide based on feedback
* Does a general cleanup/update/simplification of `huggingface_hub` README.

Update Hub and huggingface_hub docs

---

widgets/src/lib/InferenceWidget/widgets/TextToImageWidget/TextToImageWidget.svelte

Render images in their original size (output from pipeline) and clip the size with `max-width` css if needed.
Fixes the problem of images being rendered as too big:

Add text2image max-width

---

docs/hub/adding-a-library.md

This PR fixes a broken link to one of the images in the docs.
Before
After

Fix link to library tags image

---

widgets/src/lib/Icons/IconAudioClassification.svelte
widgets/src/lib/InferenceWidget/InferenceWidget.svelte
widgets/src/lib/InferenceWidget/shared/WidgetRadio/WidgetRadio.svelte
widgets/src/lib/InferenceWidget/widgets/AudioClassificationWidget/AudioClassificationWidget.svelte
widgets/src/lib/ModelPipelineIcon/ModelPipelineIcon.svelte
widgets/src/lib/interfaces/Types.ts
widgets/src/routes/index.svelte

Implemented audio classification widget.
Request to Inference API (same as input for ASR, Audio-to-Audio widgets):
```js
const requestBody = { file }; // file is an audio file
```
Response from Inference API (same as Image Classification Widget):
```
Array<{ label: string; score: number }>
```
Find this [slack thread](https://huggingface.slack.com/archives/C02D0F0TGRW/p1630507899016300) for more 
FYI, @patrickvonplaten @anton-l 
Screenshots:
| initial state                                                                                                                                                         | success state                                                                                                                                                         | fail state …

Implement audio classification widget

---

src/huggingface_hub/repository.py

This PR adds the `repo_visibility` parameter to the `Repository` method to be able to create a private repository when pushing to the hub. 
usage:
```python
repo = Repository(
src_dir,
clone_from=f"{user}/{repository_id}",
use_auth_token=use_auth_token,
repo_visibility="private"
)
repo.push_to_hub("Adding Infinity model to HF hub")
```

added option to create private repo

---

src/huggingface_hub/__init__.py
src/huggingface_hub/commands/user.py

This PR adds a widget to be able to login to the HF website from a Jupyter Notebook. The command
```
! huggingface-cli login
```
does not work in a Jupyter notebook, as one cannot write in the output of the cell (it does work in a colab however).
With this PR, a user can do:
```
from huggingface_hub import notebook_login
notebook_login()
```
and they will get the following:
Filling the username and password will then login like the `huggingface-cli login` command.

Add a widget to login in notebook

---

docs/hub/model-repos.md

Context/goal: have a stable link on our doc to link to, in the context of the upcoming metadata validation
Question: should we split that list into its own page? (i feel like its ok like this)

Have our own List of license identifiers

---

src/huggingface_hub/repository.py

- git push errors rejections should be displayed well, as discussed with @LysandreJik, we'll verify this once https://github.com/huggingface/moon-landing/pull/958 is in production.
- **But** git push will also output model-card warnings (but git push accepted) in stderr thatn we want huggingface_hub to display. cf. https://github.com/huggingface/moon-landing/pull/958

display git push warnings

---

src/huggingface_hub/snapshot_download.py
tests/test_hf_api.py
tests/test_snapshot_download.py

This PR adds a `use_auth_token` argument to `snapshot_download` so private repos can be downloaded from the Hub. 
```python
from huggingface_hub import snapshot_download
filepath = snapshot_download("some-private-repo", use_auth_token="api_XXX")
filepath = snapshot_download("some-private-repo", use_auth_token=True)
```

Add auth to snapshot download

---

tests/test_hf_api.py

In PR #340, we observed that `HfApi.model_info` isn't explicitly tested for private repositories, where the absence of a token should throw a HTTP 404 error. This PR aims to cover this case. 
I took inspiration from `HfApiPublicTest` test class to create a private version.

Add model info test for private models

---

.gitignore
src/huggingface_hub/README.md
src/huggingface_hub/repository.py
tests/test_repository.py

This PR introduces a non-blocking git push as asked in https://github.com/huggingface/huggingface_hub/issues/169 and proposed by @cccntu in https://github.com/huggingface/huggingface_hub/pull/171.
It is currently painful to have to wait until a `git push` is over before continuing to something else. Since this uses nothing else than bandwidth, it is fine for it to happen behind the scenes.
This implementation:
- Implements a `blocking` parameter to `git_push` and the `commit` context manager; these variables default to `True`.
- In case of `blocking=False`, outputs a variable that can be monitored to follow the status of the `git push` command
- In case of `blocking=False`, outputs a variable that can be monitored to ensure the `git push` command has terminated
- These variables are added …

Non blocking git push

---

widgets/src/lib/interfaces/Libraries.ts

In `timm`, you must add the prefix `hf_hub:` before any Hugging Face model identifier when using `timm.create_model`. 
The code sample currently being shown on the hub is incorrect, and will fail when you run it.

:bug: Fix timm code sample

---

setup.py
src/huggingface_hub/constants.py
src/huggingface_hub/repocard.py
src/huggingface_hub/repository.py
tests/test_repocard.py

Tentatively close #54 
Example use case:
- goal: updating all licenses for Helsinki-NLP models with no license, to `apache-2.0` – see https://github.com/huggingface/transformers/issues/13328#issuecomment-916455471
- example script: https://gist.github.com/julien-c/b2dcde5df5d5e41ad7c4b594cb54aba3

Repo metadata load and save

---

.github/workflows/python-api-speechbrain.yaml
api-inference-community/docker_images/speechbrain/app/common.py
api-inference-community/docker_images/speechbrain/app/pipelines/audio_classification.py
api-inference-community/docker_images/speechbrain/app/pipelines/audio_to_audio.py
api-inference-community/docker_images/speechbrain/app/pipelines/automatic_speech_recognition.py
api-inference-community/docker_images/speechbrain/requirements.txt
api-inference-community/docker_images/speechbrain/tests/test_api.py
api-inference-community/docker_images/speechbrain/tests/test_api_audio_to_audio.py
api-inference-community/docker_images/speechbrain/tests/test_api_automatic_speech_recognition.py
api-inference-community/tests/test_dockers.py

This PR changes the `speechbrain` Inference to use the class specified in the `config` instead of basing in the model card tag. This also upgrades the `speechbrain` version so it works with `EncoderASR`.
CC @TParcollet

Use config for Speechbrain instead of the tags

---

api-inference-community/docker_images/espnet/requirements.txt

Add `pyopenjtalk` to dependencies for `espnet`, which is required for models as discovered in https://github.com/espnet/espnet/pull/3326#discussion_r663513293

Add pyopenjtalk to espnet dependencies

---

api-inference-community/docker_images/speechbrain/app/pipelines/automatic_speech_recognition.py
api-inference-community/docker_images/speechbrain/requirements.txt
api-inference-community/tests/test_dockers.py

Latest `speechbrain` version fails for some `audio-classification` models. This PR reverts to a working version and reverts `EncoderASR` changes since it's not in previous versions.

Revert speechbrain version to a stable one

---

src/huggingface_hub/hf_api.py

When a user passed a bad token to create a Repository, it ends up with a bit of cryptic error in `HfApi.whoami`:
```
Traceback (most recent call last):
File "examples/pytorch/text-classification/run_glue_no_trainer.py", line 488, in <module>
main()
File "examples/pytorch/text-classification/run_glue_no_trainer.py", line 203, in main
repo_name = get_full_repo_name(Path(args.output_dir).name, token=args.hub_token)
File "/home/sgugger/git/transformers/src/transformers/file_utils.py", line 2249, in get_full_repo_name
username = HfApi().whoami(token)["name"]
File "/home/sgugger/git/huggingface_hub/src/huggingface_hub/hf_api.py", line 330, in whoami
r.raise_for_status()
File "/home/sgugger/.pyenv/versions/3.7.9/envs/base/lib/python3.7/site-packages/requests/models.py", line 941, in …
```

Better error message for bad token.

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

This PR adds a small utility function to get the full repo name from a model ID which:
- extracts the username if no organization is passed and returns username/model_id
- just returns organization/model_id otherwise
This function is used in all examples of Transformers.

Add utility to get repo name

---

docs/hub/model-repos.md

- Context : metadata validation on the git server side
- Those licenses are already present in the hub, and it makes sense keeping them

add missing licenses to docs

---

.github/workflows/python-api-generic.yaml
api-inference-community/docker_images/generic/app/main.py
api-inference-community/docker_images/generic/tests/test_api.py
api-inference-community/docker_images/generic/tests/test_api_audio_to_audio.py
api-inference-community/docker_images/generic/tests/test_api_automatic_speech_recognition.py
api-inference-community/docker_images/generic/tests/test_api_feature_extraction.py
api-inference-community/docker_images/generic/tests/test_api_image_classification.py
api-inference-community/docker_images/generic/tests/test_api_question_answering.py
api-inference-community/docker_images/generic/tests/test_api_speech_segmentation.py
api-inference-community/docker_images/generic/tests/test_api_structured_data_classification.py
api-inference-community/docker_images/generic/tests/test_api_text_classification.py
api-inference-community/docker_images/generic/tests/test_api_text_to_image.py
api-inference-community/docker_images/generic/tests/test_api_text_to_speech.py
api-inference-community/docker_images/generic/tests/test_api_token_classification.py
api-inference-community/tests/test_dockers.py

This PR removes the mapping of type to exactly the same pipeline for all types. This means that if a new repo type is added to the API, then `generic` already supports it out of the box.
I'm not 100% sure if we should keep the unit tests under docker_images. I would prefer to leave them since they help in debugging quite easily for any other repo.
cc @nateraw

Generic is all you need

---

.github/workflows/python-tests.yml
setup.py
src/huggingface_hub/__init__.py
src/huggingface_hub/hub_mixin.py
src/huggingface_hub/keras_mixin.py
tests/test_keras_integration.py
tests/test_keras_mixin.py

Both mentioned in #230 
---
**Note** -  I had to switch to using `snapshot_download` because:
1. The SavedModel format doesn't play nice when filenames are hashes instead of folder containing `keras_model.pb` `metadata.pb`, `variables/`, etc.
2. You have to enforce the structure of the directory tree.
Using `forced_filename` also _could_ have worked, but you'd have to gather up all the files within `variables`/`assets`/etc
I've seen some folks just [zip up the specific file tree](https://gist.github.com/ramdesh/f00ec1f5d01f03114264e8f3d0c226e8) instead due to similar issues.

Update Keras Mixin

---

docs/hub/model-repos.md

Currently the title fixed does not appear in the sidebar of the docs : https://huggingface.co/docs/hub/model-repos#how-can-i-fork-or-rebase-a-repository-with-lfs-pointers
This PR fixes that

Fix model-repos.md title level

---

src/huggingface_hub/hub_mixin.py

Checking if json is in the filename can be problematic when loading from the hub, as the config file name might be a hash.

don't check if 'json' in filename when loading config file

---

widgets/src/lib/InferenceWidget/shared/WidgetInputSamples/WidgetInputSamples.svelte
widgets/src/routes/index.svelte

CSS style update for WidgetInputSamples.svelte
1. Rounded outline
2. Wider
Checkout demo [here](https://617aa41f47f6b43722756eeb--huggingface-widgets.netlify.app/bigscience/T0pp)

Make widgetinputsamples wider & rounded

---

widgets/src/lib/InferenceWidget/shared/WidgetDropzone/WidgetDropzone.svelte
widgets/src/lib/InferenceWidget/shared/WidgetInputSamples/WidgetInputSamples.svelte
widgets/src/lib/InferenceWidget/shared/WidgetWrapper/WidgetWrapper.svelte
widgets/src/lib/InferenceWidget/shared/helpers.ts
widgets/src/lib/InferenceWidget/shared/types.ts
widgets/src/lib/InferenceWidget/widgets/AudioClassificationWidget/AudioClassificationWidget.svelte
widgets/src/lib/InferenceWidget/widgets/AudioToAudioWidget/AudioToAudioWidget.svelte
widgets/src/lib/InferenceWidget/widgets/AutomaticSpeechRecognitionWidget/AutomaticSpeechRecognitionWidget.svelte
widgets/src/lib/InferenceWidget/widgets/ConversationalWidget/ConversationalWidget.svelte
widgets/src/lib/InferenceWidget/widgets/FeatureExtractionWidget/FeatureExtractionWidget.svelte
widgets/src/lib/InferenceWidget/widgets/FillMaskWidget/FillMaskWidget.svelte
widgets/src/lib/InferenceWidget/widgets/ImageClassificationWidget/ImageClassificationWidget.svelte
widgets/src/lib/InferenceWidget/widgets/ObjectDetectionWidget/ObjectDetectionWidget.svelte
widgets/src/lib/InferenceWidget/widgets/ObjectDetectionWidget/SvgBoundingBoxes.svelte
widgets/src/lib/InferenceWidget/widgets/QuestionAnsweringWidget/QuestionAnsweringWidget.svelte
widgets/src/lib/InferenceWidget/widgets/SentenceSimilarityWidget/SentenceSimilarityWidget.svelte
widgets/src/lib/InferenceWidget/widgets/StructuredDataClassificationWidget/StructuredDataClassificationWidget.svelte
widgets/src/lib/InferenceWidget/widgets/SummarizationWidget/SummarizationWidget.svelte
widgets/src/lib/InferenceWidget/widgets/TableQuestionAnsweringWidget/TableQuestionAnsweringWidget.svelte
widgets/src/lib/InferenceWidget/widgets/TextGenerationWidget/TextGenerationWidget.svelte
widgets/src/lib/InferenceWidget/widgets/TextToImageWidget/TextToImageWidget.svelte
widgets/src/lib/InferenceWidget/widgets/TextToSpeechWidget/TextToSpeechWidget.svelte
widgets/src/lib/InferenceWidget/widgets/TokenClassificationWidget/TokenClassificationWidget.svelte
widgets/src/lib/InferenceWidget/widgets/ZeroShowClassificationWidget/ZeroShotClassificationWidget.svelte
widgets/src/routes/index.svelte

Update: vision & audio preview before selecting
| Vision widget                                                                                         | Audio widget                                                                                          |
|-------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------|
| <video src="https://user-images.githubusercontent.com/11827707/139964749-2e608b42-e139-41fb-a0c9-0a3dbf3ec3b3.mov" controls autoplay loop/> | <video src="https://user-images.githubusercontent.com/11827707/139964788-e0176b92-c6c3-4b74-8186-06d451eca979.mov" controls autoplay loop/> |
| NLP widget …

Fix sample chooser for vision & audio widgets

---

docs/sagemaker/_sections.yml
docs/sagemaker/getting-started.md
docs/sagemaker/main.md

This PR adds a quick start guide for SageMaker, showing a basic end-to-end example of fine-tuning and deploying a pretrained model on SageMaker. Also replaces the old FAQs section on the main page with a link to the Reference.

Add get started guide for SageMaker

---

setup.py

To be able to do
```python
from typing_extensions import TypeAlias
```
we need to have `typing-extensions>=3.7.4.3`
Fix https://github.com/huggingface/huggingface_hub/issues/452

Fix typing-extensions minimum version

---

src/huggingface_hub/repository.py

This fixes the deprecation warning one gets when creating a `Repository` object.

Fix argument order in `create_repo` for `Repository.clone_from`

---

src/huggingface_hub/repository.py

Should default to `True` so that two consecutive `push_to_hub` do not end up failing. Will greatly reduce friction in examples/downstream usage.

clean_ok should be True by default

---

docs/sagemaker/getting-started.md

It's a minor fix on the sample code for resolving `NameError: name 'test' is not defined.`

Typo fix: sample code for Amazon SageMaker

---

src/huggingface_hub/commands/user.py

Minor fix for the command line interface when using huggingface-cli login function.

Typo fix: huggingface-cli for login

---

widgets/src/lib/InferenceWidget/shared/WidgetTextarea/WidgetTextarea.svelte
widgets/src/lib/InferenceWidget/widgets/FillMaskWidget/FillMaskWidget.svelte
widgets/src/lib/InferenceWidget/widgets/TextToSpeechWidget/TextToSpeechWidget.svelte
widgets/src/lib/InferenceWidget/widgets/TokenClassificationWidget/TokenClassificationWidget.svelte

1. Updated widgets (FillMaskWidget (which is TextClsWidget), TokenClsWidget, TextToSpeechWidget) to use `textarea` as their input element, rather than `input`. 
2. Made `textarea` input height auto-growable until 500px
[Checkout netlfy demo here](https://6193b4a5ec227207e6ff4874--huggingface-widgets.netlify.app/)
cc: @Pierrci @lewtun 
Closes https://github.com/huggingface/moon-landing/issues/1523
<video src="https://user-images.githubusercontent.com/11827707/141996190-8c8f551f-f4d0-48b6-b451-071ea81737f7.mov" controls autoplay loop/>

Update some widgets to use `textarea` rather than `input`

---

widgets/src/lib/InferenceWidget/shared/WidgetOutputChart/WidgetOutputChart.svelte

Changing some `p` elements to `span`:
1. Nothing changes render-wise
2. When it is <p>, prose tailwind CSS messes up the view on widgets inside course pages

Minor p -> span change

---

widgets/src/lib/InferenceWidget/shared/WidgetTextarea/WidgetTextarea.svelte

While adding a hack to bypass firefox (noted [here](https://github.com/huggingface/huggingface_hub/pull/474#pullrequestreview-808286966)), I broke the fillmask widget. This pr is a hotfix for that.

Hotfix fillmask widget

---

widgets/src/lib/InferenceWidget/shared/WidgetOutputText/WidgetOutputText.svelte
widgets/src/routes/index.svelte

When there is a newline, render output of TextGenerationWidget as code output (pre with new line rendering)
[Try here](https://6197ca7027904a0a2fd3ff80--huggingface-widgets.netlify.app/) the `huggingface-course/codeparrot-ds` checkpoint
<video src="https://user-images.githubusercontent.com/11827707/142653609-b7edca42-70ee-4128-9d97-41d6ae6486fe.mov" controls autoplay loop/>
cc: @lvwerra

Render newlines in code outputs

---

src/huggingface_hub/commands/user.py

This PR adapts the `notebook_login` widget to use the new token system (it doesn't change anything behind the scenes, it's just a front change) by linking to the token page of the user and hiding the login with password by default:
Clicking the link sends the user [here](https://huggingface.co/settings/token). Clicking the button at the button switches to the old notebook login interface.

Adapt notebook login to use tokens

---

docs/hub/spaces.md

This PR fixes a mismatch between the filename `package.txt` needed to install external dependencies in a Space and what is actually used in the Docker logs:
```
Step 5/25 : COPY packages.txt /root/packages.txt
```
This problem was reported by a participant in the 🤗 course event 😉

Fix filename for external dependencies in a Space

---

src/huggingface_hub/repository.py

Fixes #424 
Started a draft to add the ability to skip large files when git cloning a repo from the hub (as I need it ASAP).
To do:

Add ability to skip large files

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

it was initially implemented just for backward compat to the old S3 system
I doubt anyone's using it, and it feels "unnatural" as an API now that every file is repo-centric

Deprecate `list_repos_objs` as probably no-one uses it

---

src/huggingface_hub/constants.py
src/huggingface_hub/file_download.py
src/huggingface_hub/snapshot_download.py
tests/test_snapshot_download.py

This PR adds more function params to the snapshot download method. @LysandreJik @osanseviero - are there any reasons why we wouldn't add those?

[Snapshot download] Allow to load local repo id with snapshot download

---

src/huggingface_hub/commands/user.py
src/huggingface_hub/hf_api.py
tests/test_hf_api.py
tests/testing_constants.py

Offers the access tokens as the main login handler.
When doing `huggingface-cli login`, a `Token: ` prompt will appear, preceded by the following:
```
To login, `huggingface_hub` now requires a token generated from https://huggingface.co/settings/token.
To login with username and password instead, interrupt with Ctrl+C.
```
If the user does Ctrl+C, it redirects automatically to a Username/Password prompt:

Access tokens

---

src/huggingface_hub/commands/user.py

Quick fix for:
```python
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/huggingface_hub/commands/user.py in login_token_event(t)
380         token_widget.value = ""
381         clear_output()
--> 382         _login(token=token)
383 
384     token_finish_button.on_click(login_token_event)
TypeError: _login() missing 1 required positional argument: 'hf_api'
```
cc @patrickvonplaten : small blocker for the CommonVoice demo

Pass the HfApi object when using `notebook_login` with a token

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py
tests/test_hubmixin.py
tests/test_keras_integration.py

api change: /api/datasets[...] now returns cardData not card_data (for consistency with models)
We didn't find any evidence for people using this API attribute yet so are hotfixing it on master

[Hotfix][API] card_data => cardData on /api/datasets

---

src/huggingface_hub/repository.py

The environment changes that had to happen for the `GIT_LFS_SKIP_SMUDGE` ended up modifying the progress bars for that specific command.
A test should be setup to ensure this doesn't happen.

Fix the progress bars when cloning a repository

---

tests/README.md

Adds a small markdown file that contains directions for running the test suite, since it took me a moment to get everything setup on my side.

Add test directions

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

Searching by `authors` and `search` (so just a string) is currently missing, linked to #513 
I've edited the logic inside `hf_api.HfApi.list_models`. Pasted below for convenience
```python
def list_models(....):
....
if filter is not None:
params.update({"filter": filter})
params.update({"full": True})
if author is not None: # <- here
params.update({"author": author})
if search is not None: # <- here
params.update({"search": search})
.....
```
[EDIT] After discussing it we also included the same logic in `list_datasets`
I've added a few new lines in the tests under `HfApiPublicTest`, maybe a test with a complex query + `authors`, `search` is not a bad idea.
**Since I've edited my `main` branch on the `fork` this branch has the commits from the `main` branch that contains the code for …

Search by authors and string

---

widgets/src/lib/InferenceWidget/shared/WidgetOutputText/WidgetOutputText.svelte
widgets/src/routes/index.svelte

Reverts huggingface/huggingface_hub#484
#484 was doing:
if output contains `\n` newline character, then render like code output
otherwise, render as a normal text output

Revert "Render newlines in code outputs"

---

api-inference-community/docker_images/fairseq/app/pipelines/audio_to_audio.py

Fixes the dimension of the output of AudioToAudioPipeline.

Hotifixing `fairseq`.

---

widgets/src/lib/InferenceWidget/shared/WidgetDropzone/WidgetDropzone.svelte
widgets/src/lib/InferenceWidget/shared/WidgetHeader/WidgetHeader.svelte
widgets/src/lib/InferenceWidget/shared/WidgetInfo/WidgetInfo.svelte
widgets/src/lib/InferenceWidget/shared/WidgetInputSamples/WidgetInputSamples.svelte
widgets/src/lib/InferenceWidget/shared/WidgetQuickInput/WidgetQuickInput.svelte
widgets/src/lib/InferenceWidget/shared/WidgetWrapper/WidgetWrapper.svelte
widgets/src/lib/InferenceWidget/widgets/FillMaskWidget/FillMaskWidget.svelte
widgets/src/lib/InferenceWidget/widgets/TableQuestionAnsweringWidget/TableQuestionAnsweringWidget.svelte
widgets/src/lib/ModelPipelineTag/ModelPipelineTag.svelte

Fix  [#1627](https://github.com/huggingface/moon-landing/issues/1627)
WDYT @gary149  ? One minor issue with the current design is that on mobile the "select example" dropdown sometimes looks like it's part of the widget form it self. Maybe we could accentuate a bit the difference between the two section - not sure how much it really matters.

Adjust widget responsiveness

---

tasks/src/image-classification/data.ts
tasks/src/sentence-similarity/data.ts
tasks/src/summarization/data.ts
tasks/src/translation/data.ts

- added sacrebleu as indicated by @thomwolf
- fixed name of f1 so that the definition will be gathered from hf.co/metrics
- removed squad from sentence similarity datasets (honestly no idea when it ended up there 🥲)
cc: @osanseviero

Small additions & edits

---

js/src/lib/components/InferenceWidget/shared/WidgetHeader/WidgetHeader.svelte
js/src/lib/components/ModelPipelineTag/ModelPipelineTag.svelte

close #604 
only visual change is on task label mouseover (underline + title attribute):

Update widget links

---

tests/test_hf_api.py

The `apiToken` is only available on the `valid_org` organization in the staging environment.
Thanks for raising the issue, @julien-c.

Remove rogue API token

---

.github/workflows/python-tests.yml
src/huggingface_hub/constants.py
src/huggingface_hub/hf_api.py
tests/test_hf_api.py

Closes https://github.com/huggingface/huggingface_hub/issues/557

Include "model" in repo_type to keep consistency 

---

setup.py
src/huggingface_hub/keras_mixin.py
tests/test_hubmixin.py
tests/test_keras_integration.py

This PR addresses the discussion we had in [#598](https://github.com/huggingface/huggingface_hub/issues/598).
I did a quick and dirty implementation and haven't tested yet so it's a WIP, I want to hear the review first.
For context: this parameter prevents models with custom optimizers (like the ones built with tfa) to be serialized and is by default set to True so I set it to False and made it an optional parameter.
cc: @osanseviero

include_optimizer parameter introduced to push_to_hub_keras()

---

docs/hub/model-repos.md

Fixes #643 
This PR clarifies the non-text example URLs in the documentation.
cc @osanseviero @julien-c

DOC change and clarify non-text example URLs

---

src/huggingface_hub/keras_mixin.py

Fixing the typo in docstring for `push_to_hub_keras`

fix: typo in docstring

---

js/src/lib/components/InferenceWidget/shared/WidgetTextarea/WidgetTextarea.svelte

This PR fixes a bug where copied text was being pasted with a style inside the span text area (which is the default span behaviour)
Test it [here on netlify](https://61f16ed04efc61d1044b4c73--huggingface-widgets.netlify.app/facebook/bart-large-cnn)

Fix pasting copied text inside TextAreaWidget

---

docs/hub/adding-a-model.md

The hub now prevents binary files over 1MB from being committed (unless LFS)

Add precision about binary LFS files

---

src/huggingface_hub/keras_mixin.py
tests/test_keras_integration.py

TensorBoard for Keras models

---

setup.py
tests/test_hf_api.py
tests/test_hubmixin.py
tests/test_keras_integration.py

Upgrades the `huggingface_hub` library quality tool `black` to use the first stable release of `black`, version 22.0.

Upgrade black to version ~=22.0

---

js/README.md

`package.json` and `package-lock.json` are not in sync, and doing an `npm install` wouldn't work. We either need to sync them up, or ask users to install with `npm ci` instead. This PR suggests the latter.
Note that I'm an absolute newbie with JS, and took me a while to figure this out with the help of a friend of mine, and I'm not sure which solution we should take.

DOC use npm ci instead on npm install

---

src/huggingface_hub/repository.py

Currently, the `post_method` of a `CommandInProgress` is executed each time the flag `is_done` is accessed. This can yield to errors as seen in the Transformers CI (with some LFS pruning attempted in folders that don't exist anymore).
This PR destroys the `post_method` once executed, which ensures it is only executed once.

Ensure `post_method` is only executed once

---

modelcard.md

`library_name` was missing in the docs (which was the reason why I broke the 🤗 Hub yesterday) so I added it.

added library_name to yaml template

---

js/src/lib/components/InferenceWidget/shared/WidgetTextarea/WidgetTextarea.svelte
src/huggingface_hub/hub_mixin.py
src/huggingface_hub/keras_mixin.py

Private repositories do not need a paying subscription; this PR removes that from the docstring of the `push_to_hub` function.
cc @osanseviero

Remove paying subscription mention from docstring

---

docs/hub/adding-a-model.md
docs/hub/security.md
docs/sagemaker/reference.md
src/huggingface_hub/commands/user.py

As a result of [huggingface/moon-landing/pull/2159](https://github.com/huggingface/moon-landing/pull/2159)

docs(links): Update `settings/token` to `settings/tokens`

---

src/huggingface_hub/hf_api.py

This fixes https://github.com/huggingface/huggingface_hub/issues/650
We simply set HF_ENDPOINT to the URL of a private hub, and use the API as-is.  If the API itself has the endpoint, then the environment variable is ignored.
FYI, the same variable is used by the datasets library for a similar purpose.

Add support for private hub

---

js/src/lib/inferenceSnippets/servePython.ts

Right now the API url displays the user token instead of the modelId 🙈

Fix API_URL in servePython.ts

---

api-inference-community/docker_images/fairseq/requirements.txt

[facebook/tts_transformer-en-ljspeech](https://huggingface.co/facebook/tts_transformer-en-ljspeech?text=Hello%2C+this+is+a+test+run.) inference is broken, but this is fixed in a later `fairseq` version (this has not made to a release yet). I could add this to a unit test, but the library failing for a certain type of model is not something we should have in our test coverage imo

Bump fairseq version to avoid bug

---

docs/hub/main.md

Updated to reflect new move repo authorizations in https://github.com/huggingface/moon-landing/pull/2204 (and fixed a few typos)

Update rename/transfer repo rule docs

---

api-inference-community/api_inference_community/validation.py

This is required to unblock #747 and as part of #332.

Add object-detection to community Inference API

---

src/huggingface_hub/utils/endpoint_helpers.py
tests/test_hf_api.py

This PR fixes a but where it would raise if emissions is a dict, and when the value is something such as `"17g"`
This issue recently caused a failure in the test suite.
cc @muellerzr @osanseviero @LysandreJik

FIX fix a bug in _filter_emissions to accept numbers w/o decimal and dict emissions

---

src/huggingface_hub/README.md
src/huggingface_hub/hf_api.py
src/huggingface_hub/keras_mixin.py
tests/test_hf_api.py

This fixes an issue with the logging of `hf_api`, replaces `logger.error` for deprecation warnings by a `FutureWarning`, and adds a small document regarding how to use logging with `huggingface_hub`.
cc @FrancescoSaverioZuppichini as you have raised the issue with `hf_api` this morning.

Logging fix for `hf_api`, logging documentation

---

tests/test_keras_integration.py

TensorBoard logs are in parent directory of the repository so they weren't removed along with repository, I added lines to remove them so that they don't bug tensorboard tests.

Added tempfile for tensorboard logs in tensorboard tests in test_keras_integration.py

---

docs/hub/org-cards.md

Lets users know they can write simple Markdown text or more complicated HTML to style their org card if they want to (#756 ).

HTML in org card

---

docs/hub/libraries.md

Following up on #747, this PR updates the list of supported libraries in HF hub by adding docTR.
I may have checked the wrong columns and I'm not adamant about what some specifically means, so feel free to let me know if I made a few mistakes :ok_hand: 
Any feedback is welcome!
cc @osanseviero @Narsil

docs: Updates the list of libraries in the hub

---

src/huggingface_hub/keras_mixin.py

Removed `show_layer_activations` for old version compatibility. see [the PR](https://github.com/huggingface/huggingface_hub/pull/760)

removed show_layer_activations for old version compatibility

---

.github/workflows/python-tests.yml
src/huggingface_hub/keras_mixin.py

The GH Actions workflow makes reference to the python-version but there is no matrix being set. I'm not sure what's the behavior right now, but I think this is a bug
cc @merveenoyan @nateraw @muellerzr

Fix pytorch and tensorflow python matrix

---

.github/ISSUE_TEMPLATE/config.yml

This adds links to the the other recently created two repos and the forum when people try to open an issue.
You can see how it'd look like here: https://github.com/scikit-learn/scikit-learn/issues/new/choose
cc @LysandreJik @osanseviero

MNT add links to related projects and the forum on issue template

---

tests/test_inference_api.py

The test was failing as the model called through the inference API was not pinned, hence it was taking some time to load and returning the load message. This change uses a pinned test model.

Test fixes for audio inference API call

---

.github/workflows/python-tests.yml
src/huggingface_hub/hf_api.py
tests/test_hf_api.py
tests/test_hubmixin.py
tests/test_keras_integration.py
tests/test_repository.py
tests/test_snapshot_download.py

This PR makes the CI to fail on `FutureWarning` so that our test suite won't use our own deprecated API and our codebase use new API from our dependencies.

CI Error on FutureWarning

---

.github/workflows/python-tests.yml
setup.py

This PR removes tests on 3.6 and adds 3.10 support on the CI.
Fixes #786

CI support python 3.7-3.10 - remove 3.6 support

---

js/src/lib/components/InferenceWidget/widgets/AudioClassificationWidget/AudioClassificationWidget.svelte
js/src/lib/components/InferenceWidget/widgets/AutomaticSpeechRecognitionWidget/AutomaticSpeechRecognitionWidget.svelte
js/src/lib/components/InferenceWidget/widgets/ImageClassificationWidget/ImageClassificationWidget.svelte
js/src/lib/components/InferenceWidget/widgets/ObjectDetectionWidget/ObjectDetectionWidget.svelte
js/src/lib/components/InferenceWidget/widgets/TextGenerationWidget/TextGenerationWidget.svelte
js/src/lib/components/InferenceWidget/widgets/TokenClassificationWidget/TokenClassificationWidget.svelte
js/src/lib/components/InferenceWidget/widgets/ZeroShowClassificationWidget/ZeroShotClassificationWidget.svelte

Closes huggingface/hub-docs#18
Some pipeline types can produce valid empty output. Despite the output being valid, it is rather confusing for a user. Therefore, in those situation, there will be warning message about empty output. 
(we already handle it for empty outputs in Object Detection pipeline (see [internal](https://huggingface.slack.com/archives/C025RSDHH54/p1632151012057600?thread_ts=1632148300.052900&cid=C025RSDHH54)), this PR applying the same warning UI to other pipelines)
[try netlify](https://61faa5931f3fb90085d0d5ab--huggingface-widgets.netlify.app/dbmdz/bert-large-cased-finetuned-conll03-english)
cc: @osanseviero @adrinjalali

Warn empty valid output

---

tests/test_hf_api.py

There is a test few lines below that does exactly the same (test_model_info_with_security).
This partially fixes #785. There is an unrelated TF test failing (cc @merveenoyan)

Remove redundant part of security test

---

tests/test_keras_integration.py

I thought I pushed this change but it wasn't pushed and then I saw the other branch was removed because it was merged.
I couldn't reproduce the error on my local, my guess is that I was calling `delete_repo` out of `tempfile` which caused the repository not found error. Hopefully this fix will work.

TST calling delete_repo under tempfile for fixing the test

---

setup.py
src/huggingface_hub/constants.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/repository.py
tests/test_hf_api.py
tests/testing_utils.py

👨‍💻 Configure HF Hub URL with environment variable

---

.github/conda/meta.yaml
.pre-commit-config.yaml
setup.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/utils/_fixes.py

I've tested locally for all possibilities of installed packages (simplejson, json, old and new requests).
I don't think we need to add CI to test for old requests though.
Fixes #816

MNT support oder requests versions

---

src/huggingface_hub/constants.py
src/huggingface_hub/hf_api.py

This improves consistency across HF ecosystem.
https://github.com/huggingface/transformers/blob/c595b6e6a90c29242c9dbfeecc5b132fe2e3d1f4/src/transformers/utils/hub.py#L110
https://github.com/huggingface/datasets/blob/8c5f27889657a1a6a7203b2f054bd0ceffce2178/src/datasets/config.py#L24
Fixes #798

Rename the env variable `HF_ENDPOINT`.

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

Fixes https://github.com/huggingface/huggingface_hub/issues/821
If user passes `name` as a positional argument and pass `organization` as well, we fail, whereas we should raise a `FutureWarning`.
cc @LysandreJik @osanseviero 
This needs to be backported to 0.5.1 for a patch release.

FIX don't raise if name/organizaiton are passed postionally

---

docs/source/how-to-downstream.mdx
docs/source/how-to-inference.mdx
docs/source/how-to-upstream.mdx
docs/source/package_reference/hf_api.mdx
docs/source/searching-the-hub.mdx

This PR adds some general maintenance to the docs:
- Links functions to the appropriate section in the API reference.
- Cleans up code outputs, formatting, images/fixes code examples in Searching the Hub.
- Adds `DatasetSearchArguments` and `ModelSearchArguments` to the API reference.

Tidy up docs

---

src/huggingface_hub/hf_api.py
src/huggingface_hub/repository.py
tests/test_repository.py

Closes https://github.com/huggingface/huggingface_hub/issues/825.
Closed https://github.com/huggingface/huggingface_hub/issues/687.
This adds the option to automatically track binary files. It follows the following two assumptions:
- Binary files usually cannot be read with the `open` file object reader, which raises a unicode error.
- The file can sometimes be read even with the `open` keyword; in that case, we search for the null character which should only be present in binary files, and which seems to be what `grep` uses in order to identify binary files (and we use `grep` in the backend to look for these binary files)
This PR adds a new method, `auto_track_binary_files`, which automatically tracks binary files. 
A change could be seen as a breaking change, which is the …

Auto track binary files

---

docs/source/_toctree.yml
docs/source/quick-start.mdx

This PR adds a quick start guide as discussed in #841. It summarizes the core functionalities of the `huggingface_hub` library and quickly demonstrates how a user can interact with the Hub. I chose to show how to download files first since it doesn't require you to create an account and sign in like creating a repository and uploading files does. Feel free to let me know if that makes sense since typically you'd sign in and get all setup first before doing other things. 
I also created a separate section in the `toctree` for the landing page and quick start since they are more introductory-level type docs.

Add quick start guide

---

src/huggingface_hub/commands/user.py
src/huggingface_hub/repository.py
src/huggingface_hub/utils/__init__.py
src/huggingface_hub/utils/_subprocess.py

Implement a `run_subprocess` method to remove most of the verbosity introduced by `subprocess.run`

subprocess.run -> run_subprocess

---

pyproject.toml
setup.py
src/huggingface_hub/commands/lfs.py
src/huggingface_hub/commands/user.py
src/huggingface_hub/file_download.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/hub_mixin.py
src/huggingface_hub/inference_api.py
src/huggingface_hub/keras_mixin.py
src/huggingface_hub/repository.py
src/huggingface_hub/snapshot_download.py
src/huggingface_hub/utils/endpoint_helpers.py
tests/test_endpoint_helpers.py
tests/test_inference_api.py
tests/test_repository.py
tests/testing_utils.py

This PR adds `--preview` to `black` which handles strings much nicer.
cc @LysandreJik @osanseviero

MNT enable preview on black

---

docs/source/_toctree.yml
docs/source/how-to-downstream.mdx
docs/source/how-to-inference.mdx
docs/source/how-to-manage.mdx
docs/source/how-to-upstream.mdx
docs/source/package_reference/inference_api.mdx

As discussed in #818, this PR de-emphasizes integrating download/upload functions into third-party libraries. The guides simply tell a user how to use these functions. We can follow this up with an integration guide that provides more value to library maintainers/developers who want to integrate these functions into their libraries. This PR also splits the old upstream utility doc into:
1. How to upload files (`commit` context manager, `push_to_hub` and Git LFS).
2. How to create and manage a repository (`create_repo`, `delete_repo` `update_repo_visibility`, the `Repository` class and its associated git-commands). ~This page is still a work in progress :)~
3. Documents other `Repository` commands like `pull`, `add`, `commit` and `push`. I think it's nice for users to see they can manually …

Update how to guides

---

CONTRIBUTING.md

This PR updates the contribution guide based on conversation with @LysandreJik that we try not to have the author merge the PR anymore.

Update contribution guide for merging PRs

---

docs/source/_toctree.yml
docs/source/index.mdx

This PR updates `index.md` to focus only on the `huggingface_hub` library and removes mentions of the widgets and community API inference. This page provides: 
- A brief overview of what the Hub is and how the `huggingface_hub` is related to the Hub and what it can do. I think there may be some potential for confusion from users over the naming of the Hub (as a product) and `huggingface_hub` (as a library), so please let me know if I've made this distinction clear enough here!
- A lot of guardrails that will help users down the right path and find what they are looking for. This ensures a user can choose their topic and then find a resource to help them accomplish their task. Once we've merged the other PRs, I can add the links in :)
I didn't mention integrating third-party libraries yet …

Update landing page

---

src/huggingface_hub/hub_mixin.py

I know #847 is going to change a lot with the mixins, but this is a really helpful simple change that we leveraged in the HugGAN sprint that I figured we could add for now. Its nice to be able to skip LFS files when you're using a temp dir as your save dir (which you might be doing in a for loop, such as a training loop).

Add skip_lfs_files to mixins' push_to_hub

---

src/huggingface_hub/file_download.py
src/huggingface_hub/keras_mixin.py

This PR adds `library_name` and `library_version` to `snapshot_download` in Keras mixin.
I think existing `from_pretrained_keras` tests should cover this so I didn't write an additional test.

Enabling Keras download stats

---

src/huggingface_hub/keras_mixin.py
tests/test_keras_integration.py

This is a minor change that saves history as a JSON file, if history exists.
We check if history exists or not during parsing it to a markdown in `_parse_model_history()` so I handled it there not to write repetitive checks. It can be further improved inside, just wanted to keep them separately for the sake of readability. (will later refactor the whole mixin and card creation after sprint is done) This might not be the best choice ever so feel free to criticize.
Wrote a test to check if the file is there.

Keras: Saving history in a JSON file

---

src/huggingface_hub/commands/user.py

When invoking huggingface-cli login without active authentication, a helpful feedback message containing a link to the tokens page is given. The link however is followed immediately by a full stop . so that it lands on a 404 when clicked (macOS / "hyper" shell). This PR adds one space to avoid the false 404 and land on the right page.

Clickable link in huggingface-cli 

---

src/huggingface_hub/keras_mixin.py

This PR turns hyperparameters dictionary to table on model card.
Before: https://huggingface.co/merve/model-card-example
After: https://huggingface.co/merve/hyperparam_table
(You can scroll for more hyperparams)

ENH Keras Use table instead of dictionary for hyperparameters in model card

---

src/huggingface_hub/hf_api.py
src/huggingface_hub/utils/_deprecation.py
tests/test_hf_api.py

Pushes back the deprecation warnings to v0.8 as we're doing an express release for a forgotten commit.

Pushback deprecation for v0.7 release

---

src/huggingface_hub/__init__.py
src/huggingface_hub/snapshot_download.py
tests/test_snapshot_download.py

In https://github.com/huggingface/huggingface_hub/pull/874 we had to rename the `snapshot_download.py` file which makes `from huggingface_hub.snapshot_download import blah` fail.
This PR deprecated such imports and warns the user instead of failing.
Ref: https://github.com/scientific-python/lazy_loader/pull/9
cc @LysandreJik @osanseviero 
P.S.: I won't be available to apply suggestions here this week, but I think we should have this in the release. If you think anything needs to be changed in this PR, please apply the suggestions and then merge :)

MNT deprecate imports from snapshot_download

---

docs/source/_toctree.yml
docs/source/package_reference/utilities.mdx
src/huggingface_hub/file_download.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/utils/__init__.py
src/huggingface_hub/utils/_errors.py
tests/test_file_download.py
tests/test_hf_api.py

This PR adds finer error management to the Hugging Face Hub error messages.
Here's the difference between current `main` and this PR on the following errors:
<details>
<summary>An example for <code>hf_api</code>: <code>model_info</code></summary
<br>
Using the `model_info` method:
```py
In [1]: from huggingface_hub import model_info
In [2]: model_info('random_model')
```
Before:
```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 model_info('random_model')
[...]
File ~/Workspaces/Python/huggingface_hub/.env/lib/python3.10/site-packages/requests/models.py:960, in Response.raise_for_status(self)
957     http_error_msg = u'%s Server Error: %s for …
```

Refine 404 errors

---

src/huggingface_hub/constants.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/repocard.py
tests/test_hf_api.py
tests/test_snapshot_download.py
tests/testing_constants.py

cc @XCiD
Uses the new CI environment for tests, which uses Gitaly and is automatically updated to the latest version of the Hub.

🏗 Use `hub-ci` for tests

---

src/huggingface_hub/repository.py
tests/test_repository.py

This PR partially fixes https://github.com/huggingface/huggingface_hub/issues/672. 
I observed that the following error pops up when I create a repository using huggingface API `create_repo` and then have a local repository cloning from the URL **using a token** ([here](https://github.com/huggingface/huggingface_hub/issues/672#issuecomment-1150972003))
`ValueError: No space_sdk provided. create_repo expects space_sdk to be one of ['gradio', 'streamlit', 'static'] when repo_type is 'space'`
So I noticed the following block was causing the problem:
```
if token is not None:
whoami_info = self.client.whoami(token)
user = whoami_info["name"]
valid_organisations = [org["name"] for org in whoami_info["orgs"]]
if namespace is not None:
repo_id = f"{namespace}/{repo_id}"
repo_url += repo_id …
```

FIX Avoid creating repository when it exists on remote

---

src/huggingface_hub/README.md
src/huggingface_hub/__init__.py
src/huggingface_hub/_snapshot_download.py
src/huggingface_hub/commands/user.py
src/huggingface_hub/file_download.py
src/huggingface_hub/hf_api.py
tests/test_hf_api.py

This PR removes deprecations that should be removed with v0.8.0.

Remove deprecations

---

src/huggingface_hub/commands/lfs.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/utils/_errors.py
tests/test_hf_api.py

This adds the `X-Request-ID` header to all requests that have it.
This will result in the following change:
```diff
- requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/login
+ requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/login (Request ID: T97cILAtyKzdWeL6dRYYW)
```
Closes https://github.com/huggingface/huggingface_hub/issues/906

Add request ID to all requests

---

src/huggingface_hub/snapshot_download.py
tests/test_snapshot_download.py

This constant was available before the deprecation notice, so it should be available during the warning transition period.
Note that the sentence-transformers library makes use of this constant [link to code](https://github.com/UKPLab/sentence-transformers/blob/3433c001e5a9e0991ea09e85f8861f38eb0d6583/sentence_transformers/util.py#L407)

Constant was accidentally removed during deprecation transition

---

setup.py

Pins black to 22.3.0 in order to benefit from the --preview flag continuously. This flag adds reformats for strings, exceptions, logs, and others.
The recent black 22.6.0 version's --preview flag isn't compatible with the 22.3.0 and results in line changes.
This PR pins 22.3.0 as it was deemed the path with the least friction.

Pin black to 22.3.0 to benefit from a stable --preview flag

---

docs/source/how-to-downstream.mdx
docs/source/how-to-inference.mdx
docs/source/quick-start.mdx

Fixes #929. When the hub-docs were separated from this repo, all the assets were moved to the documentation-images dataset on the Hub, and these links weren't fixed.
There are also a couple URLs to the hub-docs that I've fixed here.

Docs: Fix some missing images and broken links

---

src/huggingface_hub/_snapshot_download.py
src/huggingface_hub/commands/user.py
src/huggingface_hub/file_download.py
src/huggingface_hub/hub_mixin.py
src/huggingface_hub/utils/logging.py
src/huggingface_hub/utils/sha.py
tests/test_hf_api.py
tests/test_hubmixin.py
tests/test_keras_integration.py
tests/test_lfs.py

Addresing [this](https://discuss.huggingface.co/t/push-keras-to-hub-fail-because-of-binary-files/19387/3) forum post. `git_add()` wasn't tracking for Hub Mixin so I fixed it.

FIX LFS track fix for Hub Mixin

---

docs/source/how-to-upstream.mdx
src/huggingface_hub/hf_api.py

This PR addresses #938. 
About the third point, I think if we show `upload_file` first (also shown in the Quickstart but not everyone may land there first) then it'll be easier for users to immediately get more value from the doc.

Clarify upload docs

---

README.md
docs/source/how-to-downstream.mdx
docs/source/package_reference/file_download.mdx
src/huggingface_hub/README.md

Main change is not promote the deprecated `cached_download` anymore, and instead focus primarily on `hf_hub_download`

[Doc] Update "Download files from the Hub" doc

---

src/huggingface_hub/commands/user.py

This is a convenient way to check what hub endpoint you're logged on to (public hub, private hub, etc.):
```
% huggingface-cli whoami
https://private-hub.huggingface.cloud
juliensimon
```
The codebase has some informational messages with hard-coded references to huggingface.co. I've left these alone, maybe we should clean them up at some point.

Display endpoint URL in whoami command

---

src/huggingface_hub/hf_api.py

If you call `create_commit` with an empty `commit_message` (either None or `""`) you will get an obscure error from the server. This PR catches it earlier to send a more informative error message.

Add a helpful errorwhen commit_message is empty in create_commit

---

src/huggingface_hub/_commit_api.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/utils/_errors.py

Related to #962 
This PR converts HTTP 400 errors from `/api/preupload` and `/api/commit` APIs into `ValueError`s
Suggestions/feedback welcome

✨ create_commit: more user-friendly errors on HTTP 400

---

setup.cfg
src/huggingface_hub/utils/endpoint_helpers.py

Low priority but W605 was disabled in flake8 checks. This PR re-enables it.
In short, since `"\d"` is not a proper escape sequence, python converts it to a `"\\d"` (and generates a `DeprecationWarning `). Good practice is to use the a r-string `r"\d"`.
This can also lead to misleading escape ("n" is escaped but not "d" in the example below):
```py
>>> "\n\d"
'\n\\d'
>>> r"\n\d"
'\\n\\d'
```

Enable flake8 on W605

---

.github/workflows/python-tests.yml
setup.cfg
setup.py

In the CI, we currently run the tests with the `--cov` option to get a code coverage report. However, as pointed out by @osanseviero in this PR (https://github.com/huggingface/huggingface_hub/pull/925), it is broken at the moment and only check coverage of the tests themselves. It has apparently already been discussed [here (internal url)](https://huggingface.slack.com/archives/C02V5EA0A95/p1657176912893549?thread_ts=1657099388.126399&cid=C02V5EA0A95) and [here (internal url)](https://huggingface.slack.com/archives/C02V5EA0A95/p1655984527352979). The purpose of the PR is to simply remove coverage for now as it is broken and give unreliable information. I will create a separate issue to fix it and enable it again (EDIT: this one https://github.com/huggingface/huggingface_hub/issues/977). …

Disable codecov + configure pytest FutureWarnings

---

src/huggingface_hub/__init__.py
src/huggingface_hub/file_download.py
tests/test_file_download.py

This PR adds the utility we use in Transformers to check if a file is in the cache when there is a connection error, while making it handle any repo type. I haven't done anything for it to be automatically used in case of connection error in `hf_hub_download`, as I don't know if it's something you want automatically baked in the library or not (in Transformers, we use this to load the files from the cache when there is any connection error, for instance a downtime on hf.co).
See [this comment](https://github.com/huggingface/transformers/pull/18438#discussion_r941304410) where we were talking of moving is here.

Add utility to load files from cache

---

docs/source/package_reference/utilities.mdx
src/huggingface_hub/file_download.py
src/huggingface_hub/utils/__init__.py
src/huggingface_hub/utils/_errors.py
tests/test_file_download.py

Fix https://github.com/huggingface/huggingface_hub/issues/979. See discussion is issue about `LocalEntryNotFound` inheritance.

Use a finer exception when local_files_only=True and a file is missing in cache

---

src/huggingface_hub/constants.py
src/huggingface_hub/file_download.py
src/huggingface_hub/repository.py
src/huggingface_hub/utils/__init__.py
src/huggingface_hub/utils/tqdm.py
tests/test_utils_tqdm.py

Solve https://github.com/huggingface/huggingface_hub/issues/978 (see API discussion in issue).
@sgugger Since both `HF_HUB_DISABLE_PROGRESS_BARS` env variable and `disable_progress_bars()`/`enable_progress_bars()` helpers are defined, there might be a conflict at some point if not correctly handled. For example a library, could call `disable_progress_bars()` even though the user has set `HF_HUB_DISABLE_PROGRESS_BARS=0`. Current solution is that `disable_progress_bars()` has higher priority but I'm not 100% sure it's clever.
The other solution would be the opposite: if `HF_HUB_DISABLE_PROGRESS_BARS` is set (either 0 or 1), then `disable_progress_bars`/`enable_progress_bars` are ignored in the code with a warning (`"cannot programmatical disable progress bars as verbosity has been set by …

Add helpers to disable progress bars globally + tests

---

src/huggingface_hub/file_download.py
tests/test_file_download.py
tests/testing_utils.py

Fix https://github.com/huggingface/huggingface_hub/issues/981.
Solution I went for is to force redirection only when the `Location` header is relative which is the case for renamed repos. It doesn't seem that an out-of-the-box argument exists to do that in `requests` so (internal) redirections are resolved and unpiled in this PR's code.
Also, I renamed `_request_with_retry` to `_request_wrapper` as it is an internal helper and its scope has expanded. I saw 
it was used at 3 different places only for its "_raise_if_offline_mode_is_enabled" feature instead of the initial "backoff" feature. I think a generic `_request_wrapper` is less misleading in that case.
@sgugger this impacts you this I saw it is used [here in Transformers](https://github.com/huggingface/transformers/blob/main/src/transf …

Handle redirections in `hf_hub_download` for a renamed repo

---

src/huggingface_hub/_snapshot_download.py
src/huggingface_hub/file_download.py
tests/test_cache_layout.py

In Transformers, we very often try to download files that do not exist: this is because each tokenizer has a list of optional files so we try to download them all and intercept the errors for those that do not exist. There is also the situation with very large model not having a weight filename like regular models but an index file instead.
This works all fine, but some users are trying to optimize things like calls to `pipeline`, and each of those requests where a file does not exist takes a bit of time. Therefore, this PR proposes a way to cache the non-existence of files at a given commit, so we can use that cache information and not try to download a file we know does not exist at a specific commit.
I suggest using the same architecture as the `snapshots` folder with a `.no_exist` …

Cache non-existence of files or completeness of repo

---

.github/workflows/python-tests.yml
README.md
codecov.yml
setup.py
tests/test_hubmixin.py

Related to https://github.com/huggingface/huggingface_hub/issues/977.
Draft mode since it's not close to be reviewed :D

Enable coverage in CI

---

src/huggingface_hub/inference_api.py

We've moved to using `"tabular-{classification, regression}"` names for tasks, this reflects the change on the API backend side.
cc @Narsil @osanseviero

MNT add tabular task types to InferenceApi

---

src/huggingface_hub/fastai_utils.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/hub_mixin.py
src/huggingface_hub/keras_mixin.py

Fix https://github.com/huggingface/huggingface_hub/issues/897. 
Mentioned issue has been solved server-side but it's still a good excuse to align the type for `private` argument. Currently it was either `private: Optional[bool] = None` or `private: bool = None`. This PR removes the possibility to have a `None` value for `private`. Default value is not `False`. Behaviour is expected to be exactly the same everywhere.

Make private a boolean-only value.

---

tests/test_keras_integration.py

In the keras tests, `HubKerasFunctionalTest` was inheriting from `HubKerasSequentialTest` itself inheriting from `HubMixingTestKeras`. Inheritance was useful to get `setUpClass` and `tearDown` initializers in all 3 classes. However, test cases were also all inherited which duplicated them at runtime (some of them being ran 3 times exactly with the same parameters).
This PR makes the inheritance from a common parent class. Number of test cases went from 44 to 22, reducing redundancy.
**EDIT:** some others tests seem to be duplicated as well (source code itself is copy-pasted) but addressing this is not the purpose of this PR.

Remove duplicated tests in Keras mixins

---

src/huggingface_hub/utils/_errors.py
tests/test_hf_api.py

Related to https://github.com/huggingface/huggingface_hub/issues/1012 and https://github.com/huggingface/moon-landing/issues/3703.
Now the error message returned by the server is added to the HTTPError. Example for a gated dataset:
```py
from huggingface_hub import snapshot_download
snapshot_download(
"sbrandeis/gated-fields",
repo_type="dataset",
use_auth_token="xxx",
)
```
```
Traceback (most recent call last):
File "/Users/lucain/projects/huggingface/huggingface_hub/imtesting.py", line 3, in <module>
snapshot_download(
File "/Users/lucain/projects/huggingface/huggingface_hub/src/huggingface_hub/utils/_deprecation.py", line 93, in inner_f
return f(*args, **kwargs)
File "/Users/lucain/projects/huggingface/huggingface_hub/src/huggingface_hub/_snapshot_download.py", line 168, in …
```

Add server message to HTTPError (if any)

---

src/huggingface_hub/repository.py

This PR simply adds a better error message for the following use case:
```python
from huggingface_hub import Repository
repo = Repository(local_dir="data", clone_from=DATASET_REPO_URL, use_auth_token=TOKEN)
```
where `TOKEN` is an org token

[Repository] Add better error message

---

src/huggingface_hub/hf_api.py

Fix https://github.com/huggingface/huggingface_hub/issues/1002. See https://github.com/huggingface/huggingface_hub/issues/1002#issuecomment-1223698972.
Since `securityStatus` can be explicitly requested by a user, let's add it to the default ModelInfo class.
Note: it was already implicitly added when returned by the server (see code below from [`__init__`](https://github.com/huggingface/huggingface_hub/blob/c03bd2917c35b44d6a38a63dac4b0f72dad3ab99/src/huggingface_hub/hf_api.py#L269) and discussed [here](https://github.com/huggingface/huggingface_hub/pull/951#discussion_r926460408)) but not default to None if not returned.
```py
for k, v in kwargs.items():
setattr(self, k, v)
```

Add securityStatus to ModelInfo object with default value None.

---

src/huggingface_hub/file_download.py

@sgugger Sorry I realized I merged https://github.com/huggingface/huggingface_hub/pull/1029 without removing the validation for `hf_hub_url` and `hf_hub_download`. As `repo_id="datasets/.../..."` is used in `transformers` I guess it's better to remove the validation for now until `transformers` is updated. Since I'm not exactly sure how critical/problematic this is, I let you tell me what you prefer to do. I can also put a warning message for wrong usage if you think it's not damaging the user experience.
My only concern is that we set validation back whenever possible and at most in a few releases (v0.12 ?). Your call :)
(cc @LysandreJik also)
Related: https://github.com/huggingface/huggingface_hub/issues/1008, https://github.com/huggingface/huggingface_hub/pull/1029#issue-1358903151 and …

Remove repo_id validation in hf_hub_url and hf_hub_download

---

src/huggingface_hub/hf_api.py
src/huggingface_hub/utils/_cache_manager.py
src/huggingface_hub/utils/_validators.py

There were extra markdown bullet points in `Raise` docstrings
which is causing UI bug:

Fix raise syntax: remove markdown bullet point

---

src/huggingface_hub/file_download.py
src/huggingface_hub/lfs.py
src/huggingface_hub/utils/__init__.py
src/huggingface_hub/utils/_http.py
tests/test_utils_http.py
tests/testing_utils.py

Fix https://github.com/huggingface/huggingface_hub/issues/1027.
This PR adds a separate helper to perform HTTP requests with a backoff strategy. Retries can be made on specific exceptions or specific status codes. By default, we mainly target Connection timeout and HTTP 503 Service Unavailable. It is a slight variation of the existing backoff implementation in `_request_wrapper` but separated so that we can unit tests and document it properly.
This PR adds backoff usage by default when pushing a LFS file to the Hub, which is the initial purpose of https://github.com/huggingface/huggingface_hub/issues/1027. At the moment sleep times will increase as such: 1s, 2s, 4s, 8s, 8s, 8s... 
I did not add the helper in the documentation since I'm not exactly sure yet if that's something we want to …

Handle backoff on HTTP 503 error when pushing repeatedly

---

src/huggingface_hub/file_download.py
tests/test_file_download.py

This PR aligns `try_to_load_from_cache` with its Transformers counterpart to return a special value when a file does not exist for a given repo/revision and that fact has been cached.

try_to_load_from_cache returns cached non-existence

---

docs/source/how-to-cache.mdx
src/huggingface_hub/commands/cache.py
src/huggingface_hub/utils/_cache_manager.py
tests/test_utils_cache.py

Add `last_modified` and `last_accessed` info to the cache scanner. Scanned as float values (timestamp) and displayed as "timesince" string (`2 weeks ago`).
This is a preliminary work for the https://github.com/huggingface/huggingface_hub/issues/1025.
Implementation is based on [python's `os.stat` function](https://docs.python.org/3/library/os.html#os.stat) and applied only to the blob files themselves and not the symlinks (that are more platform-dependent).
```text
REPO ID                       REPO TYPE SIZE ON DISK NB FILES LAST_ACCESSED LAST_MODIFIED REFS            LOCAL PATH                                                                   
----------------------------- --------- ------------ -------- ------------- ------------- --------------- …
```

1025 add time details to scan cache

---

src/huggingface_hub/_snapshot_download.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/inference_api.py
src/huggingface_hub/keras_mixin.py
src/huggingface_hub/repository.py
tests/test_hf_api.py
tests/test_hubmixin.py
tests/test_inference_api.py
tests/test_keras_integration.py

This PR deprecates the `token` argument in read-only methods of `HfApi` in favor of `use_auth_token`.
`use_auth_token` is more flexible as it allows not passing a token, whereas `token=None` fetches the token from `HfFolder`.
I personally prefer the semantics of `use_auth_token`, that I find very legible:
- `use_auth_token=False`
- `use_auth_token="token"`
- `use_auth_token=True`
cc @lhoestq

🗑 Deprecate `token` in read-only methods of `HfApi` in favor of `use_auth_token`

---

src/huggingface_hub/lfs.py

Fix https://github.com/huggingface/huggingface_hub/issues/1056 (cc @KOLANICH)

Remove legacy helper 'install_lfs_in_userspace'

---

src/huggingface_hub/repository.py
tests/test_repository.py

Fix https://github.com/huggingface/huggingface_hub/issues/1055.
I also start to think that `clone_from` method should be a standalone private helper (e.g.: not meant to be used by end users, just via the `clone_from` attribute at init). This would avoid having HF-specific attributes like `repo_type` in `Repository`: once initialized the value is not needed anymore.

1055 deprecate private and repo type in repository class

---

docs/source/package_reference/file_download.mdx
src/huggingface_hub/__init__.py
src/huggingface_hub/file_download.py
tests/test_file_download.py
tests/testing_utils.py

Fix https://github.com/huggingface/huggingface_hub/issues/1028.
By using the officially supported `get_hf_file_metadata`, `transformers` can stop using `_request_for_retry` and `_normalize_etag` private methods  (cc @sgugger @LysandreJik).
Edit: reverted back to Draft PR as the tests are not implemented.

Add get_hf_file_metadata to fetch metadata from the Hub

---

tests/test_repocard.py

Fix https://github.com/huggingface/huggingface_hub/issues/1010.
The issue seems to have been solved by @nateraw changes (https://github.com/huggingface/huggingface_hub/pull/940). I added a regression test just in case in the future.
(cc @cakiki)

Add regression test for empty modelcard update

---

src/huggingface_hub/constants.py
src/huggingface_hub/repocard.py

Hard-coding the default cache lead to a broken path with slash on Windows
Fix https://github.com/huggingface/simenv/issues/217

Fix default cache on windows

---

docs/source/quick-start.mdx
setup.py
src/huggingface_hub/__init__.py
src/huggingface_hub/_commit_api.py
src/huggingface_hub/_snapshot_download.py
src/huggingface_hub/commands/user.py
src/huggingface_hub/fastai_utils.py
src/huggingface_hub/file_download.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/hub_mixin.py
src/huggingface_hub/keras_mixin.py
src/huggingface_hub/repository.py
src/huggingface_hub/utils/__init__.py
src/huggingface_hub/utils/_deprecation.py
src/huggingface_hub/utils/_headers.py
src/huggingface_hub/utils/_hf_folder.py
tests/conftest.py
tests/test_hf_api.py
tests/test_inference_api.py
tests/test_snapshot_download.py
tests/test_utils_deprecation.py
tests/test_utils_headers.py
tests/testing_utils.py

TLDR; this works with this PR:
```py
file = hf_hub_download("CompVis/stable-diffusion-v1-4", "README.md")
```
---
(cc @julien-c @osanseviero @LysandreJik @apolinario @patrickvonplaten @Pierrci)
Fix https://github.com/huggingface/huggingface_hub/issues/926.
(related to [this discussion](https://huggingface.slack.com/archives/C03V11RNS7P/p1663331447986929) (internal link), [this discussion](https://huggingface.slack.com/archives/C02EMARJ65P/p1663771575035239) and [this discussion](https://docs.google.com/document/d/1ZE0pM8kry56Qtob5mIAYuGi5ZKpR8zTNnekEvPHtDgU/edit) as well (internal link))
The goal is to have a centralized way to handle tokens in `huggingface_hub` (and downstream libraries) that causes as low friction as possible for the users.
~The idea here is to keep the rule "if token …

Always send the cached token when user is logged in

---

src/huggingface_hub/file_download.py
tests/test_cache_no_symlinks.py

Related to https://github.com/huggingface/huggingface_hub/issues/1062#issuecomment-1255719962.
Issue is that we were checking the support of symlinks globally (in `/tmp`) instead of a per-folder check. This can be an used if the cache dir and the tmp dir are mounted on different volumes with different rules. This implementation should not be safer.
Also, warning message is displayed once per cache dir in use. In a vast majority of cases this means once per runtime since cache directory usually don't change.

Check symlinks support per directory instead of globally

---

src/huggingface_hub/fastai_utils.py
src/huggingface_hub/file_download.py
src/huggingface_hub/keras_mixin.py
src/huggingface_hub/repocard.py
src/huggingface_hub/utils/__init__.py
src/huggingface_hub/utils/_headers.py
src/huggingface_hub/utils/_runtime.py
tests/test_fastai_integration.py
tests/test_hubmixin.py
tests/test_keras_integration.py
tests/test_repocard.py
tests/test_tf_import.py
tests/test_utils_headers.py
tests/test_utils_runtime.py

Fix https://github.com/huggingface/huggingface_hub/issues/1018.
For the user agent, I took the same implementation as before (custom library name/version, python, huggingface_hub, tensorflow, torch, fastai, fastcore). This is only a first version, we can iterate afterwards if we want to update this rule.
I also moved all imports to a `_runtime.py` utility trying to keep backward compatibility everywhere for non private methods/attributes.
(cc @Kakulukian @Pierrci who where interested in having this)

Add user agent to all requests with `huggingface_hub` version (and other)

---

docs/source/how-to-cache.mdx
src/huggingface_hub/constants.py
src/huggingface_hub/file_download.py
src/huggingface_hub/utils/_headers.py
tests/test_utils_headers.py

Following recent comment from @lhoestq in https://github.com/huggingface/huggingface_hub/pull/1064#discussion_r979801597.
This way `HF_HUB_DISABLE_SYMLINKS_WARNING=0` would not be considered as true. If that's fine, I'll cherry-pick it for the v0.10 release (once merged).

Explicit true value for environment variables

---

src/huggingface_hub/_commit_api.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/lfs.py
src/huggingface_hub/utils/__init__.py
src/huggingface_hub/utils/_headers.py
tests/test_hf_api.py

Fix a regression when uploading a file as LFS using the `create_commit` endpoint. Token was NOT supposed to be `None` but wasn't checked. Now token is optional everywhere and retrieved just before making a HTTP call. This regression has been introduced by https://github.com/huggingface/huggingface_hub/pull/1064 (I did not see the use of `HTTPAuthToken(...)` for LFS endpoints). I added a regression test to ensure it works in the future.
Related to this [test failure](https://github.com/huggingface/datasets/actions/runs/3128657114/jobs/5076803366) in `datasets`. I tested it locally and it indeed fixes the problem.
(this bug has been found as part of the `huggingface_hub==v0.10.0.rc0` prerelease test. Will be patched as `v0.10.0.rc2`.)
(edit: this could have been avoided if mypy was run in …

Send token implicitly on LFS upload

---

src/huggingface_hub/__init__.py
src/huggingface_hub/hf_api.py
tests/test_hf_api.py
tests/testing_utils.py

Will close https://github.com/huggingface/huggingface_hub/issues/1014. Follow `moon-landing` implementation https://github.com/huggingface/moon-landing/pull/3846 (internal link).
Related to 2 new issues on `moon-landing` https://github.com/huggingface/moon-landing/issues/3987 and https://github.com/huggingface/moon-landing/issues/3990 (internal links).
Adds a `create_tag` method to `HfApi`.
Todo:

Add a `create_tag` method to create tags from the HTTP endpoint

---

src/huggingface_hub/__init__.py
src/huggingface_hub/commands/scan_cache.py
src/huggingface_hub/utils/__init__.py
src/huggingface_hub/utils/_cache_manager.py
tests/test_utils_cache.py

If the Huggingface cache is not found, that is useful information to report, but it is not an error. The CLI should not show an error traceback in this situation.

Cache not found is not an error

---

src/huggingface_hub/commands/_cli_utils.py
tests/test_utils_cli.py

Alternative to #1100. Makes `huggingface-cli` compliant with https://no-color.org.

respect NO_COLOR env var

---

src/huggingface_hub/repocard.py

`hfh` v0.10.0 introduced modelcards that was previously hosted on a separate repo (https://github.com/nateraw/modelcards). When moving it into `huggingface_hub`, the use of utf-8 encoding by default has been lost which cause some issues for windows users as highlighted by @BenjaminBossan in https://github.com/skops-dev/skops/pull/162#issuecomment-1263516507.
This PR forces the use of `utf-8` when loading/saving a repocard. Once that is merged, I will cherry-pick the commit in `v0.10-release` branch and bump the version to `v0.10.1` so that this inconsistency stays as little as possible in the wild :) 
@nateraw mind approving the PR ? :pray: 
cc @adrinjalali

Force modelcards to use utf-8 encoding

---

tests/test_hf_api.py

This test is not ideal anyway as we are more testing the Hub behavior than `huggingface_hub` but I guess it is still a good test to keep for now. Hub search rules have recently changed to include more than the model id. Previous implementation of the test was checking that all returned models contained `bert` in there name which is not necesarly the case anymore.
A ok-ish solution is to test only the first 10 models that are returned and assume the search is not completely broken if it works for those ones :)

Fix test `test_list_models_search`

---

src/huggingface_hub/file_download.py
tests/test_file_download.py

Should fix https://github.com/huggingface/huggingface_hub/issues/1108.

More robust create relative symlink in cache

---

src/huggingface_hub/utils/_errors.py
tests/test_utils_cache.py
tests/test_utils_errors.py

Fix https://github.com/huggingface/huggingface_hub/issues/1114.
@Narsil exception will now be raised as such:
```
huggingface_hub.utils._errors.BadRequestError:  (Request ID: A83RPh8Orl5DA0S92qTVX)
Bad request for commit endpoint:
You can't have a key with a "." or "$" character in your YAML metadata
```

Propagate error messages when multiple on BadRequest

---

src/huggingface_hub/utils/_errors.py
tests/test_file_download.py
tests/test_utils_errors.py

Related to https://github.com/huggingface/huggingface_hub/issues/1119, https://github.com/huggingface/moon-landing/issues/4164 (internal repo), https://github.com/huggingface/huggingface_hub/pull/1015 and [this thread on slack](https://huggingface.slack.com/archives/C02EMARJ65P/p1666163944610829) (internal link).
A `x-error-message` is now sent back from the server in a header in case a HEAD request as having body is not allowed in such a case. This PR uses this header to enhance the `HfHubHTTPError` error message.
cc @coyotte508 ~This is not tested yet on a real case as it as just been merged on moon-landing.~ It is now tested with a regression test on the CI.
(cc @apolinario for the gated repo use case)

Add error message from `x-error-message` header if exists

---

src/huggingface_hub/__init__.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/utils/_errors.py
tests/test_hf_api.py

Fix https://github.com/huggingface/huggingface_hub/issues/1095.
I created 2 issues in moon-landing while working on it (https://github.com/huggingface/moon-landing/issues/4219 and https://github.com/huggingface/moon-landing/issues/4223 -internal links-).
Simply adds a method to wraps the `https://huggingface.co/api/models/gpt2/tag/this_is_a_tag` endpoint introduced by https://github.com/huggingface/moon-landing/pull/4005 (internal link).

Add `delete_tag` method to `HfApi`

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

Fix https://github.com/huggingface/huggingface_hub/issues/775.
PR includes:
(cc @coyotte508 @Pierrci even though that issue was quite old)

Fix `HfApi.move_repo(...)` and complete tests

---

docs/source/package_reference/mixins.mdx
src/huggingface_hub/hub_mixin.py
src/huggingface_hub/keras_mixin.py

The docs for the PyTorch Hub mixin pointed to the generic one instead of the PyTorch one. This PR fixes that and adds new section for the generic class

Fix PyTorch & Keras mixin doc

---

tests/test_hf_api.py

Related to [slack thread](https://huggingface.slack.com/archives/C02EMARJ65P/p1666795928977419) (internal link). Easiest solution is to skip the test for now.
_Original message_:
> Creating spaces on the staging environments is broken. This broke the CI in huggingface_hub. I tried on production ( [hf.co](http://hf.co/) ) and it works fine.  Problem is not so critical as it affects only 1 test.

Skip failing test in ci

---

tests/test_hf_api.py

Due to an update in moon-landing, creating a tag twice on the same repo doesn't work anymore (for good reason).
This PR updates the according test in `hfh`. Create tag is now officially released yet so no big deal here.

Create tag twice doesn't work

---

src/huggingface_hub/repocard.py
tests/test_repocard.py

Resolves #1144 by turning `RepoCard.content` into a property with an accompanying setter fn. The setter handles setting `.data` and `.text` attributes accordingly. 
This way, when you update the card text or data, the card's content will be updated as well. As an added bonus, if you update `card.content`, it will update the card data and text as well.

make repocard content a property

---

tests/test_repocard.py

Resolves #1154 
The only test in `RepoCardTest` that should raise warning about missing data is `test_repo_card_without_metadata`. This PR fixes a couple tests that were raising that warning due to incorrect string formatting while creating `content` manually.

:white_check_mark: fix content string in repocard tests

---

src/huggingface_hub/__init__.py
src/huggingface_hub/_login.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/utils/__init__.py
src/huggingface_hub/utils/_git_credential.py
src/huggingface_hub/utils/_subprocess.py
tests/test_cache_layout.py
tests/test_fastai_integration.py
tests/test_hf_api.py
tests/test_hubmixin.py
tests/test_keras_integration.py
tests/test_repocard.py
tests/test_repository.py
tests/test_snapshot_download.py
tests/test_utils_git_credentials.py

Fix https://github.com/huggingface/huggingface_hub/issues/1051. Read entire discussion there to get more context.
Also deprecate `HfApi.set_access_token` which was ambiguous (fix https://github.com/huggingface/huggingface_hub/issues/661).
Here is the new workflow:
**1.a.** In `notebook_login` or `interpreter_login`, a checkbox/prompt asks the user if the token must be set as git credential. Default value is `True` as I expect most users don't care about it and it would avoid topics will "hey my git clone doesn't work after login, what should I do ?". Since default value is explicitly displayed to the user, it doesn't seem a problem to me.
```text
>>> from huggingface_hub import login; login()
_|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_| …
```

Refactor git credential handling in login workflow

---

src/huggingface_hub/file_download.py
tests/test_file_download.py

Fix https://github.com/huggingface/huggingface_hub/issues/1161. Bug doesn't seem to be elsewhere than in `hf_hub_url` itself.
Added 2 regression tests just to be sure. 
cc @philschmid thanks for reporting it :)
(just wondering for myself: who really thought it was a good idea to have a `?` in a filename ??? :smile:)

FIX url encoding in hf_hub_url

---

setup.py

Seeing if pinning version of `mypy` to previous version fixes CI

Fix mypy ci

---

src/huggingface_hub/repocard.py
src/huggingface_hub/repocard_data.py
tests/test_repocard.py

As reported by a user, the `metadata_update` does not work anymore (likely introduced in #940) if no `"name"` field in the `"model-index"` is provided. This breaks for example `evaluate.push_to_hub` where evaluation results are pushed to the hub. 
With this PR the following behaviour is supported:
- if `"model-index"` of new metadata has a `"name"` it is used (1)
- if there is no `"name"`
- if the existing repo card has one use this one (2)
- else use the repo name as default (3)
Since the `"name"` is I think a little known feature of the PwC integration and providing a model name when pushing the results to a model repo seems a bit redundant I feel like having good defaults and not bother the user with it is a good idea. If you think this is a bad idea, we can throw an error in case (3). …

Use default `model_name` in `metadata_update`

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

Fix https://github.com/huggingface/huggingface_hub/issues/1156.
Adapt `create_commit`, add a test and adapt the docstrings.

Allow create PR against non-main branch

---

docs/source/searching-the-hub.mdx
src/huggingface_hub/hf_api.py
src/huggingface_hub/utils/endpoint_helpers.py
tests/test_endpoint_helpers.py
tests/test_hf_api.py

Fix CI (currently broken). Also fix https://github.com/huggingface/huggingface_hub/issues/1130.
And also updated tests/documentation + tried to remove some duplicate code in tests.
For context, it seems that most datasets have now a `language` tag instead of `languages`:
```text
List datasets with language:en
1750
List datasets with language:fr
196
List datasets with languages:en
7
List datasets with languages:fr
1
```
(cc @zaidalyafeai in the end I worked on this issue as our CI was broken because of it)

Rename languages to langage + remove duplicate code in tests

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

If output is truncated in `list_models` but not on user's request, raise a warning to suggest upgrading `huggingface_hub`.
This will be useful when pagination will be mandatory on Hub's side. To be removed when pagination is handled client-side as well.

Warn user if output is truncated in `list_models`

---

src/huggingface_hub/templates/modelcard_template.md

"Related Models" was underspecified.
For "Parent Model", the goal is to link to the parent model's model card. This PR attempts to clean that up a bit.

Removing "Related Models" & just asking for "Parent Model"

---

.github/ISSUE_TEMPLATE/bug-report.yml
src/huggingface_hub/__init__.py
src/huggingface_hub/commands/env.py
src/huggingface_hub/commands/huggingface_cli.py
src/huggingface_hub/utils/__init__.py
src/huggingface_hub/utils/_runtime.py

Resolve https://github.com/huggingface/huggingface_hub/issues/1173. Should ease some debugging of issues from users.
TODO:
Inspired by existing work in `transformers` `diffusers` (thanks @mariosasko)
```
➜  huggingface-cli env
Copy-and-paste the text below in your GitHub issue.
- huggingface_hub version: 0.11.0.dev0
- Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
- Python version: 3.10.6
- Running in iPython ?: No
- Running in notebook ?: False
- Running in Google Colab ?: False
- Token path ?: /home/wauplin/.huggingface/token
- Has saved token ?: True
- Token type: Personal token
- Who am I ?: Wauplin
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: 2.9.1
- Torch: 1.12.1
- Jinja2: 3.1.2
- Graphviz: 0.20.1
- Pydot: 1.4.2
```
```py
from huggingface_hub import …
```

1173 Add dump env helper

---

src/huggingface_hub/_commit_api.py
src/huggingface_hub/hf_api.py
tests/test_commit_api.py
tests/test_hf_api.py
tests/test_keras_integration.py

Fix https://github.com/huggingface/huggingface_hub/issues/1162.
**With this PR:**
- Order of the operations in the commit payload is the same as the input of `create_commit(...)`. It was not the case before which causes trouble if someone wants to delete then create a file.
- If 2 operations are modifying the same file, a warning is issued. Only case without warning is "delete a file then add this file" or "delete folder then add file that would have been in this folder".
- `CommitOperationAdd` is validated at initialization (no need for `.validate()` or `._upload_info()` calls anymore)
**Warning:** I made some breaking changes in `validate_preupload_info`, `fetch_upload_modes` and `prepare_commit_payload`. I did not care too much as those 3 methods are defined in a private module and …

1162 Reorder operations correctly in commit endpoint

---

src/huggingface_hub/_commit_api.py
src/huggingface_hub/hf_api.py
tests/test_hf_api.py

Fix https://github.com/huggingface/huggingface_hub/issues/1182.
Users were not able to push files and create a PR on a repo where they don't own write permissions. Was due to an auth rule changed in `/endpoint`.

Fix cannot create pr on foreign repo

---

src/huggingface_hub/file_download.py
tests/test_file_download.py

Resolve https://github.com/huggingface/huggingface_hub/issues/1158.
This PR adds a `size` attribute to the output of `get_hf_file_metadata`.
`RepoFile` and `HfFileMetadata` are still 2 different objects doing related stuff (getting file info from API or from HEAD request on the file itself) but this PR is not meant to harmonize this.
(cc @Narsil who were requesting it)

Parse file size in get_hf_file_metadata

---

src/huggingface_hub/__init__.py
src/huggingface_hub/hf_api.py
tests/test_hf_api.py

Resolve https://github.com/huggingface/huggingface_hub/issues/1165. Follow moon-landing implementation https://github.com/huggingface/moon-landing/pull/4395 (internal link)
This PR adds `create_branch` and `delete_branch` methods to `HfApi` client.
---
@severo: It is not documented since only available for HF users but I was able to create the `/refs/convert/parquet` branch with it:
```py
from huggingface_hub import create_branch, create_repo
repo_id = "Wauplin/tmp_to_delete_branch_creation"
create_repo(repo_id)
create_branch(repo_id, branch="refs/convert/parquet")
```
=> https://huggingface.co/Wauplin/tmp_to_delete_branch_creation/tree/refs%2Fconvert%2Fparquet

Add "create_branch" and "delete_branch" endpoints

---

src/huggingface_hub/hf_api.py
src/huggingface_hub/utils/_pagination.py
tests/test_hf_api.py
tests/test_utils_pagination.py

Related to ongoing development of pagination in moon-landing https://github.com/huggingface/moon-landing/pull/4437 (internal link).
With this PR, pages are paginated by default if a `"Link"` header is found in the response. Also removed the deprecation warning based on `X-Total-Count`.
cc @coyotte508 @julien-c

Add support for pagination in `list_models` `list_datasets` and `list_spaces`

---

src/huggingface_hub/repocard.py
src/huggingface_hub/repocard_data.py
tests/test_repocard.py

Should fix https://github.com/huggingface/huggingface_hub/issues/1185.
With this PR, 2 eval results are considered to describe the same object if and only if all attributes are the same except the metric value itself (see `is_equal_except_value`). Otherwise value is not overwritten.
cc @lewtun for review

FIX overwriting metadata when both verified and unverified reported values

---

.github/ISSUE_TEMPLATE/bug-report.yml
src/huggingface_hub/_commit_api.py
src/huggingface_hub/constants.py
src/huggingface_hub/file_download.py
src/huggingface_hub/utils/_runtime.py
tests/test_file_download.py

PR fixes an issue in `get_hf_file_metadata`.
In case of LFS file, `size` was set to the pointer file size, not the actual LFS file itself.
Also few nits from @julien-c 's reviews.

Fix get file size on lfs

---

.github/workflows/python-tests.yml
src/huggingface_hub/repository.py
tests/test_repository.py

Deprecation cycle is kept for one more version. See [slack discussion](https://huggingface.slack.com/archives/C02V5EA0A95/p1668427994770019) (internal link).
Still used (reported by @osanseviero)
https://github.com/huggingface/diffusers/blob/main/src/diffusers/hub_utils.py#L112 
From @osanseviero :
> I think this would also break transformers PushToHubCallback https://github.com/huggingface/transformers/blob/main/src/transformers/keras_callbacks.py#L342
From @nateraw :
https://github.com/rwightman/pytorch-image-models/issues/1546
https://github.com/rwightman/pytorch-image-models/blob/8ff45e41f7a6aba4d5fdadee7dc3b7f2733df045/timm/models/hub.py#L153

Set back feature to create a repo when using clone_from

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

First discussed [on slack](https://huggingface.slack.com/archives/C02EMARJ65P/p1668613089997919?thread_ts=1668609919.729479&cid=C02EMARJ65P) (internal link).
The idea is to be able to set a custom user agent for all requests made with `HfApi` client. Also added a docstring and some tests.
cc @ydshieh

Add user agent attribute to `HfApi` client

---

tests/test_keras_integration.py

Tensorflow tests are currently [broken in CI](https://github.com/huggingface/huggingface_hub/actions/runs/3496412869/jobs/5854297122) due to tensorflow 2.11 release. A new file (`fingerprint.pb` ?) is created and saved in the repo. This PR adapts the current tests that are counting the number of uploaded files.

Fix tensorflow tests

---

src/huggingface_hub/utils/_errors.py
tests/test_hf_api.py

Currently any HTTP 401 Unauthorized is processed as "Repository not found" with an error message quite unhelpful for gated repos. This PR mentions the fact that you must authenticate if a repo is gated.
See https://github.com/huggingface/moon-landing/issues/3903#issuecomment-1320137948 (internal link) and [this gist](https://gist.github.com/Wauplin/46c27ad266b15998ce56a6603796f0b9).
(cc @julien-c: realized that when making a local test for https://github.com/huggingface/huggingface_hub/issues/1198)

Specific message for unauthorized errors

---

src/huggingface_hub/repository.py

Improve the error message when a repository is being created in a non-empty folder by saying which folder is causing the error.
Fixes #1204

Name the folder causing a repository error

---

src/huggingface_hub/utils/_subprocess.py

Do not throw error on utf-8 error in run_subprocess

---

src/huggingface_hub/file_download.py
tests/test_file_download.py

Fix https://github.com/huggingface/huggingface_hub/issues/1216 (cc @mhham).
If commit hash is the same, do not overwrite the `refs` file. This make the cache system work when user has no write permission and remote model did not change.
Note: another possibility is to set `HF_HUB_OFFLINE` environment variable when using a user that has read-only access. `huggingface_hub` will not try to sync with remote => nothing is written to cache.

Fix caching reference if permission denied

---

docs/source/package_reference/utilities.mdx
src/huggingface_hub/utils/__init__.py
src/huggingface_hub/utils/_errors.py
tests/test_file_download.py

Related to discussions happening around gated repo (example : https://github.com/huggingface/huggingface_hub/issues/1198#issuecomment-1325030852). Follow [server-side PR](https://github.com/huggingface/moon-landing/pull/4627) (internal link).
This PR takes advantage of the new "GatedRepo" error code that is returned by server when a user tries to access a repo that is gated (and user is not in authorized list). It raises a  `GatedRepoError` in python (cc @sgugger).
Note: `GatedRepoError` inherits from `RepositoryNotFoundError` to avoid breaking changes.

Add custom `GatedRepoError` when trying to access gated repo

---

setup.py
src/huggingface_hub/_snapshot_download.py
src/huggingface_hub/file_download.py
src/huggingface_hub/utils/tqdm.py

Fix https://github.com/huggingface/huggingface_hub/issues/1042 (cc @abhishekkrthakur).
Make use of `tqdm.contrib.concurrent.thread_map` to easily spawn threads. Each thread handles a single file download.
This is especially useful when downloading a lot of small files. Downloading 1 file at a time is inefficient as the download is not limited by the bandwidth. 
Also fix https://github.com/huggingface/huggingface_hub/issues/1110 (cc @nerochiaro). Now possible to provide a custom tdqm class to snapshot_download if needed. Default is the `huggingface_hub.utils.tqdm` class (the progress that can be disabled programmatically or via  `HF_HUB_DISABLE_PROGRESS_BARS` env variable).

Make snapshot_download multithreaded + customizable progress bar

---

src/huggingface_hub/file_download.py
tests/test_file_download.py

Fix #1141 #1215.
Workaround I used is to infer umask from the permission set on the `blobs/` folder. This is not optimal (not getting the umask from the user directly) but good enough as at least all folders/files in cache folder will have same permissions.
```py
cache_dir_mode = Path(dst).parent.stat().st_mode
os.chmod(src, stat.S_IMODE(cache_dir_mode))
os.replace(src, dst)
```
The reason behind it that [getting the umask](https://docs.python.org/3/library/os.html#os.umask) from the user is risky. The python implementation consists in changing the value while getting the old value. Can lead to weird/undesired issues in a multi-thread process. I found a [potentially thread-safe solution](https://stackoverflow.com/a/70343066) but didn't want to have to maintain/debug it on multiple …

Set correct permissions on blob file

---

src/huggingface_hub/repocard.py
src/huggingface_hub/repocard_data.py
tests/fixtures/cards/sample_simple_model_index.md
tests/test_repocard.py

Fix metadata_update for verified evaluations

---

docs/source/installation.mdx
docs/source/package_reference/environment_variables.mdx
src/huggingface_hub/utils/_git_credential.py

I merged https://github.com/huggingface/huggingface_hub/pull/1233 a bit too soon :confused: 
This PR is fixing feedback from @osanseviero . Thank you for the comments :)

Integrate osanviero's feedback on documentation

---

docs/source/package_reference/environment_variables.mdx
src/huggingface_hub/constants.py
src/huggingface_hub/utils/_hf_folder.py
tests/test_hf_api.py
tests/test_utils_hf_folder.py

Fix https://github.com/huggingface/huggingface_hub/issues/1232. Read issue description for more details.
Basically token will now be stored under the `HF_HOME` directory and not in a hard-coded place. Should not break anything (only get user warnings).

Store token in configurable HF_HOME (in HfFolder)

---

docs/source/how-to-model-cards.mdx
src/huggingface_hub/templates/modelcard_template.md

This also helps distinguish it from the "More Information" section. It adds the jinja variables `demo`, `paper`, and `repo`. See discussion at:
https://huggingface.slack.com/archives/C025H22A3ND/p1669923069281609

Clarify what "More Resources" is by breaking it into its parts.

---

src/huggingface_hub/_commit_api.py
src/huggingface_hub/hf_api.py
tests/test_hf_api.py

Fix https://github.com/huggingface/huggingface_hub/issues/1246.
This PR adds support of `pathlib.Path` type for `path_or_fileobj` in `upload_file` method (also in `CommitOperationAdd`). Add a regression test.

Accept pathlib.Path in upload_file

---

docs/source/_toctree.yml
docs/source/concepts/git_vs_http.mdx
docs/source/concepts/http_vs_git.mdx
docs/source/index.mdx

Related to https://github.com/huggingface/huggingface_hub/pull/1226.
Added [a doc page](https://moon-ci-docs.huggingface.co/docs/huggingface_hub/pr_1245/en/concepts/git_vs_http) to explain what we refer to when writing about "git-based" or "http-based" approach. Tried to make it clear that `HfApi` should be considered the way to go all the time except for some specific situations.

Doc page: git vs http

---

src/huggingface_hub/templates/modelcard_template.md

Proposes 2 new jinja variables that have been in other cards but were not yet transferred here:
`model_summary` , the short description of the model that follows the name.
`results_summary` , the tl;dr of what the results say.

Adding "summary" variables

---

tests/test_endpoint_helpers.py
tests/test_hf_api.py

Related to https://github.com/huggingface/huggingface_hub/pull/1250.
For now and until we fix that, let's skip the failing tests. It's annoying in CI checks.

Skip failing tests related to DatasetFilter

---

.github/workflows/build_repocard_examples.yaml
Makefile
src/huggingface_hub/templates/datasetcard_template.md
src/huggingface_hub/templates/modelcard_template.md
tests/test_hf_api.py
utils/push_repocard_examples.py

Related to https://github.com/huggingface/moon-landing/pull/4815 (private link).
Goal is to keep up-to-date an empty example of ModelCard and DatasetCard, generated by `huggingface_hub`. These examples will be referenced from Hub or from docs.
Cards are pushed to:
- https://huggingface.co/templates/model-card-example
- https://huggingface.co/datasets/templates/dataset-card-example

Push empty model card and dataset card to the Hub

---

tests/test_hf_api.py

Following [this discussion](https://huggingface.slack.com/archives/C02EMARJ65P/p1670859110021119) (internal link), it's best to mock tests that requires GPUs to save some resources.

Mock Space tests requiring GPUs

---

src/huggingface_hub/utils/_pagination.py

The pagination is now active on the Hub (10.000 items)

Remove obsolete comment

---

docs/source/guides/manage_spaces.mdx
docs/source/package_reference/space_runtime.mdx
src/huggingface_hub/__init__.py
src/huggingface_hub/hf_api.py
tests/test_hf_api.py

For security the GET `/secrets` endpoint is not exposed ([see discussion](https://huggingface.slack.com/archives/C02EMARJ65P/p1670921311847139) -internal link-).
Let's remove the `get_space_secrets(...)` method for now since it's not a requested feature and not so important for now.

Remove `get_space_secrets` endpoint

---

src/huggingface_hub/_snapshot_download.py
src/huggingface_hub/fastai_utils.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/hub_mixin.py
src/huggingface_hub/keras_mixin.py
src/huggingface_hub/repocard.py
src/huggingface_hub/repository.py
tests/test_hubmixin.py
tests/test_keras_integration.py
tests/test_repository.py
tests/test_snapshot_download.py
tests/testing_utils.py

@julien-c you favorite PR is back :smile: 
This PR removes all code that was deprecated and planned to be removed in v0.12. In particular, all `push_to_hub` methods are now HTTP-based only, no more Git-based :)

Remove deprecated code in v0.12

---

src/huggingface_hub/file_download.py

For the private hub, we don't use the same host url.
But we don't need to forward the Authorization header in any case, because S3 url already contains credentials information in a query params.

fix: authorization header should never be forwarded

---

src/huggingface_hub/file_download.py

- Larger chunk help reduce overhead
- Not too large chunks so resume still works
In my very small testing I get much better download speeds already with cloudfront.
Download times go for `gpt2` from ~5s+ to ~2s- (tested both on AWS and dgx).
Testing setup:
```python
from huggingface_hub import hf_hub_download
filename = hf_hub_download("gpt2", "pytorch_model.bin", force_download=True, cache_dir="/mnt/ramdisk/")
print(filename)
```
Using a tmpfs part of the disk avoids actually writing to disk and taking it into account.

Increase the chunk size for faster download

---

docs/source/package_reference/hf_api.mdx
src/huggingface_hub/__init__.py
src/huggingface_hub/hf_api.py
tests/test_hf_api.py

This PR updates the return value for `create_repo` endpoint. The current problem is that `repo_id` input can have an implicit namespace (e.g. `create_repo("my-model")` -> `"Wauplin/my-model"`). The return value of `create_repo` is currently a URL to the new repo on the Hub. This is a bit annoying for external libraries that integrates `hfh` in their pipeline as they need to parse the _explicit_ `repo_id` from the returned URL. This can be done by the helper `repo_type_and_id_from_hf_id` but to be honest it's not very easy to find for maintainers. We end up with integrations where the parsing is done manually or where it's forgotten (e.g. implicit repo_id is passed afterwards to `create_commit` which breaks).
This PR tries to solve this problem by adding a new type …

Extend create_repo return value

---

src/huggingface_hub/hf_api.py
src/huggingface_hub/lfs.py
tests/test_hf_api.py

Server only returns public likes. This PR adapts parsing of the data (+docstring).

Fix list_liked_repos (only public likes are returned)

---

src/huggingface_hub/fastai_utils.py
src/huggingface_hub/file_download.py
src/huggingface_hub/hub_mixin.py
src/huggingface_hub/keras_mixin.py
src/huggingface_hub/repocard.py
src/huggingface_hub/repository.py
src/huggingface_hub/utils/__init__.py
src/huggingface_hub/utils/_fixes.py
tests/conftest.py
tests/test_cache_layout.py
tests/test_command_delete_cache.py
tests/test_file_download.py
tests/test_hf_api.py
tests/test_keras_integration.py
tests/test_lfs.py
tests/test_repocard.py
tests/test_repository.py
tests/test_snapshot_download.py
tests/test_utils_fixes.py
tests/test_utils_hf_folder.py
tests/test_utils_sha.py
tests/test_utils_tqdm.py

Fix #1278.
Create a custom `TemporaryDirectory` context manager that tries harder to cleanup on exit.
If it still fails to cleanup the directory, it gives up without trowing an issue.
Tested also on Windows and it works fine. See https://www.scivision.dev/python-tempfile-permission-error-windows/ for some details.

1278 More robust temporary directory

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

1. `move_repo` documentation URL was invalid
2. A test is failing in the CI because a repo has been removed. Repo itself doesn't matter too much (it just need to have a convert/parquet reference) so I changed it.

Update "move_repo" doc url + fix Bigcode test in CI

---

tests/test_hf_api.py

Related to [slack thread](https://huggingface.slack.com/archives/C02EMARJ65P/p1673970528365839) (internal link) and [issue in CI](https://github.com/huggingface/huggingface_hub/actions/runs/3940685279/jobs/6742108306#step:5:1888).
`test_comment_discussion` is comparing entire events (full raw data). Seems that some css styling is applied to the comment when listed from the API. This is not really our concern as long as the comment IDs stays the same. This PR fixes the test.

Fix test_comment_discussion

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

Related to https://github.com/huggingface/huggingface_hub/issues/1288 (but don't solve it entirely). It is now possible to create a branch from a given revision (commit id or branch name) cc @camenduru
```py
create_branch(repo_id, branch="from-initial", revision="364a1b48ef846051cbb511c438c0e1d6f6fde7f4")
create_branch(repo_id, branch="from-branch", revision="from-initial")
```
Would be good to have a way to retrieve first commit ID to solve https://github.com/huggingface/huggingface_hub/issues/1288 but that will be done later. In the meantime, a workaround is to tag the initial commit at repo creation and retrieve it later using `HfApi.list_repo_refs`. A bit clunky but does the trick while a "`list_repo_history`-like" method is not implemented.

Create branch from given revision

---

src/huggingface_hub/_login.py
src/huggingface_hub/commands/user.py

This illustrates my suggested enhancement described in issue #1290.
This adds an optional argument to `interpreter_login()` and passes `Option(token)` to it from the outer login function. If the token exists it is interrogated, a message is displayed, and a `ValueError` is raised to exit.
I chose a `ValueError` to match the pattern that `_login()` uses in the same method when a token is provided. I also considered hoisting out a `_validate_token()` method from the `_login()` code but I thought it best to keep this concise.
The CLI tests are super anemic and I haven't added any additional tests here. I'll wait for more feedback before figuring that out.

fixes 1290 - check for existing token during interpreter login

---

src/huggingface_hub/utils/sha.py

Fix https://github.com/huggingface/huggingface_hub/issues/1294 (thanks @wfjsw).
When computing the sha of a file (before uploading it), the `chunksize` was defined but never used. Therefore the file was entirely loaded in memory which is problematic for huge files. This PR solves that.
I also refactored it to make it "more readable". I tested it quickly on my machine and found out that a chunksize of 1MB seems optimal is term of performance (very rough estimation) and still ok in term of memory footprint.

Compute sha by chunks when uploading

---

docs/source/searching-the-hub.mdx
src/huggingface_hub/hf_api.py
src/huggingface_hub/utils/endpoint_helpers.py
tests/test_endpoint_helpers.py

Fix https://github.com/huggingface/huggingface_hub/issues/1280 and related to https://github.com/huggingface/huggingface_hub/pull/1250.
At the moment `DatasetTags` (therefore `DatasetSearchArguments` as well) is broken due to server-side changes. This PR fixes this by making it more robust to server-side changes. If a key does not exist anymore (e.g. `multilinguality`), the object is still initialized but with an empty list for it. This PR also adapts the tests so that we get warned if future server-side changes happen.
I've also added warnings to the documentation mentioning that `ModelSearchArguments` and `DatasetSearchArguments` are really legacy stuff meant for exploratory purposes only (+ is quite ineficient). I hesitated to even put a warning in the code so that users get warned …

Make `ModelSearchArguments` and `DatasetSearchArguments` more robust

---

tests/test_file_download.py
tests/test_hf_api.py
tests/test_snapshot_download.py
tests/test_utils_cache.py
tests/testing_constants.py

In a few cases, `hfh` tests were relying on existing repos on the staging Hub. That's a bit annoying when staging database got wiped-off for cleanup. See [related slack thread](https://huggingface.slack.com/archives/C02EMARJ65P/p1674140535316159) (internal link) (cc @coyotte508 @severo)
This PR remove the use of any pre-existing repo on staging:
- https://hub-ci.huggingface.co/datasets_server_org/gated_repo_for_huggingface_hub_ci -> now creating a gated repo on the fly
- https://hub-ci.huggingface.co//datasets_server_org/repo_for_huggingface_hub_ci_with_prs -> now creating a foreign repo with prs on the fly, using DATASET_SERVER user (cc @severo)
- https://hub-ci.huggingface.co/valid_org/repo_with_awful_filename -> there was no need to be an existing repo
- …

Make tests more robust (no pre-existing repo on staging Hub)

---

src/huggingface_hub/file_download.py
tests/test_file_download.py

If one uses `hf_hub_download` only referencing specific commits the `refs` folder will not be created even though data will be cached via `snapshots` and `blobs`.  Subsequent calls to `try_to_load_from_cache` will return None even though the desired data was in the cache.
Example:
```python
hf_hub_download(repo_id=repo, revision=commit_hash, filename=filepath, token=token)
try_to_load_from_cache(repo_id=repo, revision=commit_hash, filename=filepath)
```

fix: use cache for snapshots even if refs does not exist

---

docs/source/how-to-cache.mdx
docs/source/package_reference/cache.mdx
src/huggingface_hub/__init__.py
src/huggingface_hub/file_download.py

Resolve https://github.com/huggingface/huggingface_hub/issues/1011, following https://github.com/huggingface/huggingface_hub/pull/986 that introduced the `.no_exist` folder.
It has never been properly documented. Also exposes the `_CACHED_NO_EXIST` object. Even if it's a "private" object, I think it makes sense to expose it. This feature is quite niche even though it can be really useful (at least for transformers).
cc @sgugger 
PR documentation:
- [New section in the caching guide](https://moon-ci-docs.huggingface.co/docs/huggingface_hub/pr_1308/en/how-to-cache#noexist-advanced)
- [Reference for `try_to_load_from_cache` ](https://moon-ci-docs.huggingface.co/docs/huggingface_hub/pr_1308/en/package_reference/cache#huggingface_hub.try_to_load_from_cache)(wasn't generated before)

Document `.no_exist` folder

---

src/huggingface_hub/file_download.py
tests/test_file_download.py

Will not fix the root issue of https://github.com/huggingface/huggingface_hub/issues/1305 but fixes the non-explicit `FileNotFoundError` that was raised (in favor of the documented and expected `LocalEntryNotFoundError`).
cc @NielsRogge for some reason downloading a file in your space failed due to a connection issue (infra issue ? `HF_HUB_OFFLINE` set ?). Instead of the proper `LocalEntryNotFoundError` (that is handled nicely in `transformers`) you had a `FlieNotFoundError` because the cache in your space was not initialized yet. This also explains why it's working locally on your computer (since I guess cache structure is already good). This PR should fix it.

Fix caching error when offline and no refs dir

---

docs/source/package_reference/hf_api.mdx
docs/source/searching-the-hub.mdx

Related to https://github.com/huggingface/huggingface_hub/issues/1250, https://github.com/huggingface/huggingface_hub/issues/1280 and https://github.com/huggingface/huggingface_hub/pull/1300.
`ModelSearchArguments` and `DatasetSearchArguments` are only half-maintained and caused quite some trouble recently. Additionally they are now quite innefficient to instantiate as they require to load all models/datasets from the Hub before filtering them. The PR aims to show that those helpers can be useful but are optional.
Also in the same PR I revisited a bit the HfApi reference page to make it less verbose and more structured on the right tab.
- [Search the hub guide](https://moon-ci-docs.huggingface.co/docs/huggingface_hub/pr_1303/en/searching-the-hub#search-the-hub)
- [HfApi reference …

Revisit "search the hub" page (+HfApi reference page)

---

src/huggingface_hub/_snapshot_download.py
src/huggingface_hub/file_download.py

This PR replaces occurrences of "uploading to" with "downloading from" in the file/snapshot download functions.

[Minor] Typo

---

src/huggingface_hub/file_download.py
tests/test_file_download.py

When trying to load a file from cache with a revision of type `refs/pr/<pr-number>`, `try_to_load_from_cache` fails because the revision file is serialized to: `HUGGINGFACE_HUB_CACHE/models--<object-id>/refs/refs/pr/<pr-number>` which is not found by the current implementation using `os.path.listdir` since it only lists files at the current level.
This PR simply reads the file directly if it exists.
Maybe this should also mean that revision should use `replace("/", "--")` during download.

fix(utils): try_to_load_from_cache now correctly handles refs/pr revisions

---

docs/source/guides/manage_spaces.mdx

Was `request_hardware`, but should be `request_space_hardware`.

Fix request_space_hardware name in manage spaces guide

---

src/huggingface_hub/file_download.py
src/huggingface_hub/utils/_errors.py

FIX https://github.com/huggingface/huggingface_hub/issues/1318 by parsing correctly the "Content-disposition" header with a regex (cc @sijunhe).
Previous was:
```
Downloading (…)del_state.pdparams";:   2%|██▋
```
and now:
```bash
Downloading model_state.pdparams:   2%|██▋
Downloading (…)del_state.pdparams:   2%|██▋
```
**EDIT:** also made a fix for https://github.com/huggingface/huggingface_hub/issues/1319. It was not really a bug but I agree that have a default value is more convenient.
```py
HfHubHTTPError(message="something happened")
HfHubHTTPError(message="something happened", response=None)
```

FIX displayed filename in LFS download (+default response None in HfHubHTTPError)

---

.github/workflows/contrib-tests.yml
Makefile
contrib/spacy/requirements.txt
contrib/spacy/test_spacy.py

Related to https://github.com/explosion/spacy-huggingface-hub/pull/14 (cc @osanseviero @adrianeboyd).
`spacy-huggingface-hub` has a single feature (push model to hub) which is untested so far. Let's add it to our Contrib CI to prevent future breaking changes. To be more precise, we might break an api somewhere in the future but at least we will detect it enough in advance. Test is run with the latest dev version of `huggingface_hub` and breaks on any `FutureWarning` that is raised. If we encounter a bug, we would report it on https://github.com/explosion/spacy-huggingface-hub.

Add contrib CI for spacy_huggingface_hub

---

src/huggingface_hub/hub_mixin.py
tests/test_hubmixin.py

Fix https://github.com/huggingface/huggingface_hub/issues/1313 cc @NielsRogge.
Some legacy code in `ModelHubMixin` was accepting `revision` as part of the model_id behind a `"@"` (e.g. `model_id=namespace/repo_name@revision`). It is the only place in `hfh` that supports this pattern so I think it's best to deprecate it in favor of a proper `revision=...` parameter. This PR does this.
Also I improved a bit the docstrings, function signatures (added typing + deprecated positional arguments) and the tests (use tmp directories everywhere instead of local fixtures dirs).
In parallel to this PR, I'll work on a guide to promote `ModelHubMixin` and `PyTorchModelHubMixin`. At the moment, we have them documented "only" in the package reference.

FIX use revision in `ModelHubMixin.from_pretrained`

---

MANIFEST.in

See [discussion](https://github.com/huggingface/datasets/issues/3841) happening in `datasets`.
To fix the `reportPrivateImportUsage` issue reported by Pyright, let's just delete `py.typed` file. It's not compliant with [PEP-561](https://peps.python.org/pep-0561/#packaging-type-information) but at least it will be consistent with other huggingface libraries.
Just to mention it, it would be possible to hard-code the `__all__` variable by statically generating the file (same as what we are doing in the `if TYPE_CHECKING` section). But let's keep it simple :)
cc @mariosasko @lhoestq @LysandreJik

Remove py.typed - FIX linter issues

---

docs/source/package_reference/environment_variables.mdx
src/huggingface_hub/constants.py
src/huggingface_hub/inference_api.py

In some cases users may want to point at an api gateway or similar rather than hitting the inference api directly, allow overriding via env var.

Allow overriding inference api endpoint

---

src/huggingface_hub/repository.py

This pull request introduces the `--exclude-standard` argument to the git ls-files command.
As described in [Git - git-ls-files Documentation](https://git-scm.com/docs/git-ls-files#_options), this option adds the standard Git exclusions: .git/info/exclude, .gitignore in each directory, and the user’s global exclusion file.
This change is important because the current behavior of the command can return temporary files that may be deleted during the execution, leading to a race condition. With the new option, files that match the exclusion patterns in the .gitignore file will not be returned.
Further details can be found at the https://github.com/huggingface/transformers/issues/21586

Add --exclude-standard argument in git ls-files command

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

Resolve #1336.
Related to [`hffs` integration](https://github.com/huggingface/hffs/pull/12). Found out that canonical models/datasets are not parsed correctly. This PR fixes this.

Parse correctly canonical URLs in RepoUrl

---

docs/source/package_reference/hf_api.mdx
src/huggingface_hub/__init__.py
src/huggingface_hub/hf_api.py
tests/test_command_delete_cache.py
tests/test_hf_api.py

FIX https://github.com/huggingface/huggingface_hub/issues/1288 (following [server-side implementation](https://github.com/huggingface/moon-landing/pull/5301) -internal link- thanks @Kakulukian).
This PR adds a new helper `list_repo_commits` (similar to `list_repo_refs` and list_repo_files`). It lists the all history of a repository on the Hub for a given revision. Commits are sorted by date (last commit first).
@camenduru this will finally solve your problem on "how to create an empty branch?". I did not make a special parameter in `create_branch` that would use `list_repo_commits` under the hood as I thought it was a quite specific use case.
```py
>>> from huggingface_hub import HfApi
>>> api = HfApi()
>>> initial_commit = api.list_repo_commits("gpt2")[-1]
>>> initial_commit …
```

Add `list_repo_commits` to list git history of a repo

---

src/huggingface_hub/file_download.py

I thought that https://github.com/huggingface/huggingface_hub/blob/21a1e370f54e0af188d3ec8cbfd638b96917ab9e/src/huggingface_hub/file_download.py#L1137 was enough
Seems like we have multiple path for the same end

Remove Authorization header when following redirects

---

.github/workflows/contrib-tests.yml
contrib/timm/requirements.txt
contrib/timm/test_timm.py

Fix #1324.
HF helpers location changed in `timm` packages. This PR just changes the import (+test on smaller models to save bandwidth).

Fix contrib CI for timm

---

src/huggingface_hub/repocard.py
src/huggingface_hub/repocard_data.py

Following a suggestion from @julien-c to update the `datasets` tag in `ModelCardData` from `Optional[Union[str, List[str]]]` to `Optional[List[str]]` so we get a YAML block like 
```yaml
datasets:
- "IMDB"
```
rather than 
```yaml
datasets: "IMDB"
```
The changes here are just changing the types and doc strings, and there isn't any checking of what the user passes. This is consistent with existing behaviour, but happy to add this check if we want to enforce this type on the user.

Switch datasets type in ModelCard to a list of datasets

---

tests/test_hf_api.py

We updated the test user to HF user which is causing CI to fail. This is a quick patch...probably not ideal so @Wauplin feel free to close if you have better solution in mind :). Just didn't want permission change related to my PR #1353 to have CI failing for everyone here. 
[Link to internal slack thread for context](https://huggingface.slack.com/archives/C02EMARJ65P/p1677027533974229)

:ambulance: hotfix isHf test user permissions bug

---

docs/source/package_reference/cards.mdx
src/huggingface_hub/__init__.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/repocard.py
src/huggingface_hub/repocard_data.py
tests/test_repocard.py
tests/test_repocard_data.py

Resolve https://github.com/huggingface/huggingface_hub/issues/1348.
No need to add a `SpaceCard` class, it wouldn't have any additional features.
I took the opportunity to add a few QOL improvement to the `CardData` object (`.get`, `__getitem__`, `__setitem__`, `__contains__`, `.pop`). More of these could be added but honestly not worth the hassle (those 5 cover 99% of the use cases). Could have been simpler to just inherit from `dict` but this way we can explicitly add an "export" step when serializing the metadata. 
Added some tests and completed a docstring.

Expose `RepoCard` at top level + few qol improvements

---

src/huggingface_hub/utils/_errors.py
tests/test_utils_errors.py

Just 3 private methods (aliases for `hf_raise_for_status`).
They were used in `transformers` some versions ago but now completely removed (they were removed even before the deprecation cycle started).

Remove deprecated code (0.13)

---

src/huggingface_hub/repocard_data.py

Follows up from #1356 to update more repo card attribute types to `Optional[List[str]]`. 
@Wauplin @julien-c, at the moment, I have changed the types for:
- metrics 
- language 
- source datasets
For some attributes like `license`, it's likely that it will almost only be a single string: should I also change those types or focus only on the fields more likely to be an array with multiple items?

Updates types for RepoCards fields 

---

src/huggingface_hub/templates/modelcard_template.md

Updating the Markdown headings so it tracks with the HTML
(see [this thread](https://huggingface.slack.com/archives/C025H22A3ND/p1677198938931089?thread_ts=1677181385.790839&cid=C025H22A3ND))
Fixes: https://github.com/huggingface/huggingface_hub/issues/1366

Updating MC headings

---

src/huggingface_hub/commands/user.py

As of now it's not possible to login in a non interactive shell using `huggingface-cli login` as it always prompt to input the token. This makes it hard to use the CLI for automation, for example in GitHub Actions.
This PR adds `--token` and `--add-to-git-credential` args to `huggingface-cli login` command.
```
$ huggingface-cli login --help
usage: huggingface-cli <command> [<args>] login [-h] [--token TOKEN] [--add-to-git-credential]
options:
-h, --help            show this help message and exit
--token TOKEN         Token generated from https://huggingface.co/settings/tokens
--add-to-git-credential
Optional: Save token to git credential helper.
```
Example call:
```
$ huggingface-cli login --token $HUGGING_FACE_TOKEN --add-to-git-credential
```

Add token and git credentials to login cli command

---

docs/source/_toctree.yml
docs/source/guides/integrations.mdx
docs/source/package_reference/mixins.mdx
src/huggingface_hub/hub_mixin.py
src/huggingface_hub/keras_mixin.py
tests/testing_utils.py

Resolve #1333 (from @NielsRogge 's suggestion [in private slack](https://huggingface.slack.com/archives/C01BWJU0YKW/p1675086727579739)).
This PR adds a new guide page "Integrate any ML framework with the Hub". Contains:
1. what is an integration?
2. what is the `ModelHubMixin`. How to use it?
3. concrete example with `PyTorchHubMixin`: how to use it and how has it been implemented
(+ edited some docstrings)
Writing this guide made me realize we can even improve further the `ModelHubMixin` class, especially for cases where we want to delete files from the Hub (when pushing multiple times). This is done separately in the Keras integration to replace training logs. I think we update change this once #1352 is implemented.
(Note: failing tests are unrelated to this PR)

Write Mixins/Integration guide

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

FIX https://github.com/huggingface/huggingface_hub/issues/1371.
Hub API is already case insensitive. Somehow the issue was with the `requests` streaming implementation when generating the ndjson payload "on the fly". It seems that the server was receiving only the first line which causes a very confusing `"400 Bad Request - Add a line with the key 'lfsFile', 'file' or 'deletedFile'"`.
Passing raw bytes instead of a generator fixes the problem. I added a regression issue for that.
(note: I wouldn't find it too problematic to get an error when creating a commit with a case-issue in the repo_id. The problem here was more that the displayed error was completely unrelated).
cc @coyotte508

FIX Create_commit on lowercased repo_id failing with confusing message.

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

Corner case but used in a lot of integrations. Problem is when doing `create_repo(..., exists_ok)`. If repo already exists, it's not supposed to raise an exception. However, if the repo exists but the user do not have permission on this namespace, a HTTP 403 is thrown. Since we catch only HTTP 409 conflict, the error is not caught. 
With this PR, if we get an HTTP 403, we check if the repo exists or not before raising an exception. This is useful for third-party integrations having a "push_to_hub"-like method and `create_pr=True`. We do not want to throw an error on create repo since write permission will not be needed to create a PR.
See [related slack thread](https://huggingface.slack.com/archives/C02V5EA0A95/p1677589109007089) (internal link) cc @thomasw21 @coyotte508

FIX `create_repo` with `exists_ok` but no permission

---

src/huggingface_hub/_commit_api.py
src/huggingface_hub/community.py
src/huggingface_hub/repocard.py
src/huggingface_hub/repocard_data.py
tests/test_repocard.py

Fix https://github.com/huggingface/huggingface_hub/issues/1361 cc @davanstrien 
As suggested by @davanstrien we should raise an explicit issue + add an option if a user _really_ wants to ignore parsing error (=> better to fail by default than losing some information). For now option is used purely in `ModelCard` but also implemented in `DatasetCard` and `SpaceCard` as we're using inheritance.
This is a breaking change but as discussed on [slack](https://huggingface.slack.com/archives/C02V5EA0A95/p1677159836698829) (internal link), model cards with invalid metadata are already rejected by the server when pushed on the Hub. So this change should only affect invalid metadata on legacy model cards on the Hub.
Adapted the tests accordingly.
(cc @lvwerra who since I know you're using …

Explicit raise on invalid model_index + add `ignore_metadata_errors` option

---

docs/source/guides/upload.mdx
src/huggingface_hub/fastai_utils.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/hub_mixin.py
src/huggingface_hub/keras_mixin.py
tests/test_hf_api.py

Step 1 for #1352: add a `delete_patterns` parameter to `upload_folder`. It makes sense in a lot of cases to delete remote files before uploading new ones.
The workflow is:
1. if `delete_patterns` is provided, list remote files (can be optimized once https://github.com/huggingface/moon-landing/pull/5580 is deployed)
2. apply the pattern filter => create a list of CommitOperationDelete (never delete ".gitattributes")
3. if a file is both deleted and overwritten in the same commit, drop the deletion operation
4. (not done) we could optimize this in case the user deletes an entire folder. At the moment it's 1 file = 1 delete operation. Seems error-prone to try to decode the patterns manually so let's do it later if we see it's a limitation.
Included in PR:
- refactored …

Add `delete_patterns` option to `upload_folder`

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

`sort_dicts` is not supported in Python 3.7. Let's remove it (not so problematic IMO if keys are sorted).
Has been reported by [`transformers` CI](https://github.com/huggingface/transformers/pull/22021) when testing the pre-release.
cc @davanstrien

Fix ReprMixin for python3.7 + test

---

src/huggingface_hub/_commit_api.py
tests/test_commit_api.py
tests/test_hf_api.py

A bug have been introduced in release `v0.13` when `path_in_repo="."` in `upload_folder`. I fixed that and added a few rules to make sure that `path_in_repo` will be accepted by the server. If `path_in_repo` is obviously invalid (e.g. `path_in_repo=".."`) we raise an error early.
Without this validation, server returns a HTTP 500 (instead of HTTP 400 Bad Request). [An issue](https://github.com/huggingface/moon-landing/issues/5520) is already opened for that (internal link). 
cc @BenjaminBossan as this affected [skops CI](https://github.com/skops-dev/skops/actions/runs/4374220589/jobs/7653373631) since the new release.
cc @Pierrci @coyotte508 for server-side issue
Will release a hot-fix once this is merged (hopefully quickly)

Fix `path_in_repo` validation when committing files

---

src/huggingface_hub/file_download.py
tests/test_file_download.py

Fix https://github.com/huggingface/huggingface_hub/issues/1398, https://github.com/huggingface/diffusers/issues/2729 and https://github.com/huggingface/transformers/pull/22228.
Using absolute symlinks was not a good idea in the end. Reverted back to always use relative symlinks in the cache folder + use relative symlinks to local_dir whenever possible (i.e. always except for Windows with different volumes).
Added more docstring to remember for next time.
cc @Skquark @Schmavery who issues since the last release.
(also cc @guoyk93 who advocated for relative paths in https://github.com/huggingface/huggingface_hub/issues/1396#issuecomment-1473696131)
(and also, added back private method `_create_relative_symlink` that is used in `transformers`'s migration script)

Hotfix - use relative symlinks whenever possible

---

src/huggingface_hub/templates/modelcard_template.md

Not sure that `### How to Get Started with the Model` belongs under the `Bias, Risks, and Limitations` section, so this PR changes it from a H3 to an H2.

Model card template: Move model usage instructions out of Bias section

---

src/huggingface_hub/README.md
src/huggingface_hub/__init__.py
src/huggingface_hub/_commit_api.py
src/huggingface_hub/_login.py
src/huggingface_hub/commands/user.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/utils/__init__.py
src/huggingface_hub/utils/_git_credential.py
src/huggingface_hub/utils/_pagination.py
tests/test_cache_layout.py
tests/test_fastai_integration.py
tests/test_hf_api.py
tests/test_keras_integration.py
tests/test_repository.py

Remove deprecated methods:
- `set_access_token`
- `unset_access_token`
- `read_from_credential_store`
- `write_to_credential_store`
- `erase_from_credential_store`
All of those are related to git credentials management. The preferred methods are not `set_git_credentials` and `unset_git_credential`. Their main advantage is to respect the user preferences in term of git credential helper instead of assuming `git-credential-store` should be used. Read https://github.com/huggingface/huggingface_hub/issues/1051 and  https://github.com/huggingface/huggingface_hub/pull/1138 for more details.
I also took the opportunity of this PR to refactor some tests that were using `set_access_token`.
---
`set_access_token` was use in other HF repos. However, it was only for testing purposes and seemed to be …

Prepare for 0.14

---

docs/source/package_reference/utilities.mdx
src/huggingface_hub/__init__.py
src/huggingface_hub/_commit_api.py
src/huggingface_hub/commands/lfs.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/inference_api.py
src/huggingface_hub/lfs.py
src/huggingface_hub/repocard.py
src/huggingface_hub/utils/__init__.py
src/huggingface_hub/utils/_errors.py
src/huggingface_hub/utils/_http.py
src/huggingface_hub/utils/_pagination.py
src/huggingface_hub/utils/_telemetry.py
tests/test_hf_api.py
tests/test_inference_api.py
tests/test_utils_http.py
tests/test_utils_pagination.py
tests/test_utils_telemetry.py
tests/testing_utils.py

Related to https://github.com/huggingface/huggingface_hub/issues/1368.
The goal of this PR is to speed-up `huggingface_hub` by keeping the connection alive between HTTP calls. This can be done using `requests.Session` objects. Since sessions [are not guaranteed to be thread-safe](https://github.com/psf/requests/issues/2766), I am creating 1 session object per thread. For most users it will be an invisible change -except the speed-up-. Third-party libraries can also benefit from it by using `get_session()` if they make custom calls to the Hub:
```py
import requests
requests.post(...)
from huggingface_hub import get_session
get_session().post(...)
``` 
In addition to this, this PR adds a `configure_http_backend` method to let the user configure the session parameters. It is useful on …

Keep-alive connection between requests

---

src/huggingface_hub/file_download.py
tests/test_file_download.py

Related to https://github.com/huggingface/huggingface_hub/issues/1396.
@guoyk93 reported an inconsistency while downloading a file from the Hub. Not sure what happened (couldn't reproduce it myself) but the very least we can do is to raise an error if the file size is not the expected one at the end of a download. Message suggests to use `force_download=True` and `resume_download=False` to be sure that any existing (corrupted) file will be overwritten.
Note: I didn't want to compute the checksum of the downloaded file as it's a time consuming process for the user (can take a few seconds for a huge file).

Raise after download if file size is not consistent

---

docs/source/guides/upload.mdx
src/huggingface_hub/_commit_api.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/utils/__init__.py
src/huggingface_hub/utils/_paths.py
tests/test_commit_api.py
tests/test_hf_api.py
tests/test_utils_paths.py

Fix https://github.com/huggingface/huggingface_hub/issues/1401 and https://github.com/huggingface/huggingface_hub/issues/1402 (thanks @lewtun for reporting it).
This PR:
- adds a check in `CommitOperationAdd` and `CommitOperationDelete` => it is not possible to upload/delete a file in the `.git/` folder. Server would not accept it anyway but let's raise an issue early.
- ignores the `.git/` folder when uploading with `upload_folder`
- adds tests and docs
One thing that would be cool before having a `huggingface-cli push` command would be to comply with the `.gitignore` [specification](https://git-scm.com/docs/gitignore). However this is not straightforward (cannot be converted to a list of allow_patterns/ignore_patterns that easily). I have found a …

Raise issue if trying to upload `.git/` folder + ignore `.git/` folder in `upload_folder`

---

src/huggingface_hub/_login.py
src/huggingface_hub/utils/__init__.py
src/huggingface_hub/utils/_subprocess.py
tests/test_command_delete_cache.py
tests/test_utils_cache.py
tests/testing_utils.py

Fixes [1384](https://github.com/huggingface/huggingface_hub/issues/1384)
The PR adjusts notebook_login() to use the ipywidgets Box output to print the feedback.
This enables the logic to work in all notebooks that are compatible with ipywidgets - including Databricks where `clear_output` does not work.
Examples for the code flow:

Fix: notebook_login() does not update UI on Databricks

---

setup.py
src/huggingface_hub/hf_file_system.py

Improvements:
* pass the `ls` kwargs to `glob` in `expand_path`
* register `hf` as a `fsspec` protocol via the `entry_points` (explained [here](https://filesystem-spec.readthedocs.io/en/latest/developer.html#implementing-a-backend)).`fsspec.register_implementation("hf", huggingface_hub.HfFileSystem)` before using the HF filesystem with `fsspec` integrations is no longer required after this change

Hffs misc improvements

---

src/huggingface_hub/file_download.py

Related to https://github.com/huggingface/huggingface_hub/issues/1385. See [CI logs](https://github.com/deepset-ai/haystack/actions/runs/4619482614/jobs/8232850199?pr=4607) in dependent library.
If we try to create a symlink between 2 volumes, `common_path` will fail with `ValueError("Paths don't have the same drive")`. Let's not create symlinks in such a case on Windows (still ok on Linux/MacOS). 
cc @mayankjobanputra can you please try to run your test suite with this fix (`pip install git+https://github.com/huggingface/huggingface_hub@1385-fix-symlinks-on-different-volumes`) and report here if it definitely fixed your issue? Thanks in advance.

Fix symlinks on different volumes on Windows

---

src/huggingface_hub/file_download.py

When using `huggingface_hub.snapshot_download` to `local_dir` in mounted device with `local_dir_use_symlinks=False`, this error occurred:
```python
~/anaconda3/envs/thaiminhpv/lib/python3.9/site-packages/huggingface_hub/file_download.py in _chmod_and_replace(src, dst)
1553         tmp_file.unlink()
1554 
-> 1555     os.replace(src, dst)
1556 
1557 
OSError: [Errno 18] Invalid cross-device link: '/home/thaiminhpv/.cache/huggingface/hub/tmpzancmmsh' -> '/mnt/some_device/Storage/test/.gitattributes'
```
1. Install the latest huggingface_hub library (`0.13.4` at this moment)
```python3
!pip3 install -qU huggingface_hub
>>> import huggingface_hub
>>> huggingface_hub.__version__
'0.13.4' 
```
2. Using `snapshot_download` to download to a _mounted folder_, with `local_dir_use_symlinks=False` …

[FIX] bug "Invalid cross-device link" error when using snapshot_download to local_dir with no symlink

---

docs/source/guides/manage-spaces.mdx
docs/source/package_reference/space_runtime.mdx
src/huggingface_hub/__init__.py
src/huggingface_hub/_space_api.py
src/huggingface_hub/file_download.py
src/huggingface_hub/hf_api.py
tests/test_hf_api.py

This PR adds a new `set_space_sleep_time` method to set a custom sleeping time for Spaces. By default, a (paid) upgraded hardware will never go to sleep while a cpu-basic goes to sleep after 48h. Only upgraded hardware can be configured.
TODO:
cc @abidlabs will be helpful for https://github.com/gradio-app/gradio/pull/3809

[Feat] Add `sleep_time` for Spaces

---

docs/source/package_reference/utilities.mdx
src/huggingface_hub/utils/_http.py
tests/test_utils_http.py

Instead of using parameters (that are dependent on `requests` and that we would need to document/maintain), the user has to provide its own session factory. This will be less error-prone and allow any kind of configuration. For example, mounting a custom adapter will become possible, as done in https://github.com/narugo1992/hfmirror/blob/a5daefa54576de81da1b880ef4c3df9f2cf53000/hfmirror/utils/session.py#L28

Accept `backend_factory` to configure Sessions

---

src/huggingface_hub/__init__.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/hf_file_system.py
tests/test_hf_api.py

This PR adds `list_files_info` that is a wrapper around 2 endpoints:
1. `/paths-info` to get info about a list of paths
2. `/tree` to recursively get info about files in a folder. It is paginated so we return a Python generator instead of a list.
With `list_files_info` we should be able to implement a `CommitOperationCopy`-ish operator that was discussed in https://github.com/huggingface/huggingface_hub/issues/1083 and https://github.com/huggingface/moon-landing/issues/4370 (internal link). For more implementation details, see related discussion [on slack](https://huggingface.slack.com/archives/C03V11RNS7P/p1681219416049149) (internal) as well as [this comment](https://github.com/huggingface/hffs/issues/5#issuecomment-1474366560).
TODO:
**Examples:**
1. Get information about files on a …

Implement `list_files_info` + tests

---

src/huggingface_hub/file_download.py

- This is necessary for private models download.
- It was enabled in `hf_transfer==0.1.3`.

Passing the headers to hf_transfer download.

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

Fix https://github.com/huggingface/huggingface_hub/issues/1447.
Solve https://github.com/huggingface/huggingface_hub/issues/1447 (and https://github.com/huggingface/huggingface_hub/issues/1212 as a side effect).
Using `list_repo_files(..., expand=True)` returns more details. It's more heavy to return server-side (see https://github.com/huggingface/moon-landing/issues/5993 -private repo) so we don't make it the default. Also client side it takes a bit more time on big repo has results are paginated 50 by 50 (instead of 1000 if expand=False).
The returned details are:
- `lastCommit`: oid/title/date of the last change on this file
- `security`: full result of the security scan. Only returned by the `/tree` endpoint at the moment which means the user needs to list entire directory to get this …

Add `expand` parameter to `list_repo_files`

---

docs/source/package_reference/hf_file_system.mdx

Fix broken link in docs to `guides/hf_file_system` from `package_reference/hf_file_system`:
- From: `../guides/filesystem`
- To: `../guides/hf_file_system`
Related to:
- #1461

Fix broken link in docs to hf_file_system guide

---

src/huggingface_hub/hf_file_system.py

Remove mentions to `hffs` from docs, once that the file system is integrated in `huggingface-hub`.

Remove hffs from docs

---

src/huggingface_hub/__init__.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/utils/endpoint_helpers.py
tests/test_hf_api.py

Following 0.14 release.
Breaking changes:
- `list_models`, `list_datasets` and `list_spaces` return an iterable instead of a list (lazy-loading of paginated results)
- cannot use `cardData` in `list_datasets`. Should use `full` instead.
Both changes should have been removed in 0.14 already but I forgot :innocent:. Since they were deprecated I hope the change will not brake too much warnings. I'll still advertise internally, just in case.
(I also modified some tests to stop listing all models/datasets/spaces from the Hub just to check it returns more than 100 results. This should save 2-3min on the overall CI :exploding_head:)

Remove deprecated code + adapt tests

---

src/huggingface_hub/_snapshot_download.py

In `snapshot_download`, user-agent can be passed but is not taken into account for the `repo_info` call. This PR fixes this.

FIX user agent not passed in snapshot_download

---

src/huggingface_hub/_webhooks_payload.py
src/huggingface_hub/_webhooks_server.py

Avoids the ImportError when doing `from huggingface_hub import *` without having Gradio installed.
(The error is now raised when initializing a `WebhooksServer` object.)

Avoid `ImportError` when importing `WebhooksServer` and Gradio is not installed

---

src/huggingface_hub/utils/_deprecation.py

Micro edit!
I was cleaning up some code that leverages `huggingface_hub`, specifically I was using the method `len(list_models(...))`, which gave the deprecation warning:
```
FutureWarning: 'list_models' currently returns a list of objects but is planned to be a generator starting from version 0.14 in order to implement pagination. Please avoid to use `list_models(...).__len__` or explicitly convert the output to a list first with `list(iter(list_models)(...))`.
warnings.warn(self._deprecation_msg.format(attr_name=attr_name), FutureWarning)
```
For some reason I read `list(iter(list_models)(...))` way too literally, and thought that `iter()` worked similarly to a decorator or contained a nested function (that also took in ellipses as an arg).
I believe it is a typo, where the inside of …

Fix incorrect syntax in `_deprecation.py` warning message for `_deprecate_list_output()`

---

src/huggingface_hub/inference_api.py

Fix https://github.com/huggingface/huggingface_hub/issues/1424.
This is a temporary solution since `InferenceClient` is now the way to go for inference. `InferenceAPI` will soon be deprecated anyway.

Support image-to-image task in InferenceApi

---

src/huggingface_hub/repocard_data.py

In `datasets` we want to use `configs` yaml field to define custom configurations' parameters for datasets without scripts: https://github.com/huggingface/datasets/pull/5331#issuecomment-1570751476
So we decided to rename the old `configs` field to `config_names` cc @julien-c 
@lhoestq already changed `configs` to `config_names` in all canonical datasets.

Rename "configs" dataset card field to "config_names"

---

src/huggingface_hub/__init__.py
src/huggingface_hub/hub_mixin.py

Not much to remove which is I think a good sign that `huggingface_hub` is getting more mature :)
- force to use kwargs in `ModelHubMixin` (instead of passing everything a positional arg)
- not possible anymore to pass model_id as `username/repo_name@revision` in `ModelHubMixin`
(+2 type annotations fixes)

Remove deprecated code for v0.16.x

---

docs/source/guides/upload.mdx
docs/source/package_reference/hf_api.mdx
src/huggingface_hub/__init__.py
src/huggingface_hub/_commit_api.py
src/huggingface_hub/_multi_commits.py
src/huggingface_hub/hf_api.py
tests/test_hf_api.py

close https://github.com/huggingface/huggingface_hub/issues/1083

add CommitOperationCopy

---

docs/source/guides/inference.mdx
src/huggingface_hub/_inference.py
tests/test_inference_client.py

Related to https://github.com/huggingface/api-inference-community/pull/287 (and especially https://github.com/huggingface/api-inference-community/pull/287#issuecomment-1584578637) cc @StephenHodgson @Narsil 
With this PR, user can set custom headers and cookies to the `InferenceClient` session. This can prove useful when using custom endpoints. If set, custom headers overwrite the default user-agent and authorization headers.
(+fix documentation => save audio as .flac instead of .wav)

Custom headers/cookies in InferenceClient

---

src/huggingface_hub/file_download.py

Related to [internal slack thread](https://huggingface.slack.com/archives/C02EMARJ65P/p1686829213703489). The default timeout when downloading a file (`hf_hub_download`) is 10s. This is far enough in most cases but in a very few cases it causes a ConnectionError (especially in `transformers`'s CI recently). Except if this 10s limit is really useful, I suggest to remove it. In the worst case, there is a 60s timeout on cloudfront.
Note: I am not talking about the 10s `etag_timeout` that is used when making the HEAD call to the file. For this one I think it's good to keep it and default early (10s) to the local cache.
Thanks @ydshieh @rtrompier for debugging this one! I hope it'll solve transformers's issues :)
@julien-c @Pierrci @LysandreJik since it's about the `/resolve/` endpoint, please …

Set 30s timeout on downloads (instead of 10s)

---

src/huggingface_hub/file_download.py
src/huggingface_hub/utils/_http.py

Solves https://github.com/huggingface/huggingface_hub/issues/1526 (cc @alexmojaki). Issue caused CI failures in https://github.com/huggingface/transformers/pull/24384#issuecomment-1602990696 (cc @ydshieh).
At the moment HTTP requests failing with a `ConnectTimeout` or `ProxyError` when downloading a file are retried with a  backoff strategy. This PR adds `ReadTimeout` as an exception to retry on as well. More precisely, we now retry on any `requests.exceptions.Timeout` error (meaning both connect and read timeouts).
This change does not introduce a breaking change as `ConnectTimeout` errors are still caught. It should fix downloads in some rare occasions.

Retry on both ConnectTimeout and ReadTimeout

---

src/huggingface_hub/file_download.py

The goal is to verify the fix on infra side works. We can either keep it 10s if everything is fine, or change back to 60s if we prefer.

Set timeout to 10s

---

src/huggingface_hub/utils/_http.py
tests/test_utils_http.py

Related to https://github.com/huggingface/huggingface_hub/pull/1518. A `x-request-id` header is added to every request made to the Hub and is printed in the error message in case of error 4XX or 5XX.
In this PR, I also catch _any_ `RequestException` to add the request_id to the debug message. In particular any TimeoutError or ConnectionError will be easier to investigate.

Add request id to message in ConnectionError

---

src/huggingface_hub/utils/_http.py
tests/test_utils_http.py

Found a bug in `huggingface_hub` while investigating why CI in https://github.com/huggingface/lighteval-harness/pull/113 was failing (private repo). 
The triggered error was:
```
HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)' thrown while requesting HEAD https://huggingface.co/gpt2/resolve/main/config.json
```
It turns out that the error happens because a `request.Session` is shared between processes and somehow the session gets broken when forked. Sharing the session was not intended and is due to a bug in [`./utils/_http.py`](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/utils/_http.py). To avoid sharing a session object, I was only checking the thread ID. This PR fixes the issue by checking the process ID as well. …

Make `requests.Session` truly unique

---

src/huggingface_hub/repocard.py
tests/test_repocard.py

Following https://github.com/huggingface/huggingface_hub/issues/1546 @lhoestq 
There was an issue on Windows if a modelcard has a metadata section that was empty. This is fixed.

1546 fix empty metadata on windows

---

src/huggingface_hub/inference/_client.py
src/huggingface_hub/inference/_common.py
src/huggingface_hub/inference/_generated/_async_client.py
tests/test_inference_client.py
utils/generate_async_inference_client.py

cc @philschmid 
Tasks that expect an image to be returned by the server (i.e. image-to-image and text-to-image) must send `Accept: image/png` as header by default. This value can be overwritten by the user if needed. This PR fixes a bug happening with Inference Endpoints which returns a base64-encoded image in case Accept header is not set. This doesn't change anything for InferenceAPI calls.
**EDIT:** also fixes a bug in AsyncInferenceClient where headers set by the user where not taken into account.
**NOTE:** failing tests are unrelated

Send Accept: image/png as header for image tasks

---

src/huggingface_hub/file_download.py
tests/conftest.py
tests/test_file_download.py

In certain cases, we might assume that the model files exist (like in a docker) but huggingface token is not set, and the user only needs to run the model locally. This works for diffusers with default arguments, but in transformers, a RepositoryNotFoundError is raised if `not_local_files_only` is true, but user is not logged into huggingface. 
Example code:
```
from transformers import T5EncoderModel, T5Tokenizer
tokenizer = T5Tokenizer.from_pretrained("DeepFloyd/IF-I-XL-v1.0", subfolder="tokenizer")
prompt = "something"
text_inputs = tokenizer(prompt, padding="max_length", max_length=77, truncation=True, add_special_tokens=True, return_tensors="pt")
print(text_inputs)
```
The fix is to check if there is a token or not. If there is a token, then there might be authentication issues. If …

Check local files if (RepoNotFound, GatedRepo, HTTPError) while downloading files

---

docs/source/guides/inference.md

Fixes [table](https://huggingface.co/docs/huggingface_hub/main/en/guides/inference#supported-tasks) that displays the supported tasks for the `InferenceClient` which is a bit disjointed right now.

[docs] Fix table

---

src/huggingface_hub/_snapshot_download.py
src/huggingface_hub/file_download.py
src/huggingface_hub/hf_api.py
tests/test_file_download.py
tests/test_hf_api.py

FIX #1573 and #1082.
- Add `endpoint` to both `hf_hub_download` and `snapshot_download`. Let's be honest, this is used only in unit tests to change to staging endpoint. At least it is aligned with other methods from huggingface_hub (was not the case before)
- Add `hf_hub_download` and `snapshot_download` as aliases in `HfApi` class. Idea has been discussed [on slack](https://huggingface.slack.com/archives/C02V5EA0A95/p1690546593081429) (internal link). The main goal is to reuse endpoint, user-agent, token,... parameters from the HfApi instance instead of passing them into each individual call (same as `upload_file` and `upload_folder` currently).   
cc @severo @mariosasko for #1082 
cc @Narsil @hysts for #1573 
(note: failing tests are unrelated)

Add download alias for `hf_hub_download` to `HfApi`

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

Solves #1585 cc @osanseviero @christophe-rannou. 
Add support for factory reboot when restarting a Space.
```py
from huggingface_hub import restart_space
restart_space("Wauplin/bloomz.cpp-converter", factory_reboot=True)
```

Support factory reboot when restarting a Space

---

src/huggingface_hub/inference/_client.py
src/huggingface_hub/inference/_generated/_async_client.py
tests/cassettes/InferenceClientVCRTest.test_text_to_image_with_parameters.yaml
tests/test_inference_client.py

Fix https://github.com/huggingface/huggingface_hub/issues/1581 (cc @zwx00)
Extra parameters (width, height, guidance_scale,...) are ignored by `InferenceClient` when using `text_to_image` and `image_to_image` tasks. This was due to an invalid payload being sent to the server. This PR fixes it + add a test.

FIX `text_to_image` and `image_to_image` parameters

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

Added support for secret description

---

src/huggingface_hub/file_download.py
tests/test_file_download.py

Implemented check_disk_space function

---

src/huggingface_hub/hf_file_system.py
tests/test_file_download.py
tests/test_hf_api.py
tests/test_hf_file_system.py

`fsspec.exists` logic catches ALL exceptions which can lead to unexpected behaviors. For example, we raise a `NotImplementedError` when trying to list repositories (which is not supported). This PR adapts the logic to raise on any exception except the `NotImplementedError`.
First discovered about it since `fsspec.glob()` logic has been changed in https://github.com/fsspec/filesystem_spec/pull/1329 (released in [2023.9.0](https://filesystem-spec.readthedocs.io/en/latest/changelog.html#id1)). It now relies on [`.exists()`](https://github.com/fsspec/filesystem_spec/pull/1329/files#diff-02a7ab40d6026e60bf52f78d93fc7146e53bc2455a8cb4073838297feaa090fbR576) instead of `.find()` which catch all exceptions, including the NotImplementedError (making the CI fail)
cc @mariosasko please let me know …

Fix fsspec tests in ci

---

src/huggingface_hub/inference/_client.py
src/huggingface_hub/inference/_common.py
src/huggingface_hub/inference/_generated/_async_client.py

This PR fixes an incoherence reported by @martinbrose in https://github.com/huggingface/huggingface_hub/pull/1606#discussion_r1315233260. In the inference client logic, we have a `_bytes_to_dict` helper that is annotated as returning an `"Image"` which is wrong. 
This PR changes the return type of  `_bytes_to_dict` and adds a `_bytes_to_list` helper. Both have the exact same logic to decode JSON-encoded data. The advantage of having 2 helpers is to help devs + mypy understand what is the expected data format from the server. If the data is not in a valid form, no issue is raised at runtime.

Distinguish `_bytes_to_dict` and `_bytes_to_list` + fix issues

---

src/huggingface_hub/__init__.py

Following [`0.17.0` release](https://github.com/huggingface/huggingface_hub/releases/tag/v0.17.0). No deprecation cycle ongoing for this release so nothing much to change (cc @LysandreJik)

Prepare for `v0.18.0`

---

src/huggingface_hub/commands/upload.py
tests/test_cli.py

This PR sets `library_name="huggingface-cli"` in the upload CLI command (similar to the [download command](https://github.com/huggingface/huggingface_hub/blob/49cbeb78d3d87b22a40d04ef8a733855e82d17ef/src/huggingface_hub/commands/download.py#L180)). The goal is to be able to track usage of CLI vs script to upload files.

Add default user-agent to huggingface-cli

---

src/huggingface_hub/file_download.py
src/huggingface_hub/utils/__init__.py
src/huggingface_hub/utils/_errors.py

Several users reported getting stuck with an OSError _"Distant resource does not seem to be on huggingface.co"_ when trying to download files from the Hub. It turned out this can be caused by a wrong configuration on the client network (firewall or proxy) (example: https://github.com/huggingface/huggingface_hub/issues/1600#issuecomment-1684391061 and https://github.com/huggingface/huggingface_hub/issues/1600#issuecomment-1689782396).
This PR adds a better error message suggesting to check the config in case that happen. This might help some users getting unblocked. It also tries to fallback to a locally saved file if available. That would help users that works with different networks depending on their location.
Closes https://github.com/huggingface/huggingface_hub/issues/1600.

Suggest to check firewall/proxy settings + default to local file

---

src/huggingface_hub/hf_api.py

Since [moon-landing#7272](https://github.com/huggingface/moon-landing/pull/7272) (private repo), it is not possible to concurrently create repos on the Hub for a same user. This is rarely an issue, except when running tests (it is actually breaking all CI tests at the moment :confused:). This PR makes the lib' retry until the repo is created or a "real" error occurs.
Notes:
- Most users should not be impacted by this change. Worst case scenario, it's still better than having a 409 and retry manually. Infinite loops _shouldn't be_ a problem (:crossed_fingers:)
- This could have being fixed directly in the tests but adding it here should fixed CIs for all dependent libraries.
- If a fix is implemented server-side, we should be able to remove this retry mechanism.
cc @SBrandeis @Kakulukian …

Automatically retry on `create_repo` if '409 conflicting op in progress'

---

.github/workflows/python-tests.yml
src/huggingface_hub/commands/upload.py

In `huggingface-cli upload` command, we create the repo for the user if it doesn't exist yet. When pushing to a `Space`, the upload command fails because `space_sdk` is not set. It fails client-side no matter if the Space already exists or not. This PR fixes this by setting `space_sdk="gradio"` by default.
The reason why I prefer not to add a `--space-sdk` option is that the `upload` command is not really meant to configure how the Space should be configured (in comparison to `huggingface-cli repo create`). The fact that the repo is created by default is more a "nice to have".
```bash
huggingface-cli upload my-cool-space README.md --repo-type=space
```
I'm planning to do a **hot-fix release** after this PR is merged as the upload command is currently unusable without it (for Spaces)
--- …

Fix upload CLI when pushing to Space

---

docs/source/en/guides/upload.md

Just a quick fix for the upload guide.
It erroneously refers to "**two** types of operations supported by [`create_commit`]" and then lists **three** in the list below.

Correct typo in upload guide

---

src/huggingface_hub/file_download.py

Addresses issue #1674:
Basically allows longer part of the filename being visible during model loading, at the expense of the word "Downloading".
See more details about rationale and possible alternatives at #1674

Longer progress bar description before trim, drop D-word 

---

src/huggingface_hub/hf_api.py
tests/test_hf_api.py

Fixes filtering by tags with list_models and adds test case

---

setup.py
src/huggingface_hub/hf_file_system.py

... to avoid having to update `HfFileSystem.expand_path` when new changes are made to the default implementation (e.g., the latest `fsspec` release (`2023.9.0`) added a `maxdepth` param to the signature ([PR](https://github.com/fsspec/filesystem_spec/pull/1329)))

Pin `fsspec` to use default `expand_path`

---

src/huggingface_hub/_login.py

The `<Tip>` section doesn't look great in [login package reference](https://huggingface.co/docs/huggingface_hub/v0.17.1/en/package_reference/login#huggingface_hub.login) cc @osanseviero

Fix broken tips in login reference

---

src/huggingface_hub/hf_api.py
src/huggingface_hub/inference/_client.py
src/huggingface_hub/inference/_generated/_async_client.py
src/huggingface_hub/inference/_text_generation.py
src/huggingface_hub/utils/_errors.py
utils/generate_async_inference_client.py

`HTTPError` has 2 attributes `request` and `response`. Both are expected by users to be not `None` but it was not really enforced at any level (typed as `Any`). Since [`types-requests==2.31.0.4`](https://github.com/typeshed-internal/stub_uploader/blob/main/data/changelogs/requests.md#23104-2023-09-23), the types are now enforced to be `requests.Request` and `response.Response`. This PR adapts the current code to set the request/response attributes correctly whenever possible. However this is not always possible due to how our errors are built (it happens in rare cases that we raise a HTTPError even though it's not *really* a HTTPError per-se). I think enforcing request/response whenever possible + ignore other errors is fine for now. Let's reassess if at any point some users complain.
See …

Respect `HTTPError` spec

---

docs/source/en/guides/collections.md
src/huggingface_hub/hf_api.py
tests/test_hf_api.py

Follow-up after https://github.com/huggingface/huggingface_hub/pull/1687. From a [comment](https://github.com/huggingface/huggingface_hub/pull/1687#issuecomment-1733459586) from @davanstrien:
> Would adding a collection_url/url attribute to the Collection object make sense? I realise this can easily be got from the slug i.e. f"https:huggingface.co/collections/{collection.slug}" but maybe it's nice to make it easier for a user to quickly access that so they can check their collection via the Hub more quickly?

Add `url` attribute to Collection class

---

docs/source/de/_toctree.yml
docs/source/de/concepts/git_vs_http.md
docs/source/de/index.md

References https://github.com/huggingface/huggingface_hub/issues/1645
**Key features**
- Translates `concepts/git_vs_http` to German

Add German concepts guide

---

src/huggingface_hub/file_download.py
tests/test_file_download.py

Address issue #1690.
`_check_disk_space` fails when only provided with incomplete paths like `checkpoints/stabilityai/stable-diffusion-xl-base-1.0` and then tries to asses exactly this "path". 
It seems to be a regular case when `snapshot_download` and hence `hf_hub_download` is being called without the parameter `local_dir`.
`snapshot_download.py` (248:250) only performs `os.path.realpath()` when `local_dir` is not None:
```python
if local_dir is not None:
return str(os.path.realpath(local_dir))
return snapshot_folder
```
My change in this PR now addresses this case and ensures that the real complete path is being used in `shutil.disk_usage().free` within `_check_disk_space()`.

Address failing _check_disk_space() when path doesn't exist yet

---

docs/source/en/guides/upload.md
src/huggingface_hub/__init__.py
src/huggingface_hub/_commit_api.py
src/huggingface_hub/hf_api.py
tests/test_commit_api.py
tests/test_hf_api.py

Related to https://github.com/huggingface/datasets/issues/6257#issuecomment-1736822023 cc @mariosasko @lhoestq.
The goal of this PR is to add the possibility to preupload files before making the `create_commit` call. This is expected to be only a power-user feature meant for users generating huge files on the fly (e.g. basically `datasets` when uploading sharded parquet files). The current problem is that each file has to be committed one by one to avoid out-of-memory issues. This strategy leads to 1. users being rate-limited (too many commits) 2. messy git history.
The solution proposed in this PR is to add a `preupload_lfs_files` methods. It takes a list of `CommitOperationAdd` and upload them to S3 (if LFS). Once all the `CommitOperationAdd` are uploaded, a single `create_commit` call …

Preupload lfs files before commiting

---

tests/test_hf_api.py
tests/test_repocard.py
tests/testing_constants.py

This PR should fix the current CI failure (LFS tests not passing).
LFS tests were using password authenticating when cloning/pushing a git repo. This is now deprecated in favor of SSH or token-based auth (see [blog article](https://huggingface.co/blog/password-git-deprecation)). For those tests, let's use token-based instead. 
cc @Pierrci @coyotte508 
(I also refactored a bit the repocard tests that were using password-auth URLs as well -not wrong but a bit old and dirty :grimacing:)

Fix LFS tests after password auth deprecation

---

src/huggingface_hub/hf_file_system.py
tests/test_hf_file_system.py

Solves https://github.com/huggingface/huggingface_hub/issues/1710 by processing `refs/convert/parquet` and `refs/pr/(\d)+` as special revisions when resolving a path. Also make sure that the `unresolve` counterpart works the same. Also added some tests for it.
Use case from @Hakimovich99 now works properly without having to url-encode the revision. This time I tested with [jamescalam/llama-2-arxiv-papers-chunked](https://huggingface.co/datasets/jamescalam/llama-2-arxiv-papers-chunked) dataset which doesn't have parquet files on `main` revision:
```py
>>> from dask import dataframe as dd
>>> dd.read_parquet("hf://datasets/jamescalam/llama-2-arxiv-papers-chunked@refs/convert/parquet")
>>> dd.read_parquet("hf://datasets/jamescalam/llama-2-arxiv-papers-chunked@refs/convert/parquet/default/trai …
```

Handle `refs/convert/parquet` and PR revision correctly in hffs

---

src/huggingface_hub/inference/_common.py
src/huggingface_hub/inference/_text_generation.py

Fix https://github.com/huggingface/huggingface_hub/issues/1651.
When streaming tokens from a TGI server, an error might happen and be returned in the stream of tokens. At the moment this raises a pydantic ValidationError as it's not recognized as a proper `TextGenerationStreamResponse`. This PR adds a check to parse correctly the error message + raise a custom exception whenever possible.
cc @osanseviero @OlivierDehaene 
**Note:** I couldn't really test this PR as the problem is hard to reproduce (it happened in the falcon-180b demo Space which has heavy usage -see [thread](https://huggingface.slack.com/archives/C05PZ9K0L6R/p1694091341361899?thread_ts=1694033671.072209&cid=C05PZ9K0L6R) (internal)). Shouldn't be too risky though (error/error_type being optional client-side).

Handle TGI error when streaming tokens

---

docs/source/en/package_reference/hf_api.md
src/huggingface_hub/__init__.py
src/huggingface_hub/hf_api.py
tests/test_hf_api.py

This PR introduces the `list_repo_likers` method to the `HfApi` class, allowing users to retrieve a list of likers for a given model repository on the Hugging Face Hub.
- Implemented `list_repo_likers` method in `HfApi`.
- Added corresponding dataclass `User` to represent users who liked a repo.
- Integrated a new API endpoint to fetch likers for a given model repository.
- Added unit tests to ensure the correctness of the method.
- Fixes #1705 - Return the liked users for a Hugging Face model
- Users will now have the ability to see who liked their models, fostering community interactions and recognition.

Add list_repo_likers method to HfApi

---

src/huggingface_hub/_commit_api.py

... so that IDEs stop displaying them in the auto-complete

Hide `CommitOperationAdd`'s internal attributes

---

src/huggingface_hub/hf_api.py

Adds a `token` parameter to `HfApi`'s `snapshot_download`/`hf_hub_download` to be consistent with the rest of the methods.
(It would come in handy in https://github.com/huggingface/datasets/pull/6269 🙂)

Add `token` parameter to `HfApi`'s `snapshot_download` and `hf_hub_download`

---

src/huggingface_hub/repository.py

References #1721 
The error has been fixed by checking the number of files to be staged. If there are fewer than 5 files, a notification is created without causing an error.

Fix UnboundLocalError when using commit context manager

---

docs/source/en/package_reference/environment_variables.md
src/huggingface_hub/_snapshot_download.py
src/huggingface_hub/constants.py
src/huggingface_hub/file_download.py
src/huggingface_hub/hf_api.py
src/huggingface_hub/utils/_runtime.py

This PR purpose is to adding the ability to configure the timeout of requests during the download file operation

Adding the ability to configure the timeout of get request

---

tests/conftest.py
tests/test_hf_api.py
tests/test_hf_file_system.py
tests/test_keras_integration.py
tests/test_repocard.py
tests/test_repository.py
tests/testing_utils.py

We currently use `@retry_endpoint` on endpoint tests to retry on HTTPError 504 or OSError (git clone race condition). It has being introduced in https://github.com/huggingface/huggingface_hub/pull/682 to improve stability of the CI. What's still annoying is that it is a decorator that has to be added to every test case individually -which is prone to forgetting. **This PR updates the CI by automatically applying the retry mechanism to all tests.** 
(Note: if in the future we specifically want to opt-out some tests, it is still doable using a `pytest.mark`. But I don't see a reason to do it.).

Make `@retry_endpoint` a default for all test

---

src/huggingface_hub/__init__.py
src/huggingface_hub/inference_api.py

Follow-up after 0.18 release.
`InferenceAPI` was announced to be removed by now but I don't think it's wise. Given how much it has being used in external libraries and scripts I think it's wiser to deprecate it with no real deadline (I've set `v1.0` but not sure it'll happen someday^^).

Bump version to 0.19

---

docs/source/en/concepts/git_vs_http.md
docs/source/en/guides/repository.md
src/huggingface_hub/repository.py
tests/test_repository.py

@julien-c @LysandreJik @osanseviero WDYT of deprecating `Repository` with a link to the ["Git vs HTTP"](https://huggingface.co/docs/huggingface_hub/concepts/git_vs_http) page?
The main feature that was missing at some point was the ability to push changes in the background, which is now doable using `HfApi.run_as_future(...)`. Also, the Trainer implementation in `transformers` has already switched to the http-based approach 3 months ago (https://github.com/huggingface/transformers/pull/25095) without any reported issue.
Given how used `Repository` has been, I think it's good to deprecate it but with a long deprecation cycle (I've set `v1.0` and I'm not even sure it will happen one day :smile:). I still think it's better to have a warning message even if no deadline than nothing.
--- …

Deprecate `Repository` class

---

tests/test_commit_scheduler.py

I discovered `test_sync_and_squash_history` was improperly configured:
- `every` was set at 1-sec, but its comment said 0.1-sec
- A `time.sleep` below was set for 0.5-sec
This led to a race condition.  This solves one of the CI issues hit in https://github.com/huggingface/huggingface_hub/pull/1727.

Properly configures `every` in `test_sync_and_squash_history`

---

src/huggingface_hub/_webhooks_payload.py
tests/test_webhooks_server.py

When deserializing with pydantic:
- v1: it didn't care about missing fields
- v2: it does care about missing fields
This PR simply defaults some test-time fields so they are no longer missing. It solves one of the CI issues hit in https://github.com/huggingface/huggingface_hub/pull/1727.

Testing `WEBHOOK_PAYLOAD_EXAMPLE` deserialization

---

setup.py

Closes https://github.com/huggingface/huggingface_hub/issues/1726
I manually and locally tested with pydantic v2 using Python 3.11.4:
```bash
> pip install -e .[testing]
> pip list | grep pydantic
pydantic                  2.4.2
pydantic_core             2.10.1
> pytest tests/test_inference*.py
...
83 passed, 6 skipped, 16 warnings in 5.73s
```

Supporting `pydantic<3`

---

src/huggingface_hub/hf_file_system.py

Related to https://github.com/huggingface/huggingface_hub/issues/1733 (cc @TwoAbove)
We do not support transaction in `HfFileSystem`. This PR raises explicit `NotImplementedError` instead of allowing `fs.transaction` and `fs.start_transaction` to be used -which ends up committing files in a non-transactional a

[hffs] Raise `NotImplementedError` on transaction commits

---

src/huggingface_hub/inference/_client.py
src/huggingface_hub/inference/_generated/_async_client.py
utils/generate_async_inference_client.py

Consolidated mypy type ignores in `InferenceClient.post`

---

src/huggingface_hub/file_download.py
src/huggingface_hub/utils/_cache_manager.py
tests/test_file_download.py

The lock file could be removed when the 2nd process gets the lock.
And then the 3rd process will lock on a different lock file handle.
Although the lock path stays the same.
1st proc gets the lock
2nd proc waits for the lock
1st proc releases the lock
1st proc removes the lock file
2nd proc gets the lock
3rd proc creates a new lock file and gets the lock
Demo code to show the problem:
```py
from filelock import FileLock
import threading
import os
import time
lock_path = "/tmp/test.lock"
def lock1():
with FileLock(lock_path):
print("lock acquired in thread1")
time.sleep(1)
print("lock released in thread1")
time.sleep(1)
os.remove(lock_path)
print("lock file removed in thread1")
def lock2():
time.sleep(1)
with FileLock(lock_path):
print("lock acquired in thread2")
time.sleep(10)
print("lock …
```

Keep lock files in a `/locks` folder to prevent rare concurrency issue
