huggingface/huggingface_hub

- .github/conda/build.sh
- .github/conda/meta.yaml
- .github/workflows/release-conda.yml
Will push a new version on anaconda cloud every time a tag of with `v` is pushed (like `v0.0.2`).
Will appear here: https://anaconda.org/huggingface/huggingface_hub
Depends on no additional channels than the main one.
Installation is done as follows:
```
conda install -c huggingface huggingface_hub
```
> Conda support 

- src/huggingface_hub/commands/lfs.py
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/lfs.py
- src/huggingface_hub/repository.py
- tests/test_hf_api.py
- tests/test_repository.py
- tests/testing_constants.py
> Repository helper class: continuation of #7

- src/huggingface_hub/repository.py
Convert all `check_output` to `run` and added `stderr` and `stdout` for error handling and giving the user feedback.
> added stderr and exceptions

- src/huggingface_hub/repository.py
- tests/test_repository.py
> Helper: when pushing, return commit url

- .github/workflows/python-quality.yml
- .github/workflows/python-tests.yml
This PRs completes the GA workflows so that Github Actions may run on forks. (This PR is opened from a fork)
> Run GA on forks

- .github/workflows/python-tests.yml
- README.md
- src/huggingface_hub/__init__.py
- src/huggingface_hub/file_download.py
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/snapshot_download.py
- tests/test_file_download.py
- tests/test_hf_api.py
- tests/test_snapshot_download.py
- tests/testing_utils.py
Update: changed the PR's name as I initially wanted to make the file storage "pluggable" but in the end achieved this with simpler params
Also might be interesting to @lhoestq
> Expose more hf.co API surface, and ability to download a snapshot of a repo to a local folder

- setup.py
- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
This documents the filter argument.
> Document the `filter` argument

- api-inference-community/docker_images/sentence_transformers/requirements.txt
For example: sentence-transformers/stsb-xlm-r-multilingual
> Add protobuf as a dependency to handle tokenizers that require it:

- interfaces/Libraries.ts
Make install command more visible and add missing quotes
> SpaCy fixes

- interfaces/Libraries.ts
This PR is mainly to have the library tag, and show it in the filters at the left. The code snippet is not intended to be final, but it's a starting point to have QA. I'm not familiar enough with the library yet, but I can take a closer look to see if we could have a single code snippet to handle all pipelines.
> AllenNLP library tag + code snippet

- interfaces/Libraries.ts
> Mark model config as optional

- .github/workflows/python-api-allennlp.yaml
- .github/workflows/python-api-quality.yaml
- .github/workflows/python-api-tests.yaml
These workflows are currently broken and never running - For example: https://github.com/huggingface/huggingface_hub/actions/runs/949325181/workflow
> Fix inference API GitHub actions

- src/huggingface_hub/hf_api.py
Update the docs to mention it's not using git.
> Update `upload_file` docs

- src/huggingface_hub/hf_api.py
FYI @calpt
(the info is really already there, just making it a bit more explicit)
> Add config to model info

- src/huggingface_hub/__init__.py
- src/huggingface_hub/repository.py
- tests/test_repository.py
This PR introduces a context manager to update repositories on the hub. It is using the `Repository` backbone.
:warning: I am not sure of the `Commit` name, but I can't think of anything better. If you have ideas please mention them!
The proposed implementation handles `repo_id`, `user/repo_id` and `org/repo_id` as model identifiers. It locally syncs the repository with the online repository on the hub and manages it in a very git-like fashion:
- It clones the repository if it isn't here locally
- It pulls the recent changes with `rebase` if the repo is already here
- It adds changes, commits, and pushes.
Example usage:
```py
with Repository("text-files", clone_from="Jikiwa/text-files", use_auth_token=True).commit("My first file :)"):
with open("file.txt", "w+") as f: …
```
> Context manager

- interfaces/Libraries.ts
- interfaces/Types.ts
> Add sklearn code snippet

- docs/hub/endpoints.md
(PR on top of #155 as it's very related)
> Document hf.co webhook publicly

- api-inference-community/docker_images/spacy/app/main.py
- api-inference-community/docker_images/spacy/app/pipelines/token_classification.py
- api-inference-community/docker_images/spacy/requirements.txt
Allow any repo to be executed in the Inference API!
FYI @ines
> Upgrade spaCy to api 0.0.12 and remove allowlist

- docs/hub/endpoints.md
This reverts commit 643a13cbb490cae38bf1724dc43ca472321cf52b.
> Revert "docs: fix webhook response format (#162)"

- api-inference-community/docker_images/sentence_transformers/tests/test_api.py
- api-inference-community/docker_images/sentence_transformers/tests/test_api_sentence_similarity.py
@Narsil WDYT of this approach? If it looks good I'll change the common templates as well.
> Allow multiple models when testing a pipeline

- src/huggingface_hub/repository.py
- tests/test_repository.py
This PR adds auto-tracking for LFS files. It automatically tracks files that are larger than 10MB and that are not currently being tracked.
> Auto track with LFS

- tests/test_snapshot_download.py
Add timestamp to snapshot download tests
> Add timestamp to snapshot download tests

- src/huggingface_hub/__init__.py
- src/huggingface_hub/hub_mixin.py
- tests/test_hubmixin.py
> add _from_pretrained hook

- docs/hub/adding-a-library.md
- src/huggingface_hub/README.md
- src/huggingface_hub/repository.py
- tests/test_repository.py
Adds documentation on the `Repository` class.
> Repository documentation

- docs/hub/spaces.md
Explains how to sync a Github repo with Spaces
> doc: sync github to spaces

- docs/sagemaker/inference.md
This PR adds new documentation to SageMaker inference for "how to correctly create a model.tar.gz" and how to run batch inference.
> added batch transform documentation & model archive documentation

- widgets/src/lib/InferenceWidget/shared/WidgetDropzone/WidgetDropzone.svelte
- widgets/src/lib/InferenceWidget/widgets/AutomaticSpeechRecognitionWidget/AutomaticSpeechRecognitionWidget.svelte
- widgets/src/lib/InferenceWidget/widgets/FeatureExtractionWidget/DataTable.ts
- widgets/src/lib/InferenceWidget/widgets/FeatureExtractionWidget/FeatureExtractionWidget.svelte
- widgets/src/lib/InferenceWidget/widgets/ImageClassificationWidget/ImageClassificationWidget.svelte
Closes #210
Sync updates on widgets from hf internal
> Sync with hf internal

- api-inference-community/docker_images/common/app/batch.py
- api-inference-community/docker_images/superb/app/batch.py
- api-inference-community/tests/test_dockers.py
> Adding batching support for superb

- .github/workflows/python-api-tests.yaml
- api-inference-community/api_inference_community/normalizers.py
- api-inference-community/api_inference_community/validation.py
- api-inference-community/docker_images/common/app/pipelines/__init__.py
- api-inference-community/docker_images/common/app/pipelines/speech_classification.py
- api-inference-community/docker_images/common/app/pipelines/speech_segmentation.py
- api-inference-community/docker_images/common/tests/test_api_audio_to_audio.py
- api-inference-community/docker_images/common/tests/test_api_automatic_speech_recognition.py
- api-inference-community/docker_images/common/tests/test_api_feature_extraction.py
- api-inference-community/docker_images/common/tests/test_api_image_classification.py
- api-inference-community/docker_images/common/tests/test_api_question_answering.py
- api-inference-community/docker_images/common/tests/test_api_sentence_similarity.py
- api-inference-community/docker_images/common/tests/test_api_speech_segmentation.py
- api-inference-community/docker_images/common/tests/test_api_structured_data_classification.py
- api-inference-community/docker_images/common/tests/test_api_text_to_speech.py
- api-inference-community/docker_images/common/tests/test_api_token_classification.py
- api-inference-community/docker_images/superb/app/main.py
- api-inference-community/docker_images/superb/app/pipelines/__init__.py
- api-inference-community/docker_images/superb/app/pipelines/speech_classification.py
- api-inference-community/docker_images/superb/app/pipelines/speech_segmentation.py
- api-inference-community/docker_images/superb/requirements.txt
- api-inference-community/docker_images/superb/tests/test_api.py
- api-inference-community/docker_images/superb/tests/test_api_automatic_speech_recognition.py
- api-inference-community/docker_images/superb/tests/test_api_speech_segmentation.py
- api-inference-community/setup.py
- api-inference-community/tests/test_dockers.py
- api-inference-community/tests/test_normalizers.py
- Adding a normalizers to help reformat the tensor into a list of classes
- Test for said normalizer (depends on torch, but it should be overall optional)
- Add the actual pipeline within superb.
- Will need update to `api-inference-community`.
> Adding SD for superb (speech-classification).

- src/huggingface_hub/commands/user.py
> Fix CLI-based repo creation

- widgets/src/lib/InferenceWidget/shared/WidgetDropzone/WidgetDropzone.svelte
- widgets/src/lib/InferenceWidget/shared/helpers.ts
- widgets/src/lib/InferenceWidget/widgets/AudioSourceSeparationWidget/AudioSourceSeparationWidget.svelte
- widgets/src/lib/InferenceWidget/widgets/AutomaticSpeechRecognitionWidget/AutomaticSpeechRecognitionWidget.svelte
Abstracting proxify lines into a util function in `helpers.ts`
> Add proxify util function

- api-inference-community/tests/test_batch.py
> Fix broken batch test

- api-inference-community/docker_images/generic/app/main.py
- api-inference-community/docker_images/generic/app/pipelines/base.py
- api-inference-community/docker_images/generic/app/pipelines/token_classification.py
- api-inference-community/docker_images/generic/requirements.txt
- api-inference-community/docker_images/generic/tests/test_api.py
- api-inference-community/tests/test_dockers.py
FYI @lewtun @nateraw 
Repo template: https://huggingface.co/templates/token-classification
Repo example: https://huggingface.co/osanseviero/en_core_web_sm
> Add base generic inference and enable token classification

- docs/sagemaker/inference.md
This PR adds a dedicated section to the Inference Documentation for Batch Transform. It also introduces a new notebook and yt video.
> Add Batch Transform section with video to SageMaker documentation

- api-inference-community/api_inference_community/validation.py
Please let me know if this looks good or if I'm missing something. 
This seems like a very complex PR!
> Allow audio-classification in community API

- api-inference-community/docker_images/speechbrain/app/pipelines/audio_classification.py
Sort audio classification results by probability, not by label....
> Fix Audio Classification pipeline

- api-inference-community/docker_images/sentence_transformers/requirements.txt
> Update requirements for `sentence-transformers`.

- docs/hub/_sections.yml
- docs/hub/adding-a-library.md
- docs/hub/how-to-downstream.md
- docs/hub/how-to-inference.md
- docs/hub/how-to-upstream.md
- docs/hub/tutorial-add-library.md
This PR adds links to the new guides in the Hub docs sidebar.
> Link to new guides

- .github/workflows/python-api-sentence-transformers.yaml
- api-inference-community/docker_images/sentence_transformers/requirements.txt
Context:
* https://github.com/UKPLab/sentence-transformers/pull/1116
* https://github.com/huggingface/transformers/issues/13801#issuecomment-932046211
cc @nreimers
> Update sentence transformers version from Inference API

- api-inference-community/docker_images/speechbrain/app/pipelines/automatic_speech_recognition.py
- api-inference-community/docker_images/speechbrain/requirements.txt
- api-inference-community/tests/test_dockers.py
> Update speechbrain to use develop branch

- api-inference-community/docker_images/adapter_transformers/app/pipelines/text_classification.py
> Return all scores in adapter transformers Inference API

- widgets/src/lib/InferenceWidget/shared/WidgetOutputChart/WidgetOutputChart.svelte
> Minor p -> span change 

- docs/hub/model-repos.md
@julien-c  @osanseviero @stevhliu @abhishekkrthakur looks better?
> Adding more info about carbon emissions

- api-inference-community/docker_images/stanza/app/pipelines/token_classification.py
- api-inference-community/docker_images/stanza/tests/test_api.py
- api-inference-community/docker_images/stanza/tests/test_api_token_classification.py
- api-inference-community/tests/test_dockers.py
Added pos-tagging in stanza widgets.
cc: @osanseviero
> stanza pos-tagging added

- src/huggingface_hub/repository.py
- tests/test_repository.py
Fixes the `skip_lfs_file` and adds a test.
The `GIT_LFS_SKIP_SMUDGE` parameter only works with `git clone` and not with `git lfs clone`.
The difference between those two is that `git lfs clone` does the equivalent of the following commands:
```
GIT_LFS_SKIP_SMUDGE=1 git clone git@something.something.git
cd something
git lfs pull
```
We use `git lfs clone` as it provides a simpler environment for progress bars and therefore better feedback for the user. When specifying that the LFS files should not be fetched, the method will be changed to `git clone` using the `GIT_LFS_SKIP_SMUDGE` parameter.
PS: Next PR will try to refactor the `test_repository.py` file so that it takes less time than it currently does.
> Fix skip_lfs_file

- widgets/src/lib/InferenceWidget/widgets/AudioClassificationWidget/AudioClassificationWidget.svelte
- widgets/src/lib/InferenceWidget/widgets/AudioToAudioWidget/AudioToAudioWidget.svelte
- widgets/src/lib/InferenceWidget/widgets/AutomaticSpeechRecognitionWidget/AutomaticSpeechRecognitionWidget.svelte
Closes https://github.com/huggingface/huggingface_hub/issues/480
Closes https://github.com/huggingface/huggingface_hub/issues/508
Auto-to-Aud widget output looks like this now:
> Minor fixes for audio widgets

- tasks/src/audio-classification/about.md
- tasks/src/audio-classification/data.ts
- tasks/src/audio-to-audio/about.md
- tasks/src/fill-mask/about.md
- tasks/src/fill-mask/data.ts
- tasks/src/image-classification/data.ts
- tasks/src/image-segmentation/data.ts
- tasks/src/object-detection/data.ts
- tasks/src/sentence-similarity/data.ts
- tasks/src/summarization/about.md
- tasks/src/text-classification/about.md
- tasks/src/text-classification/data.ts
- tasks/src/text-generation/about.md
- tasks/src/token-classification/about.md
- tasks/src/token-classification/data.ts
- tasks/src/translation/about.md
- tasks/src/translation/data.ts
Fixes, text classification & JSON responses added to task schemas containing labels.
> Task fixes

- widgets/src/lib/interfaces/Libraries.ts
- widgets/src/lib/interfaces/Types.ts
[internal PR](https://github.com/huggingface/moon-landing/pull/1558)
This enables (zoom on code samples):
> Better metadata from `transformers`

- docs/hub/model-repos.md
WDYT @julien-c @abhishekkrthakur @osanseviero @Pierrci and co.?
> Adding structure of co2_emissions  :green_heart:

- src/huggingface_hub/commands/user.py
- src/huggingface_hub/file_download.py
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/inference_api.py
Quickly cleaned up the codebase to bring pretty fstrings :smile:
> Convert string functions to f-string

- api-inference-community/docker_images/espnet/app/pipelines/text_to_speech.py
The code to auto detect the sampling rate was wrong.
> Fixing FS for `espnet`.

- src/huggingface_hub/snapshot_download.py
> [snapshot_download] upgrade to canonical separator

- widgets/src/lib/Icons/IconImageToText.svelte
- widgets/src/lib/ModelPipelineIcon/ModelPipelineIcon.svelte
- widgets/src/lib/interfaces/Types.ts
@mishig25 @osanseviero carried my changes from fork
> added image-to-text

- api-inference-community/README.md
- api-inference-community/manage.py
Reviewers, do you think those changes would help you implement what's missing ?
I try to make all the docker stuff a bit separate from the minimal work (which worked great IMO)
It's just extra steps to go a step beyond in getting things approved faster.
> Attempt to improve the docs for users wanting to add a new framework.

- widgets/src/lib/InferenceWidget/shared/WidgetModelLoading/WidgetModelLoading.svelte
Closes https://github.com/huggingface/moon-landing/issues/1511
> Fix WidgetModelLoading z-index overflow

- api-inference-community/api_inference_community/routes.py
> Adding an optional `DEBUG=1 ./manage.py start ...`

- tasks/src/audio-classification/data.ts
- tasks/src/audio-to-audio/data.ts
- tasks/src/automatic-speech-recognition/data.ts
- tasks/src/image-classification/data.ts
- tasks/src/image-segmentation/data.ts
- tasks/src/object-detection/data.ts
- tasks/src/sentence-similarity/data.ts
- tasks/src/text-classification/data.ts
- tasks/src/text-to-speech/data.ts
Added links to videos in task pages
cc: @osanseviero
> added youtube links to tasks

- widgets/src/lib/interfaces/Libraries.ts
This enables
- Filtering by library
- Code snippets with example
> Add fairseq info

- tasks/src/audio-classification/data.ts
- tasks/src/audio-to-audio/data.ts
- tasks/src/automatic-speech-recognition/data.ts
- tasks/src/fill-mask/data.ts
- tasks/src/image-classification/data.ts
- tasks/src/image-segmentation/data.ts
- tasks/src/object-detection/data.ts
- tasks/src/question-answering/data.ts
- tasks/src/sentence-similarity/data.ts
- tasks/src/text-classification/data.ts
- tasks/src/text-generation/data.ts
- tasks/src/token-classification/data.ts
- tasks/src/translation/data.ts
Creating this draft PR in case if we have any nits reported from pre-prod.
@osanseviero @beurkinger @gary149
> Misc nits for task pages

- tasks/src/image-classification/data.ts
- tasks/src/object-detection/data.ts
- tasks/src/sentence-similarity/data.ts
- tasks/src/text-classification/data.ts
- tasks/src/text-generation/data.ts
- tasks/src/token-classification/data.ts
Added punctutation at the end of task definitions
> Punctutation fix for tasks

- tasks/src/text-generation/about.md
> Fixed typo in task page about text generation

- js/package-lock.json
- js/package.json
So that the color `sky` in [WidgetOutputTokens](https://github.com/huggingface/huggingface_hub/blob/3135779e94df2132935b8f4e810e1f9a6873a014/js/src/lib/components/InferenceWidget/shared/WidgetOutputTokens/WidgetOutputTokens.svelte#L99) renders
> Bump up tailwind

- .github/workflows/python-tests.yml
- setup.py
Adds the audio dependency for tests as it is now required to download audio datasets.
> Add audio dependency to tests

- .github/workflows/python-tests.yml
- setup.py
- src/huggingface_hub/hf_api.py
Based on @julien-c and @LysandreJik's comments here: https://github.com/huggingface/huggingface_hub/pull/620/files
> Hotfix for repo_type

- docs/hub/model-repos.md
> [docs] Add `other` to licenses

- js/src/lib/interfaces/Libraries.ts
Hey 👋 ,
Since we now need to specify the extension of the file during the downstream task, I added ".zip".
> Update SB3 Libraries.ts

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
> Support list_models and list_datasets with token arg

- js/src/lib/interfaces/Libraries.ts
There is some weird indentation at https://huggingface.co/ThomasSimonini/ppo-LunarLander-v2
> Fix SB3 code snippet

- docs/hub/adding-a-model.md
cc @osanseviero, applies your suggestions that came barely too late :)
> Minor nits

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
- tests/test_hubmixin.py
- tests/test_keras_integration.py
Is this the correct way to add a parameter ?
> Add security status

- src/huggingface_hub/keras_mixin.py
- tests/test_keras_integration.py
TensorBoard override enabled for when user wants to push to same repository
> TensorBoard Override for same Repository

- .github/workflows/auto-review.yml
Updates CI to work with write-all, which should bypass the selection issue
> Try with write-all permissions

- api-inference-community/requirements.txt
- api-inference-community/setup.py
Missed the real `requirements.txt` earlier.
Fixes #758
> New release (requirements are still too strict.)

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- Makefile
Adds a contributing guide and a code of conduct to the `huggingface_hub` repository.
> Contributing guide & code of conduct

- README.md
Adds a note on the README regarding the recent library split.
> Note on the README

- .github/workflows/build_pr_documentation.yaml
- docs/source/package_reference/hf_api.mdx
- docs/source/package_reference/mixins.mdx
- src/huggingface_hub/__init__.py
- src/huggingface_hub/commands/lfs.py
- src/huggingface_hub/commands/user.py
- src/huggingface_hub/file_download.py
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/hub_mixin.py
- src/huggingface_hub/inference_api.py
- src/huggingface_hub/keras_mixin.py
- src/huggingface_hub/lfs.py
- src/huggingface_hub/repocard.py
- src/huggingface_hub/repocard_types.py
- src/huggingface_hub/repository.py
- src/huggingface_hub/snapshot_download.py
- src/huggingface_hub/utils/endpoint_helpers.py
- src/huggingface_hub/utils/logging.py
This PR aims to wrap up the docstring conversion.
> Finish converting docstrings

- src/huggingface_hub/__init__.py
This is quite minor, one review should be enough.
cc @osanseviero @LysandreJik
> FIX make import machinary private

- src/huggingface_hub/keras_mixin.py
- tests/test_keras_integration.py
This PR solves #869. It's a broken down version of https://github.com/huggingface/huggingface_hub/pull/872.
> ENH Removed history writing in Keras model card

- src/huggingface_hub/keras_mixin.py
This PR houses code for rendering the hyperparameter of the Keras models vertically.
The model card with the changes would look something like this.
The model card: https://huggingface.co/ariG23498/vertical-table-keras
> [Keras Mixin] Rendering the Hyperparameter table vertically

- src/huggingface_hub/repocard.py
- src/huggingface_hub/repocard_data.py
- tests/fixtures/cards/sample_windows_line_breaks.md
- tests/test_modelcard.py
How to test:
```python
card = ModelCard.load("elonmuskceo/windows-linebreaks")
card.save("./toto.md")
```
```
$ wget https://huggingface.co/elonmuskceo/windows-linebreaks/raw/main/README.md
```
then diff the two files and check the diff
> [#940] Preserve newlines in existing card files

- src/huggingface_hub/utils/_errors.py
Solve issue https://github.com/huggingface/huggingface_hub/issues/973.
> Fix JSONDecodeError import (solve #973)

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Solve https://github.com/huggingface/huggingface_hub/issues/971.
> PR Make `path_in_repo` optional in `upload folder`

- codecov.yml
Codecov will only post a coverage after all tests have passed + at least 1 change occurred in the PR.
> Post codecov comment only when relevant

- tests/test_hf_api.py
Skip test as mentioned in https://github.com/huggingface/huggingface_hub/issues/1002.
Plan is to put it back once the issue is solved server-side.
> Skip failing security status test.

- src/huggingface_hub/_snapshot_download.py
Fix https://github.com/huggingface/huggingface_hub/issues/1004.
While downloading, output looks like this:
```
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.20k/1.20k [00:00<00:00, 396kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.20k/1.20k [00:00<00:00, 396kB/s]
Fetching 9 files:  33%|█████████████████████████████████████████████████▋                                                                                                   | 3/9 [00:06<00:13,  2.33s/it]
Downloading:   4%|█████▊ …
```
> Main progress bar in snapshot download

- src/huggingface_hub/file_download.py
- tests/test_file_download.py
Fix https://github.com/huggingface/huggingface_hub/issues/1016.
> Consider empty subfolder as None in `hf_hub_url` and `hf_hub_download`

- src/huggingface_hub/file_download.py
Fix the issue that when proxy is used, connection timeout raise "ProxyError" rather than "ConnectTimeout".
https://github.com/huggingface/huggingface_hub/issues/1020
> enable http request retry under proxy

- src/huggingface_hub/utils/_cache_manager.py
- tests/test_utils_cache.py
Fix https://github.com/huggingface/huggingface_hub/issues/1050 (cc @lewtun)
> Fix scan cache failure when cached snapshot is empty

- src/huggingface_hub/templates/datasetcard_template.md
- tests/test_repocard.py
This PR adds jinja template variables to dataset card so you can more easily programmatically update it if you wish. There currently doesn't exist a great way to test this - maybe we should think about that in the future.
> Add template variables to dataset card template

- src/huggingface_hub/hf_api.py
> Fix docstring of list_datasets

- docs/source/how-to-downstream.mdx
Fix https://github.com/huggingface/huggingface_hub/issues/915. cc @osanseviero @NielsRogge
> Add `repo_type=dataset` possibility to how-to guide

- src/huggingface_hub/templates/modelcard_template.md
This change matches the wording in the template to the corresponding metadata variable.
> Parent Model --> Finetuned from model

- .github/workflows/build_pr_documentation.yaml
- .github/workflows/delete_doc_comment.yaml
Reverts huggingface/huggingface_hub#1170
Everything is handled on the doc-builder side now 😊
> Revert "Update pr docs actions"

- .pre-commit-config.yaml
> flake8 precommit from github

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Fix https://github.com/huggingface/huggingface_hub/issues/1213 (cc @camenduru)
Same behavior as `exist_ok` in `create_repo`.
> Add option `exist_ok` in `create_branch` and `create_tag`

- README.md
Noticed the stats were out of date :)
thanks @osanseviero for https://huggingface.co/spaces/open-source-metrics/models-explorer !
> docs: update hf stats

- docs/source/concepts/git_vs_http.mdx
All of these are very minor suggestions
> Minor suggestions post #1245

- src/huggingface_hub/repository.py
Following @patrickvonplaten advice [on slack](https://huggingface.slack.com/archives/C021H1P1HKR/p1673974308228379?thread_ts=1673973232.247449&cid=C021H1P1HKR) (internal link), I've made a PR to make it more explicit that the remote repo must already exist before cloning it. It is better now ? :)
And here is the new [generated doc](https://moon-ci-docs.huggingface.co/docs/huggingface_hub/pr_1297/en/package_reference/repository#huggingface_hub.Repository.__init__).
> Update `Repository` docstring

- src/huggingface_hub/repository.py
See https://github.com/huggingface/huggingface_hub/pull/1297#discussion_r1080707491 cc @patrickvonplaten
> add link to create_repo

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Related to [hffs](https://github.com/huggingface/hffs) library (see https://github.com/huggingface/hffs/pull/10#discussion_r1073546356) cc @mariosasko. It feels cleaner if `huggingface_hub` can directly parse urls starting by `"hf://"` (and will surely avoid some troubles in the future).
PR includes:
- Support for `RepoUrl("hf://datasets/my-user/my-dataset")`
- `repo_type_and_id_from_hf_id` now raises a ValueError if `repo_type` is unknown. Avoid to silently consider "https://huggingface.co/spaesc/mdnestor/tortoise" as a `model` instead of a `space` just because of the typo.
- Updated docstrings + added some tests
> Handle `hf://` urls + raise `ValueError` if repo type is unknown

- src/huggingface_hub/hf_api.py
Add repo_type to repo_info docstring.
> Add repo_type to repo_info docstring

- docs/source/guides/manage-spaces.mdx
- docs/source/guides/repository.mdx
- src/huggingface_hub/__init__.py
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/utils/_validators.py
- tests/test_hf_api.py
Resolves #1349. No tests yet 🙈 .
> :sparkles: add duplicate_space

- docs/source/package_reference/utilities.mdx
- src/huggingface_hub/_login.py
- src/huggingface_hub/utils/tqdm.py
Enabling/disabling progress bars programmatically have been introduced in https://github.com/huggingface/huggingface_hub/issues/987 but never documented. This PR adds `enable_progress_bars`/`disable_progress_bars` helpers to the documentation with a short example.
cc @davanstrien who asked for it :)
> Docs about how to hide progress bars

- src/huggingface_hub/_login.py
- src/huggingface_hub/repository.py
Fix #1412 (see discussion in https://github.com/huggingface/diffusers/issues/2851).
> Log as warning when waiting for ongoing commands

- docs/source/_toctree.yml
- src/huggingface_hub/hf_api.py
> Fix search docstring

- src/huggingface_hub/community.py
- tests/test_hf_api.py
FIX https://github.com/huggingface/huggingface_hub/issues/1463 (cc @mishig25).
> Fix discussion URL on datasets and spaces

- src/huggingface_hub/hf_file_system.py
Following #1495. I forgot that we should update hffs implementation for copies since it's better handled in `HfApi`.
cc @lhoestq @mariosasko
> Use CommitOperationCopy in hffs

- .github/workflows/build_documentation.yaml
- .github/workflows/delete_doc_comment.yaml
- .github/workflows/delete_doc_comment_trigger.yaml
- .github/workflows/upload_pr_documentation.yaml
Companion pr to https://github.com/huggingface/doc-builder/pull/379
Please feel free to merge it yourself
> [doc build] Use secrets

- src/huggingface_hub/_commit_api.py
related to https://github.com/huggingface/huggingface_hub/issues/1503
> Batch fetch_lfs_files_to_copy

- docs/source/package_reference/inference_client.mdx
- src/huggingface_hub/__init__.py
- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_types.py
- tests/test_inference_client.py
> Refactor InferenceClient internals to prepare for TGI

- src/huggingface_hub/file_download.py
> Set timeout to 60 instead of 30 when downloading files

- .github/ISSUE_TEMPLATE/i18n.md
Realized we forgot the conceptual guides in the i18n template. This PR fixes that.
Context: https://github.com/huggingface/huggingface_hub/issues/1645#issuecomment-1725297737 cc @martinbrose
> Update i18n template

- docs/source/en/guides/overview.md
(just adding the new `Collections` guide to the overview page - follow up of https://github.com/huggingface/huggingface_hub/pull/1687)
(cc @stevhliu)
> [Fix] Add collections guide to overview page

- tests/conftest.py
Follow-up after https://github.com/huggingface/huggingface_hub/pull/1725 (cc @LysandreJik). Let's retry on HTTP 502 Bad Gateway as well. It happens from time to time when creating a repo ([example](https://github.com/huggingface/huggingface_hub/actions/runs/6508781733/job/17678825549?pr=1736)).
> Retry test on 502 Bad Gateway

- docs/source/en/guides/inference_endpoints.md
Related to https://github.com/huggingface/huggingface_hub/pull/1779. Some headers are not aligned correctly in the docs. This PR fixes this.
> Fix inference endpoints docs

- src/huggingface_hub/hf_api.py
> Fixing `gated` attribute type in docs

- src/huggingface_hub/file_download.py
Fix https://github.com/huggingface/huggingface_hub/issues/1833.
In the code that if symlinks are supported, we were testing on `os.path.dirname(os.path.commonpath([abs_src, abs_dst]))`. This means we are checking one level above what we really need (and as reported by @brycepg, it can have unexpected side effects). The reason why `os.path.dirname` was introduced was that at the time we implemented it, we were only doing symlinks **inside** the cache directory. To save some time the `are_symlinks_supported` call is cached so that we don't have to try symlink for each and every file. Using `os.path.dirname` allowed to cache the information for the whole cache at once, not just "per repo". But since we are now also doing symlinks from the cache directory to arbitrary directories (with …
> Fix `are_symlinks_supported` on windows root

- docs/source/en/guides/collections.md
- src/huggingface_hub/__init__.py
- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
> add list_collections endpoint, solves #1835

- src/huggingface_hub/hf_api.py
- src/huggingface_hub/keras_mixin.py
- src/huggingface_hub/repocard_data.py
Follow up to https://github.com/huggingface/huggingface.js/pull/296
> Update references to hub-docs

- src/huggingface_hub/utils/_git_credential.py
- tests/conftest.py
- tests/test_hf_api.py
- tests/test_utils_git_credentials.py
Fix bug introduced in https://github.com/huggingface/huggingface_hub/pull/1860.
Also make tests more robust (retry on timeout error).
> Fix git credential parsing regex

- src/huggingface_hub/file_download.py
Fix https://github.com/huggingface/huggingface_hub/issues/1882 cc @vince62s
If 2 different volumes for cache and local dir, and symlinks are support on target dir BUT not between volumes, then copy or move the file.
(**EDIT:** failing tests are unrelated)
> Fix PermissionError between volumes

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Related to https://github.com/huggingface/datasets/pull/5545#issuecomment-1438557414 (cc @mariosasko @lhoestq).
This PR harmonize the return value between `create_commit`, `upload_file` and `upload_folder`. At the moment, we have a `CommitInfo` dataclass with useful information for `create_commit` (and `delete_file`/`delete_folder`). However, `upload_file` returns a URL to the uploaded file on the Hub while `upload_folder` returns a URL to the uploaded folder on the Hub. This PR makes `CommitInfo` inherits from `str` so that return value can always contain the commit information.
This is somehow similar to the `RepoUrl` when creating a repo. It shouldn't introduce any breaking change to the existing integrations. In particular, `huggingface-cli upload` still prints the same urls as …
> Harmonize commit return type

- docs/README.md
- setup.py
In https://github.com/huggingface/huggingface_hub/pull/1849, I updated the `[docs]` extra dependency to install `hf-doc-builder` from source. The doc builder must be installed from source as the last release dates back to Aug 2022 and we don't actively maintain regular releases. This was fine until I tried to build and publish the package on PyPI. It looks like PyPI has their reason to forbid packages that have a dependency installing from source. See [github action](https://github.com/huggingface/huggingface_hub/actions/runs/7262705875/job/19786427581):
```
Run twine upload dist/* -u __token__ -p "$PYPI_TOKEN"
Uploading distributions to https://upload.pypi.org/legacy/
Uploading huggingface_hub-0.20.0rc0-py3-none-any.whl
25l
0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/357.9 kB • --:-- …
```
> Remove .[docs] extra dependency

- src/huggingface_hub/hf_api.py
Based on feedback from @justalphie
> Update the documentation of add_collection_item

- src/huggingface_hub/hf_api.py
Fix https://github.com/huggingface/huggingface_hub/issues/1956 (cc @PhilipMay)
> Make GitRefs backward comp

- docs/source/en/guides/download.md
- docs/source/en/guides/upload.md
- docs/source/en/package_reference/environment_variables.md
- setup.py
Resolves https://github.com/huggingface/huggingface_hub/issues/1964
> Added `hf_transfer` extra into `setup.py` and `docs/`

- src/huggingface_hub/hf_file_system.py
Fixes https://github.com/huggingface/datasets/issues/6577
> Retry fetching data on 502 error in `HfFileSystem`

- src/huggingface_hub/_login.py
Line 105 had a grammar mistake in file ‘src/huggingface_hub/_login.py’
> Fix grammar

- src/huggingface_hub/hf_api.py
Tweaks following [#2028](https://github.com/huggingface/huggingface_hub/issues/2028)
> List models tweaks

- tests/test_hf_api.py
In the tests we are currently listing all Spaces on the Hub 3 times. This is not necessary and takes a huge amount of time (almost 1min only for that). This PR fixes this :)
> Optimized tests

- src/huggingface_hub/utils/_cache_manager.py
Fix https://github.com/huggingface/huggingface_hub/issues/2110.
> * Handle .DS_Store files in _scan_cache_repos

- src/huggingface_hub/utils/_errors.py
Fix https://github.com/huggingface/datasets/issues/6728 by applying the patch suggested by @padeoe in https://github.com/huggingface/datasets/issues/6728#issuecomment-1987929914.
> Fix REPO_API_REGEX

- src/huggingface_hub/constants.py
- src/huggingface_hub/hf_api.py
Fix bug reported in https://github.com/huggingface/huggingface_hub/issues/2114 (cc @padeoe).
Can't/don't want to add a proper test for it but it works fine when testing it locally with the snippet shared in #2114.
> Fix uploading to HF proxy

- docs/source/ko/_toctree.yml
- docs/source/ko/package_reference/overview.md
Translated the `package_reference/overview.md` file of the documentation to Korean.
Thank you in advance for your review. 
Part of https://github.com/huggingface/huggingface_hub/issues/1626
Pull Request section?
to it if that's the case.
[documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
[here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
@Wauplin May you please review this PR?
> 🌐 [i18n-KO] Translated `package_reference/overview.md` to Korean

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- tests/cassettes/TestTextGenerationClientVCR.test_generate_non_tgi_endpoint_regression_test.yaml
- tests/test_inference_text_generation.py
Fix https://github.com/huggingface/huggingface_hub/issues/2135 cc @anakin87
> Fix InferenceClient.text_generation for non-tgi models

- src/huggingface_hub/_login.py
It's simply a message update that helps lazy people like me know what they need to do when they're in a hurry on their notebook.
> Update the note message when logging in to make it easier to understand and clearer

- docs/source/en/guides/cli.md
- setup.py
Update doc to modify the huggingface-cli download timeout
> Doc cli download timeout

- CONTRIBUTING.md
- README.md
I've been exploring `huggingface_hub` and noticed a few minor typos in `CONTRIBUTION.md` and some formatting issues in `README.md`. I've made corrections to improve readability and consistency. Thank you for considering these changes!
> Fix Typos in CONTRIBUTION.md and Formatting in README.md

- src/huggingface_hub/hf_api.py
From discussion in https://github.com/huggingface/transformers/pull/29686#issuecomment-2076694345
cc @ydshieh @amyeroberts
> Better document download attribute

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- tests/cassettes/InferenceClientVCRTest.test_chat_completion_unprocessable_entity.yaml
- tests/test_inference_client.py
- utils/generate_async_inference_client.py
Fix https://github.com/huggingface/huggingface_hub/issues/2225.
cc @aymeric-roucher
> Raise error in chat completion when unprocessable

- src/huggingface_hub/_local_folder.py
Fix https://github.com/huggingface/huggingface_hub/issues/2276 cc @XiaofuHuang
> Fix FileNotFoundError in gitignore creation

- src/huggingface_hub/hf_api.py
> fix create_inference_endpoint

- docs/source/ko/_toctree.yml
- docs/source/ko/package_reference/webhooks_server.md
Translated the `package_reference/webhooks_server.md` file of the documentation to Korean.
Thank you in advance for your review. 
Part of https://github.com/huggingface/huggingface_hub/issues/1626
Team Hugging Face KREW, may you please review this PR? 
@harheem, @cjfghk5697, @seoulsky-field, @nuatmochoi, @boyunJang, @SeungAhSon, @seoyoung-3060, @junejae, @usr-bin-ksh, @fabxoe
Pull Request section?
to it if that's the case.
[documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
[here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
> 🌐 [i18n-KO] Translated `package_reference/webhooks_server.md` to Korean

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- tests/test_inference_client.py
- utils/generate_async_inference_client.py
> Add proxy support on async client

- docs/source/en/guides/hf_file_system.md
live here: https://moon-ci-docs.huggingface.co/docs/huggingface_hub/pr_2358/en/guides/hf_file_system#integrations
source (ask me for edit access): https://www.figma.com/design/D0S8By7C8Use8ZDdVZZj8P/hf%253A%252F%252F-URLs
> add a diagram about hf:// URLs

- setup.py
- src/huggingface_hub/repocard_data.py
- utils/check_static_imports.py
- utils/generate_async_inference_client.py
- utils/generate_inference_types.py
Related to `ruff` 0.5.0 release
> Update ruff in CI

- src/huggingface_hub/file_download.py
Fix https://github.com/huggingface/huggingface_hub/issues/2359 cc @kyujin-cho
> Fix permission issue when downloading on root dir

- docs/README.md
Fixed the local preview URL in `docs/README.md`.
Closes #2381
> Update port for local doc preview in `docs/README.md`

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Follow-up after https://github.com/huggingface/huggingface_hub/pull/2333#discussion_r1681034214 cc @julien-c . Will add it as a last update in incoming release :smile: 
**EDIT:** failing CI is unrelated.
> Do not mention gitalyUid in expand parameter

- src/huggingface_hub/inference/_client.py
See https://github.com/huggingface/huggingface.js/pull/803
> fix: Handle single return value.

- docs/source/en/guides/cli.md
- docs/source/en/guides/download.md
> fix .huggingface to .cache/huggingface in doc

- src/huggingface_hub/file_download.py
Fix https://github.com/huggingface/huggingface_hub/issues/2435
> Fix typo double assignment

- docs/source/cn/index.md
Fix broken content: https://huggingface.co/docs/huggingface_hub/v0.24.6/cn/index
> Fix broken link and update translation content

- src/huggingface_hub/_space_api.py
To match https://github.com/huggingface/hub-docs/pull/1402
> Add new hardware flavors

- src/huggingface_hub/README.md
- src/huggingface_hub/__init__.py
- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
> rm list_metrics

- docs/source/en/guides/inference.md
- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
Only `Replicate` and `Fal AI` for now, correct?
> Add text-to-video to supported tasks

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Will fix https://github.com/huggingface/dataset-viewer/pull/3131#issuecomment-2618859038 cc @severo
> Fix `super_squash_history` revision not urlencoded

- src/huggingface_hub/inference/_providers/together.py
Same as https://github.com/huggingface/huggingface.js/pull/1146
> [together] Remove and reclassify models

- .github/workflows/python-prerelease.yml
Current workflow file did not trigger correctly. Wondering if it's because of `- "v*.rc*"` trigger. Will use a classic `- v*` one + add rule in first step
> maybe fix .github/workflows/python-prerelease.yml

- src/huggingface_hub/utils/_http.py
follow-up PR after https://github.com/huggingface/huggingface_hub/pull/2819
This PR fixes a small encoding bug + removes newlines from curlified body. Goal is not to have the exact body but an approximation for debug purposes.
> Fix curlify (when HF_DEBUG=1)

- .github/workflows/trufflehog.yml
Same as https://github.com/huggingface/huggingface.js/pull/1172
> feat(ci): ignore unverified trufflehog results

- tests/test_dduf.py
> Deterministic test_export_folder (dduf tests)

- .github/workflows/style-bot-action.yml
this PR simplifies a step in the style bot GH action and fix a small bug introduced in my previous PR 🙈 
(bypassing a review as it's a tiny fix in the workflow)
> Fix bot style GH action (again)

- docs/source/en/_redirects.yml
- src/huggingface_hub/utils/_http.py
- tests/test_hf_api.py
Easy to forget what the env variable is :)
> chore: Link to Authentication

- src/huggingface_hub/hub_mixin.py
- tests/test_hub_mixin.py
- tests/test_hub_mixin_pytorch.py
> Add paper URL to hub mixin

- src/huggingface_hub/inference/_providers/hf_inference.py
- tests/test_inference_providers.py
Fix https://github.com/huggingface/huggingface_hub/issues/2967 following 0.30.0 release.
Once merged I'll make a patch release.
> Fix 2967 'sentence-transformers/all-MiniLM-L6-v2' doesn't support task 'feature-extraction'

- mcp_client.py
Untested and heavily one-shooted by LLM
cc @mishig25
> mcp_client: Support multiple servers

- docs/source/en/guides/upload.md
- docs/source/en/package_reference/environment_variables.md
- also includes guidance for cluster / distributed filesystem upload considerations.
(I will confirm the links once the docs site is published with PR).
> Docs for xet env variables

- src/huggingface_hub/inference/_providers/fal_ai.py
- tests/test_inference_providers.py
same as https://github.com/huggingface/huggingface.js/pull/1377.
Tested the PR with [Dia](https://huggingface.co/nari-labs/Dia-1.6B), it works fine ✅
> [Inference Providers] update text to speech input for fal-ai

- src/huggingface_hub/inference/_providers/__init__.py
- src/huggingface_hub/inference/_providers/replicate.py
This PR adds support for LoRAs with Replicate provider. 
cc @zeke
> [Inference Providers] LoRAs with Replicate

- tests/test_hf_api.py
Error message was updated in this [server-side PR](https://github.com/huggingface-internal/moon-landing/pull/13607/files) (private).
> [Internal] fix create branch failure test

- src/huggingface_hub/constants.py
- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
fixes #3065.
More context in this internal slack [thread](https://huggingface.slack.com/archives/C03E4DQ9LAJ/p1747041722893629).
> [Inference Endpoints] fix inference endpoint creation with custom image

- src/huggingface_hub/_snapshot_download.py
originally from @Vaibhavs10 in this slack internal [message](https://huggingface.slack.com/archives/C02V5EA0A95/p1747396386743699) who reported this user feedback: https://x.com/felix_red_panda/status/1923145537693405269
Currently, if a 401 error occurs during the initial API call in `snapshot_download` and is not specifically classified as a `RepositoryNotFoundError` or `GatedRepoError`, it can fall through to a generic `LocalEntryNotFoundError`. This requires users to inspect the full stack trace to identify the underlying 401 error.
This change modifies the error handling in `snapshot_download` to explicitly check for `HfHubHTTPError` with a status code of 401. If such an error is detected, it is now re-raised directly.
> Surface 401 unauthorized errors more directly in `snapshot_download`

- docs/source/en/package_reference/oauth.md
This PR addresses a documentation issue by correcting a Markdown formatting error to ensure proper rendering and readability.
Changes:
Fixed Markdown syntax to display correctly a link in rendered documentation
>  Documentation Issue

- src/huggingface_hub/_local_folder.py
Closes #3112 
Fixes the abovementioned issue.
> Fix for wrongly saved upload_mode/remote_oid

- .github/workflows/style-bot-action.yml
So we know at least the job is triggered.
> improve style bot comment (notify earlier and update later)

- tests/test_file_download.py
More context in this internal slack [thread](https://huggingface.slack.com/archives/C035N5UE2JU/p1750930018866009).
> Update tests following server-side changes

- docs/source/en/guides/jobs.md
Adding a small fix to the hf jobs run example.
> [Update] HF Jobs Documentation

- src/huggingface_hub/inference/_mcp/cli.py
- src/huggingface_hub/inference/_mcp/constants.py
- src/huggingface_hub/inference/_mcp/utils.py
- In-line with the huggingface.js tiny-agents, allow use of AGENTS.md.
> allow use of AGENTS.md as well as PROMPT.md

- docs/source/en/guides/cli.md
- docs/source/en/guides/repository.md
as per the title. follow-up PR to #3384.
> Document new HF commands

- src/huggingface_hub/dataclasses.py
- tests/test_utils_strict_dataclass.py
reported by @zucchini-nlp on slack
> Fix forward ref validation if total false
