- src/huggingface_hub/_space_api.py
- tests/test_hf_api.py
`huggingface_hub.get_space_runtime` was previously raising an exception on Static Space because hardware is not returned by the server. This PR fixes it by setting hardware to None.
cc @clefourrier @hysts (from internal [slack](https://huggingface.slack.com/archives/C048K60MPNF/p1697547803117469?thread_ts=1697544510.248379&cid=C048K60MPNF))
> Fix Space runtime on static Space

- docs/source/en/package_reference/inference_client.md
Attempting to bring back @Wauplin's docs fix to `ModelStatus` linking, that I clobbered in https://github.com/huggingface/huggingface_hub/pull/1740
> Added `[[autodoc]]` for `ModelStatus`

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- tests/cassettes/InferenceClientVCRTest.test_unprocessable_entity_error.yaml
- tests/cassettes/test_unprocessable_entity_error.yaml
- tests/test_inference_async_client.py
- tests/test_inference_client.py
- utils/generate_async_inference_client.py
Fix https://github.com/huggingface/huggingface_hub/issues/1753 by adding a better error message to the 422 unprocessable entity. I chose not to re-raise a different error but appending the message instead (easier in term of backward compatibility and still valid). 
```py
>>> from huggingface_hub import InferenceClient
>>> client = InferenceClient(model="HuggingFaceH4/zephyr-7b-alpha")
>>> output = client.conversational("Hi how are you?")
huggingface_hub.utils._errors.HfHubHTTPError: 422 Client Error: Unprocessable Entity for url: https://api-inference.huggingface.co/models/HuggingFaceH4/zephyr-7b-alpha (Request ID: 8gb40cYT0epCW3jTQ5HUd)
Make sure 'conversational' task is supported by the model.
```
```py
>>> from huggingface_hub import AsyncInferenceClient
>>> client = …
```
> Clearer error message on unprocessable entity.

- .github/workflows/build_documentation.yaml
This token is not used by your action.
Secret is removed from the repository.
> fix: remove useless token

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_common.py
- src/huggingface_hub/inference/_generated/_async_client.py
- tests/test_inference_client.py
Closes https://github.com/huggingface/huggingface_hub/issues/1767
> Adding `InferenceClient.get_recommended_model`

- docs/source/en/package_reference/file_download.md
The link for the `cache-system` [here](https://huggingface.co/docs/huggingface_hub/main/en/package_reference/file_download#caching) is broken.
> Read the [cache-system guide](https://huggingface.co/docs/huggingface_hub/main/en/manage-cache) for a detailed presentation of caching at at HF.
> Fix document link for manage-cache

- docs/source/de/guides/repository.md
- docs/source/en/guides/repository.md
- docs/source/en/package_reference/hf_file_system.md
- src/huggingface_hub/hf_api.py
Some small fixes I found while playing with the collections and repo APIs.
> Minor doc fixes

- setup.py
Fix CI (see https://github.com/huggingface/huggingface_hub/actions/runs/6664387296/job/18111901923?pr=1779).
By default on Python3.8 in the CI, `typing-extensions==4.5.0` seems to be installed as a dependency of another dependency. It leads to:
```
ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' (/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/typing_extensions.py)
```
This PR adds an explicit dependency `>=4.8.0`. This shouldn't cause any problem as the `[typing]` extras is optional.
> Fix CI (typing-extensions minimal requirement)

- src/huggingface_hub/_multi_commits.py
- src/huggingface_hub/file_download.py
- src/huggingface_hub/utils/insecure_hashlib.py
- src/huggingface_hub/utils/sha.py
This PR aims to make `huggingface_hub` (and then other libraries from HF-ecosystem) FIPS-compliant.
Issue was first raised by @DueViktor in https://github.com/huggingface/transformers/pull/27034 and https://github.com/huggingface/transformers/pull/27038.
_Quoting @DueViktor:_
> Transformers use MD5 from hashlib, which is not a secure algorithm, but are not specifying that it is for other purposes than security. This is causing issues for organisations following certain security standard. FIPS compliance could be an example.
_From https://docs.python.org/3/library/hashlib.html:_
> Changed in version 3.9: All hashlib constructors take a keyword-only argument usedforsecurity with default value True. A false value allows the use of insecure and blocked hashing algorithms in restricted …
> Set `usedforsecurity=False` in hashlib methods (FIPS compliance)

- .github/workflows/python-quality.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- Makefile
- pyproject.toml
- setup.py
- src/huggingface_hub/_login.py
- src/huggingface_hub/file_download.py
- src/huggingface_hub/hf_file_system.py
- utils/_legacy_check_future_compatible_signatures.py
Following https://astral.sh/blog/the-ruff-formatter, I suggest we remove `black` formatter completely. It was already not very used anyway. Made a few changes so that current code is formatted the same with both `black` and `ruff` to reduce inconveniences for existing contributors.
N°1 argument IMO is speed. N°2 is that it's convenient to have everything handled by the same tool.
> Remove black formatter to use only ruff

- .github/workflows/python-quality.yml
- Makefile
- src/huggingface_hub/constants.py
- tests/conftest.py
At the moment, tests running locally can alter `huggingface_hub` cache. Two majors cases happen:
- either some "dummy" files/repos are downloaded to the cache
- either the saved token is replaced by the CI one (or simply deleted).
I previously tried to fix this problem using fixtures to use a separate cache and save/set back the registered token while running tests. But this is not really satisfying since cleanup fixtures might not be processed (if process is killed or if several pytests processed are run at once). This PR aims to definitely get rid of these problems by setting a test `HF_HOME` when running the tests. By doing so, there is no way staging and prod caches get mixed or corrupted.
Looks like something I should have done long ago. Sorry for the inconveniences @McPatate :smile: …
> Separate test and prod cache (+ ruff formatter)

- .github/workflows/build_repocard_examples.yaml
- docs/source/de/guides/manage-cache.md
- docs/source/en/guides/manage-cache.md
- docs/source/en/package_reference/environment_variables.md
- src/huggingface_hub/_snapshot_download.py
- src/huggingface_hub/constants.py
- src/huggingface_hub/file_download.py
- src/huggingface_hub/utils/_cache_assets.py
- src/huggingface_hub/utils/_cache_manager.py
- src/huggingface_hub/utils/_hf_folder.py
- src/huggingface_hub/utils/_runtime.py
- src/huggingface_hub/utils/logging.py
- tests/test_cache_no_symlinks.py
- tests/test_utils_assets.py
- tests/test_utils_hf_folder.py
From a discussion started by @thomwolf [on slack](https://huggingface.slack.com/archives/C02V5EA0A95/p1698225212883929) (private link) cc @clefourrier @LysandreJik  as well.
>  It's slightly error prone to have sometimes HF_ sometimes HUGGING_FACE_ and sometimes HUGGINGFACE_ in the env variables we use throuhout our libs (at least it tricked me a couple of times). Maybe some unification (with backward comp) to discuss across the libs as well at some point
---
This PR fixes this by making all environments prefixed either by `HF_` or `HF_HUB_`. 
IMO, this will be particularly impactful for `HF_TOKEN` and `HF_CACHE` that were previously not intuitive.
4 environment variables have been modified:
| Deprecated Variable | Replacement |
| --- | --- |
| `HUGGINGFACE_HUB_CACHE` | `HF_CACHE` |
| …
> Harmonize environment variables

- src/huggingface_hub/file_download.py
In https://github.com/huggingface/huggingface_hub/issues/1766, I have introduced a retry mechanism in the download process if a `ConnectionError` or `ReadTimeout` error happens. The mechanism is quite simple: retry up to 5 times, wait 1s in between.
This PR modifies this mechanism to reset the number of retries each time new data is received from the server. This is because (IMO) we should not assume before-hand how many retries will be needed to download a huge file on a slow connection. The only thing we want to avoid is to end up in an infinite loop, which cannot be the case here. Worst case is we retry 5 times between each chunk of data (very unlikely :smile:)
(Failing tests are unrelated. I'm trying to fix them separately)
> Reset `_nb_retries` if data has been received from the server

- src/huggingface_hub/hf_file_system.py
- tests/test_hf_file_system.py
Fixing a bug introduced in https://github.com/huggingface/huggingface_hub/pull/1783 (merged yesterday).
Since a refacto, I did not realize that `repo_type` was not forwarded in `_fetch_range` anymore. This PR fixes it.
> Fix huggingface filesystem repo_type not forwarded

- src/huggingface_hub/utils/_hf_folder.py
Related to https://github.com/huggingface/huggingface_hub/pull/1786. I replaced `HF_TOKEN` by `HUGGING_FACE_HUB_TOKEN` but overlooked a bit the backward compatibility. This PR fixes this.
cc @cbensimon who noticed it.
> Ensure backward compatibility for `HUGGING_FACE_HUB_TOKEN` env variable

- src/huggingface_hub/inference/_text_generation.py
Fixing a bug reported in https://github.com/huggingface/huggingface_hub/issues/1787. Problem was that nested dataclasses are not parsed correctly when pydantic is not installed (which is normal). This PR fixes this by adding a few rules in `__post_init__` methods. Hopefully this piece of code will not need much maintenance in the future (if TGI output stays the same) so it's fine to have this semi-manual fix. If we see that it's too complicated, let's just drop support for when pydantic is not installed. The reason why we want `pydantic` to be optional is that it is a quite heavy dependency and input/output validation is not necessary.
Also, this is not tested in the CI since `pydantic` is installed there. Let's reassess if we encounter other issues. And thanks@danielpcox who reported the …
> Fix `InferenceClient.text_generation` when `pydantic` is not installed

- src/huggingface_hub/_space_api.py
(raised on [slack](https://huggingface.slack.com/archives/C02V5EA0A95/p1699011619458609) -internal link- by @abhishekkrthakur)
Current `SpaceHardware` enum is outdated. This PR updates it with `"zero-a10g"`, `"a10g-largex2"` and `"a10g-largex4"`. Note: even when not added to the enum, users can still sets them using a simple string.
I chose to add the `zero-a10g` (cc @cbensimon) even though it is still in restricted access. Shouldn't be much of a problem (I don't think this API is much used by non-HF users) and at least it will be forward compatible.
cc @christophe-rannou who updated this list in the backend recently.
> Update `SpaceHardware` enum

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
This PR fixes a bug introduced in https://github.com/huggingface/huggingface_hub/pull/1788 that broke `SpaceInfo` initialization (cc @mariosasko).
Also realized `HfApi.space_info` was not unit tested (hence the fact we did not realized) so I added a test.
> Fix `SpaceInfo` initialization + add test

- docs/source/en/package_reference/environment_variables.md
- src/huggingface_hub/_snapshot_download.py
- src/huggingface_hub/file_download.py
- src/huggingface_hub/hf_api.py
- tests/testing_utils.py
Since the Private Hub experiment has been shut down, having a `HF_ENDPOINT` env variable or `endpoint` parameter is useless. Its only purpose now is to redirect to the staging platform in tests. This PR updates the documentation and function signatures to lower down the importance of this environment variable. It does not introduce any breaking change, meaning it is still possible to use it.
cc @julien-c @LysandreJik
> Do not promote `HF_ENDPOINT` environment variable

- docs/source/en/_toctree.yml
- docs/source/en/guides/cli.md
- docs/source/en/guides/download.md
- docs/source/en/guides/upload.md
- src/huggingface_hub/commands/lfs.py
- src/huggingface_hub/commands/user.py
Close https://github.com/huggingface/huggingface_hub/issues/1778 (cc @apolinario)
This PR adds a page to explain the main features of the CLI. The most detailed part is about `huggingface-cli download` and `huggingface-cli upload` that were not very well documented until now. Some commands are not documented in the PR on purpose (some are legacy, some are not very important).
Guide to review: https://moon-ci-docs.huggingface.co/docs/huggingface_hub/pr_1797/en/guides/cli
(failing tests are unrelated to this PR)
> Add CLI guide to documentation

- src/huggingface_hub/templates/modelcard_template.md
related to:
- https://github.com/huggingface/hub-docs/pull/1084
- https://github.com/huggingface/moon-landing/issues/7584
- https://github.com/huggingface/moon-landing/pull/7350
- https://github.com/huggingface/moon-landing/pull/7989
> change metadata key from `finetuned_from` to `base_model`

- docs/source/en/guides/download.md
- docs/source/en/guides/upload.md
- src/huggingface_hub/lfs.py
Following `hf_transfer` update (see https://github.com/huggingface/hf_transfer/pull/18) and related to https://github.com/huggingface/huggingface_hub/pull/1792 (progress bars while downloading).
Progress bars are now enabled in `hf_transfer`. This PR add support for it when uploading files. Implementation is still backward compatible with previous versions.
Kudos to @cbensimon for the Rust implementation.
> Add support for progress bars in hf_transfer uploads

- src/huggingface_hub/hf_file_system.py
- src/huggingface_hub/lfs.py
Fix https://github.com/huggingface/huggingface_hub/issues/1800 (?)
This PR does 2 things:
- if `HfFileSystemFile.__init__` fails because repo/revision do not exist, `self.resolved_path` is not set. As a consequence the magic `__del__`  (called just after since init failed) also fails because the file cannot be closed. This PR fixes this by not closing the file if `resolved_path` is not set.
- The `FileNotFoundError` error message is improved to let the user know why the file is not found (either repo not found, repo_id not valid or revision not found). Also mentions to the user that the repo must exist before writing a file to it. @lhoestq please let me know what you think of the updated message.
I am not a big fan of auto-creating the repo/revision if not found. Biggest problem is that …
> Fix `HfFileSystemFile` when init fails + improve error message

- src/huggingface_hub/__init__.py
- src/huggingface_hub/hf_api.py
Following [`v0.19.0`](https://huggingface.co/spaces/Wauplin/huggingface_hub/discussions/2) release, let's prepare for next one :)
(this PR also removes a `timeout` parameter that should have been removed from `list_repo_files` in `0.17`... :smile:)
> Prepare for `v0.20.0`

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Followup PR after https://github.com/huggingface/hub-docs/pull/1091/ (private). 
A new field `createdAt` is now returned by the server for every model/dataset/repo. This PR adds it as an official property for `ModelInfo`, `DatasetInfo` and `SpaceInfo`. Note that the lowest value is `2022-03-02T23:29:04.000Z`, corresponding to the date when we began to store creation dates (as documented [here](https://huggingface.co/docs/hub/api#repo-listing-api)).
```py
>>> from huggingface_hub import HfApi 
>>> api = HfApi()
>>> api.model_info("gpt2").created_at
datetime.datetime(2022, 3, 2, 23, 29, 4, tzinfo=datetime.timezone.utc)
>>> api.dataset_info("bigcode/the-stack").created_at
datetime.datetime(2022, 10, 3, 2, 34, 54, tzinfo=datetime.timezone.utc)
>>> …
```
> Add support for `createdAt` field

- src/huggingface_hub/repocard.py
- src/huggingface_hub/repocard_data.py
- tests/test_hf_api.py
- tests/test_repocard.py
Fix #1817.
The problem was that for models with a corrupted model-index in their data card (i.e. created before we added the check server-side), the error was not caught if a `TypeError` is raised. We were only ignoring `KeyError`. This PR fixes this and adds a regression test.
Thanks @ademait for reporting!
**Note:** this is a regression introduced by https://github.com/huggingface/huggingface_hub/pull/1788. Once this is merged, I'll ship a hot-fix release as it was working correctly in `v0.18.0` (since server data was not parsed into a Python object).
---
**EDIT:** I also fixed 2 CardData-related tests that were broken due to server-side update.
**EDIT 2:** also switched from `logger.warnings` to `warning.warn` in repocard module for consistency with the rest of the library
> [FIX] Catch TypeError when parsing card data from ModelInfo

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Followup on https://github.com/huggingface/moon-landing/pull/8038 (private repo) after discussion on [slack](https://huggingface.slack.com/archives/C04HZ32QV17/p1699526648171769) (private link) (cc @coyotte508).
There is now a new parameter `include_prs` when listing refs from a repo to include pull requests. This PR adds support for this parameter in `list_repo_refs`. Value is False by default to avoid fetching PRs refs when not necessary. And added a test for it.
> Add `include_pull_requests` to list_repo_refs

- utils/check_static_imports.py
Related to https://github.com/huggingface/huggingface_hub/pull/1783 (and especially https://github.com/huggingface/huggingface_hub/pull/1783#discussion_r1392285357). Thanks @ArthurZucker for noticing!
I forgot to use `ruff format` in the script to generate the static imports (in `check_static_imports.py`).
> Use ruff formatter in check_static_imports.py

- src/huggingface_hub/constants.py
**TL;DR:** `HF_HOME` env variable is parsed but not exposed as a `huggingface_hub` constant. Let's expose it to harmonize things in other libraries.
---
I am currently making a cleanup of the environment variables in the HF ecosystem, and especially `transformers` (following up after https://github.com/huggingface/huggingface_hub/pull/1786).
I realized `transformers` and `datasets` need to know the `HF_HOME` directory to store python modules. At the moment the parsing is done individually in those libraries. Let's harmonize that by defining a `HF_HOME` constant in huggingface_hub directly -instead of lowercased `hf_cache_home`.
I am tempted to make a new `0.19.2` release once this is merged so that it can directly be integrated in transformers/datasets.
> Expose `HF_HOME` in constants

- .github/workflows/python-tests.yml
- setup.py
- src/huggingface_hub/keras_mixin.py
- tests/test_keras_integration.py
Since we allowed pydantic>=2.x in `v0.19.0` release, we got some issues in the CI. The problem comes from the fact that on Python3.8, Pydantic>=2.x and tensorflow don't seem to be compatible. Tensorflow depends on `typing_extension<=4.5.0` while pydantic 2.x requires `typing_extensions>=4.6`. This causes a `ImportError: cannot import name 'TypeAliasType' from 'typing_extensions'`.
Examples of failed CIs:
- in [transformers "build docs" CI](https://github.com/huggingface/transformers/actions/runs/6875619848/job/18699571340?pr=27483)
- in [huggingface_hub "tensorflow 3.8" CI](https://github.com/huggingface/huggingface_hub/actions/runs/6875677790/job/18699755513) 
---
My plan is to make a new patch release `0.19.3` if that works since it's a bit of a regression right now (compared to …
> Limit to `pydantic<2.x` on `python3.8`

- src/huggingface_hub/lfs.py
- src/huggingface_hub/utils/_http.py
This PR aims to make the upload process more robust to transient errors:
- Retry on`requests.ConnectionError` -e.g. connection temporarily lost or connection reset by peer-. Before this was the case only for `requests.ProxyError` (not sure why :thinking:).
- Retry on HTTP 500. It seems that sometimes S3 raises a transient HTTP 500 error (see https://github.com/huggingface/datasets/issues/6392#issuecomment-1806059794). Not sure why but retrying when it's the case doesn't cost mush.
- Retry on `requests.Timeout` instead of `Timeout` as I just found out that `requests.Timeout` is not inheriting from `Timeout` (meaning we were not retrying on timeouts before...)
---
The retry mechanism is the same as before, implemented in `http_backoff` (up to 5 retries, backoff after 1s, 2s , 4s and 8s). …
> More robust uploads

- docs/source/en/guides/cli.md
- src/huggingface_hub/hf_api.py
Related to https://github.com/huggingface/huggingface_hub/issues/1814.
This PR updates the documentation of `ModelInfo`, `DatasetInfo`, `SpaceInfo` and `RepoSiblings` to let the users know they should not expect all attributes to exist. @ademait could you have a look and let me know what you think? I kept the wording a bit vague on purpose as I don't want to be too specific on things that we might change server-side in the future (all those objects are built in a way that is future-compatible, on purpose). (**EDIT:** I'm not saying that we will remove attributes in the future, but we might potentially add news ones and/or improve default behaviors).
> Document more list repos behavior

- src/huggingface_hub/utils/_runtime.py
This PR adds an extra check for pydantic to test whether it is correctly installed or not. If `pydantic 2.x` is installed but `typing_extensions<=4.5.0` is installed, then pydantic at import time. This should not happen when it is installed with `pip install huggingface_hub[inference]` but it can happen when it is installed manually by the user in an environment that we don't control.
Usually we won't need to do this kind of check on optional dependencies. However, pydantic is a special case
has it is automatically imported when doing `from huggingface_hub import ...` even if the user doesn't use it.
For more context see:
- [internal slack thread](https://huggingface.slack.com/archives/C014N4749J9/p1700069962026839)
- https://github.com/huggingface/datasets/pull/6411
- …
> Check pydantic correct installation

- setup.py
Fix https://github.com/huggingface/huggingface_hub/issues/1830#issuecomment-1817534362 cc @ademait
CI is building documentation using `hf-doc-builder` installed from source. This PR updates `setup.py` so that users wanting to build the docs locally have the same setup. For the record, the last "released version" of `hf-doc-builder` dates back to [Aug. 2022](https://pypi.org/project/hf-doc-builder/), hence producing the errors.
> Install doc-builder from source

- src/huggingface_hub/hf_file_system.py
The common path can be one of the directories to refresh.
This was causing a bug where the common path was the parent directory instead, and therefore `glob` would wrongly return content from the parent directory depending on the cache content
now this code returns the correct files
```python
import fsspec
from huggingface_hub import HfFileSystem
fs: HfFileSystem
path = "hf://datasets/severo/bug-hfh-lfs/data/*"
fs = fsspec.get_fs_token_paths(path)[0]
print(fs.glob(path, detail=True))
print("=" * 100)
fs = fsspec.get_fs_token_paths(path)[0]
print(fs.glob(path, detail=True))
```
this bug was introduced in https://github.com/huggingface/huggingface_hub/pull/1809
> Fix common path in `_ ls_tree`

- docs/source/en/guides/community.md
- src/huggingface_hub/constants.py
- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Add new filters to the `HfApi.get_repo_discussions` method
This PR depends on https://github.com/huggingface/moon-landing/pull/8147 (private) for the `author` filter.
Ping @Narsil 
```python
import huggingface_hub
discussion_generator = huggingface_hub.get_repo_discussions(
repo_id="openai/whisper-large-v3",
author="sanchit-gandhi",
discussion_type="pull_request",
discussion_status="open",
)
for discussion in discussion_generator:
print(discussion)
```
> ✨ Add filters to HfApi.get_repo_discussions

- setup.py
- src/huggingface_hub/inference/_text_generation.py
Fix https://github.com/huggingface/huggingface_hub/issues/1836.
In pydantic >= 2.0, `@validator` has been replaced by `@field_validator` with a deprecation warning (until pydantic 3.x). There are some differences between the legacy and the new @validator ~but they do not impact our usage (see [migration guide](https://docs.pydantic.dev/latest/migration/#changes-to-validators)).~. For now let's silent the warning and we'll update when (and if) we want to add support for pydantic v3.x in the future.
Thanks @mattf for the heads up!
**EDIT:** converting to draft.
**EDIT 2:** reworked the PR to use same logic as currently on `main` and silent the warning. We'll reassess if and when pydantic v3.x is out.
> Fix pydantic deprecation warning

- docs/source/en/guides/cli.md
- src/huggingface_hub/commands/upload.py
- src/huggingface_hub/hf_api.py
- tests/test_cli.py
- tests/test_hf_api.py
Solves https://github.com/huggingface/huggingface_hub/issues/1841 and https://github.com/huggingface/huggingface_hub/issues/1657 cc @AlpinDale
With this PR, running `huggingface-cli upload ... ... --revision=my-branch` will automatically create the branch if it does not exist yet. I added some tests and adapted the docs.
**Note:**
- it is similar to repo creation if repo doesn't exist yet
- branch is created from the latest main
- does not apply if `--create-pr`
> Create branch if missing in hugginface-cli upload

- docs/source/en/package_reference/hf_api.md
- src/huggingface_hub/__init__.py
- src/huggingface_hub/constants.py
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/utils/__init__.py
- src/huggingface_hub/utils/_safetensors.py
- tests/conftest.py
- tests/test_hf_api.py
Related to https://github.com/huggingface/huggingface_hub/issues/1832 cc @LysandreJik @Narsil 
There are 2 methods:
- `parse_safetensors_file_metadata` => parses a safetensors file on the Hub => the "real" method that parses safetensors
- `get_safetensors_metadata` => takes a repo and parses all safetensors files (if sharded with a `model.safetensors.index.json` file) => more focused towards `transformers` architecture (i.e. opinionated)
I tried to follow more or less the [typescript implementation](https://github.com/huggingface/huggingface.js/blob/main/packages/hub/src/lib/parse-safetensors-metadata.ts) with similar error handling.
> Parse safetensors metadata

- docs/source/en/guides/inference_endpoints.md
- src/huggingface_hub/_inference_endpoints.py
- src/huggingface_hub/hf_api.py
It is currently not possible to spawn an Inference Endpoint running on a custom docker image using `create_inference_endpoint`. This is especially useful to run a TGI or TEI container. Topic raised [on slack](https://huggingface.slack.com/archives/C03E4DQ9LAJ/p1700832096929319?thread_ts=1683062116.184079&cid=C03E4DQ9LAJ) (private) by @philschmid. This PR adds support for it.
The dictionary passed as `custom_image` is not very intuitive => for now let's keep a free-form dictionary. I have added an example in the doc for TGI. @philschmid  please let me know if there is a reference page somewhere I can link to.
(also used this PR to complete some typing/docstring in the IE integration).
> Allow create inference endpoint from docker image

- src/huggingface_hub/hf_api.py
Quick fix after https://github.com/huggingface/huggingface_hub/pull/1856 (cc @ceferisbarov). I just realized the `sort` parameter doesn't support `last_modified` but `lastModified` in `list_collections`. This PR fixes the type annotation + docstring. No big deal anyway :)
> Fix `list_collections` sort values

- docs/source/en/guides/upload.md
- src/huggingface_hub/_commit_api.py
- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Solves #1826 and follow-up after server-side change (https://github.com/huggingface/moon-landing/pull/8007 - private link).
I have now added a `respect_gitignore: bool = True` parameter to `create_commit` and `upload_folder` to respect the gitignore file, if it exists.
By default we check if a .gitignore file is present in the commit itself. Otherwise the one hosted on the Hub is used. Only the gitignore file at root is respected (not in subdirectories).
I have adapted the documentation and added a few tests for it.
**Note:** as mentioned by @julien-c in https://github.com/huggingface/huggingface_hub/issues/1826#issuecomment-1810934088, let's consider this as a "bug-fix" and not a "breaking change" as we can expect that no-one was intentionally uploading ignored files on purpose. 
--- …
> Respect `.gitignore` file in commits

- docs/source/en/guides/collections.md
- src/huggingface_hub/hf_api.py
Related to [slack thread](https://huggingface.slack.com/archives/C02EMARJ65P/p1701172683580399) (internal).
`GET /api/collections` do not return complete objects. Collections are truncated to keep only 4 items for performance reasons. This PR adds a warning in the `api.md` documentation.
(related PR for hub docs: https://github.com/huggingface/hub-docs/pull/1146)
> Warn about truncation when listing collections

- src/huggingface_hub/hf_file_system.py
`maxdepth` was added to the default `fsspec`'s `glob` in version `2023.9.0`, so this PR removes `maxdepth` from the `HfFileSystem.glob`'s signature to avoid an error in the older `fsspec` versions.
Fix https://github.com/huggingface/huggingface_hub/issues/1872
> Remove `maxdepth` param from `HfFileSystem.glob`

- src/huggingface_hub/repocard_data.py
- tests/test_repocard_data.py
Related to https://github.com/huggingface/hub-docs/pull/1144 and https://github.com/huggingface/moon-landing/pull/8232 (private repo).
We are adding a new field `source` for each eval result in the model card metadata. This PR adds support to it in the `EvalResult` object (cc @clefourrier).
**Example:**
```py
from huggingface_hub import EvalResult, ModelCard, ModelCardData
result = EvalResult(
task_type="image-classification",
dataset_type="beans",
dataset_name="Beans",
metric_type="acc",
metric_value=0.9,
source_name="Open LLM Leaderboard",
source_url="https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard",
)
card = ModelCard.from_template(ModelCardData(model_name="cool_model", eval_results=[result]))
```
which translates to
```yaml
---
model-index:
- name: cool_model
results: …
```
> Support source in EvalResult for model cards

- docs/source/en/guides/upload.md
- src/huggingface_hub/_commit_api.py
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/hf_file_system.py
- tests/test_hf_api.py
Followup after https://github.com/huggingface/huggingface_hub/pull/1868#issuecomment-1832705457.
Let's remove the `respect_gitignore: bool` parameter completely as we don't expect users would want to force commit files.
> Remove respect_gitignore parameter

- src/huggingface_hub/repository.py
- src/huggingface_hub/utils/_deprecation.py
In https://github.com/huggingface/huggingface_hub/pull/1724 I deprecated `Repository` but the wrong way, making `Repository` a function instead of a class. This PR fixes this. The warning message stays the same:
```
/home/wauplin/projects/huggingface_hub/src/huggingface_hub/utils/_deprecation.py:131: FutureWarning: 'Repository' (from 'huggingface_hub.repository') is deprecated and will be removed from version '1.0'. Please prefer the http-based alternatives instead. Given its large adoption in legacy code, the complete removal is only planned on next major release.
For more details, please read https://huggingface.co/docs/huggingface_hub/concepts/git_vs_http.
```
Fix https://github.com/huggingface/huggingface_hub/issues/1878 (thanks @versae for reporting)
> Fix Repository is not a class

- src/huggingface_hub/_webhooks_payload.py
- src/huggingface_hub/_webhooks_server.py
- tests/test_webhooks_server.py
This PR:
- fixes an issue with `WebhookPayload`. In Pydantic v2.0 optional fields must be explicitly set to None by default otheriwse it raises an issue. That was happening for the `comment` value that is optional in the payload. Also added a test for it.
- renames `WebhooksServer.run` to `WebhooksServer.launch` to stick to gradio naming. I also allowed users to pass parameters that are forwarded to gradio. I added a deprecation message to `.run` even though it is flagged as an "experimental feature" anyway.
(**EDIT:** failing tests are unrelated)
> Fix `WebhookPayload` schema + add `WebhooksServer.launch`

- src/huggingface_hub/community.py
> type of conflicting_files of DiscussionWDetails

- docs/source/en/package_reference/environment_variables.md
- docs/source/en/package_reference/utilities.md
- src/huggingface_hub/_snapshot_download.py
- src/huggingface_hub/file_download.py
- src/huggingface_hub/utils/__init__.py
- src/huggingface_hub/utils/_http.py
- tests/test_utils_http.py
- tests/testing_utils.py
At the moment `HF_HUB_OFFLINE` is only respected when downloading files. This PR makes it used globally for any call to the Hub.
Not respecting it makes it harder to debug things in some cases. For example:
- `snapshot_download` should not make the HTTP call to list the repo files
- `diffusers` should not make a `model_info` call => see https://github.com/huggingface/diffusers/issues/6089 which would have been easier to investigate
With this PR, any unintended call to the Hub will raise a `OfflineModeIsEnabled` error. Either the dependent libraries chose to catch it explicitly and default back to another solution or the user gets an explicit error -which is easier when reporting an issue.
cc @sayakpaul as well
> Respect HF_HUB_OFFLINE for every http call

- src/huggingface_hub/utils/_errors.py
- tests/test_utils_errors.py
In `huggingface_hub` we have a helper `hf_raise_for_status` used everywhere to raise custom HTTP errors when sending requests to the Hub.
One of the rule was to define any HTTP 401 error as a `RepoNotFound` error since this is the status code a user get when trying to access a gated/private/missing repo without been authenticated (no token in header). Was also kinda a legacy rule I think. Problem is that now more and more api calls are made to endpoints not related to specific repos (inference endpoints, collections, create repo, etc.). This PR fixes `hf_raise_for_status` by raising a `RepoNotFound` exception only if the uri starts with `/api/(models|datasets|spaces)/<repo_id>`.
(I finally fixed that after @davanstrien ran into a 
```
Repository Not Found for url: …
```
> Fix error handling on HTTP 401

- src/huggingface_hub/lfs.py
Switch from Basic auth to Bearer token in authorization header when uploading an LFS file. OAuth tokens don't work with basic auth which means uploading LFS files currently fails. See related [slack thread](https://huggingface.slack.com/archives/C02EMARJ65P/p1702485214619679) (private).
I suspect we were using Basic auth to be compatible with `git lfs` command line? In any case, the part of the code changed in the PR is not used by `huggingface-cli lfs`. 
cc @coyotte508
> Send bearer auth in LFS upload

- docs/source/en/package_reference/hf_api.md
- src/huggingface_hub/__init__.py
- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Solves https://github.com/huggingface/huggingface_hub/issues/1535.
Let's add official support to programmatically manage access requests for gated repos.
The API defines a `AccessRequest` dataclass with username, email, status, timestamp and fields + 7 endpoints. I reused as much as possible the vocabulary used in the UI. We have:
- `list_pending_access_requests` => returns "pending" list
- `list_accepted_access_requests` => returns "accepted" list
- `list_rejected_access_requests` => returns "rejected" list
- `cancel_access_request` => moves request to "pending" list
- `accept_access_request` => moves request to "accepted" list  
- `reject_access_request` => moves request to "rejected" list
- `grant_access` => add a user to "accepted" list (the user doesn't have to request access first) …
> Manage access requests programmatically

- src/huggingface_hub/_login.py
Google Colab introduced a new exception `SecretNotFoundError` that is raised when trying to access a secret that does not exist in the user vault. This PR adapts the Colab login integration to catch this error instead of relying on reading the error message itself.  
I've also updated the warning messages to be displayed on multiple lines otherwise it results in one gigantic line that no-one will ever read ^^
> Catch `SecretNotFoundError` in google colab login

- src/huggingface_hub/_commit_api.py
- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
This PR deprecates the `HfApi.list_files_info` method, as suggested in https://github.com/huggingface/huggingface_hub/pull/1809#pullrequestreview-1721928314,. The usage of this method is still low (based on the GitHub/Hub code search), so this shouldn't cause any problems for the users.
> Deprecate `HfApi.list_files_info`

- .github/workflows/python-tests.yml
- setup.cfg
- setup.py
- tests/conftest.py
Tests in CI are quite flaky lately. We have a `retry_on_transient_errors` wrapper to retry on OSError (git clone failed), TimeoutError or HTTP 502/504. But this wrapper just doesn't work (sorry I introduced it 2mo ago in https://github.com/huggingface/huggingface_hub/pull/1725 :roll_eyes:). This PR fixes this by using [`pytest-rerunfailures`](https://github.com/pytest-dev/pytest-rerunfailures) which seems to be far more robust and tested that doing it manually^^.
Note that only tests run in CI are rerun on failure. I did not make it a default locally as it's not compatible with `--pdb`. (+flaky tests are never failing locally in my experience).
> Rerun flaky tests in CI

- docs/source/en/package_reference/environment_variables.md
- src/huggingface_hub/constants.py
See https://github.com/huggingface/huggingface_hub/issues/1917 for more details.
**TL;DR:** let's respect `DO_NOT_TRACK` to disable telemetry globally (same as `HF_HUB_DISABLE_TELEMETRY` but not specific to huggingface_hub). And we keep respecting `DISABLE_TELEMTRY` -as a legacy config value- but let's not document it.
cc @allo-
> Support DO_NOT_TRACK env variable

- src/huggingface_hub/file_download.py
Fix https://github.com/huggingface/huggingface_hub/issues/1909 (cc @jone20231102).
Returning pointer_path early after waiting for lock doesn't respect `local_dir`. This PR fixes it.
> Fix `local_dir` on `hf_hub_download` edge case

- src/huggingface_hub/__init__.py
Follow up PR on the recent release of [`huggingface_hub` 0.20.0](https://huggingface.co/spaces/Wauplin/huggingface_hub/discussions/3) :tada: 
Nothing deprecated to remove.
> Prepare for 0.21.0

- src/huggingface_hub/__init__.py
- src/huggingface_hub/_login.py
- src/huggingface_hub/commands/user.py
- src/huggingface_hub/repository.py
- src/huggingface_hub/utils/__init__.py
- src/huggingface_hub/utils/_headers.py
- src/huggingface_hub/utils/_token.py
In the latest release `0.20.0`, a circular import error happens if you try to import `login` or `logout`. This is because they are defined in `huggingface_hub._login.py` which is a "high-level" module that imports a lot of utilities from `.utils`. The current problem is that it only defines `get_token` that is itself used in other utils. In order to fix the circular import quickly, this PR moves the `get_token` logic to its standalone utility module `huggingface_hub.utils._token.py`. 
With this PR, this line works (which is not the case on `main` or `v0.20.0`:
```py
from huggingface_hub import login, logout
``` 
cc @osanseviero @LysandreJik I'm planning to merge this and make a hot-fix release once it's approved.
**EDIT:** failing tests are unrelated (Spaces quota reached)
> Fix circular import in login

- src/huggingface_hub/_login.py
I embarrassingly hit my head on this  when I was setting up hugging face. The token doesn't echo so I thought something was wrong. having it not echo is probably a good security practice so I just added a note to help out folks like me that get confused by this.
The change in this PR is this:
"Token: " -> "Enter your token (input will not be visible): "
Fixes #1924
Thanks!
> added will not echo message to the login token message

- .github/workflows/build_documentation.yaml
- .github/workflows/build_pr_documentation.yaml
Follow-up after https://github.com/huggingface/huggingface_hub/pull/1916 cc @2404589803 
I realized we forgot to update `.github/workflows/build_pr_documentation.yaml` to build the `"cn"` documentation when someone opens a PR. Should be fixed by this PR (I've also ordered alphabetically the languages).
> Update .github workflow to build cn docs on PRs

- src/huggingface_hub/repocard_data.py
cc @davanstrien 
Officially document the `base_model` key in `ModelCardData`. Value can be either a model_id or a list of model_id. Note that this PR is not necessary to support `base_model` as a key since any `kwargs` is passed to the modelcard. But adding it to the official parameters + document is still beneficial.
> Document `base_model` in modelcard metadata

- tests/cassettes/TestSpaceAPIProduction.test_manage_secrets.yaml
- tests/cassettes/TestSpaceAPIProduction.test_manage_variables.yaml
- tests/cassettes/TestSpaceAPIProduction.test_pause_and_restart_space.yaml
- tests/cassettes/TestSpaceAPIProduction.test_space_runtime.yaml
- tests/cassettes/TestSpaceAPIProduction.test_static_space_runtime.yaml
- tests/conftest.py
- tests/test_file_download.py
- tests/test_hf_api.py
- tests/testing_constants.py
In our CI tests we use a production token in two cases:
1. for Spaces tests => those are flaky and always brake one way or the other (recently because of quotas). This is quite annoying and not very useful as we are more testing the Space infra rather than the `huggingface_hub` API). This PR updates these tests to use VCR tests instead (requests are replayed without hitting the Hub).  
2. for a gated repo test => this can be done programmatically on staging => updated in this PR
After this PR, we should be able to remove the `HUGGINGFACE_PRODUCTION_USER_TOKEN` token from Github secrets.
> Remove PRODUCTION_TOKEN from all tests

- src/huggingface_hub/hf_file_system.py
- tests/test_hf_file_system.py
> Pass revision in path to AbstractBufferedFile init

- src/huggingface_hub/utils/_token.py
Should fix https://github.com/huggingface/huggingface_hub/issues/1952.
It looks like `google.colab.userdata` uses `blocking_request` under the hood which states
>   Note: this function is not thread safe, e.g. if two threads
send blocking_request they will likely race with each other and consume
each other responses leaving another thread deadlocked.
~I'm not 100% sure this is what caused the issue experienced by @prhbrt in #1952 but in any case it's better to fix it. The only change in this PR is to put the `userdata.get("HF_TOKEN")` call inside a global lock. This shouldn't impact much the performances/user experience given it's supposed to be much much quicker than uploading/downloading files.~ => I'm now sure this is the problem. More details in …
> Fix thread-safety when fetching user secret in Google Colab

- src/huggingface_hub/_inference_endpoints.py
- tests/test_inference_endpoints.py
_Originally from @philschmid [on slack](https://huggingface.slack.com/archives/C02V5EA0A95/p1703081113214549) (internal):_
> i am working on a IE example with the new version of huggingface_hub which supports custom container image configs. I noticed that .wait will not break if the endpoint failed.
I made a mistake an the endpoint is in the "failed" status through the UI but the endpoint.wait() is still "blocking".
We now raise an error if the inference endpoint gets into a `failed` state instead of waiting forever.
> Raise on failed inference endpoint in `InferenceEndpoint.wait()`

- src/huggingface_hub/file_download.py
Fix #1942 (and in general should make this part more robust, it's not the first time we need to arrange this :grimacing:).
When downloading a file, a progress bar is displayed. The title of the progress bar shows the filename of the file currently being downloaded. This displayed filename is either taken from the URL for non-LFS files or from the `Content-disposition` header if hosted on a CDN -based on a regex. The PR changes this by adding a new -optional- parameter to `http_get` to pass the filename explicitly. This will definitely fix the issue by avoiding to "guess" the filename (#1942 is about an encoding issue for files like `日本語/でこんにちは.jpg`).
The parameter is made optional because `cached_file` (deprecated) cannot provide a filename. In general, the new parameter will be used in …
> improve http_get

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Pagination in `get_repo_discussions` is broken which leads to an infinite loop on repos with more than 50 discussions. This PR fixes this. Pagination is page-based (not cursor-based as other listing APIs) and the page parameter is named `"p"` server-side, not `"page_index"` (see in [moon-landing](https://github.com/huggingface/moon-landing/blob/dd3ae19a54e471ddf1392cb47eb13faf324ac974/server/app/discussionRoutes.ts#L298) -private repo-).
I encountered this issue while listing discussions on the Open LLM Leaderboard (cc @clefourrier).
```py
for d in get_repo_discussions(repo_id="HuggingFaceH4/open_llm_leaderboard", repo_type="space"):
print(d.title)
``` 
I also made a small change to use `requests.get(..., params=...)` instead of `urlencode`.
> Fix pagination when listing discussions

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Fix https://github.com/huggingface/huggingface_hub/issues/1927.
If modelcard is invalid, we fail early instead of uploading all the LFS files before getting a bad request error on the `/commit` endpoint. This is slightly non-optimized since the model card is transferred twice to the Hub (once for check, once for commit) but by far better UX overall (avoid failing after minutes of waiting).
If modelcard is valid but some warnings have been raised, we print those warnings to the user but still continue. Example: empty metadata section.
> Fail early on invalid metadata

- src/huggingface_hub/hf_file_system.py
- tests/test_hf_file_system.py
This code returns EntryNotFoundError even if the file exists
```python
fs.rm("datasets/username/datasetname@branch/data.txt")
```
and would only work on `main`.
> [HfFileSystem] Fix `rm` on branch

- src/huggingface_hub/hf_api.py
~Tweak safetensors parser: fetch only 25kb by default (instead of 100kb currently). Still valid for most use cases (82% in top 1000 models) and save some bandwidth. Most probably won't be noticed. (see https://github.com/huggingface/huggingface_hub/pull/1855#discussion_r1404286419)~ => EDIT: not changed in the end.
Fix typo in docs: wrong url in `get_safetensors_metadata` docstring.
> Fix URL in `get_safetensors_metadata` docstring

- src/huggingface_hub/utils/_hf_folder.py
- tests/test_utils_hf_folder.py
Since `0.20.x` release, `HfFolder` is planned to be deprecated in favor of `get_token`, `login` and `logout`. Deprecation warning is not thrown yet as `HfFolder` is still a widely used feature. 
@Narsil made me realize that the implementation of `HfFolder.get_token` and `get_token` are slightly different. In particular, if `HF_TOKEN` environment variable is set to an empty string and a token is saved locally, then `HfFolder.get_token` will return `None` (which is a bug) while `get_token` returns the saved token. In order to avoid any discrepancies, this PR replaces `HfFolder.get_token` implementation by a call to the more robust `get_token`.
**Note:** this change brokes `test_token_in_old_path` mocked test. I decided to remove it completely as it's quite old stuff (13 months old) and by …
> Align `HfFolder.get_token` with `huggingface_hub.get_token`

- .github/workflows/model_card_consistency_reminder.yml
PR related to https://github.com/huggingface/hub-docs/pull/1186.
If any modelcard/datasetcard content is modified, let's post a warning on the PR to remind the author/reviewers to also check the equivalent files in `hub-docs`. More details on https://github.com/huggingface/hub-docs/pull/1186#issue-2076837057.
> Add reminder for model card consistency

- src/huggingface_hub/utils/_datetime.py
Fix https://github.com/huggingface/huggingface_hub/issues/1976.
As reported by @jamesbraza in https://github.com/huggingface/huggingface_hub/issues/1976, our datetime parsing method is not correct. The string returned by the server is timezoned to UTC. In the current code, we use `astimezone` to explicitly set the timezone when parsing the datetime. However this method is dependent on the local machine time. This PR fixes this by assigning explicitly the UTC timezone, without updating to local time.
We didn't catch the error earlier most likely due to servers already been in UTC. Thanks @jamesbraza for reporting!
> Fix timezone in datetime parsing

- src/huggingface_hub/commands/download.py
Fixes https://github.com/huggingface/huggingface_hub/issues/1963 by documenting the `DownloadCommand`'s `repo-type`'s default in the `help` message.
> Documenting CLI default for `download --repo-type`

- utils/check_static_imports.py
https://github.com/huggingface/huggingface_hub/pull/1971 removed `setup.cfg`, this PR just removes an unused `Path` variable for it
> Removing unused `SETUP_CFG` path variable

- src/huggingface_hub/hf_api.py
This PR resolves issue #1911 
I've updated all classes to use dataclass except (transformerinfo class).
> Updating HfApi objects to use dataclass

- .pre-commit-config.yaml
- pyproject.toml
Added the [`toml-sort`](https://github.com/pappasam/toml-sort) to `pre-commit` to keep things clean in `pyproject.toml`
> Added `toml-sort` tool

- src/huggingface_hub/file_download.py
- tests/test_file_download.py
This PR fixes a bug when trying to download a regular file (non-LFS) from a private renamed repo. The problem came from the fact that:
1. renaming a repo induce a redirect
2. we were considering that any redirect means that we are downloading from a CDN
3. when we download from a CDN, we remove the `authorization` header since the URL is supposed to be signed
4. when making the actual GET call, the `authorization` header was not there + the url is not signed because it is still a relative redirect to huggingface.co
**=> this PR fixes this issue by keeping the `authorization` header when the redirected URL is from the same domain**
cc @LysandreJik @osanseviero who investigated the bug
cc @coyotte508 @XciD can you please review this PR as well? Just want to make sure I did not break …
> Fix download from private renamed repo

- src/huggingface_hub/file_download.py
- src/huggingface_hub/lfs.py
When dockerized applications write to STDOUT/STDERR, the applications can block due to logging back pressure (see
https://docs.docker.com/config/containers/logging/configure/#configure-the-delivery-mode-of-log-messages-from-container-to-log-driver6
HuggingFace's TGI container is one such example (see https://github.com/huggingface/text-generation-inference/issues/1186).
Setting tqdm's `disable=None` will disable the progress bar if no tty is attached and help to resolve TGI's issue #1186.
References:
https://github.com/huggingface/text-generation-inference/issues/1186#issuecomment-1906809624
https://github.com/huggingface/text-generation-inference/issues/1186#issuecomment-1908278377
> Disable tqdm progress bar if no TTY attached

- src/huggingface_hub/hf_api.py
`update_repo_visibility` currently accepts `name` and `organization` as input. This PR deprecate them in favor of `repo_id` cc @severo who pinged me about it.
(for the record, I haven't found any use of these inputs in transformers/diffusers/datasets/etc. or on [github](https://github.com/search?q=update_repo_visibility+language%3APython&type=code&l=Python))
> Deprecate legacy parameters in update_repo_visibility

- src/huggingface_hub/inference/_text_generation.py
- tests/test_inference_text_generation.py
Fixes https://github.com/huggingface/huggingface_hub/issues/2005
This PR adds tolerance for an `index` field in the TextGenerationStreamResponse.
The latest version of HuggingFace Text Generation Inference added an `index` field to the streaming response to be compatible with OpenAI clients, but the HuggingFace InferenceClient wasn't updated to accept it.
https://github.com/huggingface/text-generation-inference/commit/0eabc83541225979209ff7183b4b4442e47adf92#diff-c3259a23eb2e9e4e39f9a5226354b99508e42b05a158036dc482397410becd52R501
> Fix intolerance for new field in TGI stream response: 'index'

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
Fix https://github.com/huggingface/huggingface_hub/issues/2015. Thanks @abidlabs for noticing :pray:
> Fix optional model in tabular tasks

- tests/test_hf_api.py
- tests/testing_constants.py
Should fix the CI. 
Looks like `__DUMMY_DATASETS_SERVER_USER__` has been replaced by `DSSUser` on staging. I'll merge if CI gets green.
> update name of dummy dataset user

- src/huggingface_hub/lfs.py
~Instead of only 504 by default. Those might be transient errors happening when downloading or uploading files. Let's retry when that happens.~
~Related to https://github.com/huggingface/datasets/issues/6577#issuecomment-1937589686 (cc @sanchit-gandhi) which most likely happened due to the outage on Saturday (so a retry wouldn't have helped) but I still reviewed the process as we were currently having different retry mechanism spread in the codebase. (+it's not the first time I've seen this kind of feedback so let's "fix it" once and for all).~
**EDIT:** Retry on any 5xx on upload. Retry on any 5xx on download except 500. (see below)
> Update backoff strategy

- src/huggingface_hub/README.md
Juste a small typo in a readme : sepErated -> sepArated
> Small typo fix

- src/huggingface_hub/hf_api.py
- src/huggingface_hub/utils/endpoint_helpers.py
- tests/test_hf_api.py
Related to #1676 
Moved all attributes from ModelFilter class to list_models arguments and added a filter query builder to build a query. Updated list_models to take both filter as an Iterable and also update the filter list based on other arguments in the method
> Deprecate `ModelFilter/DatasetFilter`

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
When getting information about a model, we need to parse `widgetData`, not `widget_data`. It probably never worked correctly^^. Fixed it and added a test.
See for example https://huggingface.co/api/models/HuggingFaceH4/zephyr-7b-beta.
> Fix getting widget_data from model_info

- src/huggingface_hub/__init__.py
- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Related to https://github.com/huggingface/huggingface_hub/pull/2040.
This PR adds a new helper `revision_exists`, similar to the existing `repo_exists` and `file_exists`.
Returns True if the repo + revision exist, False otherwise.
I also fixed some docstrings (removed <Tip> section around the "examples" part)
> Add `revision_exists` helper

- src/huggingface_hub/__init__.py
- src/huggingface_hub/file_download.py
Follow up PR after [0.21 release](https://huggingface.co/posts/Wauplin/967130417344883).
Deleted the deprecated (and unused)  `http_user_agent`.
> Prepare for 0.22

- src/huggingface_hub/_space_api.py
In [moon-landing](https://github.com/huggingface/moon-landing/blob/main/server/app/spacesHandlers.ts#L68) (private repo), the `updatedAt` field is optional for Space variables. Never noticed before but it brakes the date parsing in that case. This PR fixes this by making the field optional in Python as well.
Encountered this bug while investigating an issue on https://huggingface.co/spaces/Wauplin/gradio-space-ci
> Fix Space variable when updatedAt is missing

- src/huggingface_hub/file_download.py
- src/huggingface_hub/utils/_fixes.py
- tests/conftest.py
- tests/test_cli.py
- tests/test_utils_fixes.py
Tests that use a mixture  `SoftTemporaryDirectory` and the `fx_cache_dir` fixture may fail on Mac OS. 
The failure usually says something like 
```
FAILED tests/test_file_download.py::HfHubDownloadToLocalDir::test_with_local_dir_and_symlinks_and_overwrite - OSError: [Errno 30] Read-only file system: '/tmpgucu6pwx'
```
The problem is that the code trying to create a symlink in `_create_symlink` tries to find a relative path from src to dst in
```
relative_src = os.path.relpath(abs_src, abs_dst_folder)
```
The problem is that on Mac OS, abs_src and abs_dst have a different root path due to the way the OS handles temp directories.
The one from the fixture is a resolved path to `/private/var/folders/…` while the one from `SoftTemporaryDirectory` is still an unresolved path pointing to …
> Fix tests involving temp directory on macOS

- .github/workflows/python-tests.yml
Enable `python-xdist` on all tests. This reduces overall test execution by 55% on CI down to a around 6min (from 12min).
After experimenting, using 4 instead of `auto` processes seems to avoid too much context trashing. 
|                 | Total duration |  | Comment                    |  
|----------|---------------|-|----------------------|
| Baseline        | 12m 13s        | [Workflow](https://github.com/huggingface/huggingface_hub/actions/runs/8083119316)         |                                           |
| xdist `-n auto` | 6m 33s         | [Workflow](https://github.com/huggingface/huggingface_hub/actions/runs/8086882581?pr=2059) | ubuntu a bit slower, windows a lot faster | 
| xdist `-n 4`    | 5m 46s            |  [Workflow](https://github.com/huggingface/huggingface_hub/action …
> Enable `python-xdist` on all tests

- tests/test_hf_api.py
Same as https://github.com/huggingface/huggingface_hub/pull/2054 but with a different test. Listing all models in a category is not necessary.
> Do not list all models in tests

- .github/workflows/python-tests.yml
- CONTRIBUTING.md
- tests/test_hf_api.py
cc @LysandreJik we don't use `HUGGINGFACE_PRODUCTION_USER_TOKEN` in the test CI anymore.
It is still used in `push_repocard_examples.py` to we still need to keep the GH secret.
> Some cleaning

- .github/workflows/python-quality.yml
- .github/workflows/python-tests.yml
Quick benchmarks show it saves around 30s-40s per workflow (both for code quality and CI tests)
**Note:** running `uv` instead of `pip` in Github CI is not yet a first-class citizen but should be the case once https://github.com/astral-sh/uv/issues/1526 is addressed. This is why we need to source env in each step.
> Use uv in CI to speed-up requirements install

- docs/source/en/guides/download.md
- src/huggingface_hub/hub_mixin.py
- tests/test_hub_mixin_pytorch.py
This PR uses `save_model` instead of `save_file` in order to properly save shared tensors for the `PyTorchModelHubMixin`.
In the future, this may be replaced by save_file again when we support saving sharded checkpoints, which deduplicates shared tensors as in the Transformers library.
> [PyTorchModelHubMixin] Fix saving model with shared tensors

- tests/test_hf_api.py
Related to error message update in moon-landing.
> Fix test test_delete_branch_on_missing_branch_fails

- docs/source/en/guides/integrations.md
- src/huggingface_hub/hub_mixin.py
- src/huggingface_hub/utils/__init__.py
- src/huggingface_hub/utils/_typing.py
- tests/test_hub_mixin_pytorch.py
- tests/test_utils_typing.py
Solves https://github.com/huggingface/huggingface_hub/pull/2079.
With this PR, users don't have to rely on a  `config` parameter to configure their model. We read default+passed values automatically to build the config file ourselves. This way, we are able to save a correct `config.json` file so that reloaded model have exact same config. Only "jsonable" fields are saved in config.json.
And ofc it's backward compatible so users that prefer to pass `config.json` directly are still supported.
PR is inspired by Inspired by https://github.com/facebookresearch/hiera/pull/26. cc @dbolya with this change, you won't need the `@has_config` decorator anymore :hugs: 
Here is an example to showcase it:
```python
>>> import torch
>>> import torch.nn as nn
>>> from huggingface_hub import …
```
> Correctly inject config in `PytorchModelHubMixin`

- src/huggingface_hub/hub_mixin.py
Fix breaking change introduced in https://github.com/huggingface/huggingface_hub/pull/2058.
If `__init__` expects a `**kwargs` parameter, we should pass the config to it. However if it expects something like `**croco_kwargs`, let's not forward it since `config` is most likely not expected by the underlying class that will receive the config. 
This will fix integration like the dust3r one (see [here](https://github.com/naver/dust3r/blob/b6cb1fc6b2aff25a9672483ff905d5cd717f9591/dust3r/model.py) + [slack thread](https://huggingface.slack.com/archives/C06MW6VMZHS/p1709785912955459?thread_ts=1709761490.148549&cid=C06MW6VMZHS) -private-).
cc @NielsRogge @not-lain
> Fix passing kwargs in PytorchHubMixin

- src/huggingface_hub/file_download.py
- src/huggingface_hub/utils/__init__.py
- src/huggingface_hub/utils/_fixes.py
Fix for https://github.com/huggingface/huggingface_hub/issues/2038 cc @vladmandic
If filelock release fails with OSError, let's default back to a SoftFileLock release (e.g. try to delete the file). This is not perfect but in our case it's more than enough.
> Fix unhandled filelock issue

- src/huggingface_hub/inference/_generated/types/audio_classification.py
- src/huggingface_hub/inference/_generated/types/automatic_speech_recognition.py
- src/huggingface_hub/inference/_generated/types/depth_estimation.py
- src/huggingface_hub/inference/_generated/types/document_question_answering.py
- src/huggingface_hub/inference/_generated/types/feature_extraction.py
- src/huggingface_hub/inference/_generated/types/fill_mask.py
- src/huggingface_hub/inference/_generated/types/image_classification.py
- src/huggingface_hub/inference/_generated/types/image_segmentation.py
- src/huggingface_hub/inference/_generated/types/image_to_image.py
- src/huggingface_hub/inference/_generated/types/image_to_text.py
- src/huggingface_hub/inference/_generated/types/object_detection.py
- src/huggingface_hub/inference/_generated/types/question_answering.py
- src/huggingface_hub/inference/_generated/types/sentence_similarity.py
- src/huggingface_hub/inference/_generated/types/summarization.py
- src/huggingface_hub/inference/_generated/types/table_question_answering.py
- src/huggingface_hub/inference/_generated/types/text2text_generation.py
- src/huggingface_hub/inference/_generated/types/text_classification.py
- src/huggingface_hub/inference/_generated/types/text_generation.py
- src/huggingface_hub/inference/_generated/types/text_to_audio.py
- src/huggingface_hub/inference/_generated/types/text_to_image.py
- src/huggingface_hub/inference/_generated/types/text_to_speech.py
- src/huggingface_hub/inference/_generated/types/token_classification.py
- src/huggingface_hub/inference/_generated/types/translation.py
- src/huggingface_hub/inference/_generated/types/video_classification.py
- src/huggingface_hub/inference/_generated/types/visual_question_answering.py
- src/huggingface_hub/inference/_generated/types/zero_shot_classification.py
- src/huggingface_hub/inference/_generated/types/zero_shot_image_classification.py
- src/huggingface_hub/inference/_generated/types/zero_shot_object_detection.py
- tests/test_inference_types.py
- utils/generate_inference_types.py
Adds `= None` to optional values so that the following can be done:
```py
from huggingface_hub import AutomaticSpeechRecognitionParameters
AutomaticSpeechRecognitionParameters()
```
without this PR, we cannot due to the following:
```
TypeError: __init__() missing 2 required positional arguments: 'generate' and 'return_timestamps'
```
> Add = None at optional parameters

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
This PR fixes a bug when `path_in_repo="."` or `path_in_repo="./"` is passed along `delete_patterns` in `upload_folder`. In particular it fixes the `--delete` flag when running `huggingface-cli upload` command.
First reported by @Cadene.
> Fix --delete in huggingface-cli upload command

- src/huggingface_hub/hub_mixin.py
- tests/test_hub_mixin_pytorch.py
This PR fixes a bug `ModelHubMixin` that prevented to save both config and kwargs values.
Nice catch from @not-lain  :clap:
> Fix ModelHubMixin when kwargs and config are both passed

- src/huggingface_hub/hub_mixin.py
- tests/test_hub_mixin.py
- tests/test_hub_mixin_pytorch.py
Good catch from @not-lain. If a config file is saved by `_save_pretrained`, we don't want to overwrite it (done in https://github.com/huggingface/huggingface_hub/issues/2102. But if a config file already exists before saving, we should overwrite it (as any other file). This PR fixes this + adds a test case.
(also removing a warning in a test)
> ModelHubMixin overwrite config if preexistant

- src/huggingface_hub/file_download.py
- src/huggingface_hub/hf_file_system.py
- tests/test_hf_file_system.py
Should fix the current regression in file download speed. When downloading an entire file, let's rely on `hf_hub_download` which is faster, has retry mechanism and can be speed-up with `hf_transfer` (on-demand). 
```py
import time
from tempfile import TemporaryDirectory
from datasets import Dataset
repo_id = "Open-Orca/OpenOrca"
filename = "3_5M-GPT3_5-Augmented.parquet"
parquet = f"hf://datasets/{repo_id}/{filename}"
t0 = time.time()
with TemporaryDirectory() as temp_dir:
Dataset.from_parquet(parquet, cache_dir=temp_dir)
t1 = time.time()
print(t1 - t0)
```
=> on my local setup, speed went from ~15MB/s to 45MB/s (on wifi, no hf_transfer) which is strictly the same speed as a normal `hf_hub_download`.
cc @lhoestq @julien-c (related to …
> Fast download in hf file system

- src/huggingface_hub/hub_mixin.py
- tests/test_hub_mixin.py
When the ModelHubMixin class happens to be a dataclass, `__init__` method will accept `**kwargs` when
inspecting it. However, due to how dataclasses work, we cannot forward arbitrary kwargs to the `__init__`.
This test ensures that the `from_pretrained` method does not raise an error when the class is a dataclass.
This PR fixes the SetFit integration (see https://github.com/huggingface/huggingface_hub/issues/2157). However, this is not a pattern we want to promote. Dataclasses are meant to store data. Model classes are more complex and doesn't play well with internal values.
> Fix ModelHubMixin when class is a dataclass

- src/huggingface_hub/hf_api.py
Fix https://github.com/huggingface/huggingface_hub/issues/2152. Related to https://github.com/huggingface/huggingface_hub/pull/2120 and to this [internal slack thread](https://huggingface.slack.com/archives/C0626AL5AR4/p1711370113894589).
Uploading an LFS file fails because RepoUrl(...).endpoint was not correctly overwritten with HF_ENDPOINT. We were only overwriting `RepoUrl(...).endpoint` but not the inner value `str(RepoUrl(...))`. This PR definitely fixes this by replacing it before parsing the string value. cc @padeoe.
---
Tips from @padeoe to reproduce the issue:
1. Add this line to `/etc/hosts` or `` to deactivate traffic to huggingace.co
```
127.0.0.1 [huggingface.co](http://huggingface.co/)
```
2. Run this script
```py
import os
os.environ['HF_ENDPOINT'] = "https://hf-mirror.com" …
```
> Fix HF_ENDPOINT not handled correctly

- src/huggingface_hub/_commit_api.py
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/lfs.py
- src/huggingface_hub/utils/__init__.py
- src/huggingface_hub/utils/_http.py
- tests/test_utils_http.py
Follow-up PR after https://github.com/huggingface/huggingface_hub/pull/2155 to definitively fix https://github.com/huggingface/huggingface_hub/issues/2152. Thanks @livegoplayer for reporting the remaining issue in https://github.com/huggingface/huggingface_hub/issues/2152#issuecomment-2024984796. I made a mistake when trying the fix and my machine was still able to reach hf.co. This PR should settle the problem for good.
@livegoplayer would you mind trying again on your side? You can test it by installing `huggingface_hub` from this branch:
```
pip install git+https://github.com/huggingface/huggingface_hub@fix-url-for-good-when-using-procy
```
You testing scripts from https://github.com/huggingface/huggingface_hub/issues/2152#issuecomment-2024984796 looks good so normally upload should …
> Fix URL when uploading to proxy

- src/huggingface_hub/_webhooks_payload.py
- tests/test_webhooks_server.py
Related to https://github.com/huggingface/hub-docs/pull/1252 cc @coyotte508 
Wehbook payload now sends a list of the updated refs. This is useful to react on new commits on specific pull requests, new tags and new branches. See https://huggingface.co/docs/hub/webhooks#code-changes for more details.
> Add support for `updatedRefs` in WebhookPayload

- src/huggingface_hub/hf_api.py
Fix https://github.com/huggingface/huggingface_hub/issues/2186.
(failing CI is unrelated)
> Fix SafeTensorsInfo initialization

- docs/source/en/package_reference/environment_variables.md
- src/huggingface_hub/constants.py
Solves https://github.com/huggingface/huggingface_hub/issues/2181 cc @stas00
I named the env variable `HF_TOKEN_PATH` (existing name in codebase).
(failing CI is unrelated)
> Support `HF_TOKEN_PATH` as environment variable

- docs/source/ko/_toctree.yml
- docs/source/ko/guides/community.md
Translated the `guides/community.md` file of the documentation to Korean.
Thank you in advance for your review. 
Part of https://github.com/huggingface/huggingface_hub/issues/1626
Team PseudoLab, may you please review this PR? 
@jungnerd, @heuristicwave, @harheem, @cjfghk5697, @seoulsky-field, @nuatmochoi, @boyunJang, @SeungAhSon, @seoyoung-3060, @junejae
Pull Request section?
to it if that's the case.
[documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
[here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
@jungnerd, @heuristicwave May you please review this PR?
> 🌐 [i18n-KO] Translated `guides/community.md` to Korean

- src/huggingface_hub/_inference_endpoints.py
- src/huggingface_hub/errors.py
- src/huggingface_hub/utils/__init__.py
- src/huggingface_hub/utils/_headers.py
- src/huggingface_hub/utils/_http.py
- src/huggingface_hub/utils/_safetensors.py
- src/huggingface_hub/utils/_validators.py
Define errors in utils except `utils/_errors.py` in errors.py 
#2069
> Define errors in errors.py

- setup.py
- src/huggingface_hub/_tensorboard_logger.py
Related to https://github.com/huggingface/lighteval/pull/150 and also discussed on [slack](https://huggingface.slack.com/archives/C02V5EA0A95/p1712590950104289) (internal) cc @clefourrier.
Tensorboard's `SummaryWriter` can be either retrieved from `tensorboardX` or `torch.utils.tensorboard`. In any case, we don't need to check for `tensorboard` package itself. This PR should make it easier to work with  `HFSummaryWriter` in different setups. 
(note: `HFSummaryWriter` is still flag as an experimental feature. If it gets more and more used in `lighteval` we should think of making it official)
(note2: failing CI is unrelated)
> Import SummaryWriter from either tensorboardX or torch.utils

- docs/source/en/guides/inference.md
Reported by @freddyaboulton on [slack](https://huggingface.slack.com/archives/C02V5EA0A95/p1712696508060309) (internal).
This PR marks "conversational" as deprecated in the list of supported tasks + add a line for `chat_completion`. Since we don't have a proper task for chat completion, I redirect to https://huggingface.co/tasks/text-generation which is I think the most appropriate page describing the task.
> Add `chat_completion` and remove `conversational` from Inference guide

- src/huggingface_hub/_inference_endpoints.py
- tests/test_inference_endpoints.py
From @McPatate on [slack](https://huggingface.slack.com/archives/C03E4DQ9LAJ/p1712913929852529?thread_ts=1709825452.071459&cid=C03E4DQ9LAJ) (internal):
> The condition in the InferenceEndpoints::wait function isn't what I expect to mean "ready":
> ```py
>         while True:
>             self.fetch()
>             if self.url is not None:  # Means the endpoint is deployed
>                 logger.info("Inference Endpoint is ready to be used.")
>                 return self
> ```
> as the url can be provisioned before the endpoint started. Wasn't it that we made it so that huggingface_hub queries the url until status is 200?
This PR fixes this by making a GET request on the returned URL before returning (in `.wait` call).
> Correctly check inference endpoint is ready

- src/huggingface_hub/hub_mixin.py
- tests/test_hub_mixin_pytorch.py
Would be good to be able to set a custom `pipeline_tag`. Mentioned by @julien-c in https://github.com/jasonppy/VoiceCraft/pull/90#discussion_r1566439191.
> Add support for pipeline_tag in ModelHubMixin

- tests/test_hf_api.py
Fix test failing in CI. Sorting models by ascending likes is not supported by the Hub anymore (and useless anyway).
> Remove test sort by acsending likes

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
Adding a small warning tip based on this [internal discussion](https://huggingface.slack.com/archives/C016D661PAN/p1713796729692209?thread_ts=1713796161.795809&cid=C016D661PAN).
General thought: I'm wondering how useful the `list_deployed_models` method actually is for users if they don't know if the list is up to date and they need to check with InferenceClient.get_model_status anyways. Could we have a cached list that is updated every N minutes or something like that? No idea how complicated that would be to implemented in the backend. @Wauplin @Narsil
> add warning tip that list_deployed_models only searches over cache

- docs/source/en/guides/integrations.md
- src/huggingface_hub/hub_mixin.py
- tests/test_hub_mixin.py
- tests/test_hub_mixin_pytorch.py
This PR adds some improvement to the `ModelHubMixin` class and in particular:
1. Possibility to define more metadata for a library; `license`, `license_link`, `license_name`, `pipeline_tag`, `languages`.
2. Possibility to define a custom model card template. Useful if somehow wants to add a citation section in all model cards for instance. It's also possible to dynamically generate the model card, for example to store metrics at runtime.
3. Possibility to handle arbitrary input types. Very useful when trying to integrate with libraries that instantiate models with custom values. Typically happened for [`VoiceCraft`](https://github.com/jasonppy/VoiceCraft) (expects a `argparse.Namespace`) or  [MichelAngelo](https://github.com/NeuralCarver/Michelangelo) (expects a `OmegaConf` see …
> `ModelHubMixin`: more metadata + arbitrary config types + proper guide

- src/huggingface_hub/hf_file_system.py
For normal downloads (i.e. `hf_hub_download` and `snapshot_download`), we have configurable values `HF_HUB_ETAG_TIMEOUT` and `HF_HUB_DOWNLOAD_TIMEOUT`. Let's use them in the hf filesystem as well to avoid long-lasting requests (current default is to wait indefinitely, now set to 10s).
Related to https://github.com/huggingface/dataset-viewer/pull/2752.
> Respect default timeouts in `hf_file_system`

- src/huggingface_hub/_multi_commits.py
- src/huggingface_hub/hf_api.py
This PR harmonizes all `token` parameter descriptions and type definitions as discussed in #2251.
All functions now uniformly use the following type definition for the `token` parameter:
```python
token: Union[bool, str, None] = None
```
The decision to use `Union[bool, str, None]` for the type definition allows for explicit disabling of authentication (`False`), use of a specific token (`str`), or defaulting to a saved token (`None`).
The docstring for the `token` parameter has been standardized across all relevant functions to:
```
token (Union[bool, str, None], optional):
A valid user access token (string). Defaults to the locally saved
token, which is the recommended method for authentication (see
https://huggingface.co/docs/huggingface_hub/quick-start#authentication).
To disable …
```
> Standardise token Parameter description and Type Definition

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_common.py
- src/huggingface_hub/inference/_generated/_async_client.py
- tests/cassettes/InferenceClientVCRTest.test_chat_completion_with_non_tgi.yaml
- utils/generate_async_inference_client.py
cc @LysandreJik who pinged me about this.
`transformers`'s pipeline also accepts a list of messages instead of raw text when generating text. The chat template is then rendered server-side. This PR updates the `InferenceClient.chat_template` logic for when the API is not TGI-backed to use this (new?) feature. It avoid us to render client-side the chat template which was a bit annyoing/not robust.
Note: the default workflow remains optimized to work with TGI servers which provides much more detailed information. LLMs not backed by TGI are usually smaller models like the DialoGPT family which are not that good anyway :confused: 
cc @Rocketknight1 who implemented this in `transformers` I believe?
**Note:** failing tests are unrelated.
**Note:** no need to review …
> Render chat-template server-side for transformers-backed models

- tests/test_file_download.py
- tests/test_hf_api.py
It is not possible to upload a file with the name `..\\ddd`, hence reducing the need for some tests.
Also, implicitly deleting a folder is now ok.
This should fix the CI.
> Delete legacy tests in `TestHfHubDownloadRelativePaths` + implicit delete folder is ok

- docs/source/en/guides/download.md
- src/huggingface_hub/_local_folder.py
- src/huggingface_hub/_snapshot_download.py
- src/huggingface_hub/file_download.py
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/utils/_paths.py
- tests/test_commit_api.py
- tests/test_file_download.py
- tests/test_hf_api.py
- tests/test_local_folder.py
- tests/test_utils_paths.py
Discussed in private with @LysandreJik and @julien-c (sorry about that).
In https://github.com/huggingface/huggingface_hub/issues/1738 we introduced a new workflow to download files to a local dir. It uses a small cache folder to store metadata + tmp files about the download process. This PR renames this folder from `.huggingface` to `.cache/huggingface`. 2 advantages:
- it makes it clear that it's cache
- it allows us to keep `.huggingface` if we want to introduce something similar to `.github/` in the future.
> Rename `.huggingface/` folder to `.cache/huggingface/`

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Fix https://github.com/huggingface/huggingface_hub/issues/2265 cc @jacobmarks
> Support filtering datasets by tags

- src/huggingface_hub/hf_file_system.py
...or we get rate-limited in the dataset viewer (e.g. for FineWeb)
cc @severo
> [HfFileSystem] Less /paths-info calls

- src/huggingface_hub/serialization/_base.py
- src/huggingface_hub/serialization/_numpy.py
- src/huggingface_hub/serialization/_tensorflow.py
- src/huggingface_hub/serialization/_torch.py
- tests/test_serialization.py
This PR adds the possibility to pass a string for `max_shard_size` in `split_state_dict_into_shards_factory`. This makes the docstring consistant with the API. I also fixed a typo in the example `split_torch_state_dict_into_shards`. 
Also, it would be great to change the version of the main branch to "0.24.0.dev0" as it is currently incompatible with the latest transformers that requires >= 0.23.0. 
Note: It seems like I can't put `Union[str, int]` as it makes the quality test fail ?
> Support `max_shard_size` as string in `split_state_dict_into_shards_factory`

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- src/huggingface_hub/inference/_generated/types/feature_extraction.py
Close https://github.com/huggingface/huggingface_hub/pull/1885, https://github.com/huggingface/huggingface_hub/issues/1877, and https://github.com/huggingface/huggingface_hub/issues/1939.
cc @datavistics @awinml
This PR adds support for `truncate` and `normalize` parameters in the InferenceClient.
Those options are only supported by TEI-powered servers but still worth supporting them.
cc @SBrandeis @OlivierDehaene as well on the inference part
> Support truncate and normalize in InferenceClient

- src/huggingface_hub/inference/_generated/_async_client.py
- tests/test_inference_async_client.py
- utils/generate_async_inference_client.py
Should fix warnings in optimum CI cc @dacorvo
At the moment if an error occurs while sending a POST with `AsyncInferenceClient`, we don't catch all errors. This PR makes sure that we close the connection "no matter what" and before raising the exception. Also added a test to ensure that.
> Close aiohttp client on error

- src/huggingface_hub/hf_api.py
- src/huggingface_hub/repocard_data.py
- tests/test_hf_api.py
- tests/test_repocard_data.py
The Open LLM Leaderboard has been moved to a new org: https://huggingface.co/spaces/open-llm-leaderboard/open_llm_leaderboard. This PR updates examples and tests that were relying on it which should fix a few errors in the CIs (no big deal, it's just that we need some examples for demo sometimes).
**EDIT:** fixed also some more tests related to the fact that `repo_update_visibility` don't handle implicit repo ids anymore. This is a breaking change server-side but that's for the best (more consistent with all other endpoints).
**EDIT 2:** made some more cleaning + re-enabled some Space tests that were not supported in staging before.
> Fix test: rename to open-llm-leaderboard + some cleaning

- .github/workflows/python-tests.yml
3 git tests are currently failing on the Windows CI with error:
```
fatal: active post-checkout hook found during git clone:
```
I seems to be due to a recent git security update that is not yet handled by git+lfs. See:
- https://github.com/git-lfs/git-lfs/issues/5749
- https://github.com/git-lfs/git-lfs/issues/5754
In the meantime a solution is to disable this new security feature by setting `GIT_CLONE_PROTECTION_ACTIVE=false` in the Windows test env. **This only affects the CI, not the package itself.**
CI should be green :)
> Fix windows tests (git security update)

- src/huggingface_hub/_webhooks_server.py
When using `WebhooksServer`, the webhook URLs are printed in the logs so that users can configure them in their settings. However, when running in a Space the URL looks like this:
```
Webhooks are correctly setup and ready to use:
- POST http://localhost:7860/webhooks/update_leaderboard
- POST http://localhost:7860/webhooks/update_queue
Go to https://huggingface.co/settings/webhooks to setup your webhooks.
```
This PR fixes this by looking at the `SPACE_HOST` variable (if running in a Space). Logs should now show something like
```
Webhooks are correctly setup and ready to use:
- POST http://open-llm-leaderboard-open-llm-leaderboard.hf.space/webhooks/update_leaderboard
- POST http://open-llm-leaderboard-open-llm-leaderboard.hf.space/webhooks/update_queue
Go to …
```
> Print correct webhook url when running in Spaces

- docs/source/en/guides/cli.md
The option to use local directory for downloads is local-dir and local_dir
> changed from --local_dir to --local-dir

- docs/source/en/package_reference/serialization.md
- docs/source/ko/package_reference/serialization.md
- src/huggingface_hub/__init__.py
- src/huggingface_hub/serialization/__init__.py
- src/huggingface_hub/serialization/_torch.py
Following https://github.com/huggingface/transformers/pull/31091#issuecomment-2141947327.
cc @SunMarc
> Make `get_torch_storage_id` public

- README.md
- README_cn.md
- README_de.md
- README_hi.md
- README_ko.md
Updating from https://static.pepy.tech/badge/huggingface_hub/month to https://img.shields.io/pypi/dm/huggingface_hub. 
<a href="https://pypi.org/project/huggingface-hub"><img alt="downloads" src="https://static.pepy.tech/badge/huggingface_hub/month"></a>
<a href="https://pypi.org/project/huggingface-hub"><img alt="PyPI - Downloads" src="https://img.shields.io/pypi/dm/huggingface_hub"></a>
> Update download badges in README

- src/huggingface_hub/file_download.py
When downloading files in `file_download.py`, we use a progress bar. This progress bar can be either passed by the user or we create a classic tqdm bar (see update in https://github.com/huggingface/huggingface_hub/pull/2143).
As @cbensimon noticed, the progress bar is not correctly closed when an error occurs or when `hf_transfer` is used. This PR fixes this by using a context manager. The progress bar is now always closed if created internally. When passed by the user, the progress bar is not closed as it is a the user's discretion to manage it.
Better to review with "hide whitespace" checked.
> Fix progress bar not always closed in file_download.py

- src/huggingface_hub/hub_mixin.py
- tests/test_hub_mixin.py
- tests/test_hub_mixin_pytorch.py
Hi!
There is an option to customize the model card for `Mixin`s, it would be great to support custom kwargs for a card also.
Here is an example:
```python
import torch
from huggingface_hub import PyTorchModelHubMixin
MODEL_CARD_TEMPLATE = """
---
{{ card_data }}
---
{{ custom_data }}
"""
class Model(torch.nn.Module, PyTorchModelHubMixin, model_card_template=MODEL_CARD_TEMPLATE):
pass
model = Model()
model_card_kwargs = {"custom_data": "This is an awesome model..."}
model.save_pretrained("test-model", model_card_kwargs=model_card_kwargs, push_to_hub=True)
```
Generated readme:
```
---
tags:
- pytorch_model_hub_mixin
- model_hub_mixin
---
This is awesome model...
```
Let me know what you think about this feature! If it's OK, I can add the necessary tests.
> Support custom kwargs for model card in save_pretrained

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
This PR adds a `model_id` parameter to the `InferenceClient.chat_completion` method to be sent in the request payload. Solves https://github.com/huggingface/huggingface_hub/issues/2293 cc @anubhavrana
> Send model_id in ChatCompletion request

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- tests/cassettes/TestTextGenerationClientVCR.test_generate_stream_with_details.yaml
- tests/cassettes/TestTextGenerationClientVCR.test_generate_with_details.yaml
Fix https://github.com/huggingface/huggingface_hub/issues/2315. Thanks @WesleyTheGeolien for reporting it!
Since recent refacto of the text-generation client (https://github.com/huggingface/huggingface_hub/pull/2237), `details=True` was not forwarded to TGI, which is a breaking change. This PR fixes it. I'll do a hot-fix release once merged.
> Fix  always None in text_generation output

- src/huggingface_hub/hf_api.py
Fix https://github.com/huggingface/huggingface_hub/issues/2301.
With `create_inference_endpoint`, it is possible to set a custom docker image to run in the Inference Endpoint (typically a TGI container). When adding this in https://github.com/huggingface/huggingface_hub/issues/1861, I forgot to add it to `update_inference_endpoint`. This PR fixes this for consistency. And also to save poor @datavistics regularly making bad dreams about it.
> Support custom_image in update_inference_endpoint

- src/huggingface_hub/repository.py
Better to do `whoami().get("email")` since this field is not guaranteed to be returned. It depends on token's permission which can be restricted in case of finegrained token or OAuth token.
First reported on [HF Forum](https://discuss.huggingface.co/t/why-am-i-getting-keyerror-email/89188).
> Fix Repository if whoami call doesn't return an email

- setup.py
- src/huggingface_hub/file_download.py
- tests/test_file_download.py
From a suggestion from @julien-c. It's not used since Aug 2022 so time to remove it for real I think? :) 
This PR deprecates:
- `filename_to_url`
- `url_to_filename`
- `cached_download`
- `legacy_cache_layout` parameter
Deprecation is expected for release 0.26.
I took care of fixing HF libraries that had remaining occurrences. None of them were in highly-used part of the code anyway.
- https://github.com/huggingface/tokenizers/pull/1547
- https://github.com/huggingface/transformers/pull/31284
- https://github.com/huggingface/diffusers/pull/8419
> Deprecate `legacy_cache_layout` parameter in `hf_hub_download`

- docs/source/ko/guides/integrations.md
- src/huggingface_hub/hub_mixin.py
- tests/test_hub_mixin_pytorch.py
Fix https://github.com/huggingface/huggingface_hub/issues/2334.
Thanks to @not-lain's investigation (see https://github.com/huggingface/huggingface_hub/issues/2334#issuecomment-2167092482), I have been able to reproduce the error with a simple example. The problem was that custom encoders/decoders were not used for the special attribute `config`. This PR fixes it. I also added a regression test inspired by the reproducible example. 
Once merged, I'll make a hot-fix release with this fix.
(failing tests are unrelated)
> Fix: correctly encode/decode config in ModelHubMixin if custom coders

- src/huggingface_hub/__init__.py
Great confusion in #2089 due to the actual underlying error being hidden behind importlib catching. This PR prints the error to console to help the user figure out what is going wrong.
> print actual error message when failing to load a submodule

- src/huggingface_hub/_inference_endpoints.py
- src/huggingface_hub/hf_api.py
- tests/test_inference_endpoints.py
cc @mishig25 (from private [slack thread](https://huggingface.slack.com/archives/C04F8N7FQNL/p1718282503843099?thread_ts=1718185411.507489&cid=C04F8N7FQNL))
> Do not raise on `.resume()` if Inference Endpoint is already running

- docs/source/en/guides/repository.md
- src/huggingface_hub/hf_api.py
Related to [slack thread](https://huggingface.slack.com/archives/C02EMARJ65P/p1717716797309859) (private). cc @nbroad1881 @coyotte508 
Resource groups is a Enterprise feature that allows orgs to manage which members have access to a resource. This PR adds support for `resource_group_id: Optional[str]` in `create_repo`. When passed, the repo will be created inside the corresponding resource group. Check out https://huggingface.co/docs/hub/en/security-resource-groups for more details about resource groups.
> Support `resource_group_id` in `create_repo`

- src/huggingface_hub/hf_file_system.py
...by using `expand_info=False` by default (same logic as `fs.glob()`)
before:
```python
In [1]: from huggingface_hub import HfFileSystem
In [2]: %time _ = list(HfFileSystem().walk("hf://datasets/allenai/c4/en"))
CPU times: user 275 ms, sys: 27.6 ms, total: 302 ms
Wall time: 11.6 s
```
after:
```python
In [1]: from huggingface_hub import HfFileSystem
In [2]: %time _ = list(HfFileSystem().walk("hf://datasets/allenai/c4/en"))
CPU times: user 176 ms, sys: 22.4 ms, total: 198 ms
Wall time: 3.25 s
```
> [HfFileSystem] Faster `fs.walk()`

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- src/huggingface_hub/inference/_generated/types/feature_extraction.py
Related to https://github.com/huggingface/huggingface.js/pull/781.
This PR adds `prompt_name` to `InferenceClient.feature_extraction` which was introduced in https://github.com/huggingface/text-embeddings-inference/pull/312. I also took the opportunity to add `truncation_direction`.
> Add `prompt_name` to feature-extraction + update types

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
Minijinja optional dependency not needed since https://github.com/huggingface/huggingface_hub/pull/2258
> Remove jinja tips + fix typo in chat completion docstring

- src/huggingface_hub/commands/huggingface_cli.py
- src/huggingface_hub/utils/__init__.py
- src/huggingface_hub/utils/_subprocess.py
- src/huggingface_hub/utils/tqdm.py
The best practice calls for executable scripts, such as those with shebang, to have their execution bits set.
Among other things, this helps to immediately highlight them as scripts in the file system.
> Removing shebang in python files that are not meant to be executed

- docs/source/en/package_reference/hf_file_system.md
- src/huggingface_hub/hf_file_system.py
Automate and expand `HfFileSystem` documentation
- Generates comprehensive docs for all `HfFileSystem` methods
- Fetches `fsspec` docs and adds HuggingFace-specific notes
- Updates main docs [[autodoc]] to use `all` for full method listing
Closes #2100
Cc @severo
> Document more `HfFilesyStem` Methods

- docs/source/en/guides/inference.md
- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- tests/cassettes/TestOpenAICompatibility.test_base_url_and_api_key.yaml
- tests/cassettes/TestOpenAICompatibility.test_with_stream_true.yaml
- tests/cassettes/TestOpenAICompatibility.test_without_base_url.yaml
- tests/cassettes/test_openai_compatibility_base_url_and_api_key.yaml
- tests/cassettes/test_openai_compatibility_with_stream_true.yaml
- tests/cassettes/test_openai_compatibility_without_base_url.yaml
- tests/test_inference_async_client.py
- tests/test_inference_client.py
- utils/generate_async_inference_client.py
Closes https://github.com/huggingface/huggingface_hub/issues/2369 @lappemic 
Goal is to be able to use `InferenceClient` exactly the same way as `OpenAI` client. To do so we need to:
@philschmid could you have a look at it and confirm it meets your expectations? See tests for real example ([here](https://github.com/huggingface/huggingface_hub/pull/2384/files#diff-53ed5db45d648482e7373b2291d45216a2dae782cd864772f8de717793c9cbfa) and [here](https://github.com/huggingface/huggingface_hub/pull/2384/files#diff-76a73351bb753f100ea324d6594ac33bacb13b1068a88c70a15daf4314470cc5))
```py
client = InferenceClient(
base_url="https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3-8B-Instruct",
api_key="my-api-key",
)
output = client.chat.completions.create( …
```
> True OpenAI drop-in replacement by InferenceClient

- setup.py
This change is needed, otherwise numpy won't be installed. See https://github.com/huggingface/safetensors/blob/079781fd0dc455ba0fe851e2b4507c33d0c0d407/bindings/python/pyproject.toml#L35
> `torch`  extra requires for `safetensors` dep

- src/huggingface_hub/file_download.py
- tests/test_file_download.py
Fix https://github.com/huggingface/huggingface_hub/issues/2385 cc @ankushvangari @willarmiros
Since 0.23.0 release (and more precisely https://github.com/huggingface/huggingface_hub/pull/2223), the local token is always used when downloading a file even if `token=False` is passed. This PR fixes this. I also added a regression test for it.
> Fix token=False not respected in file download

- .github/workflows/python-tests.yml
- docs/source/en/package_reference/serialization.md
- setup.py
- src/huggingface_hub/__init__.py
- src/huggingface_hub/serialization/__init__.py
- src/huggingface_hub/serialization/_base.py
- src/huggingface_hub/serialization/_tensorflow.py
- src/huggingface_hub/serialization/_torch.py
- tests/test_serialization.py
Partially resolve https://github.com/huggingface/huggingface_hub/issues/2065.
Follow-up PR after https://github.com/huggingface/huggingface_hub/pull/2314.
In https://github.com/huggingface/huggingface_hub/pull/2314, we introduce `save_torch_state_dict`. This new PR:
- adds logic to deduplicate shared layers in safetensors. This is mostly taken from safetensors's torch helpers (see [here](https://github.com/huggingface/safetensors/blob/main/bindings/python/py_src/safetensors/torch.py)). See [slack thread](https://huggingface.slack.com/archives/C03V11RNS7P/p1718183125892849) (private) for discussions around this. See also https://huggingface.co/docs/safetensors/torch_shared_tensors for more details.
- adds `save_torch_model` to directly save a torch `nn.Module`
- renames internal methods …
> Handle shared layers in `save_torch_state_dict` + add `save_torch_model`

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
- tests/testing_utils.py
Solve https://github.com/huggingface/huggingface_hub/issues/2325.
**EDIT:** added support for `model_info`/`dataset_info`/`space_info` as well as `list_models`/`list_datasets`/`list_spaces`. Added tests and docstrings for all of them.
---
First draft of what we discussed in https://github.com/huggingface/huggingface_hub/issues/2325#issuecomment-2162407468 cc @osanseviero @julien-c . In the end I went for "put everything in `ModelInfo` and have all attributes optional". For now I only implemented `expand` for models helpers but it can be easily extended to datasets/spaces.
In order to better document the available parameters, I used a `Literal` type annotations listing all valid keys. Since it's "just" a type annotation, passing any string will still be backward compatible in the future as …
> Support `expand` parameter in `xxx_info` and `list_xxxs` (model/dataset/Space)

- .github/workflows/python-tests.yml
- docs/source/en/package_reference/serialization.md
- setup.py
- src/huggingface_hub/__init__.py
- src/huggingface_hub/_local_folder.py
- src/huggingface_hub/file_download.py
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/serialization/__init__.py
- src/huggingface_hub/serialization/_base.py
- src/huggingface_hub/serialization/_tensorflow.py
- src/huggingface_hub/serialization/_torch.py
- tests/test_file_download.py
- tests/test_hf_api.py
- tests/test_local_folder.py
- tests/test_serialization.py
- tests/testing_utils.py
Change the path of the local dir to an extended path by prepending "\\?\" to the absolute path, when the absolute path is longer than 255 characters on Windows.
This addresses Issue  #2374.
Also fixed a small typo.
> Use extended path on Windows when downloading to local dir

- src/huggingface_hub/hf_api.py
This is needed when the `expand` parameter is extended server-side. It doesn't affect client-side logic but helps with autocompletion + docs. cc @SBrandeis who recently shipped `inferenceStatus`.
> Add `inferenceStatus` to ExpandModelProperty_T type

- src/huggingface_hub/constants.py
- src/huggingface_hub/utils/_fixes.py
File lock operations did not have an associated timeout, which could present problems when trying to debug an issue since nothing would be logged if we could not acquire the lock and would wait forever.
> Add a default timeout for filelock

- src/huggingface_hub/hub_mixin.py
- tests/test_hub_mixin_pytorch.py
This PR fixes a quite major issue with tags/metadata being shared between classes that inherit from `PyTorchModelHubMixin`. It has most likely been introduced in https://github.com/huggingface/huggingface_hub/pull/2305 which was fixing attributes lost in inheritance. This time we should be fine!
I also made a modification so that tags are now deduplicated and sorted.
Realized this while working on https://github.com/state-spaces/mamba/pull/471. I'll make a hot-fix release once merged as it's quite problematic. If a user has several classes inheriting from `PyTorchModelHubMixin` (typically several packages using it installed in a venv), then the pushed models will have incorrect metadata on the Hub. I realized this while pushing [6d4b46a](https://huggingface.co/state-spaces/mamba-130m/commi …
> Hot-fix: do not share tags between `ModelHubMixin` siblings

- src/huggingface_hub/_commit_api.py
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/utils/sha.py
- tests/test_hf_api.py
- tests/test_utils_sha.py
Following server-side update in https://github.com/huggingface-internal/moon-landing/pull/10547 (internal), we can now retrieve the `oid` of the existing files in the repo. This allows us to determine which files did not change since the last commit and therefore avoid empty commits. 
This PR:
- fetches the  `oid` of the remote files in the `/preupload` call. If the file doesn't exist, nothing is returned.
- compares the remote and local `oid`
- if they match => remove the `CommitOperationAdd` from the commit + log something (INFO level)
- if no operations left in the commit => return early + log something (WARNING level). Since returning `None` might break downstream libraries, we return the `CommitInfo` of the last commit for that revision
- if some operations left => continue normally …
> Prevent empty commits if files did not change

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
If a user is granted access to a repo without asking for it, their email address should not be shared to the repo owner. This has been enforced server-side by https://github.com/huggingface-internal/moon-landing/pull/10651 (internal). This PR fixes the client logic so that `email` is not required. Currently if one user from the list has been granted access, `list_accepted_access_requests` fails with a `KeyError`.
> Fix `list_accepted_access_requests` if grant user manually

- src/huggingface_hub/_tensorboard_logger.py
Following recent discussions with @severo. This PR:
- adds a tag `hf-summary-writer` to the model card metadata when using `HFSummaryWriter` (will help with discoverability/analytics)
- updates the example code snippet to showcase how easy it is to switch to it in a codebase.
See https://huggingface.co/spaces/severo/training-metrics-tab/discussions/1.
> Tag repos using `HFSummaryWriter` with 'hf-summary-writer'

- src/huggingface_hub/__init__.py
- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Follow-up PR after server-side update (https://github.com/huggingface-internal/moon-landing/pull/10607, private link). See also discussion [in slack](https://huggingface.slack.com/archives/C02EMARJ65P/p1720532137304479) (private link).
This PR handles `orgs` in `get_user_overview`. It is an `Organization` dataclass (newly defined) with avatar_url, name and fullname.
```py
>>> from huggingface_hub import get_user_overview
>>> omar = get_user_overview("osanseviero")
>>> omar.orgs[0]
Organization(avatar_url='https://cdn-avatars.huggingface.co/v1/production/uploads/1583856921041-5dd96eb166059660ed1ee413.png', name='huggingface', fullname='Hugging Face')
```
I also realized we forgot to expose `get_user_overview` at the root of the package. This PR fixed this. Also exposing `ModelInfo`, …
> List organizations in `get_user_overview`

- tests/test_fastai_integration.py
- tests/test_hf_api.py
- tests/test_hub_mixin_pytorch.py
- tests/test_keras_integration.py
`HfApi.model_info(...).modelId` is deprecated and used only in tests. Let's use `HfApi.model_info(...).id` everywhere instead. cc @julien-c _"Time to finally remove this, it's been long enough"_ (see https://github.com/huggingface-internal/moon-landing/pull/10713, private).
Also took the opportunity to (non-exhaustively) switch some `self.assert` to `assert` in tests. All diff is semantically the same as before.
> Do not use modelId + remove some self.assert

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_common.py
- src/huggingface_hub/inference/_generated/_async_client.py
- tests/cassettes/InferenceClientVCRTest.test_chat_completion_with_non_tgi.yaml
- tests/cassettes/test_async_chat_completion_not_tgi_no_stream.yaml
- tests/test_inference_async_client.py
- tests/test_inference_client.py
- utils/generate_async_inference_client.py
1. Related to https://github.com/huggingface/text-generation-inference/pull/2221. TGI now returns a `b"data: [DONE]"` stop signal when iterating through generated tokens (stream=True). This PR adds support for this stop signal. Once this PR is merged, I'll make a hot-fix release since `InferenceClient` is currently broken on newest versions of TGI for `text_generation` and `chat_completion`.
2. I also removed all the "non-tgi" logic in `chat_completion` since every model is served by TGI now, even when it's a transformers-only model (e.g. `"microsoft/DialoGPT-small"`. This simplifies a lot the logic and will avoid hiding relevant errors to the users. In case the model is transformers-served and is not compatible with chat completion, a `422 unprocessable entity: template not found` is …
> [hot-fix] Handle [DONE] signal from TGI + remove logic for "non-TGI servers"

- src/huggingface_hub/utils/_fixes.py
Fix https://github.com/huggingface/huggingface_hub/issues/2399 (cc @jeffliu-LL)
On unix, `filelock` checks if `fcntl` is available. If it is, `filelock.Filelock` is in fact a `UnixFileLock` which uses `fcntl.flock` to acquire/release the lock. Since it's a system call, the lock is supposed to be much more robust (e.g. does not rely on file existence or not). The problem is that if `fcntl` is available but at least one partition or filesystem does not support it, a `NotImplementedError` exception is raised with message `"FileSystem does not appear to support flock; use SoftFileLock instead"`. 
This PR fixes usage of `filelok` by catching this NotImplementedError when it happens and defaulting back to a `SoftFileLock`. This is a weaker solution but for our use case it should be fine (+ it's …
> Fix filelock if flock not supported

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Little QoL suggested by @coyotte508  on slack.
We've had several users reporting that they've pushed their dataset to a model repo. It is then impossible to convert the repo to dataset on the Hub, forcing them to entirely re-upload everything. This PR tries to prevent this kind of mistake by raising a warning when user does upload an arrow or a parquet file to a non-dataset repo. If the user don't stop the process, the files are still correctly uploaded since we don't want to forbid the upload.
> Warn if user tries to upload a parquet file to a model repo

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Fix https://github.com/huggingface/huggingface_hub/issues/2411 cc @narugo1992
When trying to create an empty commit, the commit call is not done. Instead we retrieve the information from the last commit on the revision. On a PR, the revision is quoted twice leading to a HTTP 404 error. This PR fixes it.
I also added a regression test for it.
**EDIT:** added https://github.com/huggingface/huggingface_hub/pull/2413/commits/0329085a9fd03eab33062cec30578ba0cb12a429 after https://github.com/huggingface/huggingface_hub/pull/2412
> Fix creating empty commit on PR

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- tests/test_inference_client.py
Fix https://github.com/huggingface/huggingface_hub/issues/2414. Thanks @alvarobartt for reporting. The implemented solution will work both when `/v1` is provided (openai compatibility) and without (backward compatibility). Trailing `"/"` are also silently ignored.
**EDIT:** failing tests are unrelated (torch update)
> Fix chat completion url for OpenAI compatibility

- src/huggingface_hub/hf_api.py
Fix https://github.com/huggingface/huggingface_hub/issues/2419 (and https://github.com/huggingface/datasets/issues/7067 / https://github.com/huggingface/datasets/pull/7069).
When creating a repo with `exists_ok=True`, if the user do not have permission to create it but the repo already exists, an HTTP 403 is returned by the server. We catch this error client-side and ignore it since the repo exists. This PR adds the same logic for `create_branch`.
cc @albertvillanova @lhoestq
> Do not raise if branch exists and no write permission

- docs/source/en/guides/cli.md
- src/huggingface_hub/commands/repo_files.py
Fix https://github.com/huggingface/huggingface_hub/issues/2416
```
huggingface-cli repo-files <repo_id> delete *
```
is wrong and must be replaced by 
```
huggingface-cli repo-files <repo_id> delete "*"
```
Problem is that the shell lists all local files and add it to the executed command line. Nothing much we can do python-side unfortunately.
> fix repo-files CLI example

- src/huggingface_hub/file_download.py
Fix implementation from https://github.com/huggingface/huggingface_hub/pull/1220.
When downloading a file, we set the correct permissions on it when applicable. However if it's not possible, we shouldn't raise an exception. This PR fixes this by ignoring any OSError in the process and convert them to a warning log.
Moreover, if copying a file with `shutils.copy2` cannot be done (copy file + metadata), we default to `shutils.copyfile` (copy file content). What's important is to have the file content on the destination path rather than the metadata.
cc @XciD who got this while working on an S3 mount
**EDIT:** failing test is unrelated
> Do not raise if chmod fails

- src/huggingface_hub/file_download.py
Follow-up PR after https://github.com/huggingface/huggingface_hub/pull/2429. Looks like I forgot to fix one other `shutil.move` call :grimacing: 
cc @XciD 
**EDIT:** failing test is unrelated.
> Fix shutil move

- README.md
- contrib/conftest.py
- docs/source/en/guides/cli.md
- docs/source/en/guides/hf_file_system.md
- docs/source/ko/guides/cli.md
- src/huggingface_hub/_login.py
"login" is a noun, and "log in" is a verb. I've corrected instances of "login" where it is used as a verb.
> Correct "login" to "log in" when used as verb

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
cc @MoritzLaurer who pinged me about this [on slack](https://huggingface.slack.com/archives/C03E4DQ9LAJ/p1721899163459559) (private link). 
It is wrong to say that `base_url` and `model` have the exact same behavior since https://github.com/huggingface/huggingface_hub/pull/2410 have been merged. The base URL is used to build the complete URL by appending `(/v1)?/chat/completions` to it. On the contrary, when an URL is passed as `model`, we use it directly without appending anything (e.g. we don't consider it as a "base url").
This PR fixes this confusion in the docs.
> Document the difference between model and base_url

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- utils/generate_async_inference_client.py
The AsyncInferenceClient doesn't use proxies set in environment variables. 
It uses aiohttp but doesn't set the trust_env parameter to True.
this PR handle trust_env parameter to and set aiohttp client and request client 
issue : [AsyncInferenceClient doesn't use proxies set in environment variables #2420](https://github.com/huggingface/huggingface_hub/issues/2420)
> Bug - [InferenceClient] - use proxy set in var env

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Close https://github.com/huggingface/huggingface_hub/issues/2427  cc @weigary
It is now possible to list models and datasets with `gated=True` or `gated=False`. By default (`gated=None`), all models/datasets are returned.
Example:
```py
from huggingface_hub import HfApi
api = HfApi()
print("id, likes, downloads, gated")
for model in api.list_models(sort="likes7d", limit=5, gated=True, expand=["gated", "likes", "downloads"]):
print(model.id, model.likes, model.downloads, model.gated)
```
```
id, likes, downloads, gated
black-forest-labs/FLUX.1-dev 1979 186639 auto
meta-llama/Meta-Llama-3.1-8B-Instruct 1778 1244445 manual
LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct 289 10889 auto
stabilityai/stable-diffusion-3-medium 3968 207853 auto
google/gemma-2-2b-it 418 113700 manual
```
(thanks to …
> Add 'gated' search parameter

- src/huggingface_hub/_webhooks_server.py
...in Webhooks Server.
We were previously relying on the `SYSTEM` environment variable which is not set for Docker Spaces. See related convo [on slack](https://huggingface.slack.com/archives/C02EMARJ65P/p1723640229716009?thread_ts=1723621029.478759&cid=C02EMARJ65P) (private). Better to use `SPACE_ID` which is officially documented [here](https://huggingface.co/docs/hub/en/spaces-overview#helper-environment-variables).
> Rely on SPACE_ID to check if app is local or in a Space

- src/huggingface_hub/utils/_errors.py
Should help investigate https://github.com/huggingface/huggingface_hub/issues/2248 and [this convo](https://huggingface.slack.com/archives/C02EMARJ65P/p1723632946733569) (private slack).
From time to time we get reported that a 416 Range Not Satisfiable is raised. This PR adds more information to the raised error (requested range + response content range, if any). Should help investigate the issue.
Example:
`huggingface_hub.utils._errors.HfHubHTTPError: 416 Client Error: Range Not Satisfiable for url: https://huggingface.co/datasets/open-llm-leaderboard/results/resolve/6a8ff66a20da618386689e7e7c9c76932f0c33bf/.gitattributes. Requested range: bytes=5000-10000. Content-Range: bytes */2307. (Request ID: Root=1-66bca67b-6ad70d2e5d2917ce5d09d6b4;ffa33b3a-74de-4d8b-9d96-b240d7f8ebe6)`
> Raise with more info on 416 invalid range

- src/huggingface_hub/hf_api.py
- `README.md` validation is moved from `create_commit` to `_prepare_upload_folder_additions`.
- `_prepare_upload_folder_additions` is moved into `HfApi` class, this provides access to `_build_hf_headers`.
- `repo_type` and `token` are added to `_prepare_upload_folder_additions`'s parameters, these are needed for the request to `/api/validate-yaml` endpoint.
- Result from `filter_repo_objects` stored in `filtered_repo_objects` (converted to a list, as it's a generator) to avoid recalculation as it is now used to find `README.md` then later to return the `CommitOperationAdd`s.
- If found, a temporary `CommitOperationAdd` is created for `README.md` to provide `as_file`.
- `break` added after `README.md` validation to avoid iterating other files.
Closes #2451
> huggingface-cli upload - Validate README.md before file hashing

- src/huggingface_hub/inference/_common.py
- tests/cassettes/test_async_chat_completion_with_stream.yaml
- tests/test_inference_async_client.py
- tests/test_inference_client.py
Fixed https://github.com/huggingface/huggingface_hub/issues/2455 reported by @cordawyn.
Let's strip bytes messages to avoid newlines. Thanks @cordawyn for noticing and reporting it. I've been able to reproduce it and updated the docs accordingly.
Also a good reminder that cassettes are not ideal for inference tests. Here the bug came from a non-tested TGI update. Surely something to improve in our CI but that will be done in a future CI.
> Fix broken AsyncInferenceClient on [DONE] signal

- contrib/spacy/test_spacy.py
- src/huggingface_hub/_commit_api.py
- src/huggingface_hub/_snapshot_download.py
- src/huggingface_hub/_tensorboard_logger.py
- src/huggingface_hub/commands/tag.py
- src/huggingface_hub/commands/upload.py
- src/huggingface_hub/errors.py
- src/huggingface_hub/file_download.py
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/hf_file_system.py
- src/huggingface_hub/hub_mixin.py
- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_templating.py
- src/huggingface_hub/repocard.py
- src/huggingface_hub/utils/__init__.py
- src/huggingface_hub/utils/_errors.py
- tests/test_cache_layout.py
- tests/test_cli.py
- tests/test_file_download.py
- tests/test_hf_api.py
- tests/test_hf_file_system.py
- tests/test_hub_mixin_pytorch.py
- tests/test_inference_client.py
- tests/test_repocard.py
- tests/test_snapshot_download.py
- tests/test_utils_errors.py
#2069 
I have implemented the suggestion from issue #2069. The `FileMetadataError` class has been moved from `huggingface_hub/inference/_templating.py` to `huggingface_hub/errors.py`.
Could you please review this PR? If this is correct, I will move the other classes in the same way.
> Define error

- src/huggingface_hub/hf_api.py
Added the ability to pass a "scale_to_zero_timeout" to both `create_inference_endpoint` and `update_inference_endpoint` on HFApi. Addresses #2462.
> Add scale_to_zero_timeout parameter to HFApi.create/update_inference_endpoint

- src/huggingface_hub/utils/_errors.py
reported by @MoritzLaurer [on slack](https://huggingface.slack.com/archives/C02EMARJ65P/p1724144499443679) (internal)
Since we have fine-grained tokens now, the current error message `"make sure you have a token with the write role."` is not relevant anymore. This PR updates it to `"make sure your token has the correct permissions."`.
> Fix error message on permission issue

- src/huggingface_hub/hf_api.py
Following server-side addition.
**EDIT:** failing tests are unrelated.
> Document `baseModels` and `childrenModelCount` as expand parameters

- src/huggingface_hub/errors.py
- src/huggingface_hub/utils/__init__.py
- src/huggingface_hub/utils/_cache_manager.py
Below is the list of descriptions for this PR.
1. Defined two errors (CacheNotFound, CorruptedCacheExcpetion) in errors.py
- imported typing and pathlib package to keep the original definition of CacheNotFound
2. Adjusted the import paths in init.py
3. Removed the original definitions of the errors in _cache_manager.py
- added "from huggingface_hub.errors import CacheNotFound, CorruptedCacheException" for API support
4. Passed Ruff check
#2069 
Duplicate on https://github.com/huggingface/huggingface_hub/pull/2456
> Define cache errors in errors.py

- src/huggingface_hub/hf_api.py
Fix https://github.com/huggingface/huggingface_hub/issues/2472 @MoritzLaurer 
Previously on `update_inference_endpoint`, all fields in the payload were populated by default with `None` values. This lead to a weird side effect which overwrites some existing values with empty ones. In particular, updating any settings of an inference endpoint deletes its environment variables. This PR fixes this by sending only not-none values.
> Fix: do not erase existing values on `update_inference_endpoint`

- src/huggingface_hub/_inference_endpoints.py
Two parameters are missing compared to the `update_inference_endpoint` method: `scale_to_zero_timeout` and `custom_image`. This PR fixes it.
Reported by @MoritzLaurer  in https://github.com/huggingface/huggingface_hub/issues/2472#issuecomment-2302088356.
> Update `endpoint.update` signature

- src/huggingface_hub/_inference_endpoints.py
- src/huggingface_hub/hf_api.py
- tests/test_inference_endpoints.py
Solves:  #2485 
Added the secrets argument to 
* create_inference_endpoint
* update_inference_endpoint
* InferenceEndpoint.update
> feat: :sparkles: allow passing secrets to the inference endpoint client

- src/huggingface_hub/hf_api.py
- src/huggingface_hub/utils/_errors.py
- tests/test_hf_api.py
This small PR exposes `repo_url` info in the `CommitInfo` class. This will make it easier to retrieve the repo_id of a commit, typically when `Model.push_to_hub` creates the repo + create a commit and returns only the commit info and not the repo info (requested by @not-lain [on Slack](https://huggingface.slack.com/archives/C06MW6VMZHS/p1724542935213179) -internal- + makes sense to expose it).
**Note:** `self.commit_url.split("/commit/")[0]` is guaranteed to succeed given [this](https://github.com/huggingface-internal/moon-landing/blob/43e11853fcc52163a0c61cf777fd0685eeaddbf0/server/app/gitViewerRoutes.ts#L1489) (private repo), [this](https://github.com/huggingface/huggingface_hub/blob/6438044cd2e47f757089b728bf9c796e5a462018/src/huggingface_hub/hf_api.py#L3856) and …
> Expose `RepoUrl` info in `CommitInfo` object

- .github/workflows/python-tests.yml
- src/huggingface_hub/hub_mixin.py
- tests/test_hub_mixin_pytorch.py
To merge before https://github.com/huggingface/huggingface_hub/pull/2440 (needed to test it). Two things in this PR:
1. we are now running the torch-test CI with `torch~=2.0` and `torch=="latest"`. This is to ensure a sense of backward-compatibility and still testing on latest updates. `2.0` was chosen arbitrarily. It has been released ~15 months ago. It doesn't mean `huggingface_hub` does not support `torch 1.0` (we would have received reports^^), just that we are not guaranteeing it.
2. Pytorch tests are currently failing in CI with this `FutureWarning`:
> _FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code …
> Torch: test on 2.0 and latest versions + explicitly load with `weights_only=True`

- src/huggingface_hub/inference/_generated/_async_client.py
- tests/cassettes/test_http_session_correctly_closed.yaml
- tests/test_inference_async_client.py
- utils/generate_async_inference_client.py
Close https://github.com/huggingface/huggingface_hub/issues/2493.
This PR adds the possibility to properly close sessions from a `AsyncInferenceClient` object using either `close` or a context manager:
```py
import asyncio
from huggingface_hub import AsyncInferenceClient
model = ...  # NOTE: I'm using a self-hosted TGI instance
async def run():
client = AsyncInferenceClient(model)
answer_stream = await client.text_generation(
"Between emacs and vim, the best editor is",
stream=True,
)
await client.close()
asyncio.run(run())
```
or a context manager:
```py
async with AsyncInferenceClient():
for token in await client.text_generation(
"Between emacs and vim, the best editor is",
stream=True,
):
break  # no one wants the answer
```
If some sessions are still opened when a client is being …
> Properly close session in `AsyncInferenceClient`

- src/huggingface_hub/commands/download.py
- tests/test_cli.py
https://github.com/huggingface/huggingface_hub/issues/2499
> Solved: Need to add the max-workers argument to the huggingface-cli command

- docs/source/en/package_reference/environment_variables.md
- docs/source/ko/package_reference/environment_variables.md
`https://api-inference.huggingface.com` --> `https://api-inference.huggingface.co`
It seems like our shiny new `huggingface.com` might have made an early cameo in this document—though we haven’t unleashed any new subdomains yet. So, let’s update the domain to .co for now 🤗
> fixes: URL fixes

- src/huggingface_hub/hf_api.py
`{model,dataset,space}_info.siblings` should be `[]` if the repo is empty no ? currently it's `None` even if the Hub API returns `"sibligns": []` in the JSON response
this causes unexpected though minor errors in the Viewer
e.g. it indirectly causes the histogram filtering UI of the [laion's viewer](https://huggingface.co/datasets/laion/relaion2B-multi-research-safe) to be disabled
> fix empty siblings

- src/huggingface_hub/file_download.py
Related to [this thread](https://huggingface.slack.com/archives/C01NE71C4F7/p1725359394435419?thread_ts=1725022278.172719&cid=C01NE71C4F7) on slack (private link).
When trying to download a file, if the file does not exist on the Hub, we cache this information by creating an empty file under the `./no-exists` folder. This is used in `transformers` to avoid requesting a given file each time the pipeline is reloaded. The only purpose of this file is to save a HEAD call on initialization. @ydshieh and @glegendre01 have found out that `Path.touch()` raises a `PermissionError` when used on a S3-mounted drive if the file already exists. This PR adds a try/catch block to ignore such failures.
**EDIT:** I've checked and it's the only occurrence where we use `.touch()` on a potentially existing …
> Do not fail on `touch()` if `OSError` (to cache non existence of file)

- CONTRIBUTING.md
- src/huggingface_hub/__init__.py
- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
- utils/check_static_imports.py
Follow-up after https://github.com/huggingface/huggingface_hub/pull/2147
Just noticed we were missing a few things:
- results in `list_organization_members`, `list_user_followers` and `list_user_following` must be paginated for profiles like https://huggingface.co/clem with more than 500 followers and following
- these endpoints didn't have a `token` parameter (better to have it for consistency)
- they were not exposed at the root of the package
This PR fixes all of this. I've updated the tests to check pagination works as expected.
(I also updated `utils/check_static_imports.py` script to avoid duplicates in the `__init__.py`)
> Paginate followers and following endpoints

- src/huggingface_hub/file_download.py
- tests/test_file_download.py
This PR aims at fixing an issue raised several times (last time [here](https://discuss.huggingface.co/t/unable-to-download-microsoft-phi-3-small-8k-instruct-completely/103882)) where a `HTTP 416 Range Not Satisfiable` is raised server-side. After investigation, this seems to happen when:
1. a first download of the file has been made
2. this download was completed in the ".incomplete" file
3. once the download is complete, this file is supposed to be moved to the correct location. This step fails for some reason.
4. a second download is triggered and resumes where it stopped
5. `huggingface_hub` sends an HTTP call with a `Range` header that is not satisfiable (empty range)
This PR fixes this by preventing the HTTP call if the tmp file is already fully downloaded. It is likely that the …
> Fix 416 requested range not satisfiable

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
This PR:
- adds an `inference` field to `ModelInfo` (can be requested using `expand[]`)
- adds a filter `inference` to `list_models`. Can be "warm", "cold" or "frozen"
> Filter models by inference status

- src/huggingface_hub/hf_api.py
Related to https://github.com/huggingface-internal/moon-landing/pull/11062 (private link).
This PR adds support for the `trendingScore` attribute:
- `ModelInfo`, `DatasetInfo` and `SpaceInfo` now have an official `trending_score` attribute populated when the server returns it.
- ExpandModelProperty_T`, `ExpandDatasetProperty_T` and `ExpandSpaceProperty_T` now have a `trendingScore` attribute to ask the server to return this attribute using `expand[]=trendingScore`
- updated some docstrings
In practice, those changes are purely cosmetic to make the attribute better supported.  The `ExpandXxxProperty_T` are only types to help with autocompletion while the `XxxInfo` classes are already exposing all fields they receive from the server. This PR helps by making the autocompletion + …
> Better support for trending score

- src/huggingface_hub/inference/_generated/_async_client.py
- tests/test_inference_async_client.py
- utils/generate_async_inference_client.py
Fix https://github.com/huggingface/huggingface_hub/issues/2521.
Follow-up PR after https://github.com/huggingface/huggingface_hub/pull/2496. Closing sessions when exiting the `AsyncInferenceClient` is not enough to get rid of all warnings. The `ClientResponse` objects also have to be closed explicitly when in case they are not consumed entirely. This PR fixes this by registering all pending responses that have to be closed when a `ClientSession` is closed.
It was a transient error depending on when the garbage collector was triggered, making it difficult to investigate. Many thanks to @tomjorquera who provided a reproducible example. I used it to run over 100 examples (with a progress bar) and it seems resolved:
```py
3%|██▏ …
```
> Fix unclosed aiohttp.ClientResponse objects

- tests/test_inference_client.py
This `_RECOMMENDED_MODELS_FOR_VCR` is there to avoid been impacted by updates in the recommended models (on the Hub / huggingface.js). We already use it in `InferenceClientVCRTest` but it's also useful for `TestResolveURL` class.
Expectation: CI should pass.
> FIX: Use `_RECOMMENDED_MODELS_FOR_VCR` in `TestResolveURL`

- setup.py
- src/huggingface_hub/hub_mixin.py
Two updates:
1. Implemented https://github.com/huggingface/huggingface_hub/issues/2516
2. Added `extras["torch"]` to `[dev]` in `setup.py` since `safetensors` is required for testing mixin
> Implemented https://github.com/huggingface/huggingface_hub/issues/2516

- src/huggingface_hub/file_download.py
This PR fixes an issue that has been introduced in https://github.com/huggingface/huggingface_hub/pull/2223.
It has been reported at least in https://github.com/huggingface/transformers/issues/27421 and https://github.com/huggingface/huggingface_hub/pull/2223 but also on slack (private, [here](https://huggingface.slack.com/archives/C02V5EA0A95/p1725961634325309) and [here](https://huggingface.slack.com/archives/C043JTYE1MJ/p1724233191843019)).
The issue comes from the process to download a file to the cache directory. The process is
1. fetch the metadata
2. check if file is already in cache (if yes, return)
3. acquire a lock
1. check if the file has already been downloaded to the `./blobs/` folder
1. download the file to a temporary file
2. if not, download it and move to `./blobs/` …
> Fix race-condition issue when downloading from multiple threads

- src/huggingface_hub/hub_mixin.py
- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- src/huggingface_hub/utils/_http.py
- tests/test_inference_client.py
Fix https://github.com/huggingface/huggingface_hub/issues/2484.
With the introduction of `base_url` in https://github.com/huggingface/huggingface_hub/pull/2384 and a refacto in https://github.com/huggingface/huggingface_hub/pull/2410, some bugs have been introduced on the logic to resolve the chat completion URL. This PR fixes definitely this with a dedicated `_resolve_chat_completion_url` method. I added a bunch of parametrized tests to check every possible cases. It is now possible to:
- pass a model id as `InferenceClient(model=...)`
- pass a model id as `InferenceClient().chat_completion(model=...)`
- pass a url as `InferenceClient(model=...)`, `InferenceClient(base_url=...)` or `InferenceClient().chat_completion(model=...)`
- the URL can have a trailing `/` or not
- the URL can end …
> Fix resolve chat completion URL

- src/huggingface_hub/commands/lfs.py
- src/huggingface_hub/lfs.py
- src/huggingface_hub/utils/_http.py
- src/huggingface_hub/utils/_lfs.py
- tests/test_lfs.py
Retry mechanism of [`http_backoff`](https://github.com/huggingface/huggingface_hub/blob/3cd32863bdee76e80117ae2d05eeba68045e75e1/src/huggingface_hub/utils/_http.py#L209-L332) doesn't work from [`lfs_upload`](https://github.com/huggingface/huggingface_hub/blob/3cd32863bdee76e80117ae2d05eeba68045e75e1/src/huggingface_hub/lfs.py#L193-L260)->[`_upload_multi_part`](https://github.com/huggingface/huggingface_hub/blob/3cd32863bdee76e80117ae2d05eeba68045e75e1/src/huggingface_hub/lfs.py#L323C5-L355)->[_upload_parts_iteratively](https://github.com/huggingface/huggingface_hub/blob/3cd32863bdee76e80117ae2d05eeba68045e75e1/src/huggingface_hub/lfs.py#L391-L408) path, `data` is consumed after the first attempt when using `SliceFileObj` because `io_obj_initial_pos` should be …
> http_backoff retry with SliceFileObj

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Follow-up after https://github.com/huggingface-internal/moon-landing/pull/11060 and https://github.com/huggingface-internal/moon-landing/pull/11112 (internal links).
This PR adds support for the `gguf` key in `ModelInfo`. Also documenting it as supported in `expand[]=` parameter. Note that it was supported as soon as the server-side change is made, this PR simply makes it better documented.
**Example:**
```py
>>> from huggingface_hub import model_info
>>> model = model_info("MaziyarPanahi/solar-pro-preview-instruct-GGUF", expand="gguf")
>>> model.gguf
{'total': 22140032000, 'architecture': 'llama', 'context_length': 4096, 'quantize_imatrix_file': './solar-pro-preview-instruct-GGUF_imatrix.dat', 'chat_template': "{% if not add_generation_prompt is defined %}{% set add_generation_prompt = …
```
> Add GGUF as supported expand[] parameter

- src/huggingface_hub/_upload_large_folder.py
- src/huggingface_hub/hf_api.py
Should fix https://github.com/huggingface/huggingface_hub/issues/2518 (or at least make it more reasonable).
This PR reduces the number of commits produced for `upload-large-folder` command. The main change is to make the commit size bigger, going from 25 files to either 75 regular files or 150 LFS files. Also, the rules have now been slightly modified to avoid commits with only 1 or 2 files at the beginning of the process.
This should greatly reduce the number of rate limits when using this tool while staying robust.
> Reduce number of commits in upload large folder

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Issue : #2535 
Added the variable in docs also for future reference
Fix https://github.com/huggingface/huggingface_hub/issues/2535.
> Fixed the issue #2535 Added user followers and following in class User and added test cases for it

- src/huggingface_hub/hf_api.py
When a user tries to upload a large folder using `upload_folder`, let's try to nudge them toward using `upload_large_folder` instead. For now the threshold is arbitrary based on number of files (>30 files => log). Let's see in the future if we want to update this threshold based on file sizes as well.
I've also deprecated the experimental feature `create_commits_on_pr` which is now outdated (better to use the official `upload_large_folder`).
> Suggest using upload_large_folder when appropriate

- src/huggingface_hub/inference/_common.py
- tests/test_inference_client.py
Fix https://github.com/huggingface/huggingface_hub/issues/2514 cc @lhoestq @OlivierDehaene 
When  `stream=True` is passed, the server response can be HTTP 200 but still get an error as a stream event. We were already parsing them for `text_generation` task, but not `chat_completion`. This PR fixes this.
Example
```py
client = InferenceClient("microsoft/Phi-3-mini-4k-instruct")
for message in client.chat_completion(
messages=[{"role": "user", "content": "Hello there !"}],
stream=True,
max_tokens=4091,  # values lower or equal to 4090 work
):
print(message.choices[0].delta.content, end="")
```
```
Traceback (most recent call last):
File "/home/wauplin/projects/huggingface_hub/idefi.py", line 6, in <module>
for message in client.chat_completion( …
```
> Raise error if encountered in chat completion SSE stream

- docs/source/en/package_reference/inference_types.md
- docs/source/ko/package_reference/inference_types.md
- src/huggingface_hub/__init__.py
- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- src/huggingface_hub/inference/_generated/types/__init__.py
- src/huggingface_hub/inference/_generated/types/audio_classification.py
- src/huggingface_hub/inference/_generated/types/chat_completion.py
- src/huggingface_hub/inference/_generated/types/image_classification.py
- src/huggingface_hub/inference/_generated/types/image_segmentation.py
- src/huggingface_hub/inference/_generated/types/image_to_image.py
- src/huggingface_hub/inference/_generated/types/object_detection.py
- src/huggingface_hub/inference/_generated/types/summarization.py
- src/huggingface_hub/inference/_generated/types/text_generation.py
- src/huggingface_hub/inference/_generated/types/text_to_image.py
- src/huggingface_hub/inference/_generated/types/text_to_speech.py
- src/huggingface_hub/inference/_generated/types/translation.py
Follow-up PR after https://github.com/huggingface/huggingface.js/pull/915.
Updates chat completion input parameters (tools and `stream_options`) + add supports for VLMs => sending image as text message.
Also adds `TextToSpeech` spec definition but not used at the moment (same specs as `TextToAudio`).
Also added an example in docs:
```py
image_url ="https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg"
client = InferenceClient("mistralai/Mistral-Nemo-Instruct-2407")
output = client.chat.completions.create(
messages=[
{
"role": "user",
"content": [
{
"type": "image_url",
"image_url": {"url": image_url},
},
{
"type": "text",
"text": "Describe this image in one sentence.",
},
],
},
],
) …
```
> Support VLM in chat completion (+some specs updates)

- docs/source/en/guides/repository.md
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/utils/__init__.py
- tests/test_file_download.py
- tests/test_hf_api.py
- tests/test_snapshot_download.py
This PR enhances the `update_repo_settings` method to provide more control over repository settings, and deprecates the `update_repo_visibility` method:
**Key changes:**
* Added a private parameter to set repositories as public or private.
* Made the gated and private parameters optional, allowing updates to either setting independently.
* Added checks to ensure at least one of `gated` or `private` is provided.
* Payload Optimization: `gated` and `private` are only included in the request payload if they have non-None values.
* Updated the docstring for `update_repo_settings` and replaced all references to `update_repo_visibility` in the documentation.
* Added the `@_deprecate_method` decorator to `update_repo_visibility`, marking it for removal in v0.29.x.
> Feature: switch visibility with update_repo_settings #2537

- src/huggingface_hub/hf_api.py
- src/huggingface_hub/repocard_data.py
While working with `Huggingface_hub`, I encountered two undocumented parameters. This PR updates the documentation to include them:
Added the `GGUF` parameter to the `ModelInfo` class.
Added the `pipeline_tag` parameter to the `ModelCardData` class.
> Add missing documentation

- src/huggingface_hub/hf_file_system.py
As reported in #2559, reading from HF Hub datasets can sometimes lead to 500 Internal Server Errors, which even if they're rare, can cause issues on large training runs.
The source of this error is not yet identified, but a simple fix seems to be to add the missing 500 error code to the retry list.
> Add 500 HTTP Error to retry list

- tests/test_hf_api.py
The returned models don't always have a config (if parsing by moon-landing fails). Let's add another filter to fix this. It's just a dummy test so no need to invest too much time.
> Fix CI (failing test)

- src/huggingface_hub/__init__.py
- src/huggingface_hub/file_download.py
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- tests/test_file_download.py
- tests/test_hf_api.py
PR following the [0.25.0 release](https://github.com/huggingface/huggingface_hub/releases/tag/v0.25.0) to prepare for next one.
- bump version to 0.26.0.dev0
- remove `url_to_filename`, `filename_to_url` and `cached_download` functions.
- remove `legacy_cache_layout` argument from `hf_hub_download`.
- remove `cached_download` tests and `legacy_cache_layout` test.
- remove `deprecate_positional_args` from `InferenceClient.__init__` and `AsyncInferenceClient.__init__`, This means enforcing keyword-only arguments for all parameters after `model` is now effective!
> Prepare for release 0.26

- src/huggingface_hub/hf_api.py
~This PR modifies the `model_info` method to ensure that the `SafeTensorsInfo` instance is initialized with a list of dictionaries for the `parameters` attribute, as intended by the class definition.~
This PR changes the type definition of `parameters` attribute in `SafeTensorsInfo` to be a `Dict` instead of `List[Dict[str, int]]`
The model_info response for repo_id = `allenai/Molmo-72B-0924` is of the form:
```
"safetensors": {
"parameters": {
"F32": 73308285952
},
"total": 73308285952
},
```
which is ~not~ expected since `parameters` should be of type ~`List[Dict[str, int]]`~ `Dict[str, int]`
This PR **might** serve as an extension for #2190
> Enforce parameters as a List of Dictionaries in modelinfo.safetensors

- src/huggingface_hub/repocard.py
- src/huggingface_hub/repocard_data.py
- tests/test_repocard.py
This PR ensures the format/ordering of card metadata is preserved on load->save.
Example:
```python
from huggingface_hub import ModelCard
model_card = """---
license: mit
datasets:
- foo
- bar
---
Hello
"""
card = ModelCard(model_card)
card.data.license = "test"
card.content
```
Currently produces:
```
---
datasets:
- foo
- bar
license: test
---
Hello
```
Now:
```
---
license: test
datasets:
- foo
- bar
---
Hello
```
Fixes #2564
> Preserve card metadata format/ordering on load->save

- tests/test_inference_async_client.py
- tests/test_inference_client.py
- tests/test_repository.py
Should fix CI now that bloom model is not served anymore.
> Fix tests listing text generation models

- src/huggingface_hub/_snapshot_download.py
- tests/test_snapshot_download.py
This PR fixes a bug reported internally in this private [slack message](https://huggingface.slack.com/archives/C02V5EA0A95/p1728304375203759).
The issue comes from `huggingface_hub.snapshot_download()` which does not return the folder that already contains the downloaded files if:
- `local_dir` is provided.
-  we are in offline mode, i.e. no internet connection, hub down, or internet connection is deactivated (`local_files_only=True` or `HF_HUB_OFFLINE=True`).
When `local_dir` is provided, we should check if it exists and contains files, as it's expected to have the latest version of the repo replicated there rather than in a snapshot folder.
> Fix snapshot download when `local_dir` is provided.

- src/huggingface_hub/file_download.py
Should fix https://github.com/huggingface/transformers/issues/33897 (cc @sanketsudake).
When trying to download a file that doesn't exist on a remote repo, `huggingface_hub` caches the information locally. Next time the user tries to download this file again, we will raise an error directly instead of attempting to make an HTTP call. This saves a few HTTP calls in `transformers` since the lib is not always aware of which tokenizers files exists on a given repo. This feature exists only when revision is passed with a specific commit_hash.
Since this feature is an optimization, it should be purely optional. That's why we have a try/catch around the `file.touch()` call to store non-existence of a given file. In https://github.com/huggingface/transformers/issues/33897, @sanketsudake reported …
> Fix PermissionError while creating '.no_exist/' directory in cache

- tests/test_repository.py
This test is flaky which is annoying for the CI. Since it's only testing an internal method of a legacy class (`Repository().git_push(blocking=False)._process.kill()`), I think it's more than ok to skip the test. We are testing how `Process` works more than anything.
> Skip flaky Repository test

- src/huggingface_hub/__init__.py
- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Fixes #2553 
This PR introduces `list_papers` using the [Daily Papers API](https://huggingface.co/docs/hub/en/api#get-apidailypapers), `search_papers` using the `papers/search` endpoint and `get_paper` using `papers/{paper_id}` endpoint.
We add `DailyPaper` dataclass, containing `Paper` and associated metadata.
`Paper` dataclass containing metadata about the paper itself.
`PaperAuthor` dataclass containing metadata about the paper's author.
`PaperAuthor`'s `user` and `DailyPaper`'s `submitted_by` use existing `User` dataclass, although these contain fewer fields than `User` itself so could have their own dataclasses.
We add `list_papers` to `HfApi` which accepts `date` as `str`, `YYYY-MM-DD` is the expected format, this could also accept datetime as a parameter. The endpoint itself also …
> Daily Papers API

- src/huggingface_hub/_login.py
- src/huggingface_hub/commands/user.py
- src/huggingface_hub/utils/_auth.py
This is a small PR to use proper logging in the authentication module.
- replacing print statements by proper logging with the level that reflects the severity of the messages.
- replacing some `warnings.warn()` by `logger.warning()` following logging best practices : [Python Logging HOWTO](https://docs.python.org/3/howto/logging.html)
- setting verbosity level to INFO for authentication commands.
> Use proper logging in auth module

- .github/workflows/build_pr_documentation.yaml
- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_common.py
- src/huggingface_hub/inference/_generated/_async_client.py
- tests/test_inference_client.py
This PR  is a first attempt to factorize the payload build in multiple `InferenceClient` methods. In fact, there's some repetitive logic across several methods for handling inputs and parameters, so here we introduce a new (private) helper function to factorize this logic.
1. Adding a helper function that:
- handles both raw content (images or audio) and string/dict inputs uniformly.
- base64 encodes raw content when at least one parameter is present.
- filters out None values from the parameters.
- .. and returns an `_InferenceInputs` object containing the json payload and raw data if any. (I don't have a strong opinion on this, we can also return a Tuple instead).
2. A unit test to verify the correct behavior of the refactored logic.
⚠️ These changes only affect the internal/private …
> [Inference Client] Factorize inference payload build

- setup.py
- src/huggingface_hub/hub_mixin.py
Fix https://github.com/huggingface/huggingface_hub/issues/2609.
It's not the first time I see this so let's fix it. It's not really an error, just some IDEs that might yell because of how the import is made.
`packaging` is a package [installed by default](https://github.com/huggingface/huggingface_hub/blob/9bb6bd680d507223fef6e40c99ef087086194b58/setup.py#L17) with `huggingface_hub`.
> Fix 2609 - Import packaging by default

- src/huggingface_hub/commands/user.py
When I logged-in with huggingface-cli command in basic ubuntu 20.04 docker image which uses python 3.8, below error occurred.
- command
```
Huggingface-cli login
huggingface-cli login --token hf_xxxx
```
- error log
```
Traceback (most recent call last):
File "/usr/local/bin/huggingface-cli", line 5, in <module>
from huggingface_hub.commands.huggingface_cli import main
File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/commands/huggingface_cli.py", line 26, in <module>
from huggingface_hub.commands.user import UserCommands
File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/commands/user.py", line 165, in <module>
class AuthSwitchCommand(BaseUserCommand):
File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/commands/user.py", line 203, in AuthSwitchCommand
def …
```
> bugfix huggingface-cli command execution in python3.8

- i18n/README_cn.md
This PR fixes the formatting of documentation and source code links in the README.
Current issue:
The links are enclosed in backticks, which causes them to be displayed as code instead of clickable links.
Changes made:
- Removed backticks surrounding the documentation and source code links
- Kept the HTML <a> tags to maintain the "target="_blank" functionality
Reason for change:
This formatting error affects the usability of the README, as users cannot directly click on the links. The fix improves navigation and overall user experience when viewing the project's GitHub page.
Related files:
- README.md
> Fix documentation link formatting in README_cn

- src/huggingface_hub/repocard_data.py
- tests/test_repocard_data.py
More details in https://github.com/huggingface/datasets/issues/7243#issuecomment-2427121987 and especially https://github.com/huggingface/datasets/issues/7243#issuecomment-2429286597.
When serializing repo cards metadata, we are currently removing any none values from any dictionary, set, list or tuple. This is done since the module has been introduced in https://github.com/huggingface/huggingface_hub/pull/940 and never caused problems until https://github.com/huggingface/datasets/issues/7243 was reported. I do find automatically removing None values inside values to be pretty clunky as it is values set by the user and not default ones.
This PR updates this behavior to remove only top-level None values, i.e. values that are None by default and that therefore shouldn't be serialized (as …
> Do not remove None values in RepoCardData serialization

- src/huggingface_hub/_local_folder.py
- tests/test_local_folder.py
Fix https://github.com/huggingface/huggingface_hub/issues/2607.
See https://github.com/huggingface/huggingface_hub/issues/2607#issuecomment-2416255310 for explanations.
In the end I went for the solution to remove `@lru_cache` usage. This leads to more IO disk calls but less code complexity. Hopefully the extra cost is likely to be negligible.
> Fix download local dir edge case (remove lru_cache)

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
As reported by @CISC in https://github.com/gradio-app/gradio/issues/9820#issuecomment-2432961165, using `get_token_permission` with an OAuth token is broken:
```py
...
File "/home/user/app/app.py", line 985, in template_data_from_model_files
if info and oauth_token and hfapi.get_token_permission(oauth_token.token) == "write":
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 1691, in get_token_permission
return self.whoami(token=token)["auth"]["accessToken"]["role"]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'accessToken'
```
This is because the whoami response for an OAuth token doesn't contain the detailed permission for that token.
This PR fixes `get_token_permission` to not raise an error when a …
> Fix and deprecate get_token_permission

- src/huggingface_hub/repocard_data.py
Fixes #2642.
Small PR to update `ModelCardData.datasets` type from `Optional[List[str]]` to `Optional[Union[str, List[str]]]` to match server-side `ModelMetadata.datasets` type (see [here](https://github.com/huggingface-internal/moon-landing/blob/e808c999f25e584caf8d013e9defcd336beafc73/server/lib/ModelMetadata.ts#L169)).
> Fix `ModelCardData`'s datasets typing

- docs/source/en/guides/hf_file_system.md
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/hf_file_system.py
- tests/test_hf_file_system.py
Fixes #2552.
This PR fixes a bug where `HfFileSystem.exists()` returns `True` even after the repository has been deleted. The issue arises because the cache is not properly invalidated when the repository is deleted, causing `HfFileSystem` to rely on stale cache data. The fix updates the `HfFileSystem.invalidate_cache()` method to clear the repository 'existence' cache when the provided path matches the repository root.
This PR also includes an update to `HfFileSystem` documentation.
- Update `HfFileSystem.invalidate_cache()` to clear repository cache.
- Update `HfFileSystem` documentation to suggest using `HFApi` methods when possible.
- Add docstrings to `HfFileSystem`'s methods.
- Make `HfApi` class docstring visible in package reference by moving it from `__init__` to class level.
> Fix `HfFileSystem.exists()` for deleted repos and update documentation

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
fixes #2652.
tiny PR to fix incorrect default value of `max_tokens` and `max_new_tokens` in `InferenceClient.text_generation()` and `InferenceClient.chat_completion()` docstrings, reflecting the default values in [text-generation-inference/lib.rs](https://github.com/huggingface/text-generation-inference/blob/main/router/src/lib.rs). 
The default value in `InferenceClient.chat_completion()` was incorrectly documented as 20 instead of 100. The `max_new_tokens` parameter default value was also added in `InferenceClient.text_generation()` docstring, given that it's an important generation parameter.
> [InferenceClient] Update `max_tokens` and `max_new_tokens` default value in docstring

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
This PR fixes a bug reported in an internal [slack message](https://huggingface.slack.com/archives/C02V5EA0A95/p1730735733880359) where the `created_at` field in `ModelInfo` does not work as a valid sort parameter for listing models via the api. the correct parameter should be `createdAt` rather than `created_at`. The same issue applies to the `trending_score` field. 
I’ve restricted the list of possible sort values in the docstring to match those defined on the API side, as seen [here](https://github.com/huggingface-internal/moon-landing/blob/main/server/lib/SearchBuilder.ts) (private link). also, I'm not sure if the sorting feature is widely used, but I've added some tests just in case!
> [HfApi] Fix sorting properties in `list_models()`, `list_datasets()` and `list_spaces()`

- src/huggingface_hub/serialization/_torch.py
- tests/test_serialization.py
This small PR adds `is_main_process` parameter to `save_torch_state_dict()` to prevent race conditions during distributed environment. This aligns with accelerate's, transformers' and diffusers' implementations and will enable standardization of model saving across these libraries. See #2314 and this [internal slack message](https://huggingface.slack.com/archives/C01Q6JPP6NA/p1730370857167919) for more context.
Once this is released in huggingface_hub==0.27.0, PRs will be opened to update accelerate's [save_model()](https://github.com/huggingface/accelerate/blob/b0e5fd353c884d443aacffa18328971db9dd728a/src/accelerate/accelerator.py#L2814), transformers' [save_pretrained()](https://github.com/huggingface/transformers/blob/b5919e12f74190a5f50a47f07cb708ceb029244d/src/transformers/modeling_ut …
> [Serialization] Add `is_main_process` argument to `save_torch_state_dict()`

- src/huggingface_hub/hf_api.py
update attribute used in `delete_collection_item` docstring
> update attribute used in delete_collection_item docstring

- .github/workflows/model_card_consistency_reminder.yml
The line:
```
- [src/.../datasetcard_template.md](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/templates/modelcard_template.md)
```
should link to `.../datasetcard_template.md`.
> Bug in model_card_consistency_reminder.yml

- src/huggingface_hub/utils/_cache_manager.py
> Fix the error caused by reading `.DS_Store` when running the `scan-cache` command.

- src/huggingface_hub/_snapshot_download.py
Updating snapshot_download so that it doesn't re-write the commit hash *every* single time. 
This has been incredibly problematic if we're keeping a repo saved to disk, and snapshot_download can't write to that disk.
This should at least partially resolve the issue.
> Don't write the ref file unless necessary

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
This PR fixes `InferenceClient.zero_shot_image_classification` to accept `candidate_labels` as a parameter rather than an input. See this [internal slack message](https://huggingface.slack.com/archives/C069KSP486B/p1731923978189269) for more context.
> [Inference Client] fix `zero_shot_image_classification`'s parameters

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- tests/test_inference_client.py
- utils/check_task_parameters.py
This PR does two things:
- fixes a bug in the parameter docstring formatting when it's not an optional one, see [this comment](https://github.com/huggingface/huggingface_hub/pull/2664/files#r1847893906) for more context. 
- deprecates `labels` parameter in `InferenceClient.zero_shot_classification` and `InferenceClient.zero_shot_image_classification` in favor of `candidate_labels`. 
This PR should be merged before #2664.
> [Inference Client] fix param docstring and deprecate `labels` param in zero-shot classification tasks

- README.md
- i18n/README_cn.md
- i18n/README_de.md
- i18n/README_hi.md
- i18n/README_ko.md
Tiny PR to fix the logo when dark mode is on. A dark mode compatible logo has been added in https://huggingface.co/datasets/huggingface/documentation-images/blob/main/huggingface_hub-dark.svg 
before:
now:
> Fix logo in README when dark mode is on 

- src/huggingface_hub/inference/_generated/_async_client.py
- utils/generate_async_inference_client.py
Fix https://github.com/huggingface/huggingface_hub/issues/2672 (cc @james-deee)
> Use asyncio.sleep in AsyncInferenceClient (not time.sleep)

- src/huggingface_hub/_commit_scheduler.py
- tests/test_commit_scheduler.py
I realized that having a context manager for the `CommitScheduler` makes a lot of sense while reviewing https://github.com/AnswerDotAI/fastdata/pull/9. It's a quick win, so let's do it. Benefit is to guarantee everything is committed correctly.
cc @AndreaFrancis the solution implemented in the PR is still correct, no need to change anything. This PR is more for convenience next time we want to integrate it.
> Support context mananger in commit scheduler

- src/huggingface_hub/_commit_scheduler.py
- src/huggingface_hub/_tensorboard_logger.py
- src/huggingface_hub/_upload_large_folder.py
- src/huggingface_hub/fastai_utils.py
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/hub_mixin.py
- src/huggingface_hub/keras_mixin.py
- tests/test_hf_api.py
- tests/testing_constants.py
see slack [thread](https://huggingface.slack.com/archives/C02EMARJ65P/p1732513068709469) (private)
Enterprise Hub allows organizations to force all repositories to be private. Since `create_repo` assumes that a repo is public when `private=True` is not explicitly passed, an error is thrown by the server 
```
403 Forbidden: org-name forbids the creation of public models.
``` 
This is because `private: False` is passed by default (since https://github.com/huggingface/huggingface_hub/pull/1001 :confused:). This PR updates this by making `None` the default value for `private` and send the value to the server only when explicitly set by the user. This should make the life of Enterprise Hub users much easier (today they need to explicitly pass `private=True` in their calls).
Note: tests are …
> Make sure create_repo respect organization privacy settings

- src/huggingface_hub/utils/_datetime.py
- tests/test_utils_datetime.py
fixes #2671.
See the original [slack thread](https://huggingface.slack.com/archives/C03E4DQ9LAJ/p1729806188701489) (internal) for more context.
The client expects timestamps to follow the pattern `%Y-%m-%dT%H:%M:%S.%fZ`, but the server was inconsistently returning timestamps without milliseconds when they were zero (e.g. "2024-11-20T20:01:58Z"). This causes the parsing error reported in the issue mentioned above. 
we're handling this client-side as it's intentional behavior in the API to reduce precision, see[ this comment](https://github.com/huggingface-internal/workloads/pull/2524#discussion_r1860758864) (private).
this is fixed by a small refactoring of `parse_datetime()` function and adding a normalization to ensure it has six digits of microseconds by padding with zeros or …
> Fix timestamp parsing to always include milliseconds

- docs/source/en/package_reference/inference_types.md
- docs/source/ko/package_reference/inference_types.md
- src/huggingface_hub/__init__.py
- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- src/huggingface_hub/inference/_generated/types/__init__.py
- src/huggingface_hub/inference/_generated/types/chat_completion.py
- utils/check_task_parameters.py
This PR updates `InferenceClient.chat_completion()` to match the latest (TGI) changes (see: [huggingface.js#1030](https://github.com/huggingface/huggingface.js/pull/1030)). This is done manually rather than with `utils/check_task_parameters.py` script because chat completion specs are listed in a [ChatCompletionInput](https://github.com/huggingface/huggingface_hub/blob/d0a948fc2a32ed6e557042a95ef3e4af97ec4a7c/src/huggingface_hub/inference/_generated/types/chat_completion.py#L81) dataclass, unlike other tasks that use a *Parameters dataclass to list the task parameters. 
IMO it's better to handle `InferenceClient.chat_completion()` updates manually to ensure maximum reliability and avoid adding special cases to the `utils/check_task_parameters.py` script which is already quite clunky. …
> [InferenceClient] Manually updating `chat_completion()`'s params types

- src/huggingface_hub/hub_mixin.py
- tests/test_hub_mixin.py
Fix https://github.com/huggingface/huggingface_hub/issues/2694.
Issue comes from a bad type annotation in `__new__`. Best to use type alias there (as done in other parts of the module already).
Added a quick test using `jedi` (an autocomplete tool we already use in some tests).
> Fix autocompletion not working with ModelHubMixin

- src/huggingface_hub/serialization/_torch.py
- tests/test_serialization.py
Related to [transformers#35080](https://github.com/huggingface/transformers/issues/35080).
Currently, when saving a torch state dict with shared tensors, the key to keep is chosen alphabetically which might not be the desired behavior. This PR simply adds an optional `state_dict_keys_to_discard` argument to both `save_torch_state_dict()` and `save_torch_model()` that allows users to specify which keys should be discarded in priority when duplicates are found.
_Note_ : The logic behind choosing which key should be discarded in priority is framework/model-specific and should be handled by the user. For example, for `transformers.PreTrainedModel` models, this is specified in the `_tied_weights_keys` attribute, example usage:
```python
model = ... # A model inheriting from PreTrainedModel …
```
> [Serialization] add argument to pass shared tensors names to drop when saving

- tests/test_hf_api.py
https://huggingface.co/spaces/open-llm-leaderboard/open_llm_leaderboard#/ is not linked to models/datasets on the Hub anymore (most likely due to recent update) cc @clefourrier 
We were using it in our tests so it broke. Replaced it with https://huggingface.co/spaces/stabilityai/stable-diffusion .
> Fix test_list_spaces_linked

- src/huggingface_hub/serialization/_torch.py
This PR fixes some failing tests in transformers when using the hfh loading helpers introduced in #2687.
See: https://app.circleci.com/pipelines/github/huggingface/transformers/113474/workflows/1a1ecbcd-26dc-4d3e-872d-79e5aedf04f2/jobs/1516443/tests#failed-test-1
- in `test_model_from_pretrained_from_mlx` : mlx weights should be loaded as `pt` according to this comment : https://github.com/huggingface/transformers/blob/3d213b57fe74302e5902d68ed9478c3ad1aaa713/src/transformers/modeling_utils.py#L3966
- in `test_resume_training_with_safe_checkpoint` : The UnboundLocalError occurred because in the context manager _load_shard_into_memory, the finally block tried to delete state_dict before it was created due to probably an exception in the try block. Instead of fixing this directly in the …
> [Serialization] Fix: remove context manager when loading shards + handle `mlx` weights

- src/huggingface_hub/inference/_generated/types/automatic_speech_recognition.py
- src/huggingface_hub/inference/_generated/types/image_to_text.py
- src/huggingface_hub/inference/_generated/types/text_to_audio.py
- src/huggingface_hub/inference/_generated/types/text_to_speech.py
Following up on the failing test in transformers related to Hub spec compliance for pipelines (see the related test [here](https://github.com/huggingface/transformers/blob/66531a1ec3e2aafe7ffb23a9ca715cfb67b9fea0/tests/test_pipeline_mixin.py#L932)). The test failure occurs because there's a mismatch between `generate_kwargs` (current name in transformers) and `generation_parameters` (name in huggingface.js specs).
For now, we'll maintain the use of `generate_kwargs` since the renaming hasn't been implemented in transformers. This is purely a naming convention issue, and we'll update it to `generation_parameters` when we do the full rename in `transformers`.
Note that in huggingface.js, this field was originally named `generate` (not `generate_kwargs`). It was later renamed to …
> [InferenceClient] Keep `generate_kwargs` instead of `generation_parameters`

- src/huggingface_hub/hf_api.py
Replace "model repo" with "repo" in docstrings.
> Replace model repo with repo in docstrings

- src/huggingface_hub/hf_api.py
Fixes the failing tests.
following [moon-landing#11757](https://github.com/huggingface-internal/moon-landing/pull/11757) and [moon-landing#12004](https://github.com/huggingface-internal/moon-landing/pull/12004) (private links) which add new repositories properties: `usedStorage` and `resourceGroup`, this PR aligns the list of the different repo types (`models`, `datasets` and `spaces`) properties and update the docstrings accordingly.
> [HfApi] update list of repository properties following server side updates

- src/huggingface_hub/constants.py
- src/huggingface_hub/utils/_http.py
The issue was triggered when user added a **tail slash '/'** in `HF_ENDPOINT`, like `$set HF_ENDPOINT=https://hf-mirror.com/`. 
Then it's interesting (stupid?) to visit a link like - [https://hf-mirror.com//api/models/sentence-transformers/all-MiniLM-L6-v2/revision/main](https://hf-mirror.com/api/models/sentence-transformers/all-MiniLM-L6-v2/revision/main) by huggingface.
Okay then you got 404 and don't know why. Bad experience and you should take care of them in the code with urljoin and carefully strip.
> [BUG] Fix 404 NOT FOUND issue caused by endpoint tail slash

- src/huggingface_hub/hub_mixin.py
- tests/test_hub_mixin.py
Proposed fix for #2727
`typing.get_type_hints` tries to resolve the type of an object at runtime. This means that the `global` and `local` namespaces this function uses won't have access to whatever has been defined only for static type checkers (typically using `typing.TYPE_CHECKING`).
In this case, `DataclassInstance` is only defined in such a way.
This proposes to add a default fallback definition of `DataclassInstance` for runtime type checking.
> Fix `typing.get_type_hints` call on a `ModelHubMixin`

- src/huggingface_hub/hf_api.py
closes #2731.
`HfApi.get_safetensors_metadata()` does not take `filename` as a parameter but it still appears in the method's docstring. This PR fixes the docstring accordingly.
> [HfApi] Remove unused parameter from method's docstring

- setup.py
- src/huggingface_hub/_commit_api.py
- src/huggingface_hub/commands/scan_cache.py
- src/huggingface_hub/file_download.py
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/serialization/_base.py
- src/huggingface_hub/serialization/_torch.py
- src/huggingface_hub/utils/logging.py
- tests/test_cache_layout.py
- tests/test_utils_cache.py
- tests/testing_utils.py
Ruff 0.9.0 introduced a new "2025 style guide" formatter that changes how code is formatted (see release notes [here](https://github.com/astral-sh/ruff/releases/tag/0.9.0)). 
This PR runs ruff formatter to comply with the new formatting standards. I'd rather comply to this new (maintained) stable style rather than pinning ruff version.
> Migrate to new Ruff "2025 style guide" formatter

- src/huggingface_hub/__init__.py
- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
This PR removes the support for the `like` endpoint which is being removed server-side. `unlike` is kept for the same reason mentioned in [moon-landing#12147](https://github.com/huggingface-internal/moon-landing/pull/12147) (private link).
Given the low usage of this endpoint, there is no need for a full deprecation cycle. This will be included in the next `huggingface_hub` release.
> [HfApi] remove `like` endpoint

- src/huggingface_hub/_local_folder.py
- src/huggingface_hub/utils/_fixes.py
- tests/test_local_folder.py
- tests/test_utils_fixes.py
- utils/check_contrib_list.py
Should definitely fix https://github.com/huggingface/huggingface_hub/issues/2399#issuecomment-2560250580 cc @jeffliu-LL
Now when creating a new local folder, we only wait 0.1s to write the .gitignore file. Worse case scenario, the gitignore file is not written for some obscure reason -but that's really not a critical problem-. For context, this logic should be called only one time at folder creation and that's it (happening a few times in parallel in case of snapshot_download hence the concurrent issues).
I also added tests to ensure everything works as expected.
> Add timeout to WeakFileLock

- tests/test_hf_api.py
this PR removes org tokens related test cases that are no longer relevant. This should fix some of the failing tests in the CI.
> Remove org tokens related tests

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Related to https://github.com/huggingface/hub-docs/pull/1575
> Add optional rejection_reason when rejecting a user access token

- src/huggingface_hub/hf_api.py
https://github.com/huggingface/hub-docs/pull/1581#discussion_r1920657746
> rejection reason docstring

- src/huggingface_hub/repocard_data.py
- tests/test_repocard_data.py
fixes #2769 
Fix inconsistent behavior in `CardData.get()` where `get(key, default_value)` returns `None` even when a default is provided. 
The fix makes `get()` handle `None` values consistently with `to_dict()` behavior by returning the default value both when the key doesn't exist AND when its value is `None`:
```python
card = CardData()
card.key = None
card.to_dict()  # Returns {} - None values are filtered out
card.to_dict().get("key", "default")  # Returns "default" because key doesn't exist
```
So with the fix in this PR, `card.get("key", "default")` will return "default".
> Fix`CardData.get()` to respect default values when `None`

- src/huggingface_hub/repocard.py
- tests/test_repocard.py
Fix https://github.com/huggingface/huggingface_hub/issues/2768.
Simply replace `repo_id_or_path.exists()` by `repo_id_or_path.is_file()`.
> Fix `RepoCard.load` when passing a `repo_id` that is also a dir path

- tests/test_repocard.py
This should fix the test introduced in #2771 on Windows Python 3.8.
> Fix `RepoCard` test on Windows

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_common.py
- src/huggingface_hub/inference/_generated/_async_client.py
- src/huggingface_hub/inference/_generated/types/text_to_video.py
- src/huggingface_hub/inference/_providers/__init__.py
- src/huggingface_hub/inference/_providers/fal_ai.py
- src/huggingface_hub/inference/_providers/replicate.py
- src/huggingface_hub/inference/_providers/together.py
- tests/test_inference_providers.py
Resolve #2784 
This PR:
- Adds `text-to-video` task. (no tests yet for this task 😄).
- Update supported models for providers based on [huggingface.js/inference/providers](https://github.com/huggingface/huggingface.js/tree/main/packages/inference/src/providers) : The API is compatible with each model. ✅ 
- Remove TGI-specific limitations from `chat_completion` docstring. Also updated `text_generation` docstring.
> [InferenceClient] Add `text-to-video` task and update supported tasks and models 

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- src/huggingface_hub/inference/_providers/__init__.py
Small PR to get correct autocompletion
> Add type hints for providers

- src/huggingface_hub/_local_folder.py
- tests/test_local_folder.py
Fix https://github.com/huggingface/huggingface_hub/issues/2756 cc @adamkarvonen
Using hashlib.md5 on filename to avoid collisions. If two files in the same repo are identical, we will still download them twice as their .incomplete file paths are different. It was already the case without the PR. I don't think we should optimize for this use case.
> Fix filename too long when downloading to local folder

- src/huggingface_hub/inference/_providers/fal_ai.py
- src/huggingface_hub/inference/_providers/replicate.py
- src/huggingface_hub/inference/_providers/sambanova.py
- src/huggingface_hub/inference/_providers/together.py
- src/huggingface_hub/utils/_http.py
Few things:
- Update Meta Llama 3 8B (together). See https://github.com/huggingface/huggingface.js/pull/1145
- in `hf_raise_for_status` => convert to string to avoid parsing issues. We could parse dicts in better ways but not worth it (format can vary depending on provider)
- if `api_token` not passed in provider, use the HF one
cc @pcuenca
> Fix few things (inference providers)

- .github/workflows/python-prerelease.yml
Goal is to automatically trigger CI jobs for prerelease candidates on other major libraries: transformers, datasets, diffusers, etc. 
Example created from this PR: https://github.com/huggingface/transformers/compare/main...ci-test-huggingface-hub-v0.27.0rc1.
CI run: https://github.com/huggingface/huggingface_hub/actions/runs/13009228602/job/36282963731?pr=2792
> Automate release candidate testing

- docs/source/en/guides/cli.md
reported by @BramVanroy in this slack [message](https://huggingface.slack.com/archives/C039P47V1L5/p1738070885457699) (private).
> [Docs] Fix broken link in CLI guide documentation

- docs/source/cn/guides/repository.md
- docs/source/de/guides/repository.md
- docs/source/en/guides/repository.md
- docs/source/ko/guides/repository.md
- src/huggingface_hub/README.md
- src/huggingface_hub/__init__.py
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- tests/test_file_download.py
- tests/test_hf_api.py
- tests/test_snapshot_download.py
Follow-up after https://github.com/huggingface/huggingface_hub/releases/tag/v0.28.0
`update_repo_visibility` was supposed to be removed but I post-poned the complete removal as it is still documented in hub-docs and used in transformers tests (:shrug:)
> Prepare for 0.29.0

- src/huggingface_hub/constants.py
Revert the use of `urljoin` to join `HF_ENDPOINT` and path. 
fixes #2806
> fix(#2806): revert use of urljoin for HF_ENDPOINT paths

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- tests/test_inference_client.py
Fix https://github.com/huggingface/huggingface_hub/issues/2804.
`base_url` was first introduced to match OpenAI chat completion API. It has the exact same behavior as `self.model` when using `client.chat_completion`. However, since it's a public parameter also for other tasks, I do think it makes sense to use it if provided. The problem in https://github.com/huggingface/huggingface_hub/issues/2804 was that user provided a URL as `base_url` and expected it to be used in `text_generation` (which seems fair) but wasn't. Therefore it defaults to Inference API with default model which in not intended. This small PR should prevent this. 
---
Not related at all but I took the opportunity to rephrase a bit the error raised in case of a 422 unprocessable entity. Usually the response body provides …
> Default to `base_url` if provided

- tests/test_cache_no_symlinks.py
- tests/test_file_download.py
- tests/test_utils_cache.py
Looks like we are sending the staging token to production quite often in our tests. Wasn't a problem until recently but now invalid tokens are unauthorized even when trying to access a public repo. Let's make sure we don't do this anymore.
(still some tests to fix)
**EDIT:** all good
> Do not send staging token to production

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- src/huggingface_hub/inference/_providers/__init__.py
- src/huggingface_hub/inference/_providers/fal_ai.py
Similar to https://github.com/huggingface/huggingface.js/pull/1148.
Will keep it as draft for now. I mostly wanted to see how that integration would work given that it doesn't use the same parameters as we have for `text_to_speech` (has an extra `"genres"` parameters). For now I added it to the signature + docstring but it's not compliant with https://github.com/huggingface/huggingface.js/blob/main/packages/tasks/src/tasks/text-to-speech/spec/input.json. 
Another possibility is to add a `text-to-audio` or `text-to-music` but that seems premature given it's a single model, single provider and still experimental. Will have to wait more example before an harmonization.  
**Working code example:**
```py
import os
lyrics = """
[verse]
In the town …
```
> Add YuE (music gen) from fal.ai

- .github/ISSUE_TEMPLATE/bug-report.yml
- docs/source/en/package_reference/environment_variables.md
- src/huggingface_hub/constants.py
- src/huggingface_hub/utils/_http.py
- src/huggingface_hub/utils/logging.py
I got bored of putting breakpoints to understand which requests have been sent :grimacing: :rage: 
What this PR does:
- adds a new `HF_DEBUG` environment variable
- when `HF_DEBUG=1`, `huggingface_hub` logger is set to debug level
- when `HF_DEBUG=1`,  all requests made by the lib are logged as curl commands
- update package reference + bug report template
**Example:**
```py
client = InferenceClient(model="black-forest-labs/FLUX.1-dev", provider="fal-ai")
image = client.text_to_image("An astronaut riding a unicorn in space.")
image.save("astronaut_unicorn.png")
```
```sh
➜  HF_DEBUG=1 python script.py
Calling fal.ai provider through Hugging Face proxy.
Send: curl -X POST -H 'Accept: image/png' -H 'Accept-Encoding: gzip, deflate, br' -H …
```
> Add `HF_DEBUG` environment variable for debugging/reproducibility

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- utils/check_task_parameters.py
Originally suggested by @julien-c [here](https://github.com/huggingface/huggingface_hub/pull/2812#pullrequestreview-2587806170). This way we maintain consistency with OpenAI's python sdk. I took the opportunity to add this argument to chat_completion as well.
> [InferenceClient] Renaming `extra_parameters` to `extra_body` 

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- src/huggingface_hub/inference/_generated/types/automatic_speech_recognition.py
should fix https://github.com/huggingface/huggingface_hub/issues/2706#issuecomment-2631115722 and it should work correctly with fal as well, since the timestamp chunks is returned in `timestamp` instead of `timestamps` (see [here](https://fal.ai/models/fal-ai/whisper/api#type-WhisperChunk)).
cc @kiansierra
> [InferenceClient] Fix `automatic-speech-recognition` output parsing and add `extra_body` as an argument

- .github/workflows/python-prerelease.yml
To be tested next time we make a release :) (should work out of the box, right? :smile:)
> Add datasets and diffusers to prerelease tests

- tests/test_hf_api.py
- tests/testing_utils.py
This PR fixes the CI. Currently `test_dataset_info` tries to read info from https://huggingface.co/datasets/lhoestq/test which doesn't exist anymore. I've replaced it with https://huggingface.co/datasets/gaia-benchmark/GAIA which should be future-proof :) 
Fun fact: this test has been added 4 years ago :smile: https://github.com/huggingface/huggingface_hub/pull/164
> Fix test_dataset_info (missing dummy dataset)

- tests/test_hf_api.py
Let's skip the tests while the API is being refactored.
Related to server-side updated (https://github.com/huggingface-internal/moon-landing/pull/12485, private link) and https://github.com/huggingface/huggingface.js/pull/1198
> Skip list_models(inference=...) tests in CI

- src/huggingface_hub/utils/_typing.py
- tests/test_utils_typing.py
Fix https://github.com/huggingface/huggingface_hub/issues/2856 cc @not-lain
> Fix `is_jsonable` if integer key in dict

- src/huggingface_hub/inference/_providers/hf_inference.py
- tests/cassettes/TestInferenceClient.test_sentence_similarity[hf-inference,sentence-similarity].yaml
- tests/cassettes/test_async_sentence_similarity.yaml
Related to https://github.com/huggingface/huggingface_hub/pull/2851 and https://github.com/huggingface/huggingface.js/pull/1201.
There was a little misunderstanding on what we were trying to achieve :smile:
> Partial revert #2851: allow task override on sentence-similarity

- .github/workflows/python-prerelease.yml
Took me some time to debug this yesterday but we now have a working workflow file (hence the v0.29.0 **.rc7** 
:see_no_evil:  :grimacing:). The goal of the `python-prerelease.yml` is to trigger CIs on datasets/diffusers/transformers repos when a prerelease is made on PyPI. This saves us some manual work when making a release.
Changes made:
- before pushing to external repos, we need to make sure the prerelease is available on PyPI
- fixed some char escape in sed commands
- all `uv pip install` commands in workflows file of external repos must be updated to allow prereleases (with `--prerelease=allow`)
Note that this is still failing for `datasets` due to permission issues. See https://github.com/huggingface/huggingface_hub/actions/runs/13395895366/job/37414702549: 
```
To …
```
> Fix prerelease CI

- src/huggingface_hub/_upload_large_folder.py
When using following code to upload folders:
```python
from huggingface_hub import HfApi
api = HfApi()
api.upload_large_folder(
repo_id="amphion/Emilia-Dataset",
repo_type="dataset",
folder_path="/mnt/yodas",
revision="refs/pr/10"
)
```
We got errors like "Failed to get upload mode: 404 Client Error: Not Found for url: https://huggingface.co/api/datasets/amphion/Emilia-Dataset/preupload/refs/pr/10 (Request ID: xxx)"
But the revision is already created manually and accessible via https://huggingface.co/datasets/amphion/Emilia-Dataset/tree/refs%2Fpr%2F10.
Here we note that the revision is URL-encoded in the link above (`refs%2Fpr%2F10`), but not encoded in the error message (`refs/pr/10`). By adding a `urllib.parse.quote` function solve this problem.
Besides, I've check other function calls …
> Fix revision bug in _upload_large_folder.py

- src/huggingface_hub/__init__.py
- src/huggingface_hub/_webhooks_server.py
- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
Follow-up PR after https://github.com/huggingface/huggingface_hub/releases/tag/v0.29.0
Breaking change in `InferenceClient`:  `labels` has been removed from `zero_shot_classification` and `zero_shot_image_classification` tasks in favor of `candidate_labels`. There has been a proper deprecation warning for that.
I've also updated `_webhooks_server.py` to make type annotation work with latest gradio version (an url that could be None in theory but cannot in practice => let's still explicitly raise if that ever happen). Webhook server is an experimental feature anyway.
> Prepare for 0.30

- docs/source/en/guides/model-cards.md
This Space linked to here isn't maintained AFAIK, and seems to not work reliably currently. Maybe better to remove the link for now? cc @Wauplin @julien-c
> Remove link to unmaintained model card app Space

- .github/workflows/style-bot-action.yml
small fix: wrapping the style command in `bash -c` which ensures that the shell properly interprets the && operator in the command string.
> Small fix in style bot GH action

- src/huggingface_hub/hf_api.py
Following https://github.com/huggingface-internal/moon-landing/pull/12735 (private), this PR adds `xetEnabled` as an expand property. This will be quite really useful in #2887 and #2893.
> add `xetEnabled` as an expand property

- src/huggingface_hub/inference/_providers/hf_inference.py
- tests/test_inference_providers.py
Fixes #2908 
a bug was introduced in #2836 where the payload model was set to "tgi" if the model ID is a URL, regardless of the model name passed in parameters. This causes issues with vLLM endpoints (as reported in #2908) which require the actual model name to be passed.
Note that "tgi" was previously used as a default value since the payload model is required in TGI's API but not actually used. `InferenceClient`/`AsyncInferenceClient` are compatible to other frameworks like vLLM, so let's fallback to "dummy" instead of "tgi" to avoid any confusion.
cc @Spycsh
> Fix payload model name when model id is a URL

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
This PR updates `update_repo_settings` to add the ability to enable or disable xet storage.
**Note**: No test has been added for now as xet storage is not properly integrated into the staging environment (https://hub-ci.huggingface.co/) and  we cannot test in production for an obvious reason: the CI would need to be the owner of the repo to be able to update this setting.
A proper test will be added once the staging environment supports xet storage. 
cc @bpronan
> Add ability to enable/disable xet storage on a repo

- src/huggingface_hub/utils/_http.py
This PR fixes a bug I ran into with `_curlify`: when the body request contains a `BytesIO` object, `_curlify()` attempts to get the length of this object, and obviously it fails because it doesn't have a __len__ method and we don't handle the case when the body contains file-like objects.
> Handle file-like and IO objects in `_curlify()`

- docs/source/en/guides/inference_endpoints.md
- src/huggingface_hub/__init__.py
- src/huggingface_hub/constants.py
- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
solves https://github.com/huggingface/huggingface_hub/issues/2880 cc @ErikKaum 
This PR adds `list_inference_catalog` and `create_inference_endpoint_from_catalog` to list the HF Model Catalog (https://endpoints.huggingface.co/catalog) and create an Inference Endpoint from any of the listed models. Both methods are flagged as experimental as we might want to update the format in the future. This should be a low hanging fruit to allow people to quickly deploy a model.
> Support deploy Inference Endpoint from model catalog

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- tests/test_auth_cli.py
- tests/test_inference_client.py
- tests/test_inference_providers.py
- tests/testing_utils.py
This PR fixes a bug in the `InferenceClient`'s token initialization and adds a test for this.
Also, took the opportunity to add more unit tests for `TaskProviderHelper`'s methods 🙈
> [InferenceClient] Fix token initialization and add more tests

- tests/cassettes/TestInferenceClient.test_chat_completion_with_stream[nebius,conversational].yaml
- tests/cassettes/TestInferenceClient.test_chat_completion_with_stream[novita,conversational].yaml
regenerating some cassettes for which the call to `https://huggingface.co/api/models/{model_id}?expand=inferenceProviderMapping` was missing. This should fix the failing tests in the CI.
> Fix inference client tests by regenerating the cassettes

- .github/workflows/python-tests.yml
- docs/source/en/package_reference/environment_variables.md
- pyproject.toml
- setup.py
- src/huggingface_hub/_commit_api.py
- src/huggingface_hub/_inference_endpoints.py
- src/huggingface_hub/_upload_large_folder.py
- src/huggingface_hub/constants.py
- src/huggingface_hub/errors.py
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/utils/__init__.py
- src/huggingface_hub/utils/_runtime.py
- src/huggingface_hub/utils/_xet.py
- tests/conftest.py
- tests/test_file_download.py
- tests/test_inference_endpoints.py
- tests/test_xet_upload.py
- tests/test_xet_utils.py
- tests/testing_utils.py
Partially resolves #2713 
This PR contains **only** the Xet upload workflow implemented in [xetpoc_huggingface_hub](https://github.com/huggingface-internal/xetpoc_huggingface_hub) (internal).
The main branch for xet storage integration is [xet-integration](https://github.com/huggingface/huggingface_hub/tree/xet-integration).
Main changes:
Note: since it's a common part for download and upload, this has been pushed directly into the [xet-integration](https://github.com/huggingface/huggingface_hub/tree/xet-integration) branch.
to try it in from this branch:
```bash
pip install -e ".[dev,hf_xet]"
export HF_DEBUG=1 #  if you want to set huggingface_hub logger to debug level
huggingface-cli upload --repo-type model rajatarya/xet-enable-test ~/data/yelp_sample
```
> Xet upload workflow

- src/huggingface_hub/hub_mixin.py
- tests/test_hub_mixin.py
We already handle dataclasses but only for the `config` parameter. Let's handle it for any parameter since we already have the logic to do that. Added an example as well.
Goal: would have avoided to manually define the coders in https://github.com/SesameAILabs/csm/pull/59 cc @NielsRogge
> [HubMixin] handle dataclasses in all args, not only 'config'

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- src/huggingface_hub/inference/_providers/_common.py
- src/huggingface_hub/inference/_providers/black_forest_labs.py
- src/huggingface_hub/inference/_providers/cohere.py
- src/huggingface_hub/inference/_providers/fal_ai.py
- src/huggingface_hub/inference/_providers/fireworks_ai.py
- src/huggingface_hub/inference/_providers/hyperbolic.py
- src/huggingface_hub/inference/_providers/nebius.py
- src/huggingface_hub/inference/_providers/novita.py
- src/huggingface_hub/inference/_providers/replicate.py
- src/huggingface_hub/inference/_providers/together.py
- tests/test_inference_providers.py
This PR adds asynchronous polling to the fal.ai `text-to-video` implementation. This allows running inference with large models that may take > 2 min to generate results.
**Main Changes**
- Implemented a polling mechanism in `FalAITextToVideoTask.get_response` that periodically checks generation status.
- URL, headers and API key are stored as class attributes for use during polling instead of passing these values as argument to `get_response`. Not 100% sure if this is the best solution.
- Updated fal.ai tests.
Once the structure is approved, we can add async calls for replicate (directly in this PR?), which should be straightforward.
I've tested locally the generation with models that take more than 2min and it works fine.
> [Inference Providers] Async calls for fal.ai

- docs/source/en/guides/download.md
- docs/source/en/guides/manage-cache.md
- docs/source/en/guides/upload.md
- docs/source/en/package_reference/environment_variables.md
Docs describing enabling and using Xet Storage with huggingface_hub.
These docs reference docs in HF Hub, which will be anchored here: https://huggingface.co/docs/hub/repositories (as a new Storage section).
The PR for those docs are here: https://github.com/huggingface/hub-docs/pull/1622 (draft PR for now).
> Xet Docs for huggingface_hub

- src/huggingface_hub/inference/_providers/fal_ai.py
Related to this discussion : https://github.com/huggingface/huggingface.js/pull/1292#discussion_r2000759123
Let's use the same interval polling for our clients. 0.5s should be smaller enough to fetch updates frequently enough and larger enough to avoid querying the API too often (hopefully).
> [Inference Providers] update polling interval for fal-ai

- docs/source/en/guides/inference.md
- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- utils/generate_async_inference_client.py
Clean-up PR I wanted to do since a bit of time :smile: 
In details:
- move up the `Supported providers and tasks` section in the Inference guide
- remove the "Domain" column from the table to gain some space => also reordered everything alphabetically 
- remove the `Custom requests` section as it's deprecated
- rephrased the `Timeout` section => since HF Inference is not on-demand anymore, most of the text was outdated
- remove the `Legacy InferenceAPI client` section => deprecated for >1year + it won't work very soon since it relies on api-inference.huggingface.co
- in `InferenceClient.inner_post` (same for async client), remove the `while True` loop. This was useful at some point when we where retrying on HF Inference in case of HTTP 503. We have forgotten to remove the loop when …
> Clean up some inference stuff

- src/huggingface_hub/inference/_providers/fal_ai.py
- tests/test_inference_providers.py
This PR fixes an edge case where the provider model id used in the request is different from the one used to fetch the status and the result of a request. This is the case for https://huggingface.co/Wan-AI/Wan2.1-T2V-1.3B. 
The PR introduces a more robust way to construct the status and the result URLs. 
More context in this slack [message](https://huggingface.slack.com/archives/C0664PDFGSJ/p1741632564147909) (private link).
This should (will) be fixed as well in https://github.com/huggingface/huggingface.js/pull/1292.
> [Inference Providers] Fix status and response URLs when polling text-to-video results with fal-ai

- src/huggingface_hub/constants.py
This pull request includes changes to the `src/huggingface_hub/constants.py` file to improve environment variable handling by expanding user variables and environment variables. The most important changes include modifications to the way paths are set for various cache and token-related environment variables.
Improvements to environment variable handling:
* [`HF_HOME`](diffhunk://#diff-b9ea02465324089a58bcb914a78b6c50143dfa0aadf772cef27478581f1346bcL117-R164): Changed to use `os.path.expandvars` and `os.path.expanduser` to ensure environment variables and user home directory are properly expanded.
* `HUGGINGFACE_HUB_CACHE` and `HUGGINGFACE_ASSETS_CACHE`: Updated to use `os.path.expandvars` and `os.path.expanduser` for better handling of environment variables and user paths.
* …
> Add expanduser and expandvars to path envvars

- src/huggingface_hub/constants.py
- src/huggingface_hub/file_download.py
- src/huggingface_hub/utils/__init__.py
- src/huggingface_hub/utils/_xet.py
- tests/test_xet_utils.py
Based on [the discussion here](https://github.com/huggingface/huggingface_hub/pull/2920#issuecomment-2749373899), we are using the link header to extract the xet refresh route from the response headers.
> Extracting the refresh route from the link header

- src/huggingface_hub/inference/_generated/types/image_to_image.py
- utils/check_task_parameters.py
Related to https://github.com/huggingface/huggingface_hub/pull/2933/files.
@hanouticelina I had to edit the `utils/check_task_parameters.py` script. In `_check_parameters` we run both the `DataclassFieldCollector` and the `MethodArgumentsCollector`. However in `MethodArgumentsCollector`, we filter out parameters that are considered `CORE_PARAMETERS`. Since `prompt` is one of them in `image_to_image`, it was discarded and therefore considered as a "new" parameter in `_check_parameters` (and therefore updating the docstring). Running multiple times the script in a row was adding the argument in the docstring over and over again. I've pushed what I think is a fix for that (at least it doesn't complain and it fixed the bug^^) but could you have a closer look to it?
> Add prompt in image_to_image type

- docs/source/en/guides/inference.md
- src/huggingface_hub/constants.py
- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- tests/test_inference_client.py
Related to https://github.com/huggingface/huggingface.js/pull/1297. Discussed in [DMs](https://huggingface.slack.com/archives/C07KX53FZTK/p1741882879007139) (private link)
Basically adds a parameter allowing a user to charge all their requests on their organization account instead of personal account.
PR to merge only once `"X-HF-Bill-To"` header is supported server side cc @SBrandeis 
```py
client = InferenceClient(provider="fal-ai", bill_to="openai")
image = client.text_to_image(
"A majestic lion in a fantasy forest",
model="black-forest-labs/FLUX.1-schnell",
)
image.save("lion.png")
```
> Support `bill_to` in InferenceClient

- src/huggingface_hub/_space_api.py
cc @XciD @julien-c 
It's a breaking change since we are modifying the enum but I don't expect any usage of it.
And users are still able to pass a string instead of using the enum if they really want to set a TPU (and if Spaces allows it)
> Unlist TPUs from SpaceHardware

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- src/huggingface_hub/inference/_providers/nebius.py
- src/huggingface_hub/inference/_providers/novita.py
- src/huggingface_hub/inference/_providers/together.py
This PR fixes `text_generation` when used with an external provider. The response was not handled in the corresponding subclasses which made the task unusable with these providers (spotted this while debugging the HF integration in langchain). 
Also, note that the output schema of text generation is based on TGI [/generation](https://huggingface.github.io/text-generation-inference/#/Text%20Generation%20Inference/generate) and it's not incompatible with the OpenAI completion API schema which is followed by most of the providers. 
Changing the output schema of `text_generation` to make it OpenAI-compatible is a breaking change and I believe it's not worth it now, especially that the usage is low (?) for this task.
> [Inference Providers] Fix `text-generation` when using an external provider

- src/huggingface_hub/inference/_providers/hf_inference.py
- tests/test_inference_providers.py
Reported by @abidlabs [on slack](https://huggingface.slack.com/archives/C02V5EA0A95/p1744076140260639) (private link)
Snippet in https://huggingface.co/google/gemma-3-27b-it?inference_api=true&inference_provider=hf-inference&language=python currently does not work. Issue is with the `task` defined for `HFInferenceConversational` which should be `"conversational"` (otherwise the `_check_supported_task` fails).
(tested it locally and it indeed fixes the issue with the snippet above)
=> once merged we should make a patch release
> Fix HfInference conversational

- src/huggingface_hub/utils/_pagination.py
- tests/test_utils_pagination.py
This PR enhances the `paginate` function in `src/huggingface_hub/utils/_pagination.py/_pagination.py` by implementing automatic retries using the `http_backoff` function. Previously, when attempting to list all models via `api.list_models()`, the process would fail due to rate limiting (HTTP 429) after approximately 500K models (this number depends on many factors). This led to data loss and required restarting the process from the beginning. Additionally, after restarting, the process would hit the rate limit again after another 500K models, making it impossible to scrape all models in a single run.  
- **Replaced `session.get` with `http_backoff`** to enable automatic retries.  
- **Configured `max_retries=20` and `retry_on_status_codes=429`** to handle API rate limits gracefully.  
- …
> Handle Rate Limits in Pagination with Automatic Retries

- src/huggingface_hub/file_download.py
- tests/testing_utils.py
_Originally from @Wauplin on [Slack](https://huggingface.slack.com/archives/C07EPSS7ELX/p1743675730107059?thread_ts=1743584493.306359&cid=C07EPSS7ELX) (internal link):_
>> I'm guessing huggingface_hub doesn't have retry for 429. Should be a good thing to add?
> 
> _Well, I have no idea why we haven't spotted that before_ 🫠
> _http_get relies on `_request_wrapper` which itself has been refactored in Oct. 2023 (!!) by ... hmm... myself. I wrote in comments Perform request and return if status_code is not in the retry list. . But the implementation is a simple `response = get_session().request(method=method, url=url, **params)` without any retry mechanism :see_no_evil:   See https://github.com/huggingface/huggingface_hub/pull/1766._
So basically this PR adds a retry mechanism when …
> Retry on transient error in download workflow

- .github/workflows/style-bot-action.yml
- src/huggingface_hub/hf_api.py
ref: https://huggingface.slack.com/archives/C016D661PAN/p1744900723918749?thread_ts=1742997838.592509&cid=C016D661PAN
> add route payload to deploy Inference Endpoints

- docs/source/en/guides/download.md
- docs/source/en/guides/upload.md
- docs/source/en/package_reference/environment_variables.md
- src/huggingface_hub/file_download.py
Ciao 👋 Super-tiny PR to enable direct copy paste of the new `pip install "huggingface_hub[hf_xet]"` on MacOS :))
PS: loving XET's speed 💨 ⚡
> Super-micro-tiny-PR to allow for direct copy-paste :)

- docs/source/en/package_reference/environment_variables.md
- src/huggingface_hub/commands/upload.py
- src/huggingface_hub/utils/_runtime.py
- tests/test_xet_utils.py
Changes:
* Adds HF_HUB_DISABLE_XET boolean environment variable to disable using hf_xet, even if installed
* Adds logger.info() if `hf-xet` is not available for cli upload, suppresses logger.info() about `hf-transfer` if `hf-xet` is available.
Fixes: XET-474, XET-492
> Minor xet changes: HF_HUB_DISABLE_XET flag, suppress logger.info

- docs/source/en/guides/manage-cache.md
I think it was wrong to say that the CACHE_DIR was usually your user's home directory. I fixed it by putting the default value.
> Fix CACHE_DIR value in cache documentation

- src/huggingface_hub/_upload_large_folder.py
This small PR resolves the `logger.warn()` deprecation warnings:
```python
D:\a\huggingface_hub\huggingface_hub\src\huggingface_hub\_upload_large_folder.py:212: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
See [CI logs](https://github.com/huggingface/huggingface_hub/actions/runs/14861309262/job/41726632111) for more information.
> Migrate to `logger.warning` usage

- .github/conda/meta.yaml
Fixes the failing conda release [workflow](https://github.com/huggingface/huggingface_hub/actions/runs/14885625698) job. 
The failure was due to `hf-xet` (required dependency) being missing in `meta.yaml`.
> [Internal] Fix conda release workflow

- .github/conda/meta.yaml
- setup.py
Related to #3073 and #3067 
more context in this internal slack [thread](https://huggingface.slack.com/archives/C087TU2FE3G/p1747038120179199).
> [Internal] bump `hf-xet` min version

- .github/conda/meta.yaml
- .github/workflows/python-tests.yml
- setup.py
follow-up PR after #3078. Let's make `hf-xet` optional for now until the package size is further reduced. This shouldn’t break anything. 
cc @bpronan @rajatarya
> [Internal] make `hf-xet` optional

- src/huggingface_hub/_upload_large_folder.py
When calling `hf_api.upload_large_folder`, we aren't properly threading through the `endpoint` all the way to the network request. This means that even if we end up creating a `hf_api(endpoint="http://localhost:3000/v1/hf")`, calls to `upload_large_folder` will still try to make call to `https://huggingface.co`, via this line of code:
https://github.com/matthewgrossman/huggingface_hub/blob/57b927c6858e45d3301100961b0e52fb57acf9dc/src/huggingface_hub/_commit_api.py#L672
The quickest workaround is to just make sure you `export HF_ENDPOINT="http://localhost:3000/v1/hf"`, but given that the `api` has that information already, we should just pass it explicitly to the call.
---
Assuming this change seems reasonable, happy to add a test!
> Add `api.endpoint` to arguments for `_get_upload_mode`

- src/huggingface_hub/commands/huggingface_cli.py
- src/huggingface_hub/commands/repo.py
- src/huggingface_hub/commands/user.py
- src/huggingface_hub/hf_api.py
The `huggingface-cli repo create` command was very outdated, with git logic inside, requesting a name/org args, prompting confirmation to user, etc. This PR refactors it to meet the standard from other commands e.g.
- moved the command to a `RepoCommands` module instead of having it under the `UserCommands`
- `repo_id` instead of `name`
- `--repo-type` instead of `--type`
- no `--organization`
- no `--yes`
- added `--private`, `--resource-group-id`,`--exist-ok`
- removed git logic
- removed logic to check if logged in user (already done by HfApi)
- actual errors are raised
All of this should be with 0 breaking change except that users are not prompted to confirm repo creation anymore. The output text is still a breaking change though. We warn on deprecated arguments but I haven't set a …
> Refactor `huggingface-cli repo create` command

- pyproject.toml
- setup.py
- src/huggingface_hub/_oauth.py
- src/huggingface_hub/dataclasses.py
- src/huggingface_hub/hub_mixin.py
- src/huggingface_hub/utils/insecure_hashlib.py
For the record, mypy version is pinned to avoid unexpectedly breaking the CI on an update. But it has been quite some time now that we haven't updated it manually so let's do it (also, I need [`typing.Unpack`](https://docs.python.org/3/library/typing.html#typing.Unpack) for another PR which current mypy complains about). 
Since 1.15.0 does not support Python 3.8 anymore, I pinned the version to the latest available (1.14.1). No big deal anyway, we will surely remove Python 3.8 soon-ish.
> Update mypy to 1.15.0 (current latest)

- src/huggingface_hub/inference/_mcp/mcp_client.py
Followed implementation from https://github.com/huggingface/huggingface.js/pull/1422
cc @evalstate if you can have a look at it
```py
import os
from huggingface_hub import ChatCompletionInputMessage, ChatCompletionStreamOutput, MCPClient
async def main():
async with MCPClient(
provider="nebius",
model="Qwen/Qwen2.5-72B-Instruct",
api_key=os.environ["HF_TOKEN"],
) as client:
await client.add_mcp_server(type="sse", url="https://evalstate-flux1-schnell.hf.space/gradio_api/mcp/sse")
messages = [
{
"role": "user",
"content": "Generate a picture of a cat on the moon",
}
]
async for chunk in client.process_single_turn_with_tools(messages):
if isinstance(chunk, ChatCompletionStreamOutput):
delta = chunk.choices[0].delta
if delta.content:
print(delta.content, end="")
elif isinstance(chunk, …
```
> [MCP] add support for SSE + HTTP

- src/huggingface_hub/_local_folder.py
- src/huggingface_hub/_upload_large_folder.py
- src/huggingface_hub/hf_api.py
_Originally from @Kakulukian on [slack](https://huggingface.slack.com/archives/C02V5EA0A95/p1747837459269209) (private):_
> From the end of last weekend until yesterday, we experienced increased latency on the hub. This appears to be connected to how the upload_large_folder method works. I've identified that one user uploaded approximately ~200,000 files using this method.
According to my understanding of the code, uploading via this method requires a call to the preupload endpoint for each file (right?). The issue is that as a repository grows more significant (commits or files), this method becomes progressively slower, particularly when the calls aren't batched
Would it be possible to also implement file batching for this endpoint with a minimum threshold?
> Do not fetch /preupload if already done in upload-large-folder

- .github/conda/meta.yaml
- .github/workflows/python-tests.yml
- setup.py
Follow-up PR after #3079 in which we made `hf-xet` optional due to reports about the binaries being too big on Linux platform. Thanks to the Xet team, now the installed binaries of `hf-xet` are much much smaller! (eg. Linux went from ~96MB → ~14MB). Release notes: https://github.com/huggingface/xet-core/releases/tag/v1.1.2.
Given these improvements, we can now make `hf-xet` a required dependency again.
cc @Vaibhavs10 @jsulz
> [Internal] make `hf-xet` (again) a required dependency

- src/huggingface_hub/inference/_mcp/agent.py
- src/huggingface_hub/inference/_mcp/cli.py
- src/huggingface_hub/inference/_mcp/mcp_client.py
This PR adds support for local/remote endpoint inference with `tiny-agents`. 
Tested the PR with @Vaibhavs10's [experiments-with-mcp](https://github.com/Vaibhavs10/experiments-with-mcp) and a remote endpoint (e.g. https://router.huggingface.co/nebius/v1/chat/completions) ✅
> [MCP] Add local/remote endpoint inference support 

- src/huggingface_hub/file_download.py
- src/huggingface_hub/hf_api.py
This PR switches the `we are using Xet` log message from `INFO` to `DEBUG`. Now that Xet is installed by default and enabled in many repos, I don't think it's _that_ special anymore. And on the contrary I find the output of `huggingface-cli download` veeery verbose with all these messages been printed out to the output.
(still relevant to keep them as `DEBUG` for debug purposes :smile:)
> Make hf-xet more silent

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
Originally reported by @Xeophon in [this gist](https://gist.github.com/Xeophon/8293c2f861bcd9980d891492498b8f12), it wasn't possible to access the collection slug when a collection item was itself a collection, and this was flagged internally by @Vaibhavs10 in [this Slack message](https://huggingface.slack.com/archives/C02V5EA0A95/p1748068431965789).
This PR enables proper client-side handling of collections that include collections as items. When the item type is "collection", we now set `item_id` to the collection’s slug, ensuring consistency with how other item types (model, dataset, space, paper) are handled.
```python
from huggingface_hub import get_collection
collection_slug = "celinah/inference-providers-function-calling-6826023e8ae9b24b3039ee5f"
print(f"Fetching collection: …
```
> [HfApi] Collections in collections

- src/huggingface_hub/inference/_mcp/_cli_hacks.py
This should fix issues reported in https://huggingface.co/blog/python-tiny-agents#683c2893453e60939f704bb4.
The bug was introduced by my _dumb_ comment in [#3125](https://github.com/huggingface/huggingface_hub/pull/3125#discussion_r2111284595) (Copilot had it right 🙄). Of course, `asyncio.wait()` refuses bare coroutines, every element should be a `Future` or a `Task`.
Disclaimer: i was testing the PR #3125 in a Python 3.10 environment where it happened to work fine, but I probably missed a `DeprecationWarning`.
> [MCP] `asyncio.wait()` does not accept bare coroutines

- src/huggingface_hub/inference/_mcp/mcp_client.py
This PR fixes a minor issue where a vestigial token may be yielded despite the early exit mechanism being triggered.
The CLI's early exit mechanism goal is to, under some circunstances, exit if the first chunk received does not contain a tool call. This behavior is desirable in some scenarios.
The only issue with the current implementation is that the early exit is triggered only after a token from the first chunk has already been yielded. As a result, a vestigial token is printed to the user's CLI.
Example: 
```
Agent loaded with 5 tools:
• read_query
• write_query
• create_table
• list_tables
• describe_table
» Which tables are available?
[{"name": "list_tables", "arguments": {}}]<Tool ->list_tables {} 
Tool -
[
{
"name": "products"
}
]
The available table is "products". [
```
As shown …
> [MCP] Fix vestigial token yield on early exit

- src/huggingface_hub/__init__.py
- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
Follow-up PR after [v0.32.0 release](https://github.com/huggingface/huggingface_hub/releases/tag/v0.32.0).
🚨 Breaking change: `InferenceClient.get_model_status` and `InferenceClient.list_deployed_models` will be removed in the next release. 
Users will have to use `HfApi.model_info` to get the model status for inference providers, and use `HfApi.list_models(..., inference_provider='...')` to list warm models per provider (draft PR open to add `inference_provider` to `list_models`: #3107). 
Let's merge #3107 first before merging this!
**EDIT**: the removal of `InferenceClient.get_model_status` and `InferenceClient.list_deployed_models` is postponed to huggingface_hub==0.35.0, see this comment: https://github.com/huggingface/huggingface_hub/pull/3138#issuecomment-2935363378
> [Internal] prepare for 0.33.0 release

- src/huggingface_hub/hf_api.py
- src/huggingface_hub/inference/_providers/_common.py
following server-side [update](https://github.com/huggingface-internal/moon-landing/pull/13875) (internal) which introduced automatic validation of model inference per provider, a provider can now enter an "error" state if inference fails, either due to incorrect provider mapping or because the model is no longer served by that provider.
> [Inference Providers] Raise warning if provider's status is in error mode

- src/huggingface_hub/inference/_mcp/mcp_client.py
If I understand [this guide](https://platform.openai.com/docs/guides/function-calling?api-mode=chat) by OpenAI on function calling correctly, the assistant's tool call needs to be appended to the list of messages before the tool call result. 
Simple example, for this agent: https://huggingface.co/datasets/tiny-agents/tiny-agents/tree/main/julien-c/flux-schnell-generator
Before this PR:
```
role: system, content: "You are an AI assistant"
role: user, content: "Please generate an image of a cat"
role: assistant, content: "Sure let me do that"
role: tool, content: "Image created"
role: assistant, content: "Here is your image!"
```
After this PR:
```
role: system, content: "You are an AI assistant"
role: user, content: "Please generate an image of a cat"
role: assistant, content: None, …
```
> [Tiny agents] Add tool call to messages

- src/huggingface_hub/_inference_endpoints.py
- tests/test_hf_api.py
- tests/test_inference_endpoints.py
This PR fixes a status handling issue with the newly introduced vLLM container on Inference Endpoint.
Currently, the library attempt to send a `GET /` to the endpoint URL and expect a `200 OK` to update the internal status to RUNNING.
While this works with TGI based container, vLLM do not expose such route and thus `GET /` leads to a `404 NOT FOUND` leaving the status in a on-going status pulling loop.
This PR proposes to move from `GET /` to `GET /health` which is exposed by both (and certainly more generally) other endpoint types.
> fix(inference_endpoints): use GET `healthRoute` instead of GET / to check status

- src/huggingface_hub/inference/_providers/_common.py
- src/huggingface_hub/inference/_providers/hf_inference.py
- tests/test_inference_providers.py
`None` values in payload can lead to a BadRequest error if the Inference Provider did not expect the field and is doing input validation. This is for instance what's happening in https://github.com/huggingface/huggingface_hub/pull/3170 with groq complaining if `tool_calls` and `tool_call_id` are both set (with None values in them). Groq is complying to the OpenAI specs, this is more a problem on our side but won't be in this PR (*).
What we currently do to avoid these issues is to filter out None values using `filter_none`. However this helper only removes None values at the top-level of the dictionary. **This PR updates `filter_none` to recursively remove None values.** I added some tests to ensure that values like `""`, `0` and `[]` are not removed. This PR should fix the Groq issue and …
> Recursive filter_none in Inference Providers

- src/huggingface_hub/inference/_mcp/agent.py
- src/huggingface_hub/inference/_mcp/cli.py
- src/huggingface_hub/inference/_mcp/types.py
Currently headers are configured in `tiny-agent` using `servers[].config.options.requestInit.headers` (which we inherited from JS MCP client). However it would be preferable to follow [VSCode MCP configuration](https://code.visualstudio.com/docs/copilot/chat/mcp-servers#_configuration-format) i.e. `servers[].headers`:
```json
{
"model": "Qwen/Qwen2.5-72B-Instruct",
"provider": "nebius",
"inputs": [
{
"type": "promptString",
"id": "hf-token",
"description": "Token for Hugging Face API access",
"password": true
}
],
"servers": [
{
"type": "http",
"url": "https://huggingface.co/mcp",
"headers": {
"Authorization": "Bearer ${input:hf-token}"
}
}
]
}
```
---
I also updated the "default env variable loading" logic. Before we were loading based on the key where the value will be used (in this …
> [Tiny-Agent] Fix headers handling + secrets management

- src/huggingface_hub/file_download.py
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/utils/_xet.py
- tests/test_xet_utils.py
fixes #3168.
as mentioned by @coyotte508 in this (private) [comment](https://github.com/huggingface-internal/moon-landing/pull/14209#issuecomment-3000994756) , client-side handling is much simpler and future-proof, introducing a new server header would be overkill and doesn't really justify a change server-side.
cc @bpronan
> Override xet refresh route's base URL with HF Endpoint

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
- src/huggingface_hub/inference/_providers/hf_inference.py
- tests/test_inference_client.py
Fixes #3193
This PR fixes a bug in the `_build_chat_completion_url` helper function, which was incorrectly handling URLs that contained query parameters. previously, the function relied on simple string checks like `model_url.endswith("/v1")` or `model_url.endswith("/chat/completions")` to decide whether to append a path suffix. this logic failed when a URL contained a query string, as the suffix would no longer be at the very end of the string.
this led to malformed urls. for e.g.:
```python
input_url = "https://something.com/something/chat/completions?query=123"
output = _build_chat_completion_url(input_url)
```
the function has been refactored to use `urllib.parse`.
the `model` docstring in `InferenceClient`/`AsyncInferenceClient`  was also misleading, stating that when passing a URL, …
> [Inference] Correctly build chat completion URL with query parameters

- src/huggingface_hub/hf_file_system.py
- tests/test_hf_file_system.py
HfAPi has it set to False by default, so should HfFileSystem. In this PR I set it to False by default for HfFileSystem.
This will be particularly useful for `pyarrow` 21.0 when it comes out. Currently having expand=True by default causes issues because it's an expensive operation:
```python
In [1]: import pyarrow.dataset as ds
...: 
...: uri = "hf://datasets/HuggingFaceFW/fineweb-2"
...: dataset = ds.dataset(uri)
HTTP Error 429 thrown while requesting GET https://huggingface.co/api/datasets/HuggingFaceFW/fineweb-2/tree/main?recursive=True&expand=True&cursor=ZXlKbWFXeGxYMjVo...
Retrying in 1s [Retry 1/20].
HTTP Error 429 thrown while requesting GET https://huggingface.co/api/datasets/HuggingFaceFW/fineweb-2/tree/main?recursive=True&expand=True&cursor=ZXlKbWFXeGxYMjVo...
Retrying in 1s …
```
> Align HfFileSystem and HfApi for the `expand` argument when listing files in repos

- src/huggingface_hub/inference/_mcp/constants.py
Fix https://github.com/huggingface/huggingface_hub/issues/3203.
Fix docs example after https://github.com/huggingface/huggingface_hub/pull/3166 / https://github.com/huggingface/huggingface.js/pull/1556. Since release [0.33.2](https://github.com/huggingface/huggingface_hub/releases/tag/v0.33.2) `tiny-agents` config follow VSCode format. We made the change without a proper deprecation warning as it's still experimental and we wanted to harmonize with VSCode as quickly as possible (to avoid future conflicts).  
Related PRs:
- https://github.com/huggingface/hub-docs/pull/1816
- https://github.com/huggingface/transformers/pull/39245
- https://github.com/huggingface/huggingface_hub/pull/3205
- https://github.com/huggingface/huggingface.js/pull/1599
> Update tiny-agents example

- src/huggingface_hub/constants.py
- src/huggingface_hub/file_download.py
- src/huggingface_hub/utils/_runtime.py
- tests/test_xet_utils.py
Suppresses the WARN message to install `hf-xet` if `hf-xet` has been disabled (using `HF_HUB_DISABLE_XET` env variable).
See image below of WARN message.
> Suppress xet install WARN if HF_HUB_DISABLE_XET

- src/huggingface_hub/inference/_mcp/constants.py
Fixes #3213.
OpenAI validates every function -> parameters object as a full json schema, if the schema contains a "properties" field, at least one property has to be defined. according to OpenAI’s specs, omitting parameters is the correct way to express a function that takes no arguments:
> Omit `parameters` in default tools of `tiny-agent`

- src/huggingface_hub/__init__.py
Seems like we forgot to do it ^^ No deprecation or changes planned
> Bump to 0.34.0.dev0

- src/huggingface_hub/repocard.py
I discover a problem (even lots of problems...) when I wanted to use push_to_hub on an agent of smolagents, and the problem is due to huggingface_hub, in the file :
Bug #1: UnicodeEncodeError when creating README.md Error:
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f440' (for exemple) in position 32: character maps to <undefined>
Root cause:
Location: Path.write_text() in huggingface_hub/repocard.py:279 Problem: Windows uses CP1252 encoding by default instead of UTF-8 Trigger: A Unicode emoji (\U0001f440 = 👀 for exemple) in the README.md metadata
Context:
smolagents automatically generates a README.md with emojis, but Windows cannot encode them using CP1252
Bug mechanism:
agent.push_to_hub() calls metadata_update()
metadata_update() creates a RepoCard with an emoji …
> Solve encoding issue of repocard.py

- setup.py
- utils/check_inference_input_params.py
this PR fixes two internal issues:
- `make quality` fails on Python 3.13 because `utils/check_inference_input_params.py` looks for the literal fragment
"            {param_name} (" in every docstring., not 100% sure but maybe it's related to CPython 3.13 stripping the common indentation of docstrings, see: https://docs.python.org/3/whatsnew/3.13.html#other-language-changes. 
- `libcst` (used to update python files) installation failure on (at least) Python 3.13: when setting up the repo locally with newer Python versions (e.g., 3.13), the installation of `libcst` fails.
> [Internal] Fix docstring param spacing check and `libcst` incompatibility with Python 3.13

- src/huggingface_hub/inference/_common.py
`AsyncInferenceClient` creates an `aiohttp.ClientSession` each time it makes a request. when streaming, the session is only closed after the async generator that yields the data finishes iterating:
```python
async for chunk in response.content:  
yield chunk
await client.close()                   
```
if the user stops iteration as soon as they see the `[DONE]` event (see `_async_stream_chat_completion_response` and `_format_chat_completion_stream_output`), the `await client.close()` line is never executed. later, when the client object is garbage collected, we get this warning:
```
UserWarning: Deleting 'AsyncInferenceClient' client but some sessions are still open. This can happen if you've stopped streaming data from the server before the stream was complete. To close the client …
```
> Fix: "UserWarning: ... sessions are still open..." when streaming with `AsyncInferenceClient`

- src/huggingface_hub/utils/_git_credential.py
- tests/test_utils_git_credentials.py
This pull request introduces improvements to the detection and handling of Git credential helpers in the Huggingface Hub client for Linux environments.
1. **Support for Git Credential Manager (GCM)**
- Updated the regex to match `git-credential-manager`.
- Added tests to verify GCM is recognized and handled.
- Ref: https://git-scm.com/doc/credential-helpers
2. **Support for git-credential-libsecret**
- Extended the regex to recognize `git-credential-libsecret`, enabling integration with Secret Service-compatible keyrings (e.g., GNOME Keyring, KDE Wallet) on Linux.
- Added unit tests to validate detection and handling of `git-credential-libsecret`.
- Ref: https://git-scm.com/doc/credential-helpers
These changes improve compatibility with modern credential storage solutions and enhance …
> Improve Git Credential Helper Detection for Linux (GCM & libsecret support)

- src/huggingface_hub/cli/auth.py
- src/huggingface_hub/commands/user.py
Follow-up PR after https://github.com/huggingface/huggingface_hub/pull/3267. We added the prefix `user:` to the deprecated `huggingface-cli whoami` command instead of only updating `hf auth whoami`. 
This PR fixes that by restoring the original output for the deprecated command and adding the user: prefix only to `hf auth whoami`.
> [CLI] add "user:" prefix only for `hf auth whoami` output

- src/huggingface_hub/hf_file_system.py
- tests/test_hf_file_system.py
If the response is gzipped, we should decode the content.
Fixes #3269
> Make requests decode content

- docs/source/en/guides/cli.md
Swap quotes to fix bash history expansion event not found error
> Fix bash history expansion in hf jobs example

- docs/source/en/guides/cli.md
- src/huggingface_hub/cli/jobs.py
- src/huggingface_hub/hf_api.py
- src/huggingface_hub/utils/_dotenv.py
- tests/test_utils_dotenv.py
Add the `hf_auth:` syntax to pass a local Hugging Face token.
E.g. `HF_TOKEN=hf_auth:<token_name>` (uses the current token if `<token_name>` is empty)
> [Jobs] Use current or stored token in a Job secrets

- docs/source/en/guides/jobs.md
As discussed in (internal) Slack thread https://huggingface.slack.com/archives/C07RD3RVD5W/p1753978425762419, it might be nice to have some more information on timeout so users know to set longer timeouts for training jobs, etc.
> Add timeout info to Jobs guide docs

- src/huggingface_hub/_upload_large_folder.py
- src/huggingface_hub/hf_api.py
- tests/test_upload_large_folder.py
This PR adds "pre-flight" validation checks to `upload_large_folder` to warn users about repository limits before they start uploading. This helps users avoid discovering these limits after spending significant time uploading data.
Fixes #3278
The validation checks run automatically after listing files and before starting the upload process. They check for:
- **Total file count**: Warns if uploading more than 100k files (recommended limit)
- **Files per folder**: Warns if any folder contains more than 10k files (recommended limit)
- **File sizes**: Warns about files larger than 20GB (recommended) or 50GB (hard limit)
When limits are exceeded, users will see warnings like:
```
WARNING:huggingface_hub._upload_large_folder:You are about to upload 150,000 files. This exceeds the recommended …
```
> Add validation warnings for repository limits in upload_large_folder

- src/huggingface_hub/hf_api.py
(follow up on https://github.com/huggingface/huggingface_hub/pull/362 :smile:)
Currently on a `whoami` call, we print a `Invalid token` message if any `HTTPError` happens.
This is not correct as many errors can lead to a HTTP Error, not just an invalid token. This PR fixes this by setting the custom message only on a HTTP 401 unauthorized.
Here is an example of a HTTP 429 with current `main` branch (see private [slack thread](https://huggingface.slack.com/archives/C07RD3RVD5W/p1753854604683449))
```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_http.py in hf_raise_for_status(response, endpoint_name)
408     try:
--> 409 …
```
> Whoami: custom message only on unauthorized

- src/huggingface_hub/_jobs_api.py
- tests/test_cli.py
This PR adds the owner and avatarUrl attributes to the `JobOwner` type to match the api response
```json
{
"id": "6452d5ba3f80ad88c77b2f05",
"name": "drbh",
"type": "user",
"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/6452d5ba3f80ad88c77b2f05/Elc2R5dvn-iQlgROdRikX.png"
}
```
this command errors prior to these changes `hf jobs run ubuntu sleep 10`
relevant api changes https://github.com/huggingface-internal/moon-landing/pull/14672
> Add type to job owner

- docs/source/en/guides/search.md
- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
As highlighted by @d-kleine in https://github.com/huggingface/huggingface_hub/issues/3313, filtering models with `list_models` as the same behavior no matter if you use `language`, `library`, `tags` and `task`. They are all forwarded to the server as `filter`. This is unnecessary misleading to the end user. Let's just promote `filter` and deprecate the rest.
Same for `list_datasets`.
> Deprecate library/tags/task/... filtering in list_models

- src/huggingface_hub/hf_api.py
- tests/test_hf_api.py
This PR adds `apps` as a parameter to `HfApi.list_models` in order to retrieve models that support the specified apps, e.g., `ollama` or `vllm`.
1. Solves issue #3319 
1. This PR's implementation uses the `apps` parameter of the Hugging Face API instead of adding the value of `apps` to the `filter` list. This is due to the fact that a query such as https://huggingface.co/api/models?apps=ollama produces different results from https://huggingface.co/api/models?filter=ollama, with the latter listing some models that do not actually support Ollama.  Is this observation correct and tested thoroughly? Is this expected behaviour?
2. Perhaps add more exhaustive tests in `test_list_models_apps` since it only checks for Ollama supported models.
3. Is the method of checking for files ending with …
> Added `apps` as a parameter to `HfApi.list_models`

- docs/source/en/guides/cli.md
- docs/source/en/guides/jobs.md
- src/huggingface_hub/hf_api.py
- tests/test_cli.py
support `hf jobs uv run command` in addition to `hf jobs uv run script.py` as in the official `uv`
this is useful to run cli commands from python packages, e.g.
```bash
hf jobs uv run --with lighteval -s HF_TOKEN lighteval endpoint inference-providers "model_name=openai/gpt-oss-20b,provider=groq" "lighteval|gsm8k|0|0"
```
> [Jobs] Support commands in `hf jobs uv run`

- docs/source/en/guides/cli.md
- setup.py
- src/huggingface_hub/__init__.py
- src/huggingface_hub/cli/__init__.py
- src/huggingface_hub/cli/_cli_utils.py
- src/huggingface_hub/cli/auth.py
- src/huggingface_hub/cli/cache.py
- src/huggingface_hub/cli/download.py
- src/huggingface_hub/cli/hf.py
- src/huggingface_hub/cli/jobs.py
- src/huggingface_hub/cli/lfs.py
- src/huggingface_hub/cli/repo.py
- src/huggingface_hub/cli/repo_files.py
- src/huggingface_hub/cli/system.py
- src/huggingface_hub/cli/upload.py
- src/huggingface_hub/cli/upload_large_folder.py
- tests/test_cli.py
Resolves #3363 and #3364.
This PR migrates the `hf` CLI from built-in `argparse` to [`Typer`](https://typer.tiangolo.com) using idiomatic, function based commands. this significantly reduces boilerplate, making the CLI easier to maintain, less error prone, and faster to extend with new `HfApi` features.
- new dependencies: 
- [`typer`](https://github.com/fastapi/typer), latest version is 0.17.4,  it should be stable enough and it's widely adopted.
- [click](https://github.com/pallets/click), typer s foundation, pure Python, should be stable too. latest version is 8.2.2.
- ⚠️ rich has been disabled in all cases in commit [(#3364) disable rich in all cases](https://github.com/huggingface/huggingface_hub/commit/93136efe5f4a3f7fd5c096579259ed77d9e189bc) to keep a consistent UI regardless of …
> Refactor CLI implementation using Typer

- src/huggingface_hub/inference/_client.py
- src/huggingface_hub/inference/_generated/_async_client.py
The following line in the docstring of `sentence_similarity` was misleading. This minimal PR updates it to reflect the actual purpose of the function. 
https://github.com/huggingface/huggingface_hub/blob/3b562cada2f031c7b265f9e0dd6ab9f7dad7f86e/src/huggingface_hub/inference/_client.py#L1631
Link to the issue: https://github.com/huggingface/huggingface_hub/issues/3374
> update the `sentence_similarity` docstring (#3374)

- src/huggingface_hub/file_download.py
- src/huggingface_hub/hf_file_system.py
- src/huggingface_hub/lfs.py
- src/huggingface_hub/utils/_http.py
Partially reverting back https://github.com/huggingface/huggingface_hub/pull/2976.
This PR harmonizes the `http_backoff` default value in `huggingface_hub` by retrying on any 5xx error while downloading or fetching metadata for a file, but not on 429 rate limit error. Before this PR 5xx errors were retried when using `HfFileSystem` and `429` were retried when using `hf_hub_download`.
---
In https://github.com/huggingface/huggingface_hub/pull/2976, I've added a basic retry mechanism on 429 errors. It looks like this change coincides with a peak of 429-related issues been opened (https://github.com/huggingface/huggingface_hub/issues/3312, https://github.com/huggingface/huggingface_hub/issues/3201, https://github.com/huggingface/huggingface_hub/issues/3342). It looks like retrying on 429 …
> Do not retry on 429 (only on 5xx)

- src/huggingface_hub/errors.py
- tests/test_utils_errors.py
Found out that `requests.HTTPError` inherits from `OSError` but `httpx.HTTPError` don't. This means that `HfHubHTTPError` do not inherit from `OSError` anymore which is a breaking change. This PR makes `HfHubHTTPError` inherit from it so that existing code don't break (happened at least once in `transformers`).
We could have also kept the breaking change and listed it in the migration guide but I don't think it's worth it. Issues caused by a failing `try ... except OSError ...` can be quite hard to locate so let's avoid that friction.
> Make `HfHubHTTPError` error inherit from OSError

- src/huggingface_hub/inference/_mcp/mcp_client.py
This PR allows the agent to use all tools unless there is an explicit `allowed_tools` list in the configuration file.
Fixes: https://github.com/huggingface/huggingface_hub/issues/3396
> [Tiny-Agents] Use all tools unless allowed_tools is set explicitly

- docs/source/en/guides/cli.md
- docs/source/en/installation.md
- utils/installers/install.ps1
- utils/installers/install.sh
This PR updates the docs to cover adding `/cli` to the install scripts paths.
> update CLI installers paths
